### ISSUE TITLE
Make it Easier to Upgrade to a Newer Version

### ISSUE THREAD

**Issue by TaylorJonesTRT** [streamlink/streamlink-twitch-gui#145]
Maybe make it have an auto upgrade / download feature so users don't have to download a separate zip file every time there is an update.

**Comment by bastimeyer** [comment]
I know it's quite annoying to manually download and extract archives all the time, but I really dislike the idea of implementing an update mechanism into the application. This would be a complex task and would also be prone to errors, especially by implenting this for multiple platforms.
Actually, it's the task of a package manager to do the software updates of your system and not the task of each application itself. I know that there are only just two packages available at the moment, but I'll try to add more soon.

> zip file

As it seems that you are a Windows user, you should check out [chocolatey](https://chocolatey.org/) and install [`livestreamer-twitch-gui`](https://chocolatey.org/packages/livestreamer-twitch-gui). It's a shame that this isn't more popular on Windows... :disappointed:
There's also a chocolatey GUI for managing all package installations and upgrades, so the shell doesn't need to be used.

**Comment by RenanOliv** [comment]
This issue is kinda a double edge sword. In one side I fully agree that it is the package manager job to handle all software updates in your system, but in the other hand we have a situation where both Windows and OS X are well know for having multiple ways to install and update apps. 

I looked for something that could help and I found an open issue about this topic in the [nwjs repository itself](https://github.com/nwjs/nw.js/issues/233). From what I've read there is no official support yet, but there is this [node-webkit-updater](https://github.com/edjafarov/node-webkit-updater) that tries to fill the gap and it seems to work well with nw-builder apps.

Since livestreamer-twitch-gui is a quite large app and I'm not sure how troublesome would be to implement this feature since this package only gives you a low-level API to write the update logic.

By the way, this [chocolatey](https://chocolatey.org/) looks really useful, thanks for sharing it.

**Comment by bastimeyer** [comment]
Yeah, I know about node-webkit-updater, but like you've already said, this is basically just a lib with downloading, unpacking and copying logic, so it's actually not that useful. You'd still have to deal with all the platform related differences and stuff like write access, etc. There's also the problem that the application doesn't allow running multiple instances of itself, so that's just another hurdle for an auto-upgrade mechanism.

IMO it's absolutely not worth building it into the application. PRs are welcome, but those need to be really good in order to change my mind...

**Comment by brian-gates** [comment]
Popcorn Time had a fantastic upgrade process and it was/is a NW.js app.  You could probably dig up the source and/or contact the devs for more info.

**Comment by bastimeyer** [comment]
Working on it on the [`windows-installer`](https://github.com/bastimeyer/livestreamer-twitch-gui/tree/windows-installer) branch.

The Windows archives will be replaced by installers in future releases. By doing this, the "internal" update procedure should become much easier to solve. The application will be able to simply download the installer into a temp directory, run it from there and then kill its own process. This avoids the single-instance problem and the installer can also request administrator privileges.

**Comment by Dr-Flay** [comment]
Could you please include notification in the GUI for updates of the CLI client ?
That updates a lot more often than the GUI so it seems would be advisable to let users know.

**Comment by bastimeyer** [comment]
> Could you please include notification in the GUI for updates of the CLI client ?

Streamlink Twitch GUI only executes Streamlink when launching a stream. When a stream gets launched for the first time in the current session or after modifying the settings, it'll perform a version check and it compares it with the [minimum version requirement](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.13.0/src/config/streaming.json#L9-L17). If it doesn't meet this requirement, the stream can't be launched and it'll show an update message instead. Streamlink Twitch GUI doesn't care if you're using the latest Streamlink release. All it cares about that it's compatible with its command line interface. There will be a bump to 2.4.0 soon, as some of the used parameters here got deprecated and need to be replaced before Streamlink 3.0.0.

Having independent upgrade messages don't make sense. If you want to be notified about new Streamlink releases, then give the repo on GitHub a star or add it to you watch list. You can also subscribe an Atom/RSS feed for its releases.

----

Regarding this thread's original topic though, I'm going to close this, because it's been stale for years and I'm not going to implement internal upgrades. I had a look at it years ago, but it's more complicated than necessary, especially on Windows, as you can't overwrite files of applications which still have file handles active (while the application is running). It's also a problem for the two different kinds of application releases of Windows, namely the installer and "portable" ZIP archives.

I'm very much against this updating scheme anyway, and people should use package managers, even on kindergarten operating systems like Windows.
