### ISSUE TITLE
rpm fedora

### ISSUE THREAD

**Issue by vitteloil** [streamlink/streamlink-twitch-gui#149]
Hi!
Could you provide an rpm in rpmfusion for fedora users ?

**Comment by bastimeyer** [comment]
Hi,
I'm actually looking for package maintainers right now who could help me out with this. It's just too much time that I'd need to spend on this, especially when I'm not familiar with it...

There's also the issue that binary packages are not allowed everywhere, so I'm not entirely sure if this also applies to [rpmfusion](http://rpmfusion.org/Contributors#Read_the_packaging_guidelines), which is following the [Fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#No_inclusion_of_pre-built_binaries_or_libraries).

> Software which downloads code bundles from the internet in order to be functional or useful is not acceptable for inclusion in Fedora (regardless of whether the downloaded code would be acceptable to be packaged in Fedora as a proper dependency)

During the build process, NWjs binaries will be downloaded from the NWjs website first (if not cached) and then all the built application content will be appended to the executable. This stands in conflict with the rules stated above, so NWjs itself would need to be compiled first.

The other available packages (AUR and Chocolatey) are both just downloading the binaries from github, but this seems to be prohibited here in this case as well.

As you can see, this can become fairly complex and I'd be more than glad if someone could offer me their help. Thanks.

**Comment by enjoyaol** [comment]
Hi,

I believe the build process downloading things is ok, since the resulting artifact won't. But I am not sure about that. However, rpmfusion contains a 'non-free' repository also.

You could contact the guy in charge of http://negativo17.org/ who proposes a repository with non-free things, I bet he would gladly accept to host an rpm for you ? His repository is quite known in the fedora world.

Myself, I could try to help you but I have never done rpm packaging so I'm not sure I am a good bet :)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/pull/319#issuecomment-636613841
