### ISSUE TITLE
Support for chromecast (if possible)

### ISSUE THREAD

**Issue by stubbegianni** [streamlink/streamlink-twitch-gui#164]
# Chromecast

Hello,

Could it be possible to add support for the chromecast? I know the twitch app supports it but I'd love to choose which quality I want to watch my stream in (which livestreamer gui has).

Greetings

**Comment by bastimeyer** [comment]
Hi!
Chromecast is currently not supported by livestreamer. See chrippa/livestreamer#358...

Streaming the GUI to chromecast is also not possible right now, since there's no support for native chromium extensions with the current version of NW.js. I'm also not sure if this would be very useful at all.
Support for chrome extentions will be added in the [upcoming NW.js version](https://groups.google.com/forum/#!msg/nwjs-general/YuwMHd_uvPM/pLFWG3vYBwAJ) and afaik, [google's official chrome extention](https://chrome.google.com/webstore/detail/google-cast/boadgeojelhgndaghljhdicfkmllpafd) is required for this, right?

**Comment by stubbegianni** [comment]
Hello,

I didn't know if I had to adress this to you or the maker of the livestreamer core. It's not the gui I would like but the stream itself (through the gui), that's why I thought it would belong here!

I have no idea if the chrome extension is needed for it. I haven't seen pc software with the cast functionality only apps.

**Comment by bastimeyer** [comment]
> It's not the gui I would like but the stream itself

For the video stream, see the thread I've linked above...

> I have no idea if the chrome extension is needed for it

There are node.js modules that are able to stream to chromecast, but only video files, so they are useless for streaming the GUI. That's why the chrome extention is needed (I think).

**Comment by bastimeyer** [comment]
Closing, since it's been two years.

Such a feature request belongs to the Streamlink issue tracker, if still desired. Once it gets implemented into Streamlink, adding options for streaming to a chromecast device may be considered here.

As an addition, chromecast related stuff can be done by using the chrome extension API of the *new* NW.js releases, I think. I'm not willing to rewrite the streaming related code just for this feature.
