### ISSUE TITLE
Play sound when on Desktop Notification 

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink-twitch-gui#169]
It would be great if it could play a sound when the desktop notification pops up.
Even better if we can use our own mp3 files as the notification sound.

Just a thought, thanks for the best application ever <3

**Comment by bastimeyer** [comment]
Well, I'm not sure about this yet...

Adding a simple sound playback mechanism (in addition to the notifications) *could* of course be implemented, but the issue I'm seeing with this is, that it could interfere with the notification system of the OS: notification sounds will already be played on different systems, depending on the configuration. And adding another audio source is just unnecessary IMO.
This would all be no problem if there was a way to add sound-data to the notifications themself, but the API that's being used does not support this, so there's no way.

Then there's also the issue with multiple or different sound devices on Windows, etc...

**Comment by Tholur** [comment]
True, thanks for the reply.
And I understand. Really happy with the program.
________________________________

**Comment by bastimeyer** [comment]
Closing the thread, since it's been two years since this issue was created.
The notification system has been rewritten a few times now. All supported OSes except Windows7 have native notification systems, which are being used here. Sound can be configured in the system settings, which is the proper place for this kind of feature.
