### ISSUE TITLE
Add hitbox? 

### ISSUE THREAD

**Issue by sxealex** [streamlink/streamlink-twitch-gui#192]
I really enjoy the app! I know its called twitch-gui but would you be interested in adding hitbox?
thanks for your hard work!

**Comment by bastimeyer** [comment]
I'm afraid I can't answer this question at this moment...

I understand that there are users out there who'd like to be able to browse hitbox streams as well, but just think a second for yourself what kind of big undertaking this would be. The whole application would not only needed to be completely rewritten in some kind, but also renamed, etc. This would be a **huge** task and I don't even know if this would be worth it. Also, I'm working on the project in my free time and I'm not sure whether I want to sacrifice even more time to it when I don't know if this is going to work out well enough.
So just think about the implications of implementing other/multiple platforms. :neutral_face: 

Let me just quickly talk about what it would mean to implement hitbox.tv:

- First of all, how should the application handle multiple platforms? Should users be able to decide which platform they are browsing or should they be merged, if this is even possible in a nice way? If there was a way of merging multiple platforms, could there be users who do only prefer one and don't want to have another platform listed? Can all the items in the main menu stay the same or do they need to be changed? What about special features like CS:GO stream filtering, which is of course not implemented right now, but certainly could be added in the future?

- I'm not a hitbox.tv user, so from what it looks like, it seems to be feature-equal with twitch and the API also seems to be similar at the first glimpse. But can I be sure that this doesn't change and both stay equal to a certain degree in the future? I also haven't looked at the user login yet and how you can get a client-id for using access tokens in an application like this. How can I be sure that they don't block my client-id if they think the application causes them to lose money by preventing ads from being run? Do they have something similar like monthly subscriptions?

- What about livestreamer? Are there any differences between both platforms? Will livestreamer keep hithox.tv support in the future?

- What about the chat? I know a lot of people use chatty, etc. Is there even a way of opening the chat without the stream? From what I've seen in the API docs, the chat is websocket based, so this would mean that I'd need to add this to my not yet done internal twitch IRC chat implementation (if I will ever be able to finish this :cry:).


As you see, there are a trillion of follow-up questions and decisions to be made.
However, the most important one wouldn't be technical question, but rather if hitbox keeps staying alive, since twitch is by far the more bigger and popular one.

I'm not closing the thread for now, but don't expect me to make a decision any time soon.

**Comment by sxealex** [comment]
understandable, no pressure. :+1:

**Comment by bastimeyer** [comment]
> However, the most important one wouldn't be a technical question, but rather if hitbox keeps staying alive, since twitch is by far the bigger and more popular one.

Well, as you can see, this is exactly what I was saying. Just because some streamers are moving away from Twitch doesn't mean that those other platforms are worth considering for an implementation here.

Hitbox and Azubu have merged now. Let's see how long this streaming service will last.
https://www.smashcast.tv/

**Comment by bastimeyer** [comment]
Closing the thread, since other streaming services won't get implemented here.
I just left this thread open for so long, because I was hoping to not get any duplicates, but that did not happen.
