### ISSUE TITLE
Badges in left sidebar

### ISSUE THREAD

**Issue by Poorchop** [streamlink/streamlink-twitch-gui#194]
The badge icon in the taskbar is really useful but I think that it should be included in the application itself. I follow some games and the only way to see if anyone is streaming a followed game is to manually navigate to the game's page via the application. With badges next to the categories, it will be easier to see if anyone is live, especially in the case of followed games.

**Comment by bastimeyer** [comment]
The followed games list sadly doesn't contain any stats, this is related to #148...
https://api.twitch.tv/api/users/[USER_NAME_HERE]/follows/games?oauth_token=[TOKEN_HERE]

I also can't add game filters to the followed streams menu (which could then be linked by the followed games), because the API doesn't allow any filtering parameters.
https://api.twitch.tv/kraken/streams/followed?game=[GAME_NAME_HERE]&oauth_token=[TOKEN_HERE]
