### ISSUE TITLE
Setting to automatically refresh GUI even when not active

### ISSUE THREAD

**Issue by Luterin70** [streamlink/streamlink-twitch-gui#226]
I know that the notifications usually is enough for most to see if anyone started to stream, but the notifications do not work with all fullscreen games/applications, and it's not always prefered to have notifications on either. But if you have a multi-monitor setup, which is pretty common these days, then one could have the Livestreamer Twitch GUI open on another monitor and keep a track of whats streaming there, without having to activate the window for it to refresh.

Having to activate the window for it to refresh when you are in a full screen game/application is not always someting you prefer. And with some poorly written games/apps they might even crash if you tab out, so this feature would help with that aswell, if you are waiting for something special to start on Twitch.

This should ofcourse be completely optional and have a seperate setting under GUI/Refresh content, but it should be easy to implement since the functionality already exists.

**Comment by bastimeyer** [comment]
I'm not quite sure about this idea. I really don't like automatic refresh mechanisms, even if they need to be enabled first. The "regain-focus-refresh" setting is an exception here, since it will only refresh when the user is active again.

I'm a little bit concerned, because right now in the current version there's a memory leak when rerendering certain components of the application. Infinitely refreshing content and rerendering stream lists would be terrible as long as this hasn't been fixed (and sadly I haven't found the issue of this yet).

I also think that refreshing the content in the situation you've described would not be very useful. New streams would appear at the bottom of your followed streams list and may not be visible at all, depending on other streams and the window size of the GUI.

If your desktop notifications are hidden behind fullscreen applications, then you should change the position of those to a different spot on one of your monitors.

**Comment by Luterin70** [comment]
I can understand the concern with the memory leak for sure, and without that being fixed it would most likely be a bad idea to have an auto refresh every minute when in the background. And I know how anoying it can be to find memory leaks, especially JavaScript ones, so you have my complete understanding here.

Having new streams appear at the bottom is just strange. Either refresh the whole "page", as you do when the window gets refreshed after being active again. Ofcourse, with a memory leak, this might be a really bad idea.

Or sort the induvidual boxes based on viewers after they have been drawn, if that information is passed along from the Twitch API. But depending on how you have made your output, this might be a bunch of work.

As for moving the desktop notification, it's something I never really even considered and it has it's merits. But having notification on one of the other monitors will ofcourse make it easier to miss, but I will think about it atleast.

Perhaps I can lend a hand and check out the code once I have a bit fewer work related projects and more spare time to code for fun. The feature request is not a big deal, its just something I would have liked, but not important.

**Comment by bastimeyer** [comment]
I will implement this, once I have upgraded to the latest NW.js version. See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/207#issuecomment-193560303

**Comment by Luterin70** [comment]
Awesome! Thanks for your great work on swatting the bugs and your overall dedication to everything!

**Comment by JanRK** [comment]
I hope this gets implemented. Also, when refreshing, you should consider doing a small icon animation, instead of clearing the whole page.

**Comment by sfkpmr** [comment]
@bastimeyer So the streams should only update when you interact with the GUI?

Surely it should only display currently online streams, or does it build up a notifications buffer until the GUI regains focus?

Every now and then I get a bunch of notifications of mostly offline streams. 

[Screenshot](http://i.imgur.com/E8mgJj2.png)

As you see, the Paradox stream started around 15:00, and ended a few hours later, but I got the notification 6+ hours after it ended. This particular time I got 15+ notifications after these three faded away, lots of offline streams.

**Comment by bastimeyer** [comment]
@sfkpmr 
Notifications are unrelated to this feature request. If you think that there's a bug in the notification system, please open another issue. But from what you're describing, this sounds like a NWjs/Chromium issue with the chromium-rich-notifications being hidden until the application regains focus. Please try using a different notification provider. Since you're on W7, your only other option is using growl, because W7 does not have a native notification system. But let's not comment on this here any further.

**Comment by bastimeyer** [comment]
I'm closing this, since it's not going to be implemented. The new Twitch API will have rate limiting, which makes this kind of feature impossible.
