### ISSUE TITLE
Can no longer retry launching an offline stream.

### ISSUE THREAD

**Issue by SanyaIV** [streamlink/streamlink-twitch-gui#265]
### Description

Previously I have been able to launch an offline stream which would then just retry every 10 seconds (which is what I set it to) and this has been working just fine and worked at least Tuesday the 28th of June, but now when I went to launch an offline stream there is just no way to do it? I'm unable to launch the stream as it gives me no such options. The image that usually holds the play button now doesn't and right-clicking it shows me no "Launch Stream".

No change whatsoever has been made to the software, I haven't updated, modified or uninstalled either Livestreamer nor Livestreamer GUI.
### Expected / Actual behavior

Expected: I expected to be able to "launch" an offline stream and have it retry launching it every X seconds which is defined in the settings.

Actual: There is no way to launch an offline stream (used to be) so there is no way to have it retry launching the stream.
### Reproduction steps
1. Set up desired retry settings in the settings menu and apply them.
2. Go to a channel which is offline.
3. Try to launch it so livestreamer tries to retry launching it. (Hint: no way to do so)
### Environment details (operating system, etc.)

Windows 10 Pro
Not sure what more you need.
### Comments, logs, screenshots, etc.

Not sure exactly what you want, don't know where the logs are located.
Screenshot of the About section and an example of missing play button for offline channel are attached.

![untitled 2](https://cloud.githubusercontent.com/assets/7038749/16592392/c5540c42-42e0-11e6-97a9-5a6324672a21.jpg)
![untitled](https://cloud.githubusercontent.com/assets/7038749/16592393/c573417a-42e0-11e6-8d03-cad73cdfc589.jpg)

**Comment by bastimeyer** [comment]
> Previously I have been able to launch an offline stream

Attempting to launch offline streams was never possible. This has been disabled since the first implementation and did only work, if the shown channel data was not up to date and the channel was incorrectly shown as being online.

By default, trying to launch offline streams with livestreamer will result in it terminating immediately with the `error: No streams found on this URL: twitch.tv/CHANNEL` error message. This was the reason why launching offline streams had been disabled.

When using the `--retry-open` and `--retry-streams` parameters (which have just been added a couple of releases ago), this behavior will change and livestreamer will keep retrying until it the channels starts broadcasting.

So yeah, the offline behavior could technically be changed in the GUI, so people can wait for streams to go live...

**Comment by SanyaIV** [comment]
So in other words, when I was able to launch streams which were actually offline, causing it to retry opening the stream, it was only possible because Livestreamer GUI actually thought the channel was live?

If so I'd like to request a way to retry launching offline streams, either by giving them the normal play button or by right-click > retry or something. Since it actually works and it's able to correctly retry streams, all that is needed is a way to initiate it in the GUI (Which I think is what you just said)

Hope to see this feature added in the future, in the meantime I've created a batch file with the channel I want to watch and such hardcoded. It's not as elegant but it works.

**Comment by bastimeyer** [comment]
> If so I'd like to request a way to retry launching offline streams

That's what I meant why my last sentence. I will see that I will add before the next release...

> in the meantime I've created a batch file

Yes, this works if the desktop notifications are not enough...

**Comment by SanyaIV** [comment]
I've had desktop notifications turned off since I close livestreamer whenever not using it. Don't really like notifications either but I'll give it a try.

Just now noticed a few other features that would be nice when using notifications:
1. Auto-start with Windows (With additional option to launch as minimized when auto-started) That way the user doesn't need to manually start it in order to get notifications after a system reboot.
2. Close to tray (so the cross will minimize the application to tray and you need to right-click it in tray and click "Close applications" in order to close it). Mostly want this because I have a habit of clicking the cross...

I'll personally fix autostart with task scheduler but it'd be nice with a built-in option.

**Comment by bastimeyer** [comment]
> Auto-start with Windows

Just create a shortcut in your [autostart folder](https://www.google.com/#q=windows+autostart+shortcut).
Implemting this feature on all platforms and all desktop environments on Linux can be a bit tedious and challenging. I know that this could also be done by adding a simple entry to the registry on Windows, but I don't want to add features that are not available on all platforms...

> minimized when auto-started

See https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Launch-parameters

> Close to tray

This can already be enabled in the settings menu...

> I've had desktop notifications turned off

You can also set the notifications to a whitelist mode (*exclude all, but...*), so that you're able to enable each channel individually instead of blacklisting channels. This makes it easier for receiving notifications for single channels only...

**Comment by SanyaIV** [comment]
I solved it by creating a scheduled task (I prefer them to autostart folder) and using the tray launch parameter as suggested and it works like it should.

Regarding close to tray. Currently, from what I can see, there is an option to minimize to tray (So clicking on " - " will minimize to tray) but there is no close to tray (where clicking " x " will minimize to tray)
It's not that important really, I just keep accidentally closing the application when I mean to minimize it to tray. =P

I'm going to try notification for all channels and see what I think of it and I'll make changes based on that.

Thanks for the help. =)

**Comment by bastimeyer** [comment]
Closing in favor of #661
