### ISSUE TITLE
Notifications don't stay in the Action Center on Windows 10

### ISSUE THREAD

**Issue by LB--** [streamlink/streamlink-twitch-gui#290]
### Description

Currently, when a notification appears, I have a very short window to see it. Then, it vanishes. It does not go into the action center like all other application notifications do. If I open the action center while it is still visible, it does appear there, but still disappears shortly after.

I have the option to group notifications disabled, but I'm not sure how this could ever be relevant if notifications don't stay, which leads me to believe that this is a bug.
### Expected / Actual behavior

Notification(s) stay in the action center until I dismiss them. I'd also be happy if this was an option that could be toggled on/off.
### Reproduction steps
1. Enable notifications
2. Disable notification grouping
3. Wait for streams to start
4. Watch for the notification in the action center after it times out
### Environment details (operating system, etc.)

Windows 10 Pro 64-bit, version 1607, build 14393.51

![screenshot of version info](https://cloud.githubusercontent.com/assets/1296838/17605885/36f123a8-5fe2-11e6-88da-09c371240176.png)
### Comments, logs, screenshots, etc.

![screenshot of notification settings](https://cloud.githubusercontent.com/assets/1296838/17605812/e1a2e2ba-5fe1-11e6-80f5-463930b4618e.png)

By the way, excellent work! I really appreciate this project.

**Comment by bastimeyer** [comment]
The GUI doesn't have any control of the behavior of notifications. It simply uses the API provided by NW.js, which is basically [`window.Notification`](https://developer.mozilla.org/en-US/docs/Web/API/notification) with pre-enabled permissions.

I don't know anything about the toast notifications API on Windows, but you can [check here what NW.js is doing](https://github.com/nwjs/nw.js/tree/nw-v0.12.3/src) (see the `nw_notification_manager*` files). There won't be any fixes, though, since `v0.12.3` is a legacy version and is not being maintained anymore.

An upgrade to the new and rewritten NW.js `>=0.13.0` (see the progress here: #275) won't fix this issue, because native notifications have been replaced by "Chromium Rich Notifications". I have asked about native notification support (nwjs/nw.js#4560), but the devs said they wanted to build a nodejs addon for this instead of reimplementing it into the platform. This was a while ago and I don't know if this is still the plan.

Having a [nodejs addon](https://nodejs.org/api/addons.html) is again another problem. The nw-builder doesn't support compiling nodejs addons (yet) and I don't think this will ever be implemented. At least not in the near future...

Writing a nodejs addon on our own and adding custom build steps for compiling addons for the used NW.js version could be possible, but this kind of stuff exceeds my competence by quite a bit. Help would definitely be required.

There are node modules available with 3rd party binaries that can create native notifications for all platforms, but those can't be added to the GUI right now because of limitations of the build system. It would also unnecessarily bloat up the builds. I have to think about this.

This answer was maybe a bit too detailed, but I wanted to sum this all up again.

**Comment by LB--** [comment]
Okay, I understand. I think Gitter Desktop uses [this](https://www.npmjs.com/package/node-notifier) which has the ability to wait for user interaction, but maybe this is what you mean by "modules with 3rd party binaries", since it installs a `toast.exe` application on my system in a temp folder. It works pretty well, has a nice clean CLI and supports the ability to wait for interaction, but it sounds like you'd have to refactor your build process to use it?

> It simply uses the API provided by NW.js, which is basically [`window.Notification`](https://developer.mozilla.org/en-US/docs/Web/API/notification) with pre-enabled permissions.

I saw `Notification.requireInteraction` but it seems to be not supported by NW.js, as a full text search could not find `requireInteraction` in any of the source files for the version you linked me. (Or maybe I didn't understand what you meant - I have no experience with NW.js, or anything JS for that matter).

I've also spent like half an hour searching for documentation on the Windows toast notification API but it's really hard to find anything relevant. I did find a [demo program source provided by Microsoft](https://code.msdn.microsoft.com/windowsdesktop/Sending-toast-notifications-71e230a2) that seems to have been rather obviously copied into NW.js (or vice versa) and from there I found some documentation, but it seems like the notification expiration has to be an actual date. I guess you could set that to really far in the future, but the problem is that I can't find any indication that NW.js exposes this property at all. So, dead end there.

Anyway, it's a pretty minor issue. I didn't realize notifications was such a complicated thing until now.

**Comment by bastimeyer** [comment]
Yes, I was talking about `node-notifier`. [These are the 3rd party binaries]...(https://github.com/mikaelbr/node-notifier/tree/v4.6.0/vendor).

I don't know what Gitter is doing with their NW.js/Electron app, but most of these apps simply add their whole `node_modules` folder to their builds, containing their package dependencies, devDependencies and all of the sub-dependencies as well. That's not being done here, because it's a terrible idea and bloats up the builds immensely. I've seen so many other projects from careless devs having issues with the nw-builder because of just that.

Eventually I will be able to include npm packages (and node-notifier) by using webpack instead of requirejs. I'm working on that right now. This is a requirement for the NW.js upgrade I'm looking forward to, because notifications are basically the only thing blocking it right now.

**Comment by jake2xr** [comment]
This may be a very simple fix involving Windows 10 notification settings.

1. Open Windows 10 Settings menu, then click System > Notifications and actions
2. Scroll down to "Get notifications from these senders" and click Streamlink Twitch GUI
3. Change "Show notifications in action center" to On

The default option for that setting seems to be Off. I tested this with the Test Notification button in the GUI and the notification persisted in the Action Center after the toast went away. Please confirm if this change works when actual streams come online.

**Comment by bastimeyer** [comment]
Yep, notifications will only stay in the action center after it has been enabled in the system notification settings. I forgot to close this issue after the implementation of the new notification system.
Thanks for confirming.
