### ISSUE TITLE
Top Games Section, Games without covers should display infos by default

### ISSUE THREAD

**Issue by marteaurouge** [streamlink/streamlink-twitch-gui#315]
In the Top Games Section, you usually select a game by its cover,

Games without a cover use the default "purple twitch logo" picture:
https://static-cdn.jtvnw.net/ttv-static/404_boxart-272x380.jpg

You have to mouseover to actualy discover what game it is,
displaying the infos by default for those games would  be useful,

**Comment by bastimeyer** [comment]
I'm afraid this is not possible.
It would work if the 404 image link was included in the box attribute of the [Game](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.15.2/src/app/models/twitch/Game.js#L9) model, but unfortunately those 404 image urls are the result of a http redirect of the CDN webserver when the real images are unavailable.

See the RCT2 record for instance:

```json
{
  "name": "RollerCoaster Tycoon 2",
  "popularity": 1404,
  "_id": 10260,
  "giantbomb_id": 11178,
  "box": {
    "large": "https://static-cdn.jtvnw.net/ttv-boxart/RollerCoaster%20Tycoon%202-272x380.jpg",
    "medium": "https://static-cdn.jtvnw.net/ttv-boxart/RollerCoaster%20Tycoon%202-136x190.jpg",
    "small": "https://static-cdn.jtvnw.net/ttv-boxart/RollerCoaster%20Tycoon%202-52x72.jpg",
    "template": "https://static-cdn.jtvnw.net/ttv-boxart/RollerCoaster%20Tycoon%202-{width}x{height}.jpg"
  },
  "logo": {
    "large": "https://static-cdn.jtvnw.net/ttv-logoart/RollerCoaster%20Tycoon%202-240x144.jpg",
    "medium": "https://static-cdn.jtvnw.net/ttv-logoart/RollerCoaster%20Tycoon%202-120x72.jpg",
    "small": "https://static-cdn.jtvnw.net/ttv-logoart/RollerCoaster%20Tycoon%202-60x36.jpg",
    "template": "https://static-cdn.jtvnw.net/ttv-logoart/RollerCoaster%20Tycoon%202-{width}x{height}.jpg"
  },
  "_links": {}
}
```

There's no way of implementing such a feature without sending another HEAD/GET http request for each of those images just to check whether the server returns a 3xx status code. This would be terrible solution performance-wise.

**Comment by lukashoegh** [comment]
In theory, couldn't you look at the image pixels after its loaded with canvas?

**Comment by bastimeyer** [comment]
In theory, yes, in practice, no...
Also, once this image gets replaced by a different one, this (crazy overkill) approach would fail

**Comment by lukashoegh** [comment]
Ok, so instead of comparing the images directly, clearly it would be more efficient to just compare file sizes (that having been said canvas is actually very fast, and I do think it would work just fine with that as well).

As for what image to compare it to, you can just load [https://static-cdn.jtvnw.net/ttv-static/404_boxart-136x190.jpg](url) and use that for the comparison.

I could write this is you're interested.

**Comment by bastimeyer** [comment]
Thanks, but it's really not necessary. I appreciate your efforts, though.

Using a stable API endpoint is what ensures the application to work flawlessly with a promise of being some kind of future proof (until certain things get deprecated). Implementing features based on URLs from a CDN on the other hand are not future proof and can break any day. Using just file sizes as a comparison method also doesn't sound like a good implementation. Hashing would be, but with a bigger performance impact.

I honestly don't think that using techniques like canvas can be efficient enough when they are used for many images at the same time. This would increase the rendering time of each PreviewImageComponent and GameItemComponent by too much. Also, using canvas elements instead of simple images could be quite a big hit for Chromium on the drawing speed of the DOM.

Non existent game preview images are such an edge case that I believe it's not worth the effort of programming a way around this. It's Twitch's job to add an image, since the 404 images are displayed on their website, too.

**Comment by lukashoegh** [comment]
Fair enough, up to you of course :)

With regards to canvas performance, I once made a web-app that loaded images of Dota2 items from the steam market place (size around 300*200 pixels if I recall correctly), cropped them, made them black and white, and applied an alpha mask (this was all basically a single arithmetic operation per pixel). There was no noticeable slowdown even with hundreds of images.

**Comment by bastimeyer** [comment]
There could be a solution for this once the chrome extensions API becomes available:
https://developer.chrome.com/extensions/devtools_network

Requires #275 to be merged
