### ISSUE TITLE
Different stream list view options

### ISSUE THREAD

**Issue by alok0** [streamlink/streamlink-twitch-gui#328]
This is a feature request another style of stream list, I'm thinking maybe more of a list format (maybe like Windows's tile view or Outlook 3-line auto preview view).

I'm thinking of a more traditional list, each stream gets a fat row.

Sorta like the header of the channel info page, with the channel icon and three lines.
This plus the game cover art, thumbnail, and if there is still space any of the other channel statistics.

On a side note, the current normal list view could really be helped if the channel name were bigger/bolder, and if it included the channel icon and game cover art.

**Comment by bastimeyer** [comment]
There were some plans in the past to implement different layouts ([there's still a layout attribute in the settings model](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.15.2/src/app/models/localstorage/Settings.js#L48)), but at that time there also were a couple of issues regarding the application's list-implementation and how it worked in the old Ember version. This has changed long time ago, but I still haven't added this feature yet because I don't really see the need of this anymore, other than making it more complicated.

Lists as an alternative to tiles could be added of course, but I'm not really sure if this would be a good idea. Lists do only work well if there's enough data that can be used to fill the entire row. This is not guaranteed when users are responsible for the content. That's also the reason why you rarely see this on other platforms/websites. The tiling layout has the advantage that it only consists of the preview thumbnail image and a couple of brief infos like channel name and viewer count. In a list there's much more space to be filled and this should preferably be done by having long enough texts (channel status/description) and enough data that is *not repetitive*.

Right now I have other tasks with a much higher priority and less risk of unnecessarily wasting time. I will mark this as a feature request, though.

> On a side note, the current normal list view could really be helped if the channel name were bigger/bolder, and if it included the channel icon and game cover art.

This would cause more issues than it would be beneficial. Adding bold or larger text will make everything much more noisy and the structure of the whole menu falls apart. The same can be said about adding icons. Those are either too tiny or if they're large enough too distracting.

**Comment by alok0** [comment]
In the meantime, would it be possible to create a user stylesheet system and maybe even a user template override system? It would be nice to tweak a few things without having to install the whole toolchain.

For example as a minor readablity fix for myself I find this beneficial:
```
.stream-item-component > header > span > a {
  font-size: 1.2em;
}
```

Also there are two things I'd like to note about how the twitch site shows their list
![image](https://cloud.githubusercontent.com/assets/224369/19293274/8ea2a75a-8ff0-11e6-8aea-78c9e3c097d6.png)
- There are varying colors, brighter and darker. It is subtle, but really helps with readability imo. 
- The game cover art sits inside the thumbnail with a border. My suggestion would be to have the channel icon on the left and game cover art on the right in this style, sitting on top of thumbnail.

**Comment by bastimeyer** [comment]
> In the meantime

Don't you think yourself that this sounds just *a tiny, little bit* more complex than adding another stream list view? 😁

> user stylesheet system

I've been asked about custom user stylesheets before. This can be added once #275 has been merged. The currently used NWjs (legacy) version doesn't support CSS variables, but those are required for this kind of feature. Direct stylesheet hacking is not going to be implemented and can be done by building the application on your own.

> maybe even a user template override system

Handlebars templates are being compiled during build time and can't be customized during runtime. I also don't think that Ember's rendering engine Glimmer does support swapping templates on the fly.

> There are varying colors, brighter and darker. It is subtle, but really helps with readability imo.

If you're looking for a higher color contrast, you can try the dark theme. See the "Main" settings menu.

> My suggestion would be to have the channel icon on the left and game cover art on the right in this style, sitting on top of thumbnail.

There are already enough customization options in the "Lists" settings menu. Overloading the stream preview image with more and more stuff and other images is bad. The game icons are also completely useless if a game doesn't have an icon. I honestly dislike these game icons, because they are too small and don't provide real information, unless you know each icon, which is impossible for new or rarely played games.
Adding more images is also bad, because it increases the number of CDN requests by the factor 3 in a worse case scenario. The Twitch website doesn't wait for everything to load before showing the list, because there is no loading animation.
