### ISSUE TITLE
Unexpected version check output

### ISSUE THREAD

**Issue by styxku** [streamlink/streamlink-twitch-gui#348]
### 
Snapshot:
[https://i.imgur.com/2S3NlE4.png](https://i.imgur.com/2S3NlE4.png)

```
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 11, in <module>
from streamlink_cli.main import main
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
from streamlink.stream import StreamProcess
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\__init__.py", line 6, in <module>
from .hls import HLSStream
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 4, in <module>
from Crypto.Cipher import AES
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\__init__.py", line 78, in <module>
from Crypto.Cipher._mode_ecb import _create_ecb_cipher
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
"""
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
```

### 
Getting the error after trying to play any stream. Tested on streamlink cli and the streams open up in mpv as intended. This is after uninstalling livestreamer and livestreamer-twitch-gui. Using the same settings as before. Changing player executable to mpv and using hls as stream type. 

Windows 10 Pro 14393.479
streamlink 0.1.0
streamlink-twitch-gui 1.0.0-win64
Python 3.5.2 64-bit

**Comment by danepark** [comment]
Hi there, I was getting the exact same error and my setup/situation is identical (migrating from livestreamer to streamlink), and this fixed it for me:

Go to Settings -> Streamlink -> Python Executable

I changed    **pythonw.exe**   to    C:\Program Files (x86)\Streamlink\Python\\**pythonw.exe** (or find pythonw.exe wherever you installed streamlink).

**Comment by styxku** [comment]
Yup did the job. Just added my own 64-bit path to test and it gave me the error. Thanks.

**Comment by bastimeyer** [comment]
The "Unexpected version check output" error message means that the validation of Streamlink failed (see the tracelog). **Please make sure that Streamlink and its own dependencies do work with the python version you're using**, especially if you've already installed python on your system.

This is what Streamlink Twitch GUI does while validating Streamlink:
If no custom path was defined, then it will first look for the python executable (`pythonw.exe` on Windows) in one of the directories defined in the system's `PATH` environment variable. If it can't find it, then it will look for it in a list of known fallback paths, which includes the default path of the Streamlink installer. The same is also being done for the `streamlink-script.py` file. This ensures that an installation via `pip` does also work, since the folder is usually included in the `PATH` var.

See the default config:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.0/src/config/streamprovider.json#L17-L60

I knew that the transition might be a bit unsmooth, because Streamlink doesn't use the same bundler as Livestreamer did with its installer. This is why I included the "please re-validate your Streamlink/Livestreamer configuration" in the changelog. I think I need to add all this to the installation guide in the wiki.

Thanks for already helping here, @danepark

**Comment by cfb90** [comment]
How do I create the python script for the streamlink ?
The installer didn't create the script anywhere.

**Comment by bastimeyer** [comment]
`streamlink-script.py` is located in the `bin` subfolder of the install directory when using the Windows installer. When using python-pip instead, it's in the default "Scripts" folder.

You have to make sure that Streamlink and/or Python have been registered in your system's PATH env var, as described in the settings menu next to the input fields, or in the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki).

The registration of the install dir can be blocked by an antivirus software AFAIK. If this is the case you either have to do this manually, or explicitly choose the folder in the Streamlink Twitch GUI settings, so that it is able to find it.

**Comment by cfb90** [comment]
I am using the 64 bits version of the installer, but the installation doens't create a bin subfolder. 
Is it a problem wim my antivirus or is it something else?

**Comment by bastimeyer** [comment]
[**Streamlink** and **Streamlink Twitch GUI** are two different programs...](https://github.com/streamlink/streamlink-twitch-gui/tree/v1.0.0#description)

Also see
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation

**Comment by cfb90** [comment]
Thank you. Now it's working.

**Comment by bastimeyer** [comment]
Closing this now. It's been 10 days since 1.0.0 and most users should have upgraded by now...
Btw, 1.0.1 has just been released
https://github.com/streamlink/streamlink-twitch-gui/releases/latest
