### ISSUE TITLE
Start.sh issue on Fedora 25

### ISSUE THREAD

**Issue by 100Hamburger** [streamlink/streamlink-twitch-gui#349]
Start.sh ends with error "error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory"

**Comment by bastimeyer** [comment]
I'm unable to reproduce this. What's the value of your `LD_LIBRARY_PATH` env var? Maybe there's something wrong. The libnw.so file is located in the `lib` subfolder.

Also, unrelated to your issue, NW.js requires libXss.so.1, which is missing on a bare Fedora25 installation.
`sudo dnf install libXScrnSaver`

**Comment by bastimeyer** [comment]
I forgot to ask if running the main NW.js executable also doesn't work on your sytem.

SDK build
https://dl.nwjs.io/v0.19.0/nwjs-sdk-v0.19.0-linux-x64.tar.gz
Normal build
https://dl.nwjs.io/v0.19.0/nwjs-v0.19.0-linux-x64.tar.gz

The [start.sh](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.0/build/resources/linux/start.sh) script which is included here actually doesn't do much ([anymore, luckily](https://github.com/streamlink/streamlink-twitch-gui/commit/4f9649d3d8ae3ef53fae2545d1f25bb8afca03f6#diff-275a8edf0d9a930191f0d933eebfc423)).

If both don't work on your system and you're sure that this is caused by NW.js, please open a new thread on the [NW.js issue tracker](https://github.com/nwjs/nw.js/issues).

**Comment by 100Hamburger** [comment]
NW.js seems to work (I executetd the nw file in the nwjs-v0.19.0-linux-x64.tar.gz). I don't know, the older livestreamer-tiwtch-gui version 0.16 works fine.

**Comment by bastimeyer** [comment]
The build process had not been changed. And I can assure you that the release is working correctly in my fresh Fedora25 VM.

Maybe you could try redownloading and extracting the archive again.
What is the output of `ldd /path/to/streamlink-twitch-gui`?

**Comment by 100Hamburger** [comment]
linux-vdso.so.1 (0x00007ffc135fc000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3a7353a000)
	libnw.so => not found
	librt.so.1 => /lib64/librt.so.1 (0x00007f3a73332000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f3a7301a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3a72c92000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3a72982000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f3a725ba000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e8d8474000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f3a72342000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3a7212a000)

**Comment by bastimeyer** [comment]
This list should be longer.. There's also ffmpeg.so in the lib subfolder that NW.js uses and references.

What about `readelf -d streamlink-twitch-gui | grep rpath`?
This should return `Library rpath: [$ORIGIN/lib/]`.

**Comment by 100Hamburger** [comment]
It returns  0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/lib/]

**Comment by 100Hamburger** [comment]
If I execute the start.sh with sudo twitch gui starts

**Comment by bastimeyer** [comment]
Are you sure that your current user has read access to all extracted files and folders? Are you trying to run the app with a different user than the one who owns the files?

It looks like the default permissions of the NW.js archives have been changed. All file permissions are now either 600 or 700. The NW.js creators have already messed up the permissions of the MacOS files. This issue is related: #210

**Comment by 100Hamburger** [comment]
Ok I now got it to work. It was a problem of reading permissions. Thanks for your help :)

**Comment by OlliC** [comment]
Had the same problem. I used to download and extract it as my normal user, then copy it to /opt as root and run it as my user. Worked with livestreamer.

**Comment by bastimeyer** [comment]
This has been fixed by ad65661e97870643358ac1d5830bdccb12f32b98
Upcoming releases will have the correct file permissions.
See https://github.com/streamlink/streamlink-twitch-gui/issues/210#issuecomment-265289847
