### ISSUE TITLE
New version not working on XP sp3

### ISSUE THREAD

**Issue by ceceita** [streamlink/streamlink-twitch-gui#352]
### Description

New version not working on XP sp3 the error is
"The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll."

### Environment details (operating system, etc.)
Windows Xp SP3 
Visual studio 2015 runtimes installed

### Comments, logs, screenshots, etc.
I know is very old OS and i dont know how much work is required to support it, so if is too hard to fix just put the minium requirements in the project page , and tell XP users to use v0.16.0 version with livestreamer

as i posted here , https://github.com/streamlink/streamlink/issues/246 Streamlink use Python 3.5 , but win XP supports only Python 3.4 .. and i dont know if that is an easy fix too ..

Thanks and sorry for my english

**Comment by bastimeyer** [comment]
Any compatibility issues regarding NW.js (the platform this app is built on) can't be "fixed". Google has dropped support for XP and Vista in Chromium since version 50. The currently used NW.js version is `0.19.0`, which includes Chromium 55. Any compatibility issues have to be dealt with, and if the app doesn't work, then you have to downgrade to `v0.16.0`. You can use the `--no-version-check` launch parameter, if you don't want to see a weekly popup.

The old release can only be used until februray, though. Twitch has announced some major API changes which will break it. `v1.0.0` also still needs to be upgraded for these changes, but there won't be any upgrades for the old release.

Regarding Streamlink:
Livestreamer can still be used, as described in the changelog. Just select "Livestreamer standalone" from the dropdown in the settings menu and set the path to the old livestreamer.exe (or leave it blank if it's located in the default path or can be found in the system's PATH environment variable).

**Comment by bastimeyer** [comment]
I'm closing this issue...
I'll upgrade the wiki and add a note for WinXP/Vista users
