### ISSUE TITLE
Create nightly builds

### ISSUE THREAD

**Issue by stevek123** [streamlink/streamlink-twitch-gui#360]
Do you think it would be possible to create nightly builds, similar to [streamlinks](https://github.com/streamlink/streamlink/issues/148)?

**Comment by bastimeyer** [comment]
If you can tell me a hoster that is completely free (storage and traffic), I can surely add "nightly" builds.

The difference here is that the builds are pretty large due to NW.js. Also, the Streamlink Twitch GUI archives are available for Windows, MacOS and Linux for both x86 and x64 architectures, whereas Streamlink nightlies are only available for Windows with a 32-bit python env. On MacOS and Linux you don't need an installer because you already have a python environment and Streamlink can easily be installed from the `master` branch of the git repo.

Each commit makes roughly 300MiB if the Streamlink Twitch GUI is built for every available platform (exclusing Windows installers). You can probably guess that once nightlies become available and those are limited to win64 (because this has the biggest userbase), people on other platforms are going to ask for theirs to become available, too.

https://aws.amazon.com/s3/pricing/
https://cloud.google.com/storage/pricing#storage-pricing
https://azure.microsoft.com/en-us/pricing/details/storage/files/
etc...

**Comment by bastimeyer** [comment]
Okay, forget all I have said above.

We can do this by using Github releases on a different repo/account, which will be pretty much painless and less noisy. I have also just seen that Travis CI has added a cron job feature a couple of days ago that can be used by everyone now. This means that we can modify the travis build config to only build once a day (or week) and then upload it to the releases page of the other repo. A simple script can also be created that deletes builds that are older than a couple of days, so we don't abuse the free github releases service that much. I think it's okay to just upload the archives and ignore the Windows installers for the nightly builds.

**Comment by stevek123** [comment]
Great to hear!

I agree, we don't need to create installers for nightly builds, I think a win64 zip will be fine for most of the people. I think we should take a slightly different approach: We should keep the last X nightly releases, run it daily, but we should check first if there were any changes before generating/deleting, if not, then keep everything as is, and don't generate a new one/delete an old one. I hope it makes sense.

**Comment by bastimeyer** [comment]
With the arrival of Github's own CI/CD system a few months ago, having nightly builds for Streamlink Twitch GUI may become possible without having to fall back to stupid hacks or other file hosters due to storage/traffic limitations.

[I've already rewritten Streamlink's CI setup two months ago](https://github.com/streamlink/streamlink/pull/2656) and will be doing the same thing on the Twitch GUI repo soon. This will take a bit of time though, but I have already started the initial work on it a few weeks ago. Once this is done, a simple cronjob could be set up that will store build artifacts, similar to Streamlink's nightly builds. I will have to check the docs and guidelines again though, because I don't know if this will exceed the storage quota.
