### ISSUE TITLE
Problems launching streams in ver.1.0.0

### ISSUE THREAD

**Issue by ThatOneGuyYT** [streamlink/streamlink-twitch-gui#363]
### Expected / Actual behavior
Downloaded the new ver1.0.0 (congrats, btw. love the program), logged in and tried to launch a stream to watch.
1. with streamlink i got:
Error: Streamlink misconfiguration
could not find Python executable.
Please check your settings and/or (re)install Streamlink.
2. same with livesteamer
3. livestreamer (standalone):
Error: Couldn't launch the stream
Unable to find player executable

now, it's weird because:
1. i have livestream (and tried dwonloading streamlink as well)
2. the previous version, 0.16.0 works great.

### Reproduction steps

1. download program exe installer
2. log in
3. try to watch streams

### Environment details (operating system, etc.)
win10 64x
latest version of livestreamer 1.12.2
using VLC

**Comment by bastimeyer** [comment]
> Error: Streamlink misconfiguration
> could not find Python executable.

> Error: Couldn't launch the stream
> Unable to find player executable

Please read the notes next to the input fields in the settings menu or the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

If you don't use any custom executable paths, then the GUI has to guess their locations. The paths will be resolved either by looking into all folders registered in your system's `PATH` env var or by using a list of known default locations. This is being done for both the streamprovider you have selected (Streamlink, Livestreamer or Livestreamer standalone) and also the player.

The Streamlink and Livestreamer installers register the install directory in the `PATH` env var, but this can be blocked by an antivirus software.

You must have selected a custom path in the old version. The new version doesn't use the old Livestreamer settings, even if you've copied/renamed the config folder of the old releases. That's why the changelog includes the "Please re-validate your Streamlink/Livestreamer settings" line.
