### ISSUE TITLE
Smooth Scrolling in v1.0.0

### ISSUE THREAD

**Issue by dojima** [streamlink/streamlink-twitch-gui#365]
Disabling smooth scrolling doesn't seem to work in version 1.0.0 under Windows 7.

Thanks.

**Comment by bastimeyer** [comment]
That's because smooth scrolling has been added and enabled in Chromium since version 49 (the currently used Chromium version is 55, the one being used by the previous releases was 41). This will automatically be used if the custom implementation gets deactivated in the settings menu. I didn't notice this after the NW.js upgrade, because it's barely visible.

The new Chromium behavior can be disabled by setting the `--disable-smooth-scrolling` parameter, but according to [this](https://www.reddit.com/r/chrome/comments/49zn22/how_to_disable_smooth_scrolling_in_chrome/d0x2xdz/) reddit thread, the parameter will get removed in the future, so that it can't be disabled anymore.

Unsmoothed scrolling is just ugly, clunky and simply not modern, especially since the age of smartphones. I don't know any reason why anybody would want to disable it and use the old jumpy scrolling instead. The disable option is only there for people who are using external scrolling modifier programs, which interfere with the javascript implementation in a bad way. The Chromium implementation should not be affected by those programs.

**Comment by dojima** [comment]
Thanks for the info.

Personally, I find normal scrolling to be more predictable, quick, and precise in its movement than smooth scrolling, though I do agree it works well for touchscreen devices.  I find it bizarre that support for the functionality would be removed in the future, as there are many, many people who prefer it, and there's conceivably no harm in leaving it in, but I suppose this is what Google does.
