### ISSUE TITLE
Making it easier to record a stream

### ISSUE THREAD

**Issue by SaDiablo** [streamlink/streamlink-twitch-gui#369]
### Description

I would suggest the ability to save a streams with a separate icon showing that. It is possible to use the -o option example.mp4 parameters in streamlink, but then if you want to open another stream, you have to change settings again etc.

### Expected / Actual behavior

In the settings specify the default path where the recording would be saved, the default type of file names (e.g. {name} - {YYYY-MM-DD HH: mm} - {game} or something like this).
Right-clicking the stream would give possibility to choose the recording quality, like when launching streams. And an additional thing that could be added to this: possibility to open recorded file instantly when created. That could help with watching and recording streams without any additional delay. I think that this could be quite a useful thing for some.

### Comments, logs, screenshots, etc.
Examples
![1](https://cloud.githubusercontent.com/assets/24566138/21195427/03a50942-c234-11e6-8535-7dd8d7cf7d49.png)
![2](https://cloud.githubusercontent.com/assets/24566138/21195442/17111250-c234-11e6-8596-c74056aed77a.png)
PS If something here would be in any of C languages i'd love to help with it, but since it's js and python i can't (yet)
PPS Sorry for bad English

**Comment by bastimeyer** [comment]
Thanks for the suggestion...

Stream recording is already on the 2-do list for a while, but it's more like a long-term goal, because it's tied to the VOD feature which again depends on a rewrite of Streamlink's internal streaming proxy server logic.

Your suggestion of implementing this feature is not ideal, btw. This will result in either watching or recording the stream, because of how the `-o` parameter works.

The way I'm intending on implementing a stream recording feature is a bit different:
My idea is to split the stream output and enable recording while watching the stream.

This would require a rewrite of the stream launch logic, because the GUI would need to launch the player instead of Streamlink. Streamlink then needs to have a new option for having multiple outputs ((named-)pipe and url of internal streaming server). The GUI could then pass the url of the internal streaming server to the player while reading from the pipe and writing the stream to the filesystem whenever it is desired. This way, the stream data will only be downloaded once from the Twitch servers, because streamlink is only running once. Broken video metadata/frames could be fixed by ffmpeg. It's actually a bit more complex, but that's the basic idea.

But before I can think of implementing this, other features with a higher priority need to be added first, like an internal auto upgrader for Windows. Let's see if this can be added next year 😅

**Comment by sadiablos** [comment]
Thanks for answering, and yes, i didn't thought about this as a high priority feature. But there is a way to do that downloading only once (it's only a workaround that i'm using for last 4 months). When recording by -o parameter and launching the file manually, you can watch it with additional +-2s delay(and you can do "oddshots" manually if ya miss something :D), and the options for stream would kinda work (on downloading, but still C: ). 
Btw, do you want to do you want to do whole updater by yourself, or more like using other projects for that? And thanks for your great work :D

**Comment by bastimeyer** [comment]
> there is a way to do that downloading only once

You could also write a wrapper script for streamlink that does something similar to
https://github.com/streamlink/streamlink/issues/105#issuecomment-256678800

> do you want to do whole updater by yourself, or more like using other projects for that?

In comparison to Electron, the NW.js ecosystem basically doesn't exist, so there are no libs/tools that can be used for that. It's not too complicated, though, the implementation was just blocked by other issues and the app rename, which is all done now. I'm a bit busy right now and will look into this in the next weeks, so that it can *hopefully* be added in the next minor release.

**Comment by Nepturian** [comment]
Open the stream with VLC and then record.
Best way as of now.

**Comment by DavidBerdik** [comment]
@bastimeyer - As @Nepturian commented, VLC has a stream recording feature. Until a recording feature is implemented directly in to streamlink, would it be out of the question to implement a flag that could trigger VLC to begin recording automatically once it is launched? I have a stream coming up in a few weeks that someone I know wants to watch and record. I would like to write a batch script to do all of this for them since asking them to click record may be too much.

**Comment by bastimeyer** [comment]
> Until a recording feature is implemented directly in to streamlink

?
https://streamlink.github.io/cli.html#file-output-options

> would it be out of the question to implement a flag that could trigger VLC to begin recording automatically once it is launched

You can do that already if you want

> I would like to write a batch script to do all of this

Then you don't have to the the Twitch GUI

**Comment by DavidBerdik** [comment]
The options that I see in the documentation allow you to record, but not play while recording. Is it not possible or did I miss it?

**Comment by bastimeyer** [comment]
You have to use `--stdout` / `-O` and redirect the output to the player and file output by yourself, like this for example on Linux:
```bash
streamlink --stdout URL QUALITY | tee /path/to/file | player -
```
This question has been answered many times in the streamlink issue tracker and there's also an unfinished pull request for adding a new parameter which does exactly this.
https://github.com/streamlink/streamlink/pull/920
This issue tracker here is not really the right place to ask.

**Comment by DavidBerdik** [comment]
My apologies. The person who I'm writing the script for is running Windows, so I will have a look around to see how I can do it on there. Thank you.
