### ISSUE TITLE
Streamlink version check pattern should be case-insensitive

### ISSUE THREAD

**Issue by devcompl** [streamlink/streamlink-twitch-gui#371]
The version check pattern seen [here](https://github.com/streamlink/streamlink-twitch-gui/blob/ffc64ad499bd1f04d00fbf5150d319459919ec3e/src/app/services/StreamingService.js#L44) needs to be case insensitive because the version reported by portable streamlink (on windows) is "Streamlink.exe 0.1.0".

I had to change the source of streamlink to report the version in lowercase to get the gui to work, otherwise I would get "Invalid version check output" error.

**Comment by bastimeyer** [comment]
Changing the regexp doesn't solve this issue, the value of the first capture group also needs to be turned into lowercase letters.

The portable version (`Streamlink.exe` wrapper) is not supported right now. I don't know how I feel about it and if I want to support it, because there are some things that are not that well thought out. When executing `Streamlink.exe`, there are other unnecessary, meaningless `stdout` outputs that cause the [validation promise](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/src/app/services/StreamingService.js#L352-L367) to be rejected and I think the strict validation should not be removed. Also the streamlink python script is being modified which causes this issue you're reporting.

What you are doing is selecting the included embedded python executable and the ([modified](https://github.com/streamlink/streamlink-portable/blob/69830388bea8d35191c5ffeb1f214296c0a67087/Streamlink%20for%20Windows%20(Source%20code)/Form1.vb#L231)) streamlink python script from the portable-version's directory. You can get all these (unmodified) components from here instead of using the portable version if you don't want or can't use the Streamlink installer:

- https://www.python.org/downloads/windows/  
  x86: https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-win32.zip
  x64: https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-amd64.zip
- https://github.com/streamlink/streamlink/archive/master.zip (`HEAD` of the master branch)  
  or https://github.com/streamlink/streamlink/archive/0.1.0.zip (`v0.1.0` release)

But let me quickly fix this, so that even your method works...

**Comment by bastimeyer** [comment]
Okay, nobody has seen that force push to master 😯 😅
