### ISSUE TITLE
Error: Couldn't launch a stream (Unexpected version check output)

### ISSUE THREAD

**Issue by Koisell** [streamlink/streamlink-twitch-gui#384]
### Description

... When I click on any stream I get the following error:

Error: Couldn't launch a stream
Unexpected version check output

Traceback (most recent call last):
File "/usr/bin/streamlink", line 5, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2958, in <module>

Streamlink works perfectly and all others functionality of streamlink-twich-gui seems to work. Any clues?

### Environment details (operating system, etc.)

... fedora 25 with wayland.
... streamlink-twitch-gui installed from streamlink-twitch-gui-v1.0.1-linux64.tar.gz

**Comment by bastimeyer** [comment]
You have to select a python executable that is compatible with Streamlink in the GUI settings (see the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki)). The issue template already suggests reading the wiki before submitting new issues.

You're seeing this error, because the GUI uses the first python executable found in the `$PATH` env var, which doesn't work on all systems (when multiple python versions are installed). There's no parser implemented in `1.0.1` that reads the shebang of the streamlink python script file and then automatically finds the correct python executable. The reason for this is Windows which needs a different python executable other than the one defined in the shebang.

The master branch already contains a fix/workaround for this issue since a couple of days. I have also pushed some more tweaks just a couple of minutes ago that should finally get rid of this issue on all systems.

Please use the search function next time, this has already been reported dozens of times (these threads have been closed, because it's basically a user misconfiguration and can be solved by setting explicit paths in the settings menu).

I'm leaving this thread open now, so that (hopefully) there won't be any more duplicates.

**Comment by Koisell** [comment]
I tried to look in closed issues but I couldn't identified my case. Sorry for the inconvenience.  I should try that... I found this weird to have gray text...
Streamlink-twitch-gui works fine now. thanks a lot.

**Comment by Meizwe** [comment]
I see what you have said, but I can't really find where in the wiki you are referencing, especially the fixes and workarounds that you said you made. I'm on MacOS but the same Traceback occurs, which python version should I use and can I delete the ones i don't need in frameworks.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

The `1.1.x` releases already contain the tweaked/rewritten streamlink/python resolver. You don't need to define a custom python path in the settings, unless your system is misconfigured, which would also cause streamlink to not work from the shell (when invoking the same streamlink script).

**Comment by Meizwe** [comment]
Eh it says mine says it's 0.2.0 when i look at streamlink from the command line, still wont work when i do the brew for it, so I guess I will just use command line and just use the GUI to give me a heads-up on when my streamers are online…

**Comment by bastimeyer** [comment]
What's the output of running
```bash
which streamlink
head -n1 $(which streamlink)
```

**Comment by Meizwe** [comment]
`/usr/local/bin/streamlink`
`#!/usr/local/opt/python/bin/python2.7`

**Comment by bastimeyer** [comment]
well, then you know which paths need to be set in the settings menu

**Comment by Meizwe** [comment]
VLC closes out like immediately

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/388#issuecomment-270699184

**Comment by Meizwe** [comment]
Switched it to rtmp and it is working! :D

**Comment by bastimeyer** [comment]
Closing this thread now, since a workaround for the issue has been added in the latest release which is out now for 10 days...
