### ISSUE TITLE
Able to change quality w/o opening a new player

### ISSUE THREAD

**Issue by DragonzMaster** [streamlink/streamlink-twitch-gui#395]
First it is not exactly an issue, you can consider it as a suggestion.
----

### Description
When I am watching a stream (using VLC) and decide to change the quality another player window opens
...
So can we make this app change the quality and fetch the new stream and pipe it to the current running player instead of opening a new one !?
As sometimes VLC freezes and cause high CPU usage.

**Comment by bastimeyer** [comment]
No, this can't be done, because of the way Streamlink is being used. The stream data is not being piped into the player for compatibility reasons of other players (on Windows). Using pipes also means that a future VOD implementation would cause players to not be able to seek in the video files. That's why the `--player-passthrough` Streamlink parameter is being enforced by the Twitch GUI.

There's currently no method of telling Streamlink to switch to another quality, so the process has to be restarted with a different quality name. Since Streamlink is responsible for launching the player, a new player process needs to be started as well.

Some players (especially VLC) will ignore any `SIGTERM` signals sent by the parent process, so special player parameters (or settings) need to be set first to be able to close the player. This is mainly the reason why player presets have been implemented here, so that the player can be closed when shutting down the stream from within the GUI or when changing the quality.

If you need to switch qualities often, you should consider choosing a quality that works with connections that have a lower bandwidth. The stream quality can be set globally or in each channel separately.

If VLC feezes (which is not surprising to me since it's quite a bloated player), you should also consider switching to a more lightwight player (eg. mpv).

**Comment by DragonzMaster** [comment]
I was using mpv for awhile but changed to VLC for now but when trying to change quality it hangs and uses 30-40% of my CPU.
Can we at least force closing/killing VLC when there is already a stream is running and we try to change quality ?
May be I move back to mpv.
*sorry for my English

**Comment by bastimeyer** [comment]
> Can we at least force closing/killing VLC when there is already a stream is running

This has already been added. See the player presets in the settings menu and the related VLC parameters.

**Comment by DragonzMaster** [comment]
I'm afraid that this happened even when "Allow the player to get closed" is checked, as the old window is still opened. we need to kill all process related to old stream.
As for the freezing problem it happens sometimes but don't know what exactly make this happen.

**Comment by bastimeyer** [comment]
The `--player-no-close` Streamlink parameter also needs to be disabled or else Streamlink won't even try to close the player... It's at the bottom of the player settings menu.

**Comment by DragonzMaster** [comment]
I haven't enabled it before. But I am fine now so I will close this issue and if something happens again I Will open it again, I hope you don't mind.
Thanks for your replies.
