### ISSUE TITLE
Increase launch attempts

### ISSUE THREAD

**Issue by skapytek** [streamlink/streamlink-twitch-gui#401]
Hello,
Is it possible to increase the launch attempts?
Actually the maximum is 10.
Is it possible to increase this to a user specified setting?
Sometimes the streamer have a problem with his internet connection and this will last for some minutes.

best regards

**Comment by stevek123** [comment]
It's a limitation set by streamlink, not by the GUI.

**Comment by skapytek** [comment]
Ok. Thanks for the anwer. I will contact streamlink authors.

**Comment by stevek123** [comment]
Sorry, my mistake. I mixed it up with a different value. If you are talking about the --retry-open, the max is actually set by the GUI.

**Comment by skapytek** [comment]
![2017-01-26 00_49_35-streamlink twitch gui](https://cloud.githubusercontent.com/assets/11317488/22314357/617e6e0c-e361-11e6-8b7c-db76a6afa170.png)

**Comment by bastimeyer** [comment]
Sure, this can be increased of course.
The current implementation in the GUI when waiting for channels to (re)start broadcasting is not ideal. The `retry-open` streamlink parameter is actually just a little helper tool here. The GUI only lets you launch streams when a channel is online, it won't do this for offline streams. This means that the `retry-open` solution does only work if the view in the GUI has not been updated (yet) and is still showing old data. So until there's no queuing system implemented, an increase of the max value of this option is a good idea. The max value was set, because the input field was copied from the `hls-live-edge` one when I added it. 😛

**Comment by skapytek** [comment]
Thank you very much.
