### ISSUE TITLE
Notifications type randomly changes from Freedesktop to Chromium

### ISSUE THREAD

**Issue by neffers** [streamlink/streamlink-twitch-gui#407]
### Description

I have 'Notification type' set to 'Freedesktop' in the GUI. I used to have it set to Automatic and it would use Freedesktop but it would often randomly reset to Rich notifications.
Having it specified to "Freedesktop" it will still sometimes start displaying Rich notifications

### Expected / Actual behavior

If set to 'Freedesktop' (or other specific type), do not fall back to other options

### Reproduction steps

Not certain. Usually happens while I am playing a game, most often Dota 2 with Vulkan.

### Environment details (operating system, etc.)

Ubuntu 16.04 using XFCE

**Comment by bastimeyer** [comment]
> Having it specified to "Freedesktop" it will still sometimes start displaying Rich notifications

Yeah, looks like there's a little logic error here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/app/services/NotificationService.js#L474
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/app/utils/Notification.js#L83
It should look like that, so that fallbacks are only used when "auto" has been selected:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/app/controllers/SettingsController.js#L279

I'm not sure what would cause the freedesktop implementation to fail after a certain amount of time, though. There's currently no log output for failed notifications (rejected promises are being caught). The error call stack should be printed to stderr...

**Comment by bastimeyer** [comment]
The [`1.2.1`](https://github.com/streamlink/streamlink-twitch-gui/releases/latest) release now has a logging system integrated. Launch the program with the `--loglevel debug` parameter to see debug messages. It'll also create log files in `/tmp/streamlink-twitch-gui/logs`, so you can see what may have caused the freedesktop implementation to fail.

Using the dev build and setting a breakpoint [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.1/src/app/utils/Notification.js#L94) is a better way of tracing this error, though.

**Comment by adrianAnyansi** [comment]
Yes it does still occur on the latest release. I attempted to run a dev build but not having much luck. I've never worked with this tech so I don't know how to enable proper logging. DevTools from the app nor Chrome's 8888 port nor Ember's Chrome extension (does not activate) show any logging information.

**Comment by bastimeyer** [comment]
@adrianAnyansi I think you've replied in the wrong thread... Please delete your response here and post in the other one again, so that we can avoid potential confusion. Thanks

**Comment by bastimeyer** [comment]
The notification system has been rewritten and merged into the master branch.
Freedesktop notifications are now provided by Chromium.
