### ISSUE TITLE
Assertion Failed: A helper named "light-table" could not be found

### ISSUE THREAD

**Issue by domgolonka** [streamlink/streamlink-twitch-gui#408]
I tried to install a few addons like ember-light-table and ember-data-tables but their helpers don't work for me in the template. I get this error: `"Assertion Failed: A helper named "light-table" could not be found"`

I tried to clear all cache, tmp, etc:

`npm cache clear && bower cache clean && rm -rf node_modules bower_components dist tmp && npm i && bower I`
But still not working for me

**Comment by bastimeyer** [comment]
I'm a little confused here... Are you trying to add something new to the application? I'm asking, because I have checked your profile and have seen that you opened two other issues on the "ember-light-table" repo and your logs contained NW.js' chromium extension ID of the streamlink-twitch-gui app.

This is not an ember-cli compatible application. You can't just simply add ember addons that are built for ember-cli without managing all dependencies and module resolvers by yourself.

The reason why ember-cli is not being used is that when I created the project, ember-cli didn't exist yet (or was not being used by Ember yet). There are some major issues with NW.js applications and ember-cli, even though ember-cli-nwjs exists. Also, ember-cli is bloated as hell and uses broccoli and other stuff, which I don't like.

Btw, [you should ask first](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/CONTRIBUTING.md#pull-requests) before blindly going to work and adding something new that might get rejected and costing you a lot of unnecessary time.

**Comment by bastimeyer** [comment]
Closing this since it's been 8 days without any answers...
