### ISSUE TITLE
Add support for communities

### ISSUE THREAD

**Issue by thrstn** [streamlink/streamlink-twitch-gui#409]
The latest feature on twitch is communities https://www.twitch.tv/directory/communities

The feature is still in beta but the API already supports them https://dev.twitch.tv/docs/v5/reference/communities/

**Comment by bastimeyer** [comment]
The v3 API version is still being used here, so communities can't be implemented yet...

Unfortunately, it's not a simple switch, as all channel/stream endpoints are not referenced by names anymore, but by the twitch-users's id, which requires another API request in most cases. I don't know how much work this will be, since I haven't looked into this yet in detail. The deadline for a v5 switch is mid february 2018.

**Comment by bastimeyer** [comment]
The Teams API also needs to be checked again (#93). It looks like they have resolved the issues that prevented an implementation.

**Comment by bastimeyer** [comment]
The Twitch v5 API upgrade has just been completed: d4e9885bc12a1fa578cfaa29f7456899e1a2f2ae

Cummunities and team pages (and also channel news feeds) can now be implemented.

**Comment by bastimeyer** [comment]
I'm not yet 100% convinced by the current implementation of the CommunityItemComponent.
It's basically the same as the GameItemComponent, but unlike game images, community avatars are pretty poor sometimes and either don't show the name of the community and what it is about, or are simply missing. So, I think they need to be displayed a bit differently. I'm not sure if always showing the elementes when hovering the component is a good idea (as requested in #315 for the GameItemComponent when game images are missing... missing images can be detected by the API, though, so it could work, but would be ugly for good community images).

**Comment by bastimeyer** [comment]
Okay, looks like the LessCSS compiler is breaking the InfiniteScrollMixin when compressing the stylesheets because of the identical GameItemComponent and CommunityItemComponent stylesheets.
