### ISSUE TITLE
Chatty Start Location (-cd support)

### ISSUE THREAD

**Issue by i-cant-git** [streamlink/streamlink-twitch-gui#410]
Chatty has a parameter `-cd` which allows users to store Chatty data inside `%cd%` (Windows) / `cwd` (Linux / Mac)

Can you please add a text box below Chatty location path

* If empty, no parameters will be added to Chatty (no `-cd`)
* If **not empty**, app will set CD to specified location and start Chatty with `-cd`

I made an example below to show the change:

Can be empty. Allows user to set start location

![streamlink-chatty-cd](https://cloud.githubusercontent.com/assets/16619091/23086286/bdb1eb5c-f574-11e6-8d6c-477e9cc25595.png)

**Comment by bastimeyer** [comment]
Custom chatty parameters can be added when the chat method selection gets rewritten to the same system the player presets are using (basically chat method presets). Currently, the value of the custom chatty path is shared between the other methods, as you might have noticed. That's the motivation behind this.

Until this gets rewritten, just can use a custom Chatty command line. You can find the used one [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/config/chat.json#L67). Then simply add the `-cd` parameter to it.

**Comment by i-cant-git** [comment]
Right now I have to use a custom `chatty.bat` file:

```batch
@echo off
cd /D "Change to your Chatty location"
Chatty.jar -cd %*
```

and start with this line:

```
…\chatty.bat -connect -channel "{channel}"
```

But if we allow users to set **current directory / start location** for "Custom Application" setting
Users can start any app cares about cwd

Example:
![streamlink-twitch-gui-custom](https://cloud.githubusercontent.com/assets/16619091/23088600/a67faafc-f586-11e6-990d-dd5427f62f79.png)

Then users don't have write a custom script at all.

I think adding start location in Custom Application option is much better than my first proposal because this way you **can set *cwd* for every app that cares about it**.

**Comment by bastimeyer** [comment]
The chat system has been rewritten and will be included in the next release (probably today).

The cwd of each spawned child process is being inherited from its parent, the Twitch GUI. That means that setting the custom -cd parameter will let Chatty use the dir of the Twitch GUI.
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

If you want a specify a different location, you still have to use a custom chat application config or change the CWD of the Twitch GUI. Or you could ask the Chatty dev to add an option for choosing the config dir via a command line parameter, which would be a much better idea.

I don't think that having a setting for a custom CWD is a good idea, because it might confuse users. This is no direct solution to this problem.
