### ISSUE TITLE
Unexpected version check output

### ISSUE THREAD

**Issue by frostpepper** [streamlink/streamlink-twitch-gui#414]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Pressing the white play button on any channel immediately returns an error "Unexpected version check output". 

### Environment details (operating system, etc.)

Solus 2017, Linux 64.

### Comments, logs, screenshots, etc.

![image](https://cloud.githubusercontent.com/assets/25919986/23153285/85788cba-f7bc-11e6-9155-32172fc6f07e.png)

![image](https://cloud.githubusercontent.com/assets/25919986/23153325/bc7bfff8-f7bc-11e6-8e22-1ad3e9a8518c.png)

**Comment by bastimeyer** [comment]
Livestreamer/Streamlink is not correctly set up on your system. Make sure that it's working on its own. This error is unrelated to the Twitch GUI...

**Comment by frostpepper** [comment]
Livestreamer and Streamlink work just fine on their own.

**Comment by bastimeyer** [comment]
Have you set a custom python executable or streamlink/livestreamer script in the settings menu that are incompatible with each other?

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by frostpepper** [comment]
No, I have left both Livestreamer/Streamlink fields blank. Should I instead add something there?

**Comment by bastimeyer** [comment]
Not necessarily. When you don't set any custom values, the GUI will run `which streamlink` and uses this as the "streamlink script" value and `head -n1 $(which streamlink) | cut -b 3-` as the "python executable" value. Basically the same when running `streamlink` from your shell.

But as I've told you, this error message is not coming from the Twitch GUI, but from python, so there must be something wrong on your system. I don't use Solus, so I can't tell you how Livestreamer has been packaged and what's going on there. And btw, you shouldn't be using Livestreamer, since it's been abandoned almost 2 years ago.

**Comment by frostpepper** [comment]
Both stream providers give the exact same errors. If the error is related to my system, then I'll need to do some more research (I consider myself still very new to the Linux env). Thank you for your prompt responses, and I'm sorry if this wasn't the appropriate place to open this issue if it's not coming from the Twitch GUI.

**Comment by bastimeyer** [comment]
Closing the thread since it's a python error and unrelated to the Twitch GUI.
