### ISSUE TITLE
Implement Stream Latency Indicator

### ISSUE THREAD

**Issue by Flat** [streamlink/streamlink-twitch-gui#416]
### Description

FrankerFaceZ includes a little statistics option that shows how far behind your stream is from the broadcaster. It's pretty nice to know how long the actual delay is without attempting to figure it out through the streamer's responses.

[This is how FFZ does it.](https://github.com/FrankerFaceZ/FrankerFaceZ/blob/1b9b695bdd74d539ad77a87407b95d210d2637bf/src/ui/channel_stats.js#L80-L95)

An example of how it looks
![2017-02-22-19 51 32](https://cloud.githubusercontent.com/assets/2048861/23239981/8e0e4108-f938-11e6-9dc1-448933894d68.png)

Now I understand they use data from the player on the twitch page itself, which isn't relevant to streamlink-twitch-gui, as obviously that player isn't used. Would it be possible to get this same information from streamlink and or the twitch api? (if it is possible I imagine it would only be accurate if not using the media players built in cache as that adds additional delay)

**Comment by bastimeyer** [comment]
Somebody sent me an email recently with this same question. Let me try to recap this real quick.

Theoretically, this could be added, but first needs to be implemented in Streamlink. I'll open a feature request for this in the Streamlink repo later on...

Twitch is using the HLS protocol for outputting their streams. The stream data is being cut into tiny data chunks/files (of a certain length/time) that can be accessed via simple https requests. Those chunks are identified by a m3u8 playlist which includes a timestamp. On Linux/MacOS you can run `curl -s "$(streamlink --stream-url twitch.tv/CHANNEL best)"` to see it. Example:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#ID3-EQUIV-TDTG:2017-02-23T01:56:22
#EXT-X-MEDIA-SEQUENCE:21823
#EXT-X-TWITCH-ELAPSED-SYSTEM-SECS:87306.456
#EXT-X-TWITCH-ELAPSED-SECS:87299.595
#EXT-X-TWITCH-TOTAL-SECS:87330.456
#EXTINF:4.000,
index-0000021824-ZIka.ts
#EXTINF:4.000,
index-0000021825-7IPc.ts
#EXTINF:4.000,
index-0000021826-QQ9O.ts
#EXTINF:4.000,
index-0000021827-Outt.ts
#EXTINF:4.000,
index-0000021828-hT92.ts
#EXTINF:4.000,
index-0000021829-yrgH.ts
```

The HTML5 player on the website knows the current delay of the playback, because it is accessing these timestamps while fetching and buffering the playlists and chunks. As you have already mentioned, an implementation in Streamlink would only be accurate, if the local player doesn't add an additional cache when reading the data from Streamlink's internal proxy server.

**Comment by Flat** [comment]
Upstream issue was closed so closing this as.
