### ISSUE TITLE
Notifications are very delayed (40 mins) and grouped up

### ISSUE THREAD

**Issue by vohzi** [streamlink/streamlink-twitch-gui#420]
### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.
Description

Instead of showing the notification at the time the stream starts it shows them grouped with other notifications about 40 minutes later.

...
Expected behavior

Instant notification

...
Reproduction steps / Stream URLs to test

Any stream

    ...
    ...
    ...

Environment details (operating system, python version, etc.)

Windows 7 64 bits python 3.5.2
...
Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
I don't know why you've chosen to use the issue template of the Streamlink repo, but okay...

Which notification provider are you using?

As you can read the in the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications), by choosing the automatic selection, all available providers are being tested first before showing a notification. Chromium's rich notifications are the fallback notifications when all provider tests have failed. Since you're using Windows 7, the only available notification providers for you are Growl and  rich notifications. So when having the automatic notifications selected, growl will be tested first.
The Growl notification provider needs to connect to the Growl server first (TCP ports 23052 and 23053), which can take a bit of time, but the connection time limit is set to [100ms](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/app/utils/notification/NotificationProviderGrowl.js#L34). If there's no Growl server running, then the next notification provider will be tested.

There is no notification spooling logic implemented, so the only reason why notifications can be delayed is the download time of the channel's logo, which is of course notification provider independent.

Notifications are only being grouped when configured in the notification settings menu.

**Comment by vohzi** [comment]
The only notification that works for me is Rich.
It seems unchecking grouped notifications fixed it and now everything is appearing instantly. (To be confirmed)

**Comment by vohzi** [comment]
test

**Comment by bastimeyer** [comment]
Could you please launch the application with the `--loglevel debug` parameter and check the log files for any kind of notification output? Also please make sure to run the latest version (`v1.3.1`).
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

**Comment by vohzi** [comment]
I wasn't running the latest version because I had some bug when I tried to update it from a portable version. 
I now did a clean install of v1.3.1 (portable) with python freshly downloaded and will tell you if this happens again.
It appears that the complilation of python showed the following errors : 

```


The following dependencies are missing:
;deptree
;streamlink+streamlink_cli
;-pkg-resources(indirect)
;-pyparsing
;-packaging
;-six
;-pycountry
;-pycountry
;-Crypto
;-requests
;-certifi
;-idna
;-urllib3

Possible solutions:
-Check if a new version is available at https://github.com/streamlink/streamlink-portable
-Manually add the dependencies to 'Files\Resources\Streamlink_Patches.zip' and build again.
-Use an older ZIP archive rather than latest snapshot
```

However, I can still watch streams and this doesn't have any visible effect (yet)

**Comment by bastimeyer** [comment]
This is unrelated to the Twitch GUI...
https://github.com/streamlink/streamlink-portable/issues/15

**Comment by vohzi** [comment]
So this still happens with the latest version and I have no clue where to find the logs (can't find streamlink-twitch-gui in "C:\Windows\temp\" )

**Comment by bastimeyer** [comment]
This isn't the right temp folder... You have to go to the folder to which the `%TEMP%` env var is pointing, which is `%APPDATA%\Local\Temp` on recent Windows versions in their default user config. The global, system wide temp folder is being for other stuff and nodejs will only use it if the %TEMP% or %TMP% env vars are not defined: https://github.com/nodejs/node/blob/v7.9.0/lib/os.js#L64-L66

I should improve the docs to make this a bit more clear for Windows users...

**Comment by vohzi** [comment]
Alright, found it. There's a bunch of errors here and there... should I send you the logs in a Zip file ?

**Comment by bastimeyer** [comment]
Sure, you can find my email address on my github profile. thanks

**Comment by vohzi** [comment]
Done. Thanks for the help !

**Comment by bastimeyer** [comment]
The notification system has been rewritten and merged into the master branch.
I'm closing the thread here for now.
