### ISSUE TITLE
Bug: Title on hover takes a very long time to load

### ISSUE THREAD

**Issue by SpaceOgre** [streamlink/streamlink-twitch-gui#422]
### Description
When hovering/mouseover a stream the title (at least it is called title in html) takes a long time to show up, over 10s if it shows at all. If I on the other hand click the arrow to show more info it is available straight away so the info is there.

### Expected / Actual behavior
To se the title after 1-2s.

### Reproduction steps

1. Click on Live Streams
2. Hover over a stream
3. Title takes a long to show

### Environment details (operating system, etc.)
Windows 10
Streamlink Twitch GUI 1.2.0

**Comment by bastimeyer** [comment]
Those kind of tooltips are not being rendered by Streamlink Twitch GUI. It's NW.js / Chromium which is responsible for this by calling a Windows API so that the Windows desktop can render a tooltip at a certain position. If there are any tooltip issues, it's either the fault of NW.js / Chromium, Windows or your Windows configuration. I'm not seeing this issue in any of my Windows VMs.

As you've said, these tooltips are coming from a HTMLElement's title property ([DOM level 1 specificiation](https://www.w3.org/TR/REC-DOM-Level-1/level-one-html.html#ID-78276800)). You can see [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/templates/components/list/StreamItemComponent.hbs#L12) and [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/app/components/stream/StreamPreviewImageComponent.js#L32) that the title property is always set on stream preview images when there's data available. There's no logic that somehow defers setting this title property.

A library could be used (similar to Bootstrap or jQueryUI) for showing DOM-tooltips, but this has some disadvantages. Those DOM-tooltips can't be rendered outside of the application window if text lengths exceed a certain limit. Also, in my experience, these libs sometimes do a poor job with the position of the tooltip and scroll events. That's why I don't want to use them.

**Comment by SpaceOgre** [comment]
It is working again, got to love computers some time ^^
