### ISSUE TITLE
Couldn't launch the stream

### ISSUE THREAD

**Issue by Yalzy** [streamlink/streamlink-twitch-gui#424]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

i cant open stream 

i try to set path at setting but still error

### Environment details (operating system, etc.)

window 10 64 bit pro

### Comments, logs, screenshots, etc.

**Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 14, in <module>
from streamlink_cli.main import main
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 14, in <module>
from streamlink import (Streamlink, StreamError, PluginError,
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\__init__.py", line 83, in <module>
from .api import streams
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\api.py", line 1, in <module>
from .session import Streamlink
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 9, in <module>
from streamlink.utils.l10n import Localization
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 10, in <module>
from streamlink.compat import urljoin, urlparse, parse_qsl, is_py2
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\compat.py", line 45, in <module>
from backports.shutil_which import which
ImportError: No module named backports.shutil_which**

**Comment by bastimeyer** [comment]
You need to make sure that you are using the correct python version that Streamlink was built for.
The Streamlink Windows installer already includes a python environment and also updates your system's `PATH` environment variable, so that the GUI is able to automatically find it.

Please try reinstalling Streamlink. Also, please see the wiki with configuration guidelines:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

If this doesn't work, try setting explicit paths to both the python executable and streamlink python script in the GUI's settings menu. Please only use the ones from the Streamlink installation directory.

**Comment by Yalzy** [comment]
i try to uninstall 3 times :( 
still not work
