### ISSUE TITLE
VLC stop working when starting stream

### ISSUE THREAD

**Issue by yuya990** [streamlink/streamlink-twitch-gui#430]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
VLC 2.2.4
streamlink twitch gui 1.2.0
livestreamer v1.12.2
whenever I tried starting a stream with video my vlc player always stops working but it works fine with audio only.

...

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details (operating system, etc.)

...

### Comments, logs, screenshots, etc.
![capture](https://cloud.githubusercontent.com/assets/26740874/24405563/e9ee44f8-13f7-11e7-89c7-0afd342a69d0.PNG)
...

**Comment by bastimeyer** [comment]
VLC seems to be broken / misconfigured on your system. You should try reinstalling VLC and maybe your graphics driver as well.

This issue has nothing to do with either Streamlink or Streamlink Twitch GUI. Please fix your VLC issues first or choose a different player for displaying the stream.

Also, before submitting a new issue, the issue template explicitly asks you to validate that using Streamlink without the Twitch GUI is working fine on your system, so that Twitch GUI unrelated issues can be excluded.
