### ISSUE TITLE
Raspberry Pi / ARM support request.

### ISSUE THREAD

**Issue by fishscene** [streamlink/streamlink-twitch-gui#431]
### Checklist

- [x] This is a feature request.
- [ ] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
What would it take to enable ARM/Raspberry Pi (Raspbian) support?
I would love to see this program on Raspberry Pi for the ability to easily tap into streams on such a low-resource device. Streamlink works perfectly on the Raspberry Pi, but my favorite twitch
I realize this may be a huge undertaking/request, so I ask with the humblest of attitude and the lowest-priority possible.

I've attempted to compile on my Raspberry Pi, but I've run into multiple issues that I have no idea how to troubleshoot or resolve. Suffice to say it appears there's no way around the issues without making this request. Specifically, I'm requesting Raspberry Pi 3 (and higher) support - or at least compiling instructions, if possible. 

### Environment details (operating system, etc.)
Device: Raspberry Pi 3
OS: Raspbian

**Comment by evaryont** [comment]
There is at least community-provided binaries for NW.js on ARM: https://github.com/LeonardLaszlo/nw.js-armv7-binaries

**Comment by bastimeyer** [comment]
@evaryont 
Thanks for the link with up2date builds.

But as I've said, the lib for building/composing the application ([`nw-builder`](https://github.com/nwjs-community/nw-builder)) first needs to be patched to support other architectures. And I'm still not sure if I want to support third party builds.

I was able to build Streamlink Twitch GUI for ARMv7 though by applying some quick hacks to the nw-builder, doing some custom cache folder preparations and adding the needed build tasks here. So if you want to build it yourself, you can do it by following these steps:

1. Download the custom NW.js ARMv7 archive from here:  
    https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.21.6  
    And extract it to `build/cache/0.21.6-normal/linuxarm64` (don't use the archive's root folder)
2. Apply this patch to the git repo (`git apply linux-arm64.patch`):  
    https://gist.github.com/bastimeyer/239671778e3a0275971b64646c14a92f  
    This sets the NW.js version to `0.21.6`, uses a custom nw-builder version patched by me (run `npm install` once), updates all build tasks and creates a `versions.json` manifest file to be used by nw-builder's `manifestUrl` option.
3. Install the [`http-server`](https://github.com/indexzero/http-server) npm module for running a simple local webserver (`sudo npm install -g http-server`) and run it from the root of the git repo like this: `http-server ./`. This is needed because of nw-builder, which loads the manifest from a http(s) server.
4. Then run `grunt build:prod dist:linuxarm64archive` from a non-ARM machine.

The archive can then be found in the `dist` folder. This is all untested since I don't have any device to test this, but it should work - at least the build steps.

**Comment by fishscene** [comment]
I know you don't support it, but I ran into a problem and have no idea how to even proceed. Please, only look into this if you're bored or super willing as I realized this is essentially asking for support.

I noticed an error was thrown when applying the patch, so I looked at the source code in the git and found you may have updated the source files to use 0.21.6, so I modified the patch and it seems to have applied just fine. Here's what I modified the patch with:
sed -i 's/0.21.3/0.21.6/g' linux-arm64.patch
-----------
~/streamlink-twitch-gui$ `grunt build:prod dist:linuxarm64archive`
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token {
Warning: Task "build:prod" not found. Use --force to continue.

Aborted due to warnings.
-----------
Here's a full output with -v:

administrator@Ubu:~/streamlink-twitch-gui$ `grunt -v --force build:prod dist:linuxarm64archive`
Initializing
Command-line options: --verbose, --force

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token {
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:373:25)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load (/home/administrator/streamlink-twitch-gui/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at loadTask (/home/administrator/streamlink-twitch-gui/node_modules/grunt/lib/grunt/task.js:316:10)
>>   at Task.task.init (/home/administrator/streamlink-twitch-gui/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/home/administrator/streamlink-twitch-gui/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/home/administrator/streamlink-twitch-gui/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/lib/nodejs/grunt-cli/bin/grunt:49:20)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load (module.js:343:32)
>>   at Function.Module._load (module.js:300:12)
>>   at Function.Module.runMain (module.js:441:10)
>>   at startup (node.js:139:18)
>>   at node.js:990:3

Running tasks: build:prod, dist:linuxarm64archive
Warning: Task "build:prod" not found. Used --force, continuing.
Warning: Task "dist:linuxarm64archive" not found. Used --force, continuing.

Done, but with warnings.

**Comment by bastimeyer** [comment]
> Ubuntu
> SyntaxError: Unexpected token {

Which nodejs version are you using? Are all dependencies set up correctly?
Debian and Ubuntu usually come with ancient packages, so you either need to register the Nodejs PPA on Ubuntu or compile node yourself.
The grunt `--force` parameter will just skip failed tasks and is pretty much useless. I don't know why they are including this message when errors occur, it's just confusing people.

**Comment by fishscene** [comment]
`nodejs -v`
v4.7.2

**Comment by bastimeyer** [comment]
@fishscene I've updated my build instructions above and pushed the `arm64` branch to the repo.
Please try this instead (the old patch file didn't include the versions.json for some reason, unrelated to your issue, though)...

Node 4 should be okay, but 6 and upwards are the preferred versions. Npm should be at least v3. Then make sure to reinstall all deps again (`rm -rf ./node_modules; npm cache clean; npm install`).

This branch is going to have some conflicts once I've merged the `update-deps` branch. This will switch from npm to yarn and will update lots of deps (currently waiting for webpack3 plugins/loaders to be fixed).

**Comment by fishscene** [comment]
Thanks for doing that bastimeyer. After much playing around, I have proceeded further, but I'm stuck on an error and I suspect it has to do with my build environment on Ubuntu. No matter what platform I try to compile for, I get the same error:

> Running "runtest" task
> Options: startTimeout=5000, testTimeout=300000, logModules, host="localhost", port=8000, path="build/tmp/test/**"
> Using v0.21.6 (sdk)
> Create cache folder in /home/administrator/streamlink-twitch-gui/build/cache/0.21.6-sdk
> Using cache for: linux64
> Launching App
> App exited with code 127
> Fatal error: NW.js exited prematurely

This occurs even on a fresh install of Ubuntu.

@bastimeyer What OS do you use for your build environment? Maybe I can work around this by getting as close to your build environment as I can.

**Comment by bastimeyer** [comment]
> Fatal error: NW.js exited prematurely

Are you by any chance trying to build on a system not running X? Chromium / NW.js requires a running X instance (headless mode has been finally integrated into Chromium 60 / NW.js 0.22, but this is not being used here yet). So in order to build (and run the tests), you need to start `xvfb` (X Virtual Framebuffer):
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/.travis.yml#L26-L27
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

Alternatively, you can just skip running the tests before actually building by skipping the specific grunt tasks (`test`): https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/build/tasks/configs/aliases.yml#L8-L11
`grunt clean:tmp_prod webpack:prod dist:linuxarm64archive`

The builds should be working on all supported systems, so it doesn't matter which one you use. One exception is the requirement of a display server and another one on Windows is that you can't build for *nix systems due to the lack of *nix file permissions.

**Comment by fishscene** [comment]
@bastimeyer I'm thinking we should go ahead and close this as "not supported" or "won't fix".

On Ubuntu fresh install and after creating my build environment. I always got stuck with a "Unable to download NWjs" error, after multiple attempts, eventually it started throwing dozens of errors about "Can't resolve 'bower/........'". Rebuilding my build environment fixed the dozens of issues, but I would get the NWjs error and then eventually the resolve bower issue...

I scrapped it all and spun up a Fedora build and set up my build environment. Again I got stuck on the unable to download NWjs error. I tracked it down to:
./node_modules/nw-builder/lib/index.js (Line 296)
In checking some things out, it appears:
self._version.version = 0.21.6
self._version.flavor = normal
After perusing the directory https://dl.nwjs.io/v0.21.6/, it appears "normal" isn't present, although I'm not certain if it is looking for a file with "normal" in the name. I'm finding reading this code is difficult and I don't recognize the language it is in. This may even be an issue strictly for https://github.com/nwjs-community/nw-builder, but as long as it isn't bothering others building, I don't see this as an issue and am chalking it up to my inexperience. I'm in over my head. :)

Thanks for at least exploring this with me, but unless someone decides to bring the arm build in-house, my vote is to drop this.

**Comment by bastimeyer** [comment]
I don't know what you're doing, but you're doing something wrong...
Let me write down a list of all required steps on a fresh and updated Ubuntu 16.04.02 environment:

```bash
cd ~/Desktop

# install dependencies (why doesn't ubuntu install curl and git? wtf)
sudo apt install curl git

# install node 6 and git
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install nodejs

# clone repo into the ~/Desktop folder and checkout the origin/arm64 branch
git clone --branch arm64 https://github.com/streamlink/streamlink-twitch-gui.git
cd streamlink-twitch-gui

# install the required dependencies for building streamlink-twitch-gui on the arm64 branch
sudo npm install -g bower grunt-cli http-server
npm install

# download and set up NW.js arm64 (nw-builder can't do this since it's not an official build)
mkdir -p ~/Desktop/streamlink-twitch-gui/build/cache/0.21.6-normal/linuxarm64
wget -O /tmp/nwjs-sdk-v0.21.6-linux-arm.tar.gz https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/download/v0.21.6/nwjs-sdk-v0.21.6-linux-arm.tar.gz
tar -xzf /tmp/nwjs-sdk-v0.21.6-linux-arm.tar.gz --strip 1 -C ~/Desktop/streamlink-twitch-gui/build/cache/0.21.6-normal/linuxarm64

# build (requires the http-server to be running, as mentioned in the post above)
http-server ~/Desktop/streamlink-twitch-gui
grunt build:prod dist:linuxarm64archive

# done
ls dist/streamlink-twitch-gui-v1.3.1-linuxarm64.tar.gz
```

I have just tested it and it works flawlessly (although hacky, but I've already said this).
If you have questions, you can join the chat on gitter, so this thread doesn't get spammed.

**Comment by fishscene** [comment]
Huge, HUGE thanks to @bastimeyer for doing some hand-holding.
Here's the bash script I threw together so it is literally copy and paste. It should pop 2 files on your Desktop that you can use on your Raspberry Pi 3. I have found 0 issues so far, except with limitations of playback in a media player such as VLC. (Yes, I did get a picture and audio, then my raspberry pi 3 choked until I only got audio and a frozen picture)

If you copy this into a file, remember to `chmod +x (filename)` the file before executing it.
Using an up-to-date Ubuntu 17.04:
```
#!/bin/bash

rootdir=~/Desktop
gitdir=$rootdir/streamlink-twitch-gui

sudo apt-get install -y curl git libgconf-2-4
#sudo apt-get install -y xvfb  ##Currently testing, possibly not-needed.

# Install node 6 and git
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

git clone --branch arm64 https://github.com/streamlink/streamlink-twitch-gui.git
cd $gitdir

sudo npm install -g bower grunt-cli http-server
npm install

mkdir -p ./build/cache/0.21.6-normal/linuxarm64
wget -O /tmp/nwjs-sdk-v0.21.6-linux-arm.tar.gz https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/download/v0.21.6/nwjs-sdk-v0.21.6-linux-arm.tar.gz
tar -xzf /tmp/nwjs-sdk-v0.21.6-linux-arm.tar.gz --strip 1 -C ~/Desktop/streamlink-twitch-gui/build/cache/0.21.6-normal/linuxarm64

nohup http-server $gitdir >/dev/null 2>&1 &
grunt build:prod dist:linuxarm64archive
killall node #Kills the HTTP server

# done
ls dist/streamlink-twitch-gui-v1.3.1-linuxarm64.tar.gz
cp dist/streamlink-twitch-gui-v1.3.1-linuxarm64.tar.gz ~/Desktop
cp dist/streamlink-twitch-gui-v1.3.1-checksums.txt ~/Desktop
```

**Comment by fishscene** [comment]
Dear me. I see that this is still open. At this point, this works and I'd hate to leave this open indefinitely. Even though support can't be added due to node.js, maybe we can treat this as the odd step-child that doesn't quite fit in. :P

**Comment by RevAngel7** [comment]
Hello everyone! 
I know, this may come as a real surprise, but instead of creating and posting solutions which would help 1% of all ARM CPU users, how much time/energy would it cost to create a working appimage solution for aarch64 for the 99% of these users instead? I am just a linux "user". I can read and experiment, but knowledge and frustration-tolerance is lower in my age-group. I understand that building times are high and can fail even after a high time investment. But it would be really nice to have this "app"-"image" for low power media systems running e.g. a RK3588(s). Thank you for reading and thinking about it. To find reasons, pro / contras is up to you, of course.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/878#issuecomment-1058568508
