### ISSUE TITLE
Chatty not opening

### ISSUE THREAD

**Issue by Echtze1t** [streamlink/streamlink-twitch-gui#432]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Chatty is not opening when clicking the chat icon

### Expected / Actual behavior

Chatty should open when clicking the chat icon

### Reproduction steps

1. I point the GUI to the Chatty.jar
2. I click the chat icon
3. The chat icon shakes and nothing further happens
4. Switching to Chromium works perfectly fine

### Environment details (operating system, etc.)

Windows 8,1

### Comments, logs, screenshots, etc.

I've read every single post and help file I could find about this problem, but nothing is working for me. Are there ANY circumstances under which Streamlink Twitch GUI isn't able to start Chatty, when the exact path to the .jar file is entered? Chatty starts just fine via double click.

I also tried the custom application solution from a different post on github:

javaw -jar "C:\PathTo\Chatty.jar" -single -connect -channel "{channel}"

**Comment by bastimeyer** [comment]
Is your local Java environment set up correctly? [javaw.exe](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/config/chat.json#L72) needs to be found either in one of the paths defined in your system's `PATH` env var or in one of [these fallback paths](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/config/chat.json#L77-L81).
Unfortunately you can't change this in the settings menu yet. It's a bit messy right now and the menu needs a reimplementation so that it works similar to the streaming provider selection.

> I also tried the custom application solution from a different post on github

Custom chat applications need an absolute path (and file extensions on Windows). You can't simply use "javaw", since it's just a keyword that needs to be resolved by your system's shell first. Try running `where javaw` to see the absolute path if it can be resolved. If it can not, then certain env vars are missing or Java has not been set up correctly and may require a reinstallation.

AFAIK there's a new Chatty standalone version. If you're using this, you'll need to use the custom application method and point to the included javaw executable (or chatty executable if it bundled).

**Comment by Echtze1t** [comment]
> C:\ProgramData\Oracle\Java\javapath

is set as `PATH`, I've installed it normally and it works with every other Java application I've tried so far.

I did specify the path now for the custom application like so, but it's still not working:

> C:\ProgramData\Oracle\Java\javapath\javaw.exe -jar "C:\PathTo\Chatty.jar" -single -connect -channel "{channel}"

I'm not using the Chatty standalone version (I think?), there's just the Chatty.jar, a readme.txt and two subfolders "sounds" and "img" in the Chatty directory. Should I try using that version instead?

Anyting else I could try?

**Comment by bastimeyer** [comment]
What's the output when you execute `C:\ProgramData\Oracle\Java\javapath\javaw.exe -jar "C:\PathTo\Chatty.jar" -single -connect -channel "CHANNEL"` from the shell?
There's currently no logging logic included in the Twitch GUI (will be in one of the next releases), so if you want to know whether the command is working, you need to check it manually.

**Comment by Echtze1t** [comment]
Okay, I got it working using this path for the custom application:

> C:\Programme\Java\jre1.8.0_121\bin\javaw.exe -jar "C:\PathTo\Chatty.jar" -single -connect -channel "{channel}"

Which isn't the cleanest solution, because you have to change the path after every update.

**Comment by Echtze1t** [comment]
And when I use the command in a shell

> C:\ProgramData\Oracle\Java\javapath\javaw.exe -jar "C:\PathTo\Chatty.jar" -single -connect -channel "{channel}"

The following error message pops up:

![clipboard image](https://cloud.githubusercontent.com/assets/25301944/24507577/161803ec-1561-11e7-892d-d240ba88bcc8.jpg)

**Comment by bastimeyer** [comment]
> you have to change the path after every update

That's what the `JAVA_HOME` or `JRE_HOME` env vars are for, which the Twitch GUI is using for resolving `javaw.exe`. One of these is usually set by the Java installers on Windows, but can be blocked by an antivirus software.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/config/chat.json#L77-L81

> The following error message pops up

So you've got multiple java environments installed and the one the Twitch GUI uses when resolving `javaw.exe` via the `PATH` env var (which is being done first) is an incompatible one.

> this message is the root of the problem

Most likely. If you don't need this java env, you could try uninstalling it (or removing it from your system's `PATH` env var).

**Comment by Echtze1t** [comment]
Thank you so much for your help, I'm really happy it works again.

Now I just need to figure out which version of Java is best to keep (x86 or x64).
