### ISSUE TITLE
Web Remote

### ISSUE THREAD

**Issue by ioangogo** [streamlink/streamlink-twitch-gui#433]
### Checklist

- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
 I would be a cool feature to allow users to users to use their phones to launch streams and stop ones that are running. This may help people who have this running on the HTPC's but also people who use this program when they are watching streams in bed<sup>1</sup> that is the use case that I originally thought of for this feature. This may just be the interface for the main app on a HTTP server with a few style changes due to this being a NodeJS app or a whole new part of the app.

Edit: By remote i mean not controling the player, but basicly what the UI does now. (This makes no sense)

### Footnotes

1. Like they watch streamers that stream late in their time zone. For example Loading artist is in NZ and I am in the UK so his streams tend to be late at night for me, so I watch them on a monitor over my bed that is connected to a PC 180° to my bed so stoping and stopping and starting streams is a pain(Basicly im being lazy, but that is kind of what happens when you are watching content)

**Comment by bastimeyer** [comment]
Sorry, but this is very much out of scope of this project.

You can't simply run NW.js applications in a normal web browser. All Node.js related code would have to be decoupled and a HTTP REST API would be required to trigger actions from the browser environment. Asynchronous code with UI interactions/responses wouldn't work this way and something more sophisticated (like websockets, etc) would be required, which would be an even bigger overkill. Then you would still have left the issue with the player.

Btw, an application which you've described doesn't require NW.js. A simple Node.js runtime would be enough in order to launch a browser and a http server with backend and frontend code.

If you want to remotely control Streamlink Twitch GUI, you could use a VNC client. This might not be the nicest solution, but it's simple and works.
An alternative could be compiling a development build and starting it with Chromium's `--remote-debugging-port` parameter, opening the dev tools in your web browser and launching/closing streams from the console (which is a bit ugly, though).

**Comment by ioangogo** [comment]
Ah, thanks for the explanation. This is reasonable and i did think after posting this that it would be out of scope for the project

**Comment by ioangogo** [comment]
Although I can see this isnt possible either. I was thinking of a remote control like the software openlp has, where the desktop app is basicly controlled using http request preformed by the remote, i think my description confused you(and myself).

In summary, the remote control i was thinking of wasnt the app but a web site(I said that for some reason in the issue) but the remote resembles the main app, but just sends requests to control the main app and to get infomation to display. But this is overkill and will probably cause proformace issues like you have said allready

**Comment by ioangogo** [comment]
So basicly it'll behave like MPD but have its own UI and the protocol is JSON
