### ISSUE TITLE
Stream qualities don't match the selection

### ISSUE THREAD

**Issue by TheEnhas** [streamlink/streamlink-twitch-gui#434]
### Description

Some partnered Twitch channels use non-standard video settings instead of Source/High/Medium/Low/Mobile. While this has been fixed before, some channels are using differently-named settings once again.

https://www.twitch.tv/imaqtpie is one example. It uses the following video options:

audio_only, 160p, 360p, 480p, 720p, 720p60, 1080p60

I use Medium for default stream quality, so when I try that channel, "480p" is not under the quality presets so the stream defaults to 160p when I launch it.

### Solution

audio_only, 160p, 360p, 480p, and 720p need to be added under the default quality presets.

Also it's really annoying that I can't just add 480p to the rest of the medium preset (or that I can't copy and paste the preset). It erases the entire preset when I do. Yes, I know that I can simply delete 480p later to get the old preset back, but I wish you could just add to it (and have a reset to default button in case you screw something up).

**Comment by bastimeyer** [comment]
Thanks, I was not aware of this. 👍 
Good thing that I haven't released `1.2.1` yet, so this can be fixed today.

> While this has been fixed before, some channels are using differently-named settings once again.

And the hunt continues... 😩 
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/app/models/stream/qualities.js

I'm almost tempted now to download and parse the HLS master playlist and give each quality name a range of min and max video resolutions, so we can target all specific qualities. This would fix this mess until the high, medium and low presets shift, but it would move the logic from Streamlink into the Twitch GUI, and I'm not a big fan of that. As soon as something gets changed on Twitch's end, we can't blame Streamlink or Livestreamer for it.

> I can't just add 480p to the rest of the medium preset (or that I can't copy and paste the preset)

That's because it is showing the default value as a placeholder text. If you enter a custom value, it will be saved in your settings profile. This means that I won't be able to update the default quality presets for users that have already saved the settings once, since their old custom profile would be used instead of the new default one.

> I wish you could just add to it

I know that the current implementation is not great, but I really don't want to add some complex UI elements just for this. The custom quality presets are just there for fixing the qualities until they get fixed in a new release (or if you don't agree with the default ones).

**Comment by bastimeyer** [comment]
It also looks like 144p and 144p30 have been upgraded to 160p and 160p30.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

**Comment by Gabriev** [comment]
I think this is related to this issue, so I'll add it here:

When selecting Source quality, when the source stream is 900p60 it selects 720p60.
On 1.2.1 the default quality preset for Source is "source, 1080p60, 720p60, **best**, 1080p30, (...)".
When changed the order to "source, **best**, 1080p60, 720p60, 1080p30, (...)", like it was in 1.2.0, it properly selects 900p60.

**Comment by bastimeyer** [comment]
This change is required because of Livestreamer which doesn't detect stream qualities that include a frame rate in their name. `best` would match the wrong quality when both `1080p60` and `1080p` are available. See the comment [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.1/src/app/models/stream/qualities.js#L18-L22).

The reason why this is now failing again is that Twitch is now also adding `900p` and more stream qualities which didn't exist before and are not included in the presets.

**For now, you can fix this issue by changing the source preset in the settings menu (please enable advanced settings first).**

-----

To be honest, at this point, I think that simply adding more and more quality names to the presets doesn't make sense any more. This is an endless hunt for new quality names and this hunt always requires new patch releases to be published.

Unfortunately, there's no public API for checking the available stream qualities. The only way of retrieving a list of qualities is getting an access token from a private part of the Twitch API, making another call to the so called usher service of Twitch that requires this access token (and a signature) and then parsing the HLS master playlist.

What I don't like about this approach is, that all these API call would have to be made twice, since Streamlink and Livestreamer need to do the same in order to fetch the stream data. I also don't want to integrate this logic into the Twitch GUI. This is the job of Streamlink.

**This ongoing issue can be fixed by adding stream quality range selections**. Streamlink and Livestreamer both have an [exclude option](https://streamlink.github.io/cli.html#cmdoption-stream-sorting-excludes) integrated that filters quality names to be used by the `best` alias. This can't be used here, though, since streams don't follow the same format. Some stream qualities on Twitch do have the frame rate included, others do not, and others again are labled as `source`, `high`, `medium`, `low` and `audio_only`.
So my idea would be either patching and improving the Streamlink parameter or integrating a range selection (without filtering) into Streamlink, so we can define exactly which kind of stream quality we want to match while being future proof. Users could also still easily change the ranges in the settings menu of the Twitch GUI if they don't agree with the default ones.

Requiring a change in Streamlink would mean that we would have to drop Livestreamer at this point, which I would very much welcome. Would this require a major version bump to `2.0.0` then? Livestreamer has been deprecated since `1.0.0`. I'm not sure. Maybe a minor release is sufficient.

**Comment by bastimeyer** [comment]
Okay, I got confused, we don't need any changes in Streamlink.
Dropping support for Livestreamer is still necessary, though, because we need to filter qualities by frame rate, which Livestreamer doesn't support. And by dropping Livestreamer, we don't need to use fallback qualities, which interfere with Streamlink.

**Testing some random channels that are listing different stream quality formats:**

#### Source

no `--stream-sorting-excludes` and quality `source,best`

```
$ streamlink twitch.tv/pgl_dota source,best
[cli][info] Available streams: audio, 144p30 (worst), 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)

$ streamlink twitch.tv/goldglove source,best
[cli][info] Available streams: 720p60_alt, audio_only, 160p (worst), 360p, 480p, 720p, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)

$ streamlink twitch.tv/summit1g source,best
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
```

#### High

`--stream-sorting-excludes ">720p30,<540p"` and quality `high,best`

```
$ streamlink --stream-sorting-excludes ">720p30,<540p" twitch.tv/pgl_dota high,best
[cli][info] Available streams: audio, 144p30, 240p30, 360p30, 480p30, 540p30 (worst), 720p30 (best), 720p60, 1080p60
[cli][info] Opening stream: 720p30 (hls)

$ streamlink --stream-sorting-excludes ">720p30,<540p" twitch.tv/goldglove high,best
[cli][info] Available streams: 720p60_alt, audio_only, 160p, 360p, 480p, 720p (best, worst), 720p60
[cli][info] Opening stream: 720p (hls)

$ streamlink --stream-sorting-excludes ">720p30,<540p" twitch.tv/summit1g high,best
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: high (hls)
```

#### Medium

`--stream-sorting-excludes ">540p30,<480p"` and quality `medium,best`

```
$ streamlink --stream-sorting-excludes ">540p30,<480p" twitch.tv/pgl_dota medium,best
[cli][info] Available streams: audio, 144p30, 240p30, 360p30, 480p30 (worst), 540p30 (best), 720p30, 720p60, 1080p60
[cli][info] Opening stream: 540p30 (hls)

$ streamlink --stream-sorting-excludes ">540p30,<480p" twitch.tv/goldglove medium,best
[cli][info] Available streams: 720p60_alt, audio_only, 160p, 360p, 480p (best, worst), 720p, 720p60
[cli][info] Opening stream: 480p (hls)

$ streamlink --stream-sorting-excludes ">540p30,<480p" twitch.tv/summit1g medium,best
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: medium (hls)
```

#### Low

`--stream-sorting-excludes ">360p30"` and quality `low,best`

```
$ streamlink --stream-sorting-excludes ">360p30" twitch.tv/pgl_dota low,best
[cli][info] Available streams: audio, 144p30 (worst), 240p30, 360p30 (best), 480p30, 540p30, 720p30, 720p60, 1080p60
[cli][info] Opening stream: 360p30 (hls)

$ streamlink --stream-sorting-excludes ">360p30" twitch.tv/goldglove low,best
[cli][info] Available streams: 720p60_alt, audio_only, 160p (worst), 360p (best), 480p, 720p, 720p60
[cli][info] Opening stream: 360p (hls)

$ streamlink --stream-sorting-excludes ">360p30" twitch.tv/summit1g low,best
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: low (hls)
```

My only concern is that for end users excluding (blacklisting) is not as intuitive as including (whitelisting) stream qualities.

**Comment by bastimeyer** [comment]
I decided against removing Livestreamer support. The new method will only be applied to Streamlink.
Livestreamer's quality presets will fail again though, once Twitch adds new stream quality names.

**Comment by ElPumpo** [comment]
There is also a `900p60` (from LIRIK)

**Comment by bastimeyer** [comment]
@ElPumpo 
Yes, I know, and as you can read in the thread here, this issue has already been fixed three weeks ago. A new release hasn't been published yet though, because I have been and still am a bit busy right now.
I'll see if I can finish the work on the remaining stuff and release `1.3.0` this WE or maybe even on friday. Until then, you can simply fix this issue by yourself and set the value of the **source** quality preset (requires advanced settings to be enabled) in the stream settings menu to `best`. This will override the weird default value which is used to fix Livestreamer's broken quality selection. This ofc requires Streamlink (which should be used anyway) to work.

**Comment by ElPumpo** [comment]
Oh, I didn't notice 0d77e19 attatched to this issue - and yes I'm using the workaround you said.

**Comment by bastimeyer** [comment]
`v1.3.0` has been released:
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

Closing the thread now. Sorry for the delay.
