### ISSUE TITLE
Excessive download and upload

### ISSUE THREAD

**Issue by trollsister** [streamlink/streamlink-twitch-gui#439]
Streamlink twitch download  so much for just one stream, that never happen before.
Impossible to use in fact.
And for no reason python.exe upload a lot i use netlimiter for know what app use my connection.
(And i dont understand why there is an upload ....)
And that upload get crazy too today...
Exemple on chrome stream use 280 kb/s ans 0.8b/s... On streamlink twitch is 1.8Mb/s dl and 500 kb/s ul ....

**Comment by bastimeyer** [comment]
I don't know how Netlimiter works, but Twitch.tv streams in source quality only have a maxium bitrate of 6000kBit/s (which is 750KiB/s). Maybe you have configured Streamlink to use multiple download threads which are downloading stream segments in parallel. Regarding the upload, it is possible that it is measuring "upload" here because of Streamlink's internal streaming relay server from which your player is usually reading when watching streams.

Btw, **Streamlink Twitch GUI** is just a launcher for **Streamlink**. If you have any issues with **Streamlink** (hence python.exe), please go to the [Streamlink Github repository](https://github.com/streamlink/streamlink) instead.
