### ISSUE TITLE
streamlink homebrew installation is not supported

### ISSUE THREAD

**Issue by sacc91** [streamlink/streamlink-twitch-gui#440]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.

### Description

Hi, It seems Streamlink Twitch GUI is not recognizing correctly installs of Streamlink on macOS.

This is the error I get on a fresh macOS installation:

```
Error: Couldn't launch the stream
Unexpected version check output

File "/usr/local/bin/streamlink", line 2
PYTHONPATH="/usr/local/Cellar/streamlink/0.5.0/libexec/lib/python2.7/site-packages:/usr/local/Cellar/streamlink/0.5.0/libexec/vendor/lib/python2.7/site-packages" exec "/usr/local/Cellar/streamlink/0.5.0/libexec/bin/streamlink" "$@"
```

### Reproduction steps

1. Install Streamlink using Homebrew (brew install streamlink)
2. Install Streamlink Twitch GUI using Homebrew Caks (brew cask install streamlink-twitch-gui)
3. Try to launch a stream using Streamlink Twitch GUI (Works fine by CLI)

### Environment details (operating system, etc.)

macOS 10.12.4
streamlink 0.5.0
Streamlink Twitch GUI 1.2.1

### Comments, logs, screenshots, etc.
  
<img width="573" alt="screenshot 2017-04-15 15 53 48" src="https://cloud.githubusercontent.com/assets/255272/25066769/0a649780-21f6-11e7-91bd-daacf59b7d20.png">

**Comment by bastimeyer** [comment]
> Works fine by CLI

What happens when you run Streamlink from the absolute path the Twitch GUI is using?
`/usr/local/bin/streamlink`

What's the output of `which streamlink` / `which python`?

Some macOS apps don't have access to the `PATH` env var. That's why the Twitch GUI needs to include hard coded fallback paths for being able to automatically resolve the python executable and streamlink python script:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.1/src/config/streamprovider.json#L17-L62

There seems to be something wrong on different macOS versions and Streamlink installation methods (easy_install and python-pip).
Could you please see the link above and check the fallback paths? I have a feeling that reversing the order might fix this issue, but I'm not exactly sure.

**Comment by sacc91** [comment]
Calling streamlink with that full path works fine.

This is what I get for which:

<img width="324" alt="screenshot 2017-04-15 18 37 06" src="https://cloud.githubusercontent.com/assets/255272/25067472/8a0ef93a-220a-11e7-86bb-976aab18a634.png">

**Comment by bastimeyer** [comment]
> Calling streamlink with that full path works fine.

Which python executable is it using?
`head -n 1 /usr/local/bin/streamlink`
This is the one the Twitch GUI will use when you don't have anything else defined in the setting menu.

Does this work or does it throw the same error you're seeing in the Twitch GUI?
`/usr/bin/python /usr/local/bin/streamlink`

Please also see this issue: #384

*It's 2am here now, so I won't respond until later today...*

**Comment by sacc91** [comment]
It does throw the same error.

![2017-04-15 at 19 06](https://cloud.githubusercontent.com/assets/255272/25067627/c0c6e0ec-220e-11e7-81dd-d327ee35375e.png)

**Comment by bastimeyer** [comment]
You're seeing this error because you were using homebrew to install streamlink. I didn't notice this yesterday and should have asked immediately. This is not an official install method (yet) and is therefore not supported by the Twitch GUI.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
streamlink/streamlink#398.

The Twitch GUI usually expects the shebang of the streamlink launch script to include the correct python executable, but homebrew creates a **bash** wrapper script, that sets an env var to force a certain python version.

If you run `cat $(which streamlink)` you'll see this after installing Streamlink via

**homebrew**:
```bash
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/streamlink/0.5.0/libexec/lib/python2.7/site-packages:/usr/local/Cellar/streamlink/0.5.0/libexec/vendor/lib/python2.7/site-packages" exec "/usr/local/Cellar/streamlink/0.5.0/libexec/bin/streamlink" "$@"
```
**easy_install** or **pip**:
```python
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'streamlink==0.5.0','console_scripts','streamlink'
__requires__ = 'streamlink==0.5.0'
import sys
from pkg_resources import load_entry_point
 
if __name__ == '__main__':
    sys.exit(
        load_entry_point('streamlink==0.5.0', 'console_scripts', 'streamlink')()
    )
```

I'll add a fix for this later today or tomorrow. Until then, please use the respective python and streamlink paths which are set in the bash script.

**Comment by sacc91** [comment]
I see, I was unaware it was unsupported. I tried to follow the installation instructions first but I only got confusing errors, then I searched homebrew so I could actually install it.

**Comment by bastimeyer** [comment]
@sacc91 Could you please verify that f921170 has fixed the issue?

Build instructions can be found [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.1/CONTRIBUTING.md#developing-and-building) or run this if you've already installed `git`, `nodejs` and `npm`, which runs a dev build off the `streamingservice` branch.
```bash
git clone --branch streamingservice https://github.com/streamlink/streamlink-twitch-gui.git
cd streamlink-twitch-gui
sudo npm install -g bower grunt-cli
npm install
grunt
```

**Comment by sacc91** [comment]
Sorry, this might be over my pay grade. I can't get it to build. I get this:

<img width="652" alt="screenshot 2017-04-16 13 31 59" src="https://cloud.githubusercontent.com/assets/255272/25073292/1533d97e-22a9-11e7-811f-92de4a7af30a.png">

**Comment by bastimeyer** [comment]
You didn't install bower (and probably grunt-cli, too)...
`sudo npm install -g bower grunt-cli`

**Comment by sacc91** [comment]
I did run that and it didn't threw any errors. Could it be a similar thing to this since my node os home-brew too?

**Comment by bastimeyer** [comment]
Try it without sudo. Homebrew might have configured npm to use a different dir for global package installs.

Or see this
https://stackoverflow.com/questions/14803978/npm-global-path-prefix

**Comment by duckness** [comment]
```
git clone --branch streamingservice https://github.com/streamlink/streamlink-twitch-gui.git
cd streamlink-twitch-gui
sudo npm install -g bower grunt-cli
npm install
grunt
```
I also had streamlink installed via brew and did this, it works.

**Comment by bastimeyer** [comment]
@duckness Thanks for confirming this.

The reason why this branch hasn't been merged yet is that I want to use the opportunity to make some further changes to the StreamingService which I already wanted to do long time ago. There a couple of commits which I haven't pushed yet onto the branch of the repo on github. I will still need a bit of time to finish my work because I'm a bit busy with other stuff atm.

So yeah, it's fine, you can use the unfinished work here if you've installed streamlink via homebrew and want it to work without using the workarounds mentioned above. It's no big deal since the code changes won't change the behavior of the app.

**Comment by bastimeyer** [comment]
The fix and the other changes I was talking about have been merged into the master branch.
So until there's a new release, please clone/pull the master branch and build from there and don't forget to report any potential issues. Thanks.
