### ISSUE TITLE
Add external command support to open Twitch URLs/pages/streams

### ISSUE THREAD

**Issue by DebugDotLog** [streamlink/streamlink-twitch-gui#441]
Increase external application support by adding a command interface which will handle the following:

- Displaying Game Page URLs
- Displaying Community URLs
  - Streams page
  - Info page
- Twitch Channels
  - Launching Stream
  - Launching Stream + Chat
  - Displaying Channel info
  - Opening Channel settings
- Displaying other URLs/pages currently handled by Streamlink Twitch GUI

It may be useful to passthrough commands to streamlink, when possible. For example, allow an external application to launch a stream + chat **and specify the media player to be used**.

My immediate use case for this feature will be to open Twitch users' Channel Info pages via a custom Base command and [Chatty's Livestreamer](https://chatty.github.io/help/help-livestreamer.html) context menu option.

**Comment by bastimeyer** [comment]
Thanks again for the suggestion.

The feature is a bit limited by the buggy implementation of NWjs, which means that multiple actions can't be performed at once. This is caused by an incorrect order of the parameters which NWjs returns in the event listener. Unfortunately, this can't be fixed on the application level.

The feature first needs to be enabled in the GUI settings menu (requires advanced settings to be enabled). These are the currently supported parameters (the wiki page will be updated once the next release gets published):
- `--launch CHANNEL`
  Launches a stream by channel name
- `--goto ROUTE|URL`
  See the [router](https://github.com/streamlink/streamlink-twitch-gui/blob/master/src/app/router.js) for all available routes. This can either be a route name with a dot as separator between sub-routes or a URL which can be parsed by the router. If a route requires a model (eg. an ID or a name), the URL format needs to be used. Example: `--goto /games/Dota%202`
