### ISSUE TITLE
Can't view Streamlink via Steam streaming to SteamLink

### ISSUE THREAD

**Issue by Retik** [streamlink/streamlink-twitch-gui#442]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I'm wanting to stream Streamlink to my TV using the Steam in-home streaming feature with a SteamLink. The overlay seems to be working but the screen is black on my TV.

### Expected / Actual behavior

Application should be visible on connected streaming device.

### Reproduction steps

1. Install Streamlink
2. Install Steam
3. Connect SteamLink to TV
4. Add shortcut to Steam library for Streamlink
5. Open BigPicture mode on SteamLink
6. Launch Streamlink
7. Observe black screen

### Environment details (operating system, etc.)

Windows 10 x64

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
I don't own a SteamLink device, but doesn't it work exactly like normal steam in-home streaming? I'm not sure what you're trying to do, but streaming the Streamlink Twitch GUI window will not be a smart idea, because when you're launching a Twitch stream, you won't be able to see the content of the video player. You need to capture your whole desktop in order to watch and browse streams with Streamlink Twitch GUI. If you're getting a black screen, there's nothing that I can do to help you. This is a NW.js application, so if there are any issues which are not caused by the end user, then you need to contact the NW.js or Chromium devs.

**Comment by ddugovic** [comment]
Works on my Windows 10 x64 PC (I launched Streamlink before launching Steam) until I power off the monitor, which causes the video stream (but not the audio stream) to freeze until I power on the monitor.

Pleasantly surprised to see this work when my original aim was just to get Steam working.
