### ISSUE TITLE
Streamlink Could not find Python Script MAC

### ISSUE THREAD

**Issue by RodrigoMayta** [streamlink/streamlink-twitch-gui#443]
Hey Guys I'm using Mac with Sierra on 10.12.4 and the Streamlink is not working, when I Start any channel on Twitch the windows says: "could not find Python script." I already downloaded the Python 3.6 but when I tried to find the item "/Library/Frameworks/Python.framework/Versions/2.7/bin/livestreamer" following this issue https://github.com/streamlink/streamlink-twitch-gui/issues/99 I cant find this "livestreamer" there's only anothers option but no one is "Livestreamer" how to solve this, help guys!    
![captura de tela 2017-04-22 as 01 58 25](https://cloud.githubusercontent.com/assets/27879019/25301503/42ed36b2-26ff-11e7-9784-cd8b0be2c3dd.png)

**Comment by bastimeyer** [comment]
You should follow the wiki when you have trouble installing and configuring "Streamlink **Twitch GUI**". 
https://github.com/streamlink/streamlink-twitch-gui/wiki
The issue template already *suggests* doing this before opening a new issue. 

As you can read in the wiki (and in the project's readme), using Livestreamer instead of Streamlink is not recommended, since Livestreamer support is just there for backwards compatibility and lazy people who haven't switched yet. 

The issue you have linked is more than two years old and totally unrelated to your issue.
