### ISSUE TITLE
Hosted streams are not handled

### ISSUE THREAD

**Issue by h1z1** [streamlink/streamlink-twitch-gui#446]
### Description

Hosted streams are not handled

### Expected / Actual behavior

Expected:
Attempting to view a hosted stream results in errors over and over.

Expected:
GUI warns user, prompts for retry.  Exponential backoff failing that.  Any player errors should not keep trying.

### Reproduction steps

1. ... Attempt to view a hosting streamer
2. ... profit

### Environment details (operating system, etc.)

Latest GIT

### Comments, logs, screenshots, etc.

Found matching plugin twitch for URL twitch.tv/halifax
halifax is hosting aimpr
hosting was disabled by command line option
Waiting for streams, retrying every 1.0 second(s)
halifax is hosting aimpr
hosting was disabled by command line option
halifax is hosting aimpr

**Comment by bastimeyer** [comment]
Hm, that's a very interesting point in time for this issue to be posted. I have just fixed this a couple of hours ago, but haven't pushed the commits to github yet because I went to bed. 😊 I'm on mobile, so I can't do this right now. I should have done it immediately.

That's not really a bug btw. The reason why the error message is printed repeatedly is that streamlink is retrying to open the stream because automatically switching to the hosted stream is disabled. This behavior was added in one of the recent streamlink releases. It needs to be disabled because opening a different stream would be confusing without the GUI knowing.

Also, to be able to encounter this "bug", you have to be a bit unlucky. Since you can only launch live streams, you have to click on a stream with outdated data in the GUI. This happens when you don't refresh or when Twitch is not sending up-to-date data. 

The Twitch GUI will now kill the process when it sees that the channel is hosting another one and will ask the user to switch. I'll push the commits as soon as I get the time.

**Comment by h1z1** [comment]
Maybe a change on Twitch's side ?  I see this quite a bit lately.  Quite often the thumbnail is also missing (generic Twitch purple logo).  

S'pose I think of it more of a bug as the error from streamlink isn't being handled.   More I think about this it might explain why I've seen streams randomly popup?  As in, they start playing even though I've not clicked on them nor necessarily following the steramer.   Looking at processes from that vm I can see 6 since yesterday, all trying to reconnect :<

This one for example is bizarre, I've never viewed the stream nor speak German:

`/bin/python /bin/streamlink --no-version-check --twitch-disable-hosting --player /tmp/ffplay --player-passthrough http --player-continuous-http --player-no-close --hls-live-edge 3 --hls-segment-threads 1 --retry-open 1 --retry-streams 1 twitch.tv/schufatv source,1080p60,720p60,best,1080p30,720p30,540p30,480p30,360p30,240p30,160p30`

**Comment by bastimeyer** [comment]
> I've seen streams randomly popup

There is no way that streams are being started randomly. Streams can only be started by clicking on any of the preview images, on a notification when notification clicks are enabled and on the random stream button of the quick menu in the top right corner.
https://github.com/streamlink/streamlink-twitch-gui/search?utf8=%E2%9C%93&q=startStream&type=

If you think there's something weird going on, you should open another issue with more details. But since you're already using a custom build, you could try debugging it yourself first. Set a breakpoint here
https://github.com/streamlink/streamlink-twitch-gui/blob/50fcfddb258ce851d9d203f52c10c51afc6c8427/src/app/services/StreamingService/index.js#L80
and enable async call stacks and see where the `startStream` call is coming from.
