### ISSUE TITLE
Right-clicking links in channel details now pops up the menu for a second, then opens browser

### ISSUE THREAD

**Issue by Robby-** [streamlink/streamlink-twitch-gui#450]
Right-clicking links in channel details now pops up the menu for a second, then opens the browser, even if you don't select `Open in browser` (or `Copy link address`).

**Comment by bastimeyer** [comment]
I'm unable to reproduce this. Can you please give a specific example.

**Comment by Robby-** [comment]
My OS is Windows 7, 64-bit. Streamlink Twitch GUI v1.3.0.

When I go into the channel details of a stream, you can see some info the streamer puts there, like info of himself, images, links, etc. The image links are fine, its only text links that have this bug.

For example, go to `SheriffEli` his stream, and look for the `Twitter` and `YouTube` links under an image with the text `Follow`, now right-click on either `Twitter` or `YouTube` and the bug should happen. I can consistently reproduce this on my end. Its like the GUI thinks I'm left-clicking at the same time.

**Comment by bastimeyer** [comment]
Hm, this is interesting. Chromium is behaving differently here on Windows than on both Linux and MacOS. This is something you wouldn't expect when developing these kind of web apps on a common platform. And that's why I didn't think it was necessary to test this in a Windows VM after making the changes (eebed66d9db1a6fbc39b2f8633af8d4ad6472805).

So what's happening here is that I had changed the event listeners because of #447 and made the code a bit more dry. Chromium doesn't trigger a `mouseup` MouseEvent when right clicking anchor DOM elements on Linux and MacOS, but does so on Windows. This is not covered by the code and the tests. You will see the same bug happening in the community and team descriptions.

I'll add a fix later. There will be a bugfix release in a couple of days when I think that I have gathered enough other reports that make it worth releasing a new version.
