### ISSUE TITLE
My AV found virus in main .exe file

### ISSUE THREAD

**Issue by Chel0861** [streamlink/streamlink-twitch-gui#455]
- [ ] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

My antivirus found exploit virus in streamlink-twitch-gui.exe file

### Expected / Actual behavior

Actually, I've ignored this. Just know about that

### Reproduction steps

1. Removed streamlink-twitch-gui.exe from quarantine and watching streams

### Environment details (operating system, etc.)

Windows 7 x64
Panda Free Security

### Comments, logs, screenshots, etc.

![streamlink](https://cloud.githubusercontent.com/assets/23583588/26278160/e90eb300-3d9c-11e7-8496-ff5b53f5eee9.png)

**Comment by bastimeyer** [comment]
Your AV software is reporting a false positive here. This can happen from time to time. There's nothing I can do about. If you want, you can report this false positive somewhere on their end.

The executable consists of the NW.js blob and the built application code attached to the end of the file. This is how the `nw-builder` is composing the app and probably the reason why your AV software is doing this.

In case you don't trust me or the file (which I don't think btw 😃), you can check the [build log on TravisCI](https://travis-ci.org/streamlink/streamlink-twitch-gui/builds/233506042) and the checksums and their upload time from the Github API. And if you still don't trust it, you can check the source code.

This could probably be a reason now to sign the files with pgp, but I don't think that anybody on Windows would care. And signing the installers/executables for the Windows UAC system is a no go, since certificates cost hundreds of dollars per year.
