### ISSUE TITLE
Issue I keep having - 'streamlink: error: unrecognized arguments: twitch.tv/imaqtpie best'

### ISSUE THREAD

**Issue by rohitiyer11** [streamlink/streamlink-twitch-gui#457]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
Same error keeps popping up. Been like this ever since switching to streamlink gui from livestreamer gui. I can use my terminal (on a macbook) to open streams just fine using streamlink but the gui isn't working for me probably because I messed something up as I'm not pretty bad with this kinda stuff :(. Not sure what all I need to post here but I'll try to be as thorough as possible. 

Also wanted to quickly note that I've tried searching multiple times since I first go tthe issue and usually give up after a while of searching to just go back to using the terminal to launch a stream. It could be very possible that I just didn't search properly or look for the right stuff as I really have no clue what I'm looking for :(

Updated to latest streamlink (0.6) and latest gui (1.3.0). I've tried reinstalling both of these with the homebrew cask thing as well just incase I messed up installs.

> usage: streamlink [OPTIONS] <URL> [STREAM]
> streamlink: error: unrecognized arguments: twitch.tv/imaqtpie best

Changing preferred quality, different streamer, trying different stream types (hls, rmtp, http) so far haven't worked for me either. Trying to switch from streamlink to livestreamer in the gui will seem to work for a split second as VLC will open up then instantly close.

### Expected / Actual behavior

Get the error above when trying to launch a stream

### Reproduction steps

1. Open the GUI and click live streams tab
2. Click on one to try and watch one through the gui
3. Starts trying to load  in the Preparing to Load window then gives me the error.

### Environment details (operating system, etc.)

- macOS Sierra v10.12.5
- MacBook Pro

### Comments, logs, screenshots, etc.

What the error on the gui looks like: 
![](https://i.gyazo.com/8507a4ac35718d7638531e940b708355.png)

Screenshot of terminal showing streamlink successfully getting a stream up with vlc:
![](https://i.gyazo.com/0e62992b542dc2996dd0dde1c5d16f8c.png)

**Comment by h1z1** [comment]
What are your options under

Misc -> Settings : Settings -> Streamlink and Player ?   If you type "which streamlink", what do you get back?

**Comment by bastimeyer** [comment]
@rohitiyer11 
Don't worry... Could you please check the error log in your system's temp dir (`open $TMPDIR/streamlink-twitch-gui`)? There you will find log files containing the resolved python and streamlink paths and the parameters the Twitch GUI used when launching it. If you want, you can link it in a github gist here (Twitch OAuth tokens may be included).

Otherwise, please check your [streamlink configuration](https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration). The Twitch GUI requires the streamlink python script and a python executable that is able to execute it and its dependencies. Usually, it should be able to resolve these files automatically without custom configurations needed (if installed via homebrew, easy_install or pip).

When executing `streamlink` from your shell (bash), it uses your sytem's `PATH` environment variable to resolve the absolute path of the streamlink python script and then looks up the python executable from the shebang of that file (first line). The Twitch GUI can't use these automated mechanisms, because it doesn't have access to the `PATH` env var.

Run this to find out the paths:
`which streamlink`
`head -n 1 $(which streamlink)`

**Comment by bastimeyer** [comment]
Closing the thread for now, since there hasn't been a response in a week.
Please make sure that Streamlink is working correctly on its own and that the Twitch GUI is using the correct Streamlink installation. The homebrew package should work ootb without any custom configuration. Please uninstall everything streamlink related and try to reinstall the latest package version.

**Comment by jj-279** [comment]
Hi, I just installed Streamlink Twitch GUI today and I am getting this same error. Is there any solution? Windows 10 user here and also a n00b with coding, I'm just looking for some support help in solving this error.

**Comment by bastimeyer** [comment]
@jj-279 Please open a new thread, this one is two years old and probably even unrelated. Please also check #618 first, in case you're running into this issue instead, which is quite likely. Otherwise, see the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki
