### ISSUE TITLE
Bug after updating (Auto-update feature when ?)

### ISSUE THREAD

**Issue by vohzi** [streamlink/streamlink-twitch-gui#458]
Hi,

I find it extremely hard to update this software from an existing portable setup on W7 64 bits.
It's always a hassle and now I get a "couldn't validate pyhon script" when launching a stream after the next update attempt.
The update instructions on the site are non existent, only clean installations are documented, which would overwrite all my custom settings.

Any way to make all this easier ?

**Comment by bastimeyer** [comment]
I agree that it's a bit troublesome to upgrade on Windows while not using a package manager, but implementing an internal upgrade mechanism is not that simple for NW.js applications.

There's already a thread about this (#145), although inactive, so let me sum it up again in this thread here:
There are currently no plans to implement an internal upgrade mechanism to *portable* installations on Windows. Making automated changes to files and directories which users have created by hand is a very bad idea and can lead to data loss of private files.
I have talked about integrating a downloader for the Windows installer a couple of times in the past, but since I'm not a Windows user and since this is still a private project with me working on it in my free time without being paid, I want to spend the time I'm using on this project on other things first. This is an open source project, so if there are things which are extremely annoying to you or anybody else, you can implement them yourself or wait for the community to do so. On Linux, there are other issues with packages for DEB and RPM based package managers (#319), and since I'm not using either of those, the same can be applied here.

Regarding your bug with streamlink portable: see #451 (you didn't even need the search function for this)

Update instructions are not needed when there's no breaking change. The wiki has a page with instructions when updating from the old Livestreamer Twitch GUI, for example. Your settings will never be overwritten and are stored in your home directory (`%LOCALAPPDATA%`), unless you're using a custom NW.js/Chromium parameter (`--user-data-dir=path`).

**Comment by MrLint** [comment]
@bastimeyer I've been poking around the very very far edges of the portableness for windows. If there a file one can grab/read via http(s) to check the current version?

**Comment by bastimeyer** [comment]
> to check the current version

You can either use Github's REST API or Github's releases atom feed:
- https://api.github.com/repos/streamlink/streamlink-twitch-gui/releases/latest
- https://github.com/streamlink/streamlink-twitch-gui/releases.atom

Or you can simply click the watch button on the repo here, so you can see the active development and new releases in your github news feed.

Or you can clone the repo and build the application off the master branch on a daily basis.

**Comment by bastimeyer** [comment]
Closing the thread here now, though, since it's a duplicate. Please use the linked thread if there's anything more to say regarding an internal updating system.
