### ISSUE TITLE
Focus grabbins issue

### ISSUE THREAD

**Issue by MrLint** [streamlink/streamlink-twitch-gui#460]
### Description
When a stream ends, even if the player is not the window with focus, streamlink-twitch-gui grabs takes system focus from frontmost app.
...
### Expected / Actual behavior
streamlink-twitch-gui should return to its last window and wait for user to focus the app.
...
### Environment details (operating system, etc.)
Win 10 x64
streamlink-twitch-gui x64 1.2.1 [and previous] (unzipped/not installed variant)
streamlink portable (portable exe) 0.6.0
VLC 2.2.5.1 (installed)
Chatty 0.8.5.1 x64 with local JRE 1.8.0_121

...
I have not tried to see what happens when streamlink is used alone to launch a stream (yet)
This is a bit troublesome when focus gets stolen away from a game.

**Comment by bastimeyer** [comment]
The only that that Streamlink Twitch GUI does is to show and restore the window if you've enabled an option in the settings menu that the window gets minimized or moved into tray when a stream launches. There are no calls to the OS to request application focus.

I know that there's a NW.js issue where the window gets resized and moved to the center when calling restore() when it's not minimized (or maximized), but AFAIK, it doesn't change the focus. I'll take a look at this when I have the time, but I'm not sure yet if there's anything that can be done.

The focus switch could also be caused by VLC (or by your OS itself), so maybe you could try to use a different player.

**Comment by MrLint** [comment]
@bastimeyer So I'm not sure if if this tell us much but I was watching a stream that was pending ending and before it did I quit the Streamlink Twitch GUI, but left the stream running in VLC. and when it ended focus did not switch from the game I was playing.

**Comment by MrLint** [comment]
With Streamlink Twitch GUI minimized, VLC is killed via cmd and the GUI app pops up and also takes focus from cmd. I guess im going to have to try and chase this back via streamlink directly also

**Comment by bastimeyer** [comment]
> and the GUI app pops up

Does the focus get stolen from your game when the stream ends and GUI is not minimized (minimize option disabled)?

As I've said, the focus API is not being used here, but it may be possible that NW.js is doing this when the GUI is calling the `nwWindow.restore()` option which is being used to unminimize the window.
This `restore` method is acting a bit weird though and also resets the window dimensions and position, but this is a NW.js related issue which I can't fix here. I have reduced the number of calls to the restore method in 364dad52a051b9d5ba6251b46944717264f0b1a6, so that it doesn't get called when the GUI is already unminimized. That's the only thing I can do.

**Comment by MrLint** [comment]
Do nothing appears to have normal behavior, as does using streamlink alone via CLI. I believe i have noticed a 'timing' based issue as the GUI is initializing the stream that has an impact on the focus behavior after VLC is quit.
