### ISSUE TITLE
The process exited with code 2

### ISSUE THREAD

**Issue by morpheus305** [streamlink/streamlink-twitch-gui#461]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I get "The process exited with code 2" when i try open a livestream. I am using streamlink, streamlink twitch gui, and vlc. All three are on the latest updates. I tried using this fix but it didn't work https://github.com/streamlink/streamlink/pull/483/files

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details (operating system, etc.)

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
Do you have any error logs from the streamlink process? An error code alone doesn't say much.

You have to make sure that streamlink itself is working correctly. Please try using it from the shell first to make sure that there are no issues with your system or configuration.

**Comment by bastimeyer** [comment]
Any response?
Being able to know which OS you're on and how you've installed Streamlink would also be good, so that we can figure out what's going on here.

**Comment by morpheus305** [comment]
I'm on windows 10 pro. Where are the error logs stored?

**Comment by bastimeyer** [comment]
Please delete your config file, as you don't need it in combination with the Twitch GUI.

Your streamlinkrc config file uses an invalid format, which is the reason for this. You have copied the git diff as plain text from the PR you've linked. You can't do that... See Streamlink's documentation first before you're making those changes. The changes of the PR are also unrelated to any Twitch streams...

Btw, the "Streamlink is working correctly on my system without using the Twitch GUI." question when opening new issues is there for a reason. 😞 Streamlink is a dependency of Streamlink Twitch GUI and it can't work if the dependent software is not working.

**Comment by morpheus305** [comment]
So you want me to delete streamlinkrc file?

**Comment by bastimeyer** [comment]
> streamlink-twitch-gui is still giving me the same error code

Did you choose the correct python executable and streamlink python script in the settings menu?
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

Error logs are stored in `%TEMP%\streamlink-twitch-gui\logs`. In the log files you can see which files and parameters the Twitch GUI is using.

> So you want me to delete streamlinkrc file?

You don't need it, since you've commented out everything.

**Comment by morpheus305** [comment]
Here's a screenshot of my settings https://gyazo.com/6b7de95458ac6eb5d972ad78b0e36ece

**Comment by bastimeyer** [comment]
Could you please start the application with the `--loglevel debug` parameter, so we can see what exactly is going on? As I've said earlier, exit codes alone don't say much.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

You also appear to be using `v1.3.0`. `v1.3.1` has been releases yesterday:
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

`v1.3.1` has a bugfix for the python resolver logic that was sometimes not using the custom python path with a higher priority than the one extracted from the python script file. Could you please post the content of the streamlink python file while we're already at it? Just to be sure there's nothing wrong here... Thanks.

**Comment by morpheus305** [comment]
Updated to v1.3.1 still getting the same error here is the log file
[2017-05-29_17-25-27.txt](https://github.com/streamlink/streamlink-twitch-gui/files/1036701/2017-05-29_17-25-27.txt)

**Comment by bastimeyer** [comment]
I have removed the link to your uploaded file, because your Twitch oauth token was included in it.

```
[2017-05-29T21:28:22.828Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink.exe",
        "params": "",
        "pythonscript": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink-script.py"
    }
}

...

[2017-05-29T21:28:23.199Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink.exe",
    "params": [
        "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink-script.py",
...
```
You're not supposed to use `streamlink.exe` as `pythonw.exe` here.
If you've installed everything the normal and expected way, you don't need to set any custom paths, so you can't do anything wrong.

See the wiki for a detailed guide:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by morpheus305** [comment]
Alright that did it. Thanks for the help. Is there any way with these programs to choose the server we want to watch video feed from? My twitch always tries to use NYC but it lags during primetime. I would like to try to use the Chicago or Dallas ones if possible.

**Comment by bastimeyer** [comment]
> Thanks for the help

Np. I'm closing the thread since your configuration issue has been solved.

> Is there any way with these programs to choose the server we want to watch video feed from?

A couple of requests have been made in the past, but it turned out that this is against the terms of service of Twitch, so it was never implemented in Streamlink and the Twitch GUI. On the technical side, such an implementation would also not be stable, since it would rely on a list of known DNS record names, which can be changed by Twitch at any time, which would break it immediately.
