### ISSUE TITLE
GUI not coming into focus after clicking on notification while in background

### ISSUE THREAD

**Issue by oakenhold** [streamlink/streamlink-twitch-gui#465]
### Description

The main GUI window does not come back into focus after clicking on notification. This only happens if the window is in the background (not minimized). When I specifically minimized the window and click on a notification, the window will come back into focus.

### Expected / Actual behavior

Expected behavior is for the window to come back into focus after clicking on the notification.

### Reproduction steps

1. Open Streamlink Twitch GUI, and then open another program which will become the active window in focus.
2. Click on notification alert
3. Streamlink Twitch GUI should be brought back into focus as the active window.

### Environment details (operating system, etc.)

Windows 10 64bit
streamlink-twitch-gui 1.3.1
Notification type: Automatic selection (notifications appear as Windows native notifications)
Notification click: Go to favorites
Restore GUI: Enabled

**Comment by bastimeyer** [comment]
This is a regression of 364dad52a051b9d5ba6251b46944717264f0b1a6.

There are a couple of issues in NW.js' `nwWindow.restore()` method, which is responsible for unminimizing and unmaximizing the window. It's not supposed to also focus the window, but has always done so as a side effect. The main issue though is that it sets the window position and size to their default values when the window is not maximized or minimized. That's why I changed the logic of the nwWindow wrapper module, so that it is aware of the current window state and doesn't call restore() if it's not necessary.

What's required here to fix the issue is to also call focus() on a notification click...

**Comment by oakenhold** [comment]
Yup, I think it is a logical interaction to have the window back in focus after a notification click.
