### ISSUE TITLE
Banned channels breaking infinite scroll mechanism

### ISSUE THREAD

**Issue by Robby-** [streamlink/streamlink-twitch-gui#466]
### Description
I can't see more than 21 followed channels. However, at the top, next to `Followed Channels` it says the correct number: `(60)`. There is also no `Loading` message or `Fetch more` button appearing at the bottom.
I also looked at the logfiles that are produced but there's nothing useful in them, even with `--loglevel debug`.

### Expected / Actual behavior
Expected: I should be able to see the full list of followed channels.
Actual: Only 21 channels are shown.

### Reproduction steps
Under `My`, click on `Channels`.

### Environment details (operating system, etc.)
Windows 7 SP1, 64-bit
Streamlink Twitch GUI 1.3.1

**Comment by bastimeyer** [comment]
Is it possible that one of your followed channels is banned? There was a similar issues a couple of months ago in the subscriptions list.

The reason why I'm asking is because of the implementation of the infinite scroll logic here. It's not making use of the `_total` metadata returned by Twitch API responses. The reason for this is that certain API calls won't return this metadata, so it's not possible to know the total amount of records of all routes. What the InfiniteScrollMixin does is [comparing the returned number of records with the requested number](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/mixins/InfiniteScrollMixin.js#L235-L237). When the returned number is lower than the requested one, this *usually* means that the end of the list has been reached.

That's why I'm asking about banned channels. Twitch seems to just leave out banned channels in the API responses, instead of filling the missing slots with additional channels.

This issue could be fixed by making use of metadata, but as I've said, this is inconsistent. But yeah, not being able to browse the whole list is definitely an issue.

**Comment by Robby-** [comment]
Yes, there is indeed one banned channel that I know of.

**Comment by Robby-** [comment]
Would it be possible to unfollow banned channels if one knows its name? Or does the API not allow for such a thing (and thus are stuck with this)? If it is possible I'll leave it like it is for now, though, for the purposes of this bug report.

**Comment by bastimeyer** [comment]
As long as you're able to retrieve data from the API, you're able to unfollow.

**Comment by Robby-** [comment]
Ok, cool. I know Chatty has an `/unfollow <channel>` command and I was hoping to do it that way.

**Comment by bastimeyer** [comment]
@Robby- 
Could you please see if the changes are working for you? This *should* be covered by the added tests, but I'd like to know if I haven't missed anything here. I don't have any banned channels in my following list, so I can't test this myself and need some help. Thanks!

The changes are on the `infinite-scroll` branch:
ac04bfa / https://github.com/streamlink/streamlink-twitch-gui/compare/master...infinite-scroll

Build instructions:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/CONTRIBUTING.md#developing-and-building

```bash
git clone -b infinite-scroll https://github.com/streamlink/streamlink-twitch-gui
cd streamlink-twitch-gui
npm install -g bower grunt-cli
npm install
grunt release
```
