### ISSUE TITLE
nwjs has stopped working 

### ISSUE THREAD

**Issue by Kiwical** [streamlink/streamlink-twitch-gui#471]
I updated my graphic card drivers now streamlink doesnt work at all i just get the nwjs as stopped working.
Win7 64bit 

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	streamlink-twitch-gui.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58ee70ee
  Fault Module Name:	nw.dll_unloaded
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	58ee6e98
  Exception Offset:	000007fee4248990
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	5129
  Additional Information 1:	c82f
  Additional Information 2:	c82fb04efe6e81efed2627847af1a3aa
  Additional Information 3:	5928
  Additional Information 4:	5928495b5324c5ad9192154efdf91b3d

**Comment by bastimeyer** [comment]
This is a upstream NW.js / Chromium issue, which is caused by your system configuration. There is nothing I can do here to help you other than suggesting to reinstall it and to clean the config/cache folder.

Please try to run an empty NW.js application from [here](https://dl.nwjs.io/v0.21.6/). If the issue persists, you should go to the issue tracker of [NW.js](https://github.com/nwjs/nw.js) or Chromium. But first, you should try to solve your issue by googling the error name: https://www.google.com/search?q=BEX64%20chromium

**Comment by Kiwical** [comment]
Cheers for the reply yeah i did a clean install and it fixed itself.

Thanks
