### ISSUE TITLE
Chat opens again on stream restart

### ISSUE THREAD

**Issue by h0rn3z0r** [streamlink/streamlink-twitch-gui#475]
### Description

When I press "restart" this program opens new Chatty window and I need to close it everytime.

### Environment details (operating system, etc.)

Windows 10

### Comments, logs, screenshots, etc.

I suggest to not open chat window again if there is already one, or add an option to automatically close chat on stream restart/close so this will fix this issue aswell.

**Comment by bastimeyer** [comment]
Which version of Chatty are you using?
Chatty has a single instance mode implementation, where it can't be launched multiple times and instead passes launch parameters to the already running main process which then opens a new chat tab instead. The Twitch GUI uses Chatty's `-single` parameter by default, so unless you're running an old Chatty version or you're using a custom Chatty command without the `-single` parameter, multiple Chatty windows should not be popping up.

As I've described in #240, the Twitch GUI does not keep track of already running chat applications, because it's not possible to implement something that understands the various behaviors of each program (eg. single instance modes).

The restart function is something different here though and chat programs should never be launched again when restarting a stream.

**Comment by h0rn3z0r** [comment]
Thanks for the answer. I had to mention that I am using Chatty 0.8.6 standalone (cause I dont want to install java just for one small programm), and because Twitch GUI expect chatty.jar in chatty folder I am forced to launch Chatty as a custom application like that: "D:\Programs\Chatty\Chatty.exe -connect -token "{token}" -channel "{channel}"". So for now I just added -single parameter and I think you can close this. Maybe you could add Chatty.exe support at least?

**Comment by bastimeyer** [comment]
> Maybe you could add Chatty.exe support at least?

The chat application preset list is using an older implementation and needs a rewrite first. I have mention this in https://github.com/streamlink/streamlink-twitch-gui/issues/410#issuecomment-280794216. I'll see if I can add a "Chatty standalone" profile, similar to the "Livestreamer standalone" streaming provider profile, once I have completed the rewrite.

**Comment by sadiablos** [comment]
I'll add also a little request for the Tc chat preset then.
