### ISSUE TITLE
32 bit python cannot cache more than 4 GiB

### ISSUE THREAD

**Issue by Jeeaaasus** [streamlink/streamlink-twitch-gui#476]
I use streamlink together with the streamlink twitch GUI and MPC-HC and would like to cache more than 4 GiB but since it's an 32 bit python, python crashes.. How can I change the python to 64 bit? 

I've tried installing 64 bit python but streamlink gives me the **unexpected version check** error when launching streams.
I feel like this is possible, I'm just too stupid.. 

Thanks everyone! 👍

**Comment by bastimeyer** [comment]
The Streamlink installer for Windows bundles a x86 python environment and byte compiles all included python script files on installation for faster startup times. If you change the python executable afterwards with a different one which the python script files have not been compiled for, you won't be able to execute them.

You're seeing the unexpected version check error in the Twitch GUI, because streamlink itself doesn't work on your system and the python executable is not returning streamlink's initial version check output. A working streamlink installation is a requirement of the Twitch GUI as stated multiple times in the readme and wiki, hence the checkbox in the issue template which you've ignored. :confused: 

You can either request an x64 installer on the streamlink repo or manually install an x64 python environment and install streamlink via `python-pip`:
https://streamlink.github.io/install.html#source-code

I don't understand though why someone would want to cache more than 4GiB of stream data in streamlink's own buffer. This doesn't help in any way with lagspike or stuttering issues. What you actually want to do is to increase the buffer of your player, which is independent from streamlink's buffer, so you can jump to different playback positions in the cached stream data. At least that's what I think was your idea, right?

**Comment by Jeeaaasus** [comment]
Okej, very informative, thank you! 

> I don't understand though why someone would want to cache more than 4GiB of stream data ... What you actually want to do is to increase the buffer of your player

Yes this is what I should do, but under Common Issues for MPC-HC caching, it says "Currently no way of configuring the cache". Is it possible to cache with MPC-HC?

I'll be installing streamlink through pip from now on then. Thank you! :)

**Comment by bastimeyer** [comment]
> Is it possible to cache with MPC-HC?

I'm not sure, I don't use MPC-HC. All I know is that there are no command line parameters and that you need to configure caching elsewhere:
https://www.google.com/#q=mpc+hc+caching

I recommend using [mpv](https://mpv.io/) instead, which is extremely configurable and much more powerful. And it's not Windows exclusive.

Closing the thread now...
