### ISSUE TITLE
Stream fails to specified stream sources, lists an available source not in list

### ISSUE THREAD

**Issue by xingped** [streamlink/streamlink-twitch-gui#479]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

When launching a stream, it fails to launch with an error stating the following...

```
error: The specified stream(s) 'source, 1080p60, 900p60, 720p60, best, 1080p30, 900p, 720p30, 540p30, 480p30, 360p30, 240p30, 160p30' could not be found.
Available streams: 810p60, audio_only
```

### Expected / Actual behavior

Expected stream would launch. Stream fails to launch with the error above.

### Reproduction steps

1. Attempt to launch a particular stream which is not streaming with one of the above stream sources. Unsure which streams cause this, but it was noted on twitch.tv/Sir_Jynx

### Environment details (operating system, etc.)

Windows 10 x64
Streamlink Twitch GUI v1.3.1

### Comments, logs, screenshots, etc.

http://imgur.com/a/T1sQr

**Comment by bastimeyer** [comment]
You need to use Streamlink instead of Livestreamer as the selected streaming provider. This can't be fixed when using Livestreamer, that's why the `1.3.0` release included changes to the stream quality selection method:
[v1.3.0 changelog](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CHANGELOG.md#v130-2017-05-18) (and the related issue #434)

There's also a section about this in the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities

**Comment by xingped** [comment]
Installing and switching to Livestreamer did fix the problem. Thank you!
