### ISSUE TITLE
"Time Out"

### ISSUE THREAD

**Issue by XeterSilvaPT** [streamlink/streamlink-twitch-gui#485]
### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
my streamlink anytime , i try to watch a stream just says "time out".
...

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details (operating system, etc.)
windows 7 
...

### Comments, logs, screenshots, etc.

...
![tiem out](https://user-images.githubusercontent.com/29165031/27937681-c2aafda2-62b0-11e7-971e-1040e0d9ed84.PNG)

**Comment by bastimeyer** [comment]
A little bit more information would really be appreciated, which is the reason why this issue template exists, so that people will hopefully take the time reading the guidelines and filling out the questions with detailled answers.

What you're seeing is most likely the streaming provider validation timeout error message. Streamlink Twitch GUI needs to validate your Streamlink (or Livestreamer) configuration and needs to execute the selected provider executable once to check its validity and its version. There is a time limit for this though, so that people don't get stuck in a non-ending validation process when they're using invalid settings. This time limit is set to 10 seconds.

Since your attached screenshot is showing some weird font rendering, I'm guessing you're trying to run the program on an older machine, where launching the Streamlink executable probably takes a little bit of time. If this is the case, then there's little I can do to help you here. You could either try to manually run the Streamlink executable once in order to let your OS cache all the files that need to be read from the filesystem. Or you could build Streamlink Twitch GUI on your own and increase the [validation timeout value](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/config/streamprovider.json#L12).
