### ISSUE TITLE
 Invalid client id specified

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#490]
As of today I receive this error whenever I start the program. Neither am I logged in anylonger and the URL yields this error:

```
{"error":"Bad Request","status":400,"message":"No client id specified"}
```

URL
```
https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=phiay4sq36lfv9zu7cbqwz2ndnesfd8&redirect_uri=http%3A%2F%2Flocalhost%3A65432%2Fredirect&scope=user_read+user_blocks_read+user_blocks_edit+user_follows_edit+user_subscriptions+chat_login
```

Version: 1.3.1 on Ubuntu x64 16.04

**Comment by ReiGelado** [comment]
I noticed the same error here, probably the twitch removes the key from the client because it does not display the ad in the videos:
Url:
` https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=phiay4sq36lfv9zu7cbqwz2ndnesfd8&redirect_uri=http%3A%2F%2Flocalhost%3A65432%2Fredirect&scope=user_read+user_blocks_read+user_blocks_edit+user_follows_edit+user_subscriptions+chat_login  `
Code:
'{"error":"Bad Request","status":400,"message":"No client id specified"}'

**Comment by bastimeyer** [comment]
I immediately checked the API responses when I saw this thread and the servers returned a 400 (request error). But noow they are returning 500 (a server error).

Streamlink Twitch GUI correctly sets the client-id header since 191c9dc147ae53227e483db18902dc1f7227c1a2 (v0.14.0), as you can see here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/store/TwitchAdapter.js#L22

More info here:
https://discuss.dev.twitch.tv/t/client-id-will-be-required-in-august/6032
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843

This looks like an issue on their end, but let's wait and see...

**Comment by pquerner** [comment]
Now (periodically) yields

```
{"error":"Internal Server Error","status":500,"message":"Internal Server Error"}
```
(HTTP 500)

**Comment by Kiwical** [comment]
Also www,twitch.tv wont even load its just white for me.
I did manage to load in games using the gui but clicking on the thumbnail resulted in python script error saying i had to reinstall gui.

**Comment by bastimeyer** [comment]
The `/kraken/streams/followed` endpoint is still working fine as it seems:
```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  -H "Authorization: OAuth ***YOUR OAUTH TOKEN HERE***" \
  "https://api.twitch.tv/kraken/streams/followed"
```

but the `/kraken/` endpoint is returning a 500, which is required for validating the cached oauth token at the application launch:
```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  -H "Authorization: OAuth ***YOUR OAUTH TOKEN HERE***" \
  "https://api.twitch.tv/kraken/"
```

**Let's all chill and wait for Twitch to resolve their server issues...** 😴

@Kiwical, no, you don't have to reinstall anything here... and the Twitch GUI is not based on Python either

**Comment by pquerner** [comment]
@bastimeyer So shall this issue be closed as its no issue with the app?

**Comment by bastimeyer** [comment]
Let's keep this open, so we don't get unnecessary duplicates 😄

**Comment by bastimeyer** [comment]
I'm closing the thread... The Twitch API seems to be working again.
