### ISSUE TITLE
can not open japanese title streaming

### ISSUE THREAD

**Issue by thtv83pvewov** [streamlink/streamlink-twitch-gui#491]
Sometimes I can not play stream that describe stream titles in Japanese.

--------------------------------logs--------------------------------------------------

Found matching plugin twitch for URL twitch.tv/akuone2410
Attempting to authenticate using OAuth token
'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Waiting for streams, retrying every 1.0 second(s)

File "livestreamer_cli\output.py", line 123, in _open
File "livestreamer_cli\output.py", line 138, in _open_subprocess
File "livestreamer_cli\output.py", line 108, in _create_arguments
ValueError: Single '}' encountered in format string

**Comment by bastimeyer** [comment]
You are using the deprecated Livestreamer streaming provider. Any bugs related to Livestreamer will be ignored. Please use Streamlink instead.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

---

Now to your bug report. It's impossible for me to reproduce this since you've omitted the issue template and didn't provide any useful informations.

> 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Since this is looking like an encoding issue of the subshell for spawning the player process in Streamlink/Livestreamer I'd like to know the following informations:

1. Are you using the latest versions of Streamlink, Streamlink Twitch GUI and your player?
2. Which OS are you using?
3. Which player are you using?
4. Which player related settings do you use? (settings in the Twitch GUI or custom Streamlink/Livestreamer parameters)
5. What's the title of the stream you're trying to watch that is causing this issue?
6. Could you please check the [debug log](https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters) of Streamlink Twitch GUI so that we can see the generated parameters when trying to launch the specific stream that is failing?

**Comment by thtv83pvewov** [comment]
thanks bastimeyer.
i can see japanese title twitch stream

**Comment by bastimeyer** [comment]
That's not really helpful... 😞
