### ISSUE TITLE
Request: who am I watching? (Linux issue)

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#494]
If you activate "Hide stream popup" (Settings > Streams) and you are watching a non popular streamer playing a popular game with hundreds of streamers, you are never gonna find him again as easily as when you are watching it on Windows.
The reason is, that the VLC Player in Ubuntu cant have the Window Title changed (I think?) so you cannot really know the streamers name.

Proposal:
New menu entry ("Live watching") with all the streamers which are currently viewed through this app.
This way you will find your little streamers before you follow them, on other systems than Windows.

**Comment by bastimeyer** [comment]
> New menu entry ("Live watching")

This already exists. Click the TV icon in the top bar next to the cog icon after you've launched a stream.

> VLC Player in Ubuntu cant have the Window Title changed

You can (and should) use player profiles, which you can find in the settings menu. The VLC profile includes an option that is enabled by default for automatically setting a VLC window title. If you don't want to use a player profile or if you want to use a different window title format, you can set your own custom VLC parameter.

This is all documented in the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

The wiki is still listing the old `--meta-title` parameter instead of `--input-title-format`, which is required on MacOS (VLC is a mess) and has been changed a couple of months ago. I'll update this later on...
See the preset config data (the param is also being shown in the Twitch GUI itself):
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/config/players.json#L47-L56

**Comment by pquerner** [comment]
Oh darn, now I feel stupid for not RTFM. :/
Thank you for getting back to me.
