### ISSUE TITLE
Smudged Text Rendering

### ISSUE THREAD

**Issue by uhRainy** [streamlink/streamlink-twitch-gui#496]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Text rendering broke after I upgraded streamlink to 0.7.0 then reverted back to 0.5.0 because of the SSL issue and my text still renders smudged. After either scrolling or waiting for a few seconds the text cleans up a bit. Minimizing to taskbar and opening again fixes the text.

Nothing on my system has changed since the text was working on streamlink 0.50 before I upgraded to 0.7.0 and got the SSL errors. I have tried reinstalling streamlink-twitch-gui over itself after downgrading to streamlink 0.5.0 and the issue is still there.

I just uninstalled and deleted the config files for both streamlink and streamlink-twitch-gui then reinstalled both. The text rendering issue is still present. I do not have this issue in any other applications.

### Expected / Actual behavior

Text renders clean and crisp

### Reproduction steps

1. Upgrade to streamlink 0.7.0
2. Downgrade to streamlink 0.5.0

### Environment details

Operating system and version: Windows 10 Pro x64
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.5.0
Configuration details: ...

...

### Comments, logs, screenshots, etc.

Smudged text: http://i.imgur.com/gK3qBXJ.png
Crisp text: http://i.imgur.com/HkuZdRA.png

**Comment by bastimeyer** [comment]
> Text rendering broke after I upgraded streamlink to 0.7.0

The streaming provider (Streamlink or Livestreamer) has nothing to do with the text rendering of the Twitch GUI. It is a [NW.js/Chromium](https://github.com/nwjs/nw.js) based application, so there is no correlation between installing Streamlink (a Python based application).

Your issue must be caused by something else on your Windows system. Unfortunately, I can't tell you what it is. Please try running a different or a blank NW.js application and see if this can be reproduced. Other than that, all I can tell you is trying to reinstall your graphics drivers and cleaning the application cache.

**Comment by uhRainy** [comment]
I just did a clean reinstall of my graphics drivers two days ago and I just tried a sample nw.js app.. There was no issue.

I also cleared the cache for streamlink-twitch-gui and the issue is still there.

**Comment by bastimeyer** [comment]
I've recently run into a similar issue on a Linux machine with Nvidia proprietary drivers where FXAA anti aliasing was globally enabled. This was causing Chromium based applications (including Google Chrome, NWjs and Streamlink Twitch GUI) to render blurry fonts. I have no idea, why this was happening, but it's clearly a Chromium issue. Just wanted to mention this.

Anyway, I'm going to close the thread, since there is nothing which can be done here. This needs to be fixed either upstream or on your system. I can't help you with that unfortunately. Please make sure to use a clean system, if possible.

The recent NW.js version used on the master branch now is 0.26.1, which has been released today with Chromium 0.62. Maybe this could help fixing the issue.
