### ISSUE TITLE
start.sh: 30: start.sh: Syntax error "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by LautaroCuello** [streamlink/streamlink-twitch-gui#501]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

I have made a fresh install of Ubuntu 17.04, installed streamlink (tried if it works) then come here and download the lastest version. I unpack the compress archive and do the normal "sh start.sh" in the terminal but this error happend, at the time is the first problem I got besides when "livestreamer" died time ago.

I have no idea, because I did the same a few times in the past and it worked!

### Expected / Actual behavior

Work.

### Reproduction steps

1. Install Ubuntu 17.04 from your ISO.
2. When it finish, come here and download the lastest linux_x64 release.
3. Unpack it and open the terminal inside that directory.
4. Put "sh start.sh" then press Enter.

### Environment details

Operating system and version: Ubuntu 17.04
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.8.1
Configuration details: ??? Default

### Comments, logs, screenshots, etc.

`zero@zero-desktop:/opt/streamlink-twitch-gui$ sh start.sh
start.sh: 30: start.sh: Syntax error: "(" unexpected (expecting "fi")`

`zero@zero-desktop:/opt/streamlink-twitch-gui$`

I have downloaded again at the time i'm writing this doing a new clean installation with the steps shown in the wiki, and still the error is appearing.

**Comment by bastimeyer** [comment]
> sh start.sh
> Syntax error

`start.sh` is a `bash` script. Depending on your distro, `sh` may be a softlink to a different shell (see `which sh`). AFAIK, Ubuntu is defaulting to `dash`, but it should be `bash` compatible, so I'm surprised to see this.

You don't have to specify an interpreting shell, btw. The file is executable by default in the archive and you can just call it like this `./start.sh`. Or you can execute `bash start.sh`. Or don't use the start script at all, because it is just a compatibility wrapper for older distros. Just execute `streamlink-twitch-gui` directly.
