### ISSUE TITLE
Make hotkeys configurable

### ISSUE THREAD

**Issue by bluewww** [streamlink/streamlink-twitch-gui#502]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Make a config file or an option menu to configure shorcuts/hotkeys

### Expected / Actual behavior
Shorcuts/Hotkeys are hardcoded and can be neither changed nor disabled

### Reproduction steps
Trivial

### Environment details

Operating system and version: GNU/Linux OpenSUSE Leap 42.3
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.7.0
Configuration details: no changes

### Comments, logs, screenshots, etc.

none

**Comment by bastimeyer** [comment]
> Shorcuts are hardcoded and can be neither changed nor disabled
> GNU/Linux OpenSUSE Leap 42.3

Which shortcuts do you mean? There is no official RPM package for OpenSUSE, so if you're talking about that and asking for a package without menu shortcuts, then you have to contact the person providing this package. When not using a package, menu items will only be created by optionally executing the additional `add-menuitems.sh` bash script which is added to the tarball from the Github releases page.

If you mean Windows start menu shortcuts, then these can't be disabled. See https://github.com/streamlink/streamlink-twitch-gui/issues/484#issuecomment-313154297 or [the wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications#toast-notifications-windows). If you don't want to see these shortcuts, then you must either hide them from the start menu or choose a different notification provider (or turn notifications off).

**Comment by skulblakka** [comment]
Hmmm, I thought he was talking about keyboard shortcuts....

**Comment by bastimeyer** [comment]
🤦‍♂️ 
Yeah, now it's clear. I call those hotkeys, so that's where the confusion is coming from 😅

**Comment by bastimeyer** [comment]
After fixing the recent issues with hotkey modifiers in #696, I've decided to finally re-implement the hotkeys system and added support for customizable keybindings.

I'm not sure if I'm following the wrong path here by going back to using the KeyboardEvent.code property for checking hotkeys (instead of KeyboardEvent.key), as it is unaware of the user's keyboard layout, but since hotkeys can be fully customized now, I hope that it won't be a problem. The reason why I'm mentioning it is that hotkey tooltips will probably be wrong for localized keyboard layouts. Using KeyboardEvent.key however will cause a lot of other issues related to the modifer keys, which is the reason why I chose to go back to KeyboardEvent.code.

The changes have not been merged into the master branch yet, but I've pushed the `customizable-hotkeys` branch to the repo which can be tested:
https://github.com/streamlink/streamlink-twitch-gui/compare/customizable-hotkeys

There's still a bit of work to do, but that's only mostly related to i18n and layout stuff.
