### ISSUE TITLE
Don't cache bust URLs

### ISSUE THREAD

**Issue by h1z1** [streamlink/streamlink-twitch-gui#503]
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Likely for cache busting (?), requests to twitch needlessly append a random token.
 
Examples are stream previews:

https://static-cdn.jtvnw.tv/previews-ttv/live_user_twitch-320x180.jpg?_=<randomnumber>

Quick grep of the source doesn't turn up where this is coming from and I don't know enough about ember to tell if that is causing it?

### Expected / Actual behavior

Don't append anything to the URL.  It's needlessly causing backend origin hits.  Chrome should be doing the right thing wrt caching.

### Reproduction steps

1. ... Run app
2. ... watch requests / network use
3. ...

### Environment details

Operating system and version: ... Linux 
Streamlink Twitch GUI version: ... 1.2.1
Streamlink version: ... GIT-head
Configuration details: ... NA

### Comments, logs, screenshots, etc.

Given moving between views fetches these over and over, the impact is fairly substantial..   The previews themselves don't update more then once every few minutes (300second expire).

**Comment by bastimeyer** [comment]
The reason why a query string is added to each requested preview image is that Twitch is updating preview images before their expiration time is reached (included in the http headers). Not requesting unique image URLs makes Chromium use the same image for five or more minutes in some cases, which is not ideal. That's why most preview images in the app are re-using an unique query string for one minute per image, before a new one is used that will make Chromium return a hopefully updated version of it. The policy here is to have an up2date preview image, but only request it once a minute, which is sufficient in most cases.

![screenshot from 2017-11-05 06-02-05](https://user-images.githubusercontent.com/467294/32412147-e70d8a32-c1ee-11e7-9c9e-3e02b2ce243b.png)

https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/models/twitch/Image.js#L72-L82
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/config/vars.json#L9
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/test/tests/models/twitch/Image.js#L78-L129

Since this is an application meant for watching streams, I don't see anything wrong with loading new images once a minute, which is not even half or even a quarter of a single MiB per request. Watching a stream with 4k bitrate is already half a MiB per second.

> Streamlink Twitch GUI version: ... 1.2.1

v1.3.1 is available since May, btw

**Comment by h1z1** [comment]
Are you sure twitch even updates that often?  From what I can tell it does not.  Images are updated once every 2 minutes regardless of the token and 4 minutes without.   

Problem isn't the size it's the frequency and cache invalidation.  Think of at a LAN or roaming on a high latency network like wifi for example.   The browser is more then capable of maintaining cache coherency without the initial stutter between views.

Some other cam sites have more updated images on mouse over but twitch doesn't. 

Just and idea.

**Comment by bastimeyer** [comment]
I've just run this bash script to see Twitch's current preview image update rate:
```bash
#!/usr/bin/env bash
url=https://static-cdn.jtvnw.net/previews-ttv/live_user_monstercat-320x180.jpg
for num in {1..300}; do
	(curl -s "${url}" | sha256sum | grep -Po '^\S+' | xargs printf '%s: %s\n' ${num}) &
	sleep 1
done
```
Turns out, they are only updating every 5 minutes.

However, if you rely on the browser's cache, you will sometimes be almost 5 minutes behind when reloading an image, which is pretty bad.

See this diagram:
```
| = new image was created by Twitch
uppercase = request
lowercase = cached image


Default cache control (300s):

OK
|ABCDEFGHIJ|KLMNOPQRST|
|aaaaaaaaaa|kkkkkkkkkk|

Bad
|---------A|BCDEFGHIJK|LMNOPQRST|
|---------a|aaaaaaaaak|kkkkkkkkt|
           ^         ^


Custom cache control (150s):

OK:
|ABCDEFGHIJ|KLMNOPQRST|
|aaaaafffff|kkkkkppppp|

Acceptable:
|---------A|BCDEFGHIJK|
|         a|aaaafffffk|
           ^    ^


Custom cache control (60s - current value):

OK:
|ABCDEFGHIJ|KLMNOPQRST|
|aacceeggii|kkmmooqqss|

OK:
|---------A|BCDEFGHIJK|
|         a|acceeggiik|
           ^ ^
```

Again, as I've said, this is an application meant for watching streams. Loading a few KiB of images when reloading a menu is pretty much a non-issue, even when having a low bandwidth connection (which makes reloading that often questionable, anyway).

**Comment by bastimeyer** [comment]
I forgot to say that CDN responses include an expiration header, but this is just the request timestamp plus cache time. They don't set the expiration time to the next preview image content generation. That would be stupid and exploitable. Imagine everyone requesting a new version at the same time in a strict interval.

**Comment by h1z1** [comment]
Weird. Not sure why this reply is just showing up, 6 days later?  

I'm quite aware of how caching works :)   Your test was almost exactly what I did, had to look a few times.   I reran the test any way, their origin - or at least the public facing cluster/whatever behind akamai), their behavior remains the same.

 As I said,  the way Twitch uses their CDNs for images, is not meant to be a camsite.  If they wanted those images to be delayed video feed previews, it would be done quite differently.   Guessing they're busying breaking beta _LUL_.

You can of course do whatever you want, best practice would dictate it's currently inefficient.  Fact that you fail to see and quite arrogantly dismiss "low bandwidth users", is telling.   Don't think there's much point explaining why.  GLHF, hope twitch doesn't ban your app :)
