### ISSUE TITLE
Add gnome-mpv as a player preset option for linux

### ISSUE THREAD

**Issue by joebonrichie** [streamlink/streamlink-twitch-gui#504]
### Checklist

- [] This is a bug report.
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

[gnome-mpv](https://gnome-mpv.github.io/) is a simple graphical front-end for `mpv` following the Gnome design philosophy. It is the default video player on [Solus Budgie and Solus GNOME](https://solus-project.com/download/).

### Comments, logs, screenshots, etc.

I'm (will be) the maintainer of `streamlink-twitch-gui` on Solus, itś just waiting to pass review before it is accepted https://dev.solus-project.com/D789 which is why having `gnome-mpv` as a player preset would improve the out of the box experience for Solus users.
  
I would add this feature myself but it requires a tiny bit of plumbing. It requires the `-n` option of streamlink to be passed to it. e.g.
`streamlink twitch.tv/blah best --player=gnome-mpv -n`

From the output of `streamlink --help`
```
-n, --player-fifo, --fifo
    Make the player read the stream through a named pipe instead of
    the stdin pipe.
```
The `-n` option works for gnome-mpv and mpv but not for vlc.

Therefore to get it implemented I would imagine you'd need to add support of "streamlink player params" for specific video players.

Thanks in advance!

### Environment details

Operating system and version: Solus 3 (Linux)
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.8.1
Configuration details:

**Comment by bastimeyer** [comment]
Hi, first off, thanks for building a package on Solus, much appreciated! 👍
Feel free to add it to the wiki once it's been finished and approved, or just tell me to add it then.

Now to gnome-mpv:
The reason why I haven't added gnome-mpv (and also other spin-offs) to the players preset list yet is that gnome-mpv doesn't support any launch parameters and relies on mpv's or its own config files. This makes it impossible to set custom window titles or making changes to the window behavior.

In order to make gnome-mpv work with Streamlink Twitch GUI, you actually don't need to set the named pipe Streamlink parameter, because the Twitch GUI is forcing the [`--player-passthrough`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough) parameter. It's doing that for exactly this reason, because some players don't read from stdin, especially on Windows. This means that all streams watched via the Twitch GUI will let Streamlink launch a local http proxy server (when using the http option) from which the player will then read instead of stdin.

> I would imagine you'd need to add support of "streamlink player params" for specific video players

If the `--player-passthrough` param would not be forced, then it would be required, yes...

I'm currently [rewriting the internal settings structure](https://github.com/streamlink/streamlink-twitch-gui/tree/rewrite-settings) and still have to do the player related stuff. I'll have a look at such an option once I've completed this. This may also be useful on macOS and VLC.

I'm not sure though if it'd be better to rethink the settings structure again, something like `Basic Streamlink settings -> Player selection/settings -> Streamlink settings based on player selection`. This would be better than forcing a specific Streamlink config for certain players or just providing a custom Streamlink parameter field for overriding the basic settings.

To me, gnome-mpv seems to be in its early stages and still needs some polish in order to have a nice watching experience. I've just installed the latest version from the AUR on Arch and had several issues on Cinnamon after using it for a few minutes, eg. inconsistent window position, forced dark GTK theme, incompatibility of the `--player-passthrough=rtmp` param, etc. I'm not sure how it is on Solus and the Budgie desktop, but I can't imagine that it's much better.

**Comment by joebonrichie** [comment]
Hi, thanks for the clarification :)

Yes the lack of launch options is indeed frustrating currently and I understand your reasoning why you would not include it (I've come around similar frustrations with adding `gnome-mpv` as a player preset in `gtk-youtube-viewer`.) I think it's a good option for a simple player and works mostly well for me, and hope it improves in the future. I think most of their frustrations is that mpv itself doesn't have a API for said launch parameters as far as I understand.

I was actually unaware of the `--player-passthrough` option, so I am happy as I can carry my own patch in Solus to add gnome-mpv as an option which works well for me currently

You can consider this resolved, at least from me, I don't mind carrying an extra patch for Solus. 

Thanks for the fast response as well, I'll send a pull request to document once it's available in Solus and lands in the stable repo there.

**Comment by bastimeyer** [comment]
@joebonrichie 
I've made a mistake in my earlier post... It's not the --player-passthrough parameter, but the --player-http parameter which is responsible for launching the http server where the player is reading from. Sorry about that.

I have merged the settings-rewrite branch into the master branch now (49b1d79a7653f505a4221c572c858d6c17c86043 has changed the default settings). It is now using stdin as default player input, which means that if you're adding patches with gnome-mpv as the default player, you should add a patch for changing the default player input method as well here:
https://github.com/streamlink/streamlink-twitch-gui/blob/9fda69a08049a7fcd4a917e393499e225ea9e081/src/app/models/localstorage/Settings/streaming.js#L38

**Comment by joebonrichie** [comment]
Thanks for the heads up!

I'll be sure to update the patch as required for the next release

**Comment by bastimeyer** [comment]
I guess this can be closed then...
