### ISSUE TITLE
Option to remove Close / Maximize / Minimize Buttons

### ISSUE THREAD

**Issue by weberval** [streamlink/streamlink-twitch-gui#505]
### Checklist

- [ ] This is a bug report.
- [X] This is a feature request.
- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] I tried solving my issue by reading the project's wiki first.
- [X] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

On Systems with a non Floating Window Manager Desktop Environment, the Close / Maximize / Minimize Buttons are obsolete. Is it possible to introduce an Option to disable them? Some of them aren't working on non Floating Window Manager Desktop Environment anyway.

### Environment details

Operating system and version: Arch (rolling release)
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.8.1
Window Manager: i3 Tiling Window Manager

**Comment by bastimeyer** [comment]
Sure, this can be added, it's a simple change. This should be hidden behind advanced settings, though.
I'll add this after I've finished [rewriting the settings](https://github.com/streamlink/streamlink-twitch-gui/compare/rewrite-settings), which should be soon.

Thinking about other platforms and configs, moving the buttons to the left side is not an option unfortunately, because of the layout. I also wish there was a way in NW.js to toggle the window frame during runtime, so that people who prefer having their OS's/DE's window decorations can use these, but since it's a web-app with non-native GUI elements, I don't think it's even a good idea.
