### ISSUE TITLE
when i click on a stream it says connection error even though i did everything right

### ISSUE THREAD

**Issue by texaschingon** [streamlink/streamlink-twitch-gui#512]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
when i click on a stream it says connection error something even though i did everything right also yes im new to github cause i have to make this issue.
...

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink Twitch GUI version: ...
Streamlink version: ...
Configuration details: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
I'll mark this thread as invalid, but will leave it open for a day for you to edit it with actual information instead of just a brief title - 84 characters of information, wow. There is no way that someone is able help you with that. Even if you're new to Github, this is not acceptable, because everything of how stuff works is described in the linked documents.
