### ISSUE TITLE
Integrate Chat?

### ISSUE THREAD

**Issue by Chris230291** [streamlink/streamlink-twitch-gui#514]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Would it be possible to build a player directly into the app with integrated chat window? Or is there a player I can use that does this?

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink Twitch GUI version: ...
Streamlink version: ...
Configuration details: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by sadiablos** [comment]
Read [projects page](https://github.com/streamlink/streamlink-twitch-gui/projects) about Internal IRC client


And if you don't want to wait _(I'm not even sure if it's appropriate to write them here)_
Apps with integrated chat:
- Original desktop twitch app
- Orion

External apps for chat:
- Chatty (supported by STG)
- Chatterino
- Tc 
- Any irc client

**Comment by bastimeyer** [comment]
Sorry for the delayed response, I've been a bit busy with other stuff...
Regarding your question, @Chris230291, integrated Twitch chat is a very complex thing to have and won't happen in the near future. As @sadiablos has already said (thanks btw), I've added an internal IRC client project to the repo's projects list with a brief description. I'll try to extend/improve all the project descriptions so that it becomes more clear what needs to be done in order to achieve all these goals.

> Would it be possible to build a player directly into the app

No, this is not how Streamlink works and would basically be the same as viewing Twitch in your Chromium(-based) web browser, as this application is based off of Chromium as well.

If you want to have a similar experience, I'd recommend using the Chromium or Google Chrome chat options in the settings menu and using a window manager that splits the screen between the fullscreen video of the player and the chat of the Chromium browser in its "app mode" (no location bar, etc). Even on Windows you should be able to do this.
