### ISSUE TITLE
Audio Plays but No Video

### ISSUE THREAD

**Issue by AceofClubs53** [streamlink/streamlink-twitch-gui#518]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Stream launches but only audio plays.

...

### Expected / Actual behavior

When launching a stream via Streamlink Twitch GUI, VLC player will open, audio will begin playing but video will never start. VLC path appears as fd://0

...

### Reproduction steps

1. Launch Streamlink Twitch GUI > Livestreams > Launch Stream ...
2. VLC launches path fd://0 appears ...
3. Audio plays but video does not appear, tested on multiple streams ...

### Environment details

Operating system and version: OS X El Capitan Version 10.11.6 ...
Streamlink Twitch GUI version: 1.4.1 ...

...

### Comments, logs, screenshots, etc.

I have basic code knowledge but have been using Twitch GUI since before Livestreamer 0.16. Upon updating to this latest Streamlink Twitch GUI I began experiencing this issue. VLC no longer seems to run a path to the correct ip for the video. (Not sure if that's the right lingo) Greatly appreciate your program and help, thank you!

...

**Comment by sadiablos** [comment]
Did you checked if you don't have "Audio only" option selected as a preferred quality?(Settings>Streams>Preferred Quality)

**Comment by AceofClubs53** [comment]
Yes I did, I thought I might have accidentally done that but it is still set to "Source"

**Comment by bastimeyer** [comment]
> VLC player will open, audio will begin playing

That's a rendering issue of your player and has nothing to do with Streamlink Twitch GUI, which is just a parameter generator and launcher for Streamlink (or Livestreamer, although deprecated). Streamlink downloads the MPEG-TS segments of the HLS stream from Twitch, concatenates these segments and in its default configuration pipes the data to the player. So if you're hearing sound, you can be sure that this all is working correctly.

> VLC no longer seems to run a path to the correct ip for the video

As you can read in the recent **changelog** and **wiki**, the default player input has been changed. So if you'd rather want to use Streamlink's internal http server as stream transport method, you have to select this in the settings menu. I doubt though that this is the reason for your issue. But I'd also not be surprised if it is, since VLC on macOS is the worst ever.

In order to fix your issue, please make sure that watching streams via Streamlink is working correctly from the CLI when not using the Twitch GUI.

**Comment by AceofClubs53** [comment]
Went in and adjusted Player Input as you suggested and that fixed it. Yeah I have noticed that VLC on macOS seems like it's not all together like it is on Windows. Thank you for the prompt help, it's currently working through HLS. 

Cheers
