### ISSUE TITLE
GUI creates a lot of temp files

### ISSUE THREAD

**Issue by h0rn3z0r** [streamlink/streamlink-twitch-gui#520]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

I have noticed an unusual behaviour of GUI when trying to start it on Windows boot. In order to launch it I put a shortcut in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp folder with --tray parameter added, but it happens with Task Scheduler also.

First of all, after restart new key in registry is created:

Enabled | Key | Program | Publisher | File
------- | --- | ------- | --------- | ----
Yes | HKCU:RunOnce | Application Restart #0 | The NWJS Community | C:\ProgramData\chocolatey\lib\streamlink-twitch-gui\streamlink-twitch-gui\streamlink-twitch-gui.exe  --tray --disable-devtools --enable-features=NativeNotifications --disable-smooth-scrolling --user-data-dir="C:\Users\user\AppData\Local\streamlink-twitch-gui\User Data" --no-sandbox --no-zygote --flag-switches-begin --flag-switches-end --nwapp="C:\Users\user\AppData\Local\Temp\nw8176_12414" --restore-last-session

Moreover, you can see a lot of folders in Temp and their amount increase after each reboot:

![-1](https://user-images.githubusercontent.com/8987403/33941097-74184b64-e022-11e7-8825-d8709f56fa3e.png)

There folders are duplicates and contain same css/js files. I also tried to set a delay on launch and that didn't change anything. If you open/close GUI manually, temp folder is deleted and of course no registry keys are created.

So that is some information for you to decide whether it is a bug or not. I think it should be only one temp folder and GUI should use it every time instead of creating another.

### Environment details

Operating system and version: Windows 10.0.16299.98
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.9.0

**Comment by bastimeyer** [comment]
> an unusual behaviour

This is default NW.js behavior, caused by the way the application is packaged on Windows (and Linux) by `nw-builder`. The application content is appended to the NW.js executable at the production build step and NW.js needs to copy these files to a temp folder first before they can be used when the built application gets started. This requires NW.js to run a second child process for actually running the application code. Usually, NW.js will clean up the temp files when its main process gets terminated (closed correctly).

> new key in registry is created

This registry key might be used for NW.js' single instance mode, but I'm not sure. What you've posted is the executable and parameter string of the child process I was talking about. It is using the `chromium-args` string defined in the package.json file here and it's also pointing to the temp files via the nwapp parameter.

> If you open/close GUI manually, temp folder is deleted and of course no registry keys are created.

Well, this seems to be a cleanup issue of NW.js then. Or maybe even a Windows issue, because it is not terminating the main app process correctly on shutdown which then results in left over temp files. Probably because it is killing the child process, indicated by the registry key, who knows.

This is nothing that can be fixed here, as it is unrelated to the code of this project. As you already said yourself, running the app manually works fine. You should try to isolate this issue with a blank NW.js app which is packaged the same way and then file a bug report on the NW.js repository if you're convinced that this is indeed a NW.js bug and not caused by Windows or an invalid autostart configuration.

**Comment by h0rn3z0r** [comment]
Thanks for the explanation.
