### ISSUE TITLE
VLC media player can't play streams that has quotation marks in stream title

### ISSUE THREAD

**Issue by DebuUsagi** [streamlink/streamlink-twitch-gui#522]
### Checklist

- [x] This is a bug report.

### Description
Using VLC, launching a specific stream makes the media player go haywire. I think this is because the stream title has 2 quotation marks( " ).

Stream title was: You see a comfortable stream, you enter, you say "hello everyone" | !mediashare

I tested stream length and that doesn't seem to be the case, so I am fairly sure that the quotation marks are killing VLC

### Expected / Actual behavior

VLC should launch and play the stream normally. / VLC tries to find the stream but can't and retries again.

### Reproduction steps

1. Launch stream that has quotation marks in its title using VLC media player

### Environment details

Operating system and version: Windows 8.1 64bit
System locale: Japanese (Japan)
Streamlink Twitch GUI version: 1.4.1
Streamlink version: I'm not sure which version but I just updated to 0.9.0
VLC media player version: 2.2.8
Configuration details: everything is default, if I remember correctly, except for: Livestreamer (Standalone) in streaming tab, VLC media player in Player tab.

### Comments, logs, screenshots, etc.
I tried to find the log files but couldn't. Have a screenshot!

![image](https://user-images.githubusercontent.com/9564875/34453252-2b17275c-ed1d-11e7-8f92-f8f95a671370.png)

**Comment by bastimeyer** [comment]
> Streamlink version: I'm not sure which version but I just updated to 0.9.0
> except for: Livestreamer (Standalone)

**Then you're not using Streamlink**, but instead Livestreamer which you should not be using:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

> Configuration details: everything is default

So you're not using the VLC player preset? If you're not using the preset, then no custom player titles are applied. See the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

If you're using custom player parameters then you need to make sure to set parameters in quotation marks, so that the content can be escaped properly by the Twitch GUI.

There were some custom player parameter issues regarding stream titles in the past, but those should have been fixed.
https://github.com/streamlink/streamlink-twitch-gui/issues?q=player+title

Please check your player settings again and tell me which config you are using.

**Comment by DebuUsagi** [comment]
> So you're not using the VLC player preset? If you're not using the preset, then no custom player titles are applied.

I wasn't sure if VLC player was default so I added it in to make sure.


When I first tried out Streamlink Twitch GUI, Streamlink and Livestreamer did not work but Livestreamer (standalone) did, so I left it at that. You are correct that this is a Livestreamer problem.

I've fixed the problem to why Streamlink wasn't working(it couldn't find pythonw.exe). Quotes don't break VLC anymore! Thanks for the reply.
