### ISSUE TITLE
Stream preview transparency too low

### ISSUE THREAD

**Issue by ValooFX** [streamlink/streamlink-twitch-gui#530]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

The transparency of Stream previews is way too low (dark and light skin). It would be nice to have an option to customize this.

### Expected / Actual behavior

Stream titles should be easily readable, even if not mouse-hovered.

### Environment details

Operating system and version: Windows 7
Streamlink Twitch GUI version: 1.4.1
Streamlink version: not sure
Configuration details: dark skin

### Comments, logs, screenshots, etc.

Non-hovered state:
https://imgur.com/hj5gh7n

**Comment by bastimeyer** [comment]
You seem to have misconfigured your language filtering settings. Please check your settings again.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Watching-streams#stream-filters

The low opacity is meant for "dimming or fading out" unwanted stream, eg. when a stream
- is being broadcasted in a foreign/unkown language
- is a duplicate item, which can happen when using the infinite scroll mechanic with a certain time offset
- is a vodcast

Regular streams are being *highlighted* this way. If you don't want to use this feature, just select the "filter out" method, which will set the language preferences when requesting streams from the Twitch API, so that they are not included in the returned list. Duplicates will always be faded out, though. Vodcasts have their own "fade out" checkbox in the "lists" settings menu, so you can disable that if you want.

Regarding the opacity value itself, I don't think that 25% is too low, since those streams should not catch the user's attention.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/styles/components/list/StreamItemComponent.less#L15

**Comment by ValooFX** [comment]
Oh, thanks. That indeed was the cause. Sorry for opening this issue then.
(I think i was confused the first time i saw those options that there was no 'dont filter streams'-sort of option by the way, which i think could be faster to grasp than having to check/uncheck all languages)
