### ISSUE TITLE
Stream thumbnails are all grayed out

### ISSUE THREAD

**Issue by vesche** [streamlink/streamlink-twitch-gui#534]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

All of my stream thumbnails/text are appearing grayed out like so:
![scrot](https://i.imgur.com/XzKpykd.png)

When I scroll over a stream it lights up like normal.

### Expected / Actual behavior

The stream thumbnails/text should not be grayed out.

### Reproduction steps

I'm sure this is a Debian or Linux specific issue as I searched and couldn't find a similar issue. For install, I followed similar steps to install on Ubuntu [found here](https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation#custom-installation-2). I'm starting streamlink twitch gui using start.sh from a symlink.

### Environment details

I'm on Linux:
  * Debian 9.3 stretch
  * x86_64 Linux 4.9.0-5-amd64

I'm using the latest v1.4.1 release of streamlink twitch gui.

streamlink 0.10.0

This issue happens on both Default and Dark themes.

**Comment by bastimeyer** [comment]
You probably have misconfigured your language filtering settings.
See #530...

**Comment by vesche** [comment]
Ah, thanks that fixed it! Is it normal for Streamlink Twitch GUI to come without any language preselected? I would have never thought to check in the Language settings. Thanks for the fast reply.

**Comment by bastimeyer** [comment]
Since there's currently no i18n support (is being worked on), the system's language is not being used as default filtering selection. However, having a default selection based on the system locale would be a bit problematic for multilingual users. That's why no language is selected by default.

I didn't notice that there's an issue with the fading when no language is selected. It should actually not fade anything in this case. Reopening...
