### ISSUE TITLE
Stream quality selection

### ISSUE THREAD

**Issue by konkersgg** [streamlink/streamlink-twitch-gui#535]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

It would be cool if we could chose the stream's quality by using all the available qualities for the stream that we are attempting to load, as you can see on the image below.

The idea is to use the data that streamlink's shows to select a preferred quality for all the streams we open, at the first time we open them. If the selected quality isn't available on the next time you attempt to load that same stream, then the Source quality will load until you decide to change it at the channel's configs.

### Expected / Actual behavior

Expected: List all available qualities when loading a stream and allow us to select one of the listed qualities.
Actual: A list that goes from Audio Only to Source.

### Comments, logs, screenshots, etc.

![sem titulo-1](https://user-images.githubusercontent.com/4704759/35790097-acaedcde-0a27-11e8-8a7d-9138d04754bb.png)

Sorry for my terrible English grammar.

**Comment by bastimeyer** [comment]
Streamlink Twitch GUI doesn't read the available streams from the output of Streamlink (or Livestreamer), because it's an unnecessary and, in terms of time, costly step. Unfortunately, there's no Twitch API endpoint that can be used for getting the available stream qualities (unless they've changed this recently). This means that all you can do is executing Streamlink twice at the beginning of each stream, wait for its output, read it and then start Streamlink again. An alternative could be executing the equivalent stuff here in the Twitch GUI, namely making the needed requests on Twitch's "usher service", requesting a viewer token and finally requesting and parsing the stream's HLS master playlist, but this wouldn't make a big difference, since the logic is basically the same.

Even if the Twitch GUI would all do this, there are still several issues. These new quality names which Twitch added in mid-2016 are all based on the input stream of the channel, making them dynamic and unpredictable. Also, the new quality names were added in addition to the old and strict naming format.

That's the reason why there's a *custom* stream quality selection. The idea is that users should always be able to **predefine** certain quality levels which can be used for every stream on the platform and which can be applied globally or individually. This further means that the quality names have to be mapped to the available qualities somehow. That's what Streamlink is doing. The Twitch GUI is setting Streamlink's `--stream-sorting-excludes` parameter when launching a stream, letting Streamlink select the best quality which matches the user selection. You can read more about this in the Twitch GUI's wiki, here:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities
