### ISSUE TITLE
Language filter removes "British" language even though "English (en)" is ticked.

### ISSUE THREAD

**Issue by lem503** [streamlink/streamlink-twitch-gui#540]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description
When using the language filter (Settings -> Languages) to hide the unchecked languages, streams with a "British" language tag are filtered even when "English (en)" is ticked in the language list.

### Expected / Actual behavior
Ticking "English (en)" on the Settings -> Languages should also disable filtering for streams that were tagged as British language.

### Reproduction steps

1. Go to `Settings` -> `Languages`.
2. Select `Fade out Streams`.
3. Tick `English (en)`.
4. Go to any page displaying live streams. 
5. Streams that are labeled as British language are faded.

### Environment details

Operating system and version: Win10 x64
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.10.0
Configuration details: ...

### Comments, logs, screenshots, etc.

![language filter](https://user-images.githubusercontent.com/10457248/36789948-22ef2aaa-1c8b-11e8-9499-f83b80501770.JPG)
![faded stream](https://user-images.githubusercontent.com/10457248/36789947-22d837d2-1c8b-11e8-8f0f-c029839693de.JPG)
![faded stream hover](https://user-images.githubusercontent.com/10457248/36789949-230f0906-1c8b-11e8-8144-4c736e558b02.JPG)

**Comment by bastimeyer** [comment]
It's faded out because it's being detected as a vodcast, either by having the [vodcast attribute(s)](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/models/twitch/Stream.js#L84-L89) set or because of its [stream status](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/models/twitch/Stream.js#L91-L96). This behavior can be configured in the settings menu, take a look at the "Lists" submenu. A custom regular expression for filtering stream statuses can be set in the "Streams" submenu if advanced settings have been enabled.

DreamLeage's channel language is currently set to `en-gb`, but its broadcaster language, which is being used for comparing the language with your selection, is set to `en`. The broadcaster language is not being displayed if it's the same as the channel language (even if the region subtag differs).

**Comment by lem503** [comment]
Awesome, thanks for the quick response. Disabling Fade out Vodcasts did the trick.
