### ISSUE TITLE
How do I watch lives only in 160p?

### ISSUE THREAD

**Issue by Darki3e** [streamlink/streamlink-twitch-gui#541]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Sorry for my English.
The problem is that my internet is not great and I wanted to watch the lives only in 160p, I already read the wiki but I did not understand, I saw some command lines but I do not understand how I should put them to work.

### Reproduction steps

1. try to start command lines without success
2. try to open streamlink but closes after 2 sec

### Environment details

Operating system and version: W10 X64
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.10.0

**Comment by bastimeyer** [comment]
No problem...

Go to the main settings menu, enable advanced settings (checkbox at the top) and then go to the streams submenu, where you'll find the quality presets configuration. As you can see there, the "low" quality preset will remove all available stream qualities greater than 360p30 and will then select "low" (which is a quality of Twitch's old naming scheme) or if it doesn't exist the best of the remaining qualities which have been filtered. This will be 360p in most cases, since everything above that has been filtered out.

I consinder everything below that unwatchable, even for the low preset, so I chose 360p as the lowest quality which can be selected in the default configuration. However, if your connection is that terrible, you can simply change the selector string from `low,best` to `worst`. This will let Streamlink always select the worst available quality. Another method is changing the filter, from `>360p30` to `>160p`, but I'm not sure if this will lead to issues when 160p is not available, but instead a slightly higher one.

To give you an overview of the difference between 360p and 160p on Twitch:
**360p**: overall video/audio bitrate of ~600kbit/s, which requires a download speed of ~75KiB/s
**160p**: overall video/audio bitrate of ~250kbit/s, which requires a download speed of ~31.25KiB/s

If you're having lag spikes, you also may want to try increasing the hls live edge value in the streaming submenu, which gives Streamlink more time to download the stream segments, at the cost of a higher delay. Increasing the hls segment threads value is probably not a good idea with an overall slow download speed.

Hope this helps...

**Comment by Darki3e** [comment]
Ok, in this part: 
"you can simply change the selector string from low,best to worst. This will let Streamlink always select the worst available quality. Another method is changing the filter, from >360p30 to >160p"

where do I change these settings? 
I downloaded the program yesterday and I do not understand much where I change these commands

**Comment by bastimeyer** [comment]
Is it possible that you're confusing **Streamlink Twitch GUI** with **Streamlink**?

> Streamlink Twitch GUI
> A **g**raphical **u**ser **i**nterface on top of the Streamlink **c**ommand **l**ine **i**nterface.

https://github.com/streamlink/streamlink-twitch-gui#description
https://streamlink.github.io/streamlink-twitch-gui/

If you're just using the Streamlink CLI, it's as simple as selecting the desired quality.
https://streamlink.github.io/cli.html#tutorial

**Comment by Darki3e** [comment]
Thank you so much, I was able to solve the problem.
