### ISSUE TITLE
"unexpected version check output" 3-1-18

### ISSUE THREAD

**Issue by TheGloriousArgonaut** [streamlink/streamlink-twitch-gui#542]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Despite researching this issue EXTENSIVELY I am still getting issues with  "unexpected version check output". I have located the file correct file path with C:\Program Files (x86)\Streamlink\Python\pythonw.exe and used the tips i found in issue #348. Yet i still get the version error.
...

### Expected / Actual behavior
I expect the streams to launch
...
they dont launch I get a version error despite linking the correct file path and version of pythonw thats included with the install.

### Reproduction steps

( im not filling this section out sorry)
1. ...
2. ...
3. ...

### Environment details

Operating system and version: ... windows 8.1 x86
Streamlink Twitch GUI version: ... 1.4.1
Streamlink version: ... 0.1.0
Configuration details: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
> despite linking the correct file path
> Yet i still get the version error.

You're seeing this error in the Twitch GUI, because Streamlink is returning an error message. The Twitch GUI first needs to validate Streamlink and it does that by checking its version before launching the first stream. But instead of its version string it is returning an error message, hence the unexpected version check output error. This means that you have to fix your Streamlink issue first, otherwise the Twitch GUI won't work.

In order to get the Streamlink error messages, try to run Streamlink from the command prompt (make sure to use the same paths which you have set in the Twitch GUI) or check the log files in the `%TMPDIR%\streamlink-twitch-gui\logs` directory.

Btw, you don't have to set any custom paths if you're using the Streamlink installer on Windows. The Twitch GUI will be able to automatically resolve the correct paths, unless your system has a messed up `PATH` env var configuration or Streamlink setup.

> Streamlink version: ... 0.1.0

This Streamlink version is ancient, more than a year old and also not supported anymore. The latest release is `0.10.0` and you [need to have at least `0.2.0` installed](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/config/streaming.json#L15). So even if you manage to get Streamlink to work, you'll see the next error message, asking you to upgrade.

**Comment by TheGloriousArgonaut** [comment]
Ok so I decided to start this process from scratch as following many threads I may have inadvertently installed incorrect stuff. So I uninstalled all versions of python, streamlink twitch GUI and streamlink. 

Yet after following the steps again I am still getting the previous issue so I will list out my steps in hopes you can find the hitch in my process.

step 1. Install latest version of  streamlink version 0.10.0, "streamlink-0.10.0" I then navigate to bin folder and launch the application, I see a quick bit of line info appear in a command prompt then it quickly  closes.

step 2. Install the latest version of streamlink twitch GUI using the "streamlink-twitch-gui-v1.4.1-win64-installer".

step 3. upon launching the Twitch GUI and attempting to launch a stream i get an error saying " couldnt find python script, executables not found, please check settings or reinstall live streamer".

step 4. manually associate the file path in the settings to locate the pythonw.exe and streamlink-script.py found in my streamlink folder.

step 5. still get version error.

step 6.  search for %TMPDIR%\streamlink-twitch-gui\logs, or any "logs" in streamlink twitch GUI folder only to come up empty handed. Manually searching for %TMPDIR% brings up no results.  I looked in my TEMP folder as well still nothing. So I am confused as where to find the error file so you can help trouble shoot.

Where am I going wrong in all of this? 

I really miss the old livestreamer twitch GUI it was infinitely more simple. My build from 2016 was working perfectly until just the other day and now I'm forced into all these fun "upgrades".

**Comment by TheGloriousArgonaut** [comment]
OK so I found my issue, the default stream service was set to livestreamer, I changed it to stream link and the issue stopped, I was able to launch the stream.

**Comment by bastimeyer** [comment]
> launch the application, I see a quick bit of line info appear in a command prompt then it quickly closes

This is not how you use Streamlink on Windows. The executable is meant to be run from the "command prompt", otherwise you won't see its output...

> streamlink-twitch-gui-v1.4.1-win64-installer

You said you were using Windows 8.1 x86... You can't run x64 applications on an x86 operating system / processor

> couldnt find python script, executables not found, please check settings or reinstall live streamer

Then you have selected Livestreamer as streaming provider and not Streamlink. The Twitch GUI still supports Livestreamer, but this will be removed in the future. If you've set it to Streamlink and tried launching a stream, this error message also means that you didn't install Streamlink correctly, since it would have found its install directory due to the installer registering its location in the system's environment variable

> search for %TMPDIR%\streamlink-twitch-gui\logs

Why search? `%TMPDIR%` is a system variable and you can just paste this path in the path bar of the Windows explorer. Windows does have multiple temp folders, so depending on your system, you may need to look at different locations. On w8.1, it should be located in your home directory, though

> Where am I going wrong in all of this?

Just follow the instructions in the wiki. There isn't actually much which can be done wrong. On Windows, just download both installers, execute them, start the Twitch GUI and be happy. It will automatically find the Streamlink install dir and you don't have to worry about anything, unless you're doing something wrong

> I really miss the old livestreamer twitch GUI it was infinitely more simple

Back then, the app did only support the standalone version of Livestreamer. Since Livestreamer is dead and Streamlink has switched to a more sane build structure on Windows, things needed to be changed here as well.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by bastimeyer** [comment]
> OK so I found my issue, the default stream service was set to livestreamer, I changed it to stream link and the issue stopped, I was able to launch the stream.

I guess this can be closed then...

**Comment by destroy** [comment]
I got same issue, I mistakenly used python.exe instead of pythonw.exe.

**Comment by Tomalak** [comment]
I had the same issue on Windows. Selecting a pythonw.exe path triggered it. It went away after leaving the Python path empty.
