### ISSUE TITLE
Chat popout window in Opera

### ISSUE THREAD

**Issue by 123sfg123** [streamlink/streamlink-twitch-gui#544]
Hello, i use Opera (based on Chrome), tried to configure it as custom application in chat settings, but chat window opens at new tab full screen. How make it appear like it auto configured for Chrome (Chromium). Now my application parameters look like: "{url}".
OS: Windows.

**Comment by bastimeyer** [comment]
Does Opera support the `"--app={url}"` parameter?
Please try and select the Chromium preset with the Opera executable as custom path and tell me if it works...

**Comment by 123sfg123** [comment]
No, it didn't help. I tried Chromium preset with and without  "--app={url}" same in custom, it just open new empty tab. I think Opera should support this parameters, m.b. in another syntax.
PS: i didn't find any info about list of these parameters

**Comment by bastimeyer** [comment]
> I tried Chromium preset with and without "--app={url}" same in custom

The Chromium preset already sets the parameter, that's one of the reasons why this preset exists... I was asking if you could select the *Opera executable* in the *Chromium executable* field.

Btw, according to https://www.opera.com/docs/switches/, Opera doesn't support Chromium's so called app mode, which is weird, because it supports other inherited features, like the kiosk mode for example.

**Comment by 123sfg123** [comment]
> I was asking if you could select the Opera executable in the Chromium executable field.
I did this, and tried besides this other variants just in case.
> Btw, according to https://www.opera.com/docs/switches/
This outdated information, after Opera v12 moved to Chrome base.

**Comment by bastimeyer** [comment]
I couldn't find any command line parameters for Opera to launch it in a minimal window mode. I don't think it even exists. I can't help you any further.
Closing the thread...
