### ISSUE TITLE
Store account data locally

### ISSUE THREAD

**Issue by daedrot** [streamlink/streamlink-twitch-gui#548]
Hello, thanks for your amazing program! I have been using it instead if twitch.tv since the day i found it. Its features are plentiful and work correctly. However, i really value privacy, and so, logging in my account does not seem very comfortable for me. Are there any options of storing personal data locally, instead of getting it from twitch data servers, and if not, may they ever be implemented? I found this feature in many apps, NewPipe(on github)works mostly the same(from my understanding) with youtube, and is a notable example. Thanks for answer and your excellent work.

**Comment by bastimeyer** [comment]
If you value your privacy, you can always choose not to login with a Twitch account. Then all of the Twitch API requests won't include any personal information ([an OAuth token](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/store/TwitchAdapter.js#L55-L62), see [AuthService#login](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/services/AuthService.js#L153-L168)) and do only include the app specific client-id in the [HTTP request headers](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/store/TwitchAdapter.js#L20-L23).

Sending an OAuth token is required for accessing the data of certain menus though, like the followed streams/channels/games or your subscriptions. It is also required for the desktop notifications to work, since it has to be able to access your followed streams of course. Apart from that, everything will work without signing in. If you're logged in, you can also disable the re-use of your OAuth token in Streamlink in the Twitch GUI's streaming settings menu, so that Streamlink doesn't perform a login while watching streams.

What do you mean with storing personal data locally? The only data being stored right now are your application- and channel settings, the application window state, size and position, the time of the last new version check and your OAuth token, you're if logged in. Any other data of your Twitch account has to be retrieved live from the Twitch API. Storing this data doesn't make sense as it is useless if it isn't up to date.

If you mean storing a local list of channels and checking their online status for the desktop notifications, then yes, this could theoretically be done, but it would be highly inefficient, as you'd need to request every stream data separately. It is however possible to "coalesce" several stream requests so that the number of all requests can be reduced, but this is fairly limited and doesn't really solve the issue. It would also probably tell Twitch more about you than just requesting the followed live streams while being logged in.

By using this app, you're already doing much better privacy wise than using the Twitch website or the official app, as there are no tracking scripts or any of that kind included here and never will be. Like using every other big online service, it is a tradeoff between your privacy and convenience, ease of use and enjoyment. I'm afraid there's not much more which can be done here.

**Comment by daedrot** [comment]
Ok, thank you for the detailed explanation.

**Comment by Rosstarz** [comment]
> If you value your privacy, you can always choose not to login with a Twitch account. Then all of the Twitch API requests won't include any personal information ([an OAuth token](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/store/TwitchAdapter.js#L55-L62), see [AuthService#login](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/services/AuthService.js#L153-L168)) and do only include the app specific client-id in the [HTTP request headers](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/app/store/TwitchAdapter.js#L20-L23).
> 
> Sending an OAuth token is required for accessing the data of certain menus though, like the followed streams/channels/games or your subscriptions. It is also required for the desktop notifications to work, since it has to be able to access your followed streams of course. Apart from that, everything will work without signing in. If you're logged in, you can also disable the re-use of your OAuth token in Streamlink in the Twitch GUI's streaming settings menu, so that Streamlink doesn't perform a login while watching streams.
> 
> What do you mean with storing personal data locally? The only data being stored right now are your application- and channel settings, the application window state, size and position, the time of the last new version check and your OAuth token, if you're logged in. Any other data of your Twitch account has to be retrieved live from the Twitch API. Storing this data doesn't make sense as it is useless if it isn't up to date.
> 
> If you mean storing a local list of channels and checking their online status for the desktop notifications, then yes, this could theoretically be done, but it would be highly inefficient, as you'd need to request every stream data separately. It is however possible to "coalesce" several stream requests so that the number of all requests can be reduced, but this is fairly limited and doesn't really solve the issue. It would also probably tell Twitch more about you than just requesting the followed live streams while being logged in.
> 
> By using this app, you're already doing much better privacy wise than using the Twitch website or the official app, as there are no tracking scripts or any of that kind included here and never will be. Like using every other big online service, it is a tradeoff between your privacy and convenience, ease of use and enjoyment. I'm afraid there's not much more which can be done here.

Thanks for explaining how data is used and stored. I think it would be a great addition to the readme or wiki!
