### ISSUE TITLE
GSOD

### ISSUE THREAD

**Issue by BoredSloth** [streamlink/streamlink-twitch-gui#550]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Causes GSOD on Win10 (DPC Watchdog Violation) if launched on next system restart that has been shut down abruptly (for example power outage).

### Reproduction steps

1. Restart OS in improper manner
2. Launch Streamlink Twitch GUI after OS fully loads
3. get GSOD
Note: launching application after recovering from GSOD will cause GSOD again

### Environment details

Operating system and version: Win10 (10.0.16299.309)
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.10.0
Configuration details: ...

### Comments, logs, screenshots, etc.

This is the only application (i have) that causes the problem.
As a workaround: doing normal system restart after the abrupt one fixes the problem.

**Comment by bastimeyer** [comment]
I can't help you with that, especially without any logs. Your issue is very likely caused by something else and what you're describing here are just side effects. Streamlink Twitch GUI is a NW.js app, which is basically just Chromium+NodeJS, similar to Electron. Those kind of issues have to be reported upstream if you're able to isolate them and find the cause of it, as it is certainly not related to the app specific code here.
