### ISSUE TITLE
Suggestion: Open chat with popout url

### ISSUE THREAD

**Issue by Bullet25fxbx** [streamlink/streamlink-twitch-gui#551]
### Checklist

- [X] This is a feature request.

### Description

The current chat option opens to https://www.twitch.tv/[stream]/chat. This URL still opens an old version of the chat page. If you open https://www.twitch.tv/popout/[stream]/chat, you get the new version of the chat page. Could an option be added to chose the popout url or not?

The issue with the old regular chat link is that bits will not work in it. Bits require the newer chat page to work now.

**Comment by bastimeyer** [comment]
> This URL still opens an old version

As I've said in #536, I can't find any source of Twitch announcing a change of the canonical chat URL.
It can be changed here of course, but I don't know how I feel about this, since they've changed the popout chat url a couple of times in the past and I don't want it to break at some point in the future if they decide to change it again.

> bits will not work in it

What do you mean? The default chat page displays bits and also lets me buy ones. The difference here, which is weird btw, is that the popout chat is showing weekly bits and the default one overall bits at the top.

----

The embedded chat URL which is described in the official developer documentation seems to be the same as the popout chat. Maybe this should be used here instead...
https://dev.twitch.tv/docs/embed/#embedding-chat

**Comment by Bullet25fxbx** [comment]
About bits not working. Sorry for not being more clear. Yes, you can buy new bits and see bits others sent but if you try to actually use any yourself, it just does nothing. The message does not send. If you use the popout chat it works fine. I'm not sure why this is the case.

Yes, I saw the post #536 and I completely understand what you're saying which is why maybe adding a new option in the chat settings to use the popout/embed url might be better way to go?

Also, just checked, the https://www.twitch.tv/embed/[stream]/chat url works fine like the popout url.

Sorry if I didn't describe anything here well enough.

**Comment by bastimeyer** [comment]
> but if you try to actually use any yourself, it just does nothing

Ah, okay...

> adding a new option in the chat settings

Yeah, this could be done. Would it make sense, though? Both URLs currently provide the same chat implementation and there's no difference. However, since Twitch is providing these two different URLs, I can see them changing something in the future, so maybe it is indeed a safer choice to let the user decide. Maybe the currently used URL should be added as well.

> Sorry if I didn't describe anything here well enough.

All fine :)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/pull/536#issuecomment-377322656
Letting the user decide is not necessary, I think. The embed-URL might change styles or something else in the future, because it is meant for, well, embedding the chat into other websites. The popout URL on the other hand is exactly what we need, and since the old URL doesn't work anymore, there's really no reason to let the user decide. If the popout chat URL does change in the future and break the app, so be it. It's a quick fix anyway.
