### ISSUE TITLE
Quality issue with 810p60

### ISSUE THREAD

**Issue by cypsss** [streamlink/streamlink-twitch-gui#553]
- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description
Twitch GUI launches 720p60 stream with decreased bitrate (3mb) when choosing source quality for a 810p60 stream that does show 810p60 is available in the livestreamer log after stream launches. Also checked the stream in chrome as well as my phone, the quality is extremely better than what I get with Twitch GUI

### Reproduction steps

1. Launch an 810p60 stream

### Environment details

Operating system and version: Windows 8.1 64 bit
Streamlink Twitch GUI version: v1.5.0

### Comments, logs, screenshots, etc.

Daum Potplayer stream codec info:
![codec](https://user-images.githubusercontent.com/38142567/38441871-0707269e-399b-11e8-9ede-40e0b13ccc1c.png)

Actual stream information from a Twitch Analyzer (https://r-1.ch/analyzer/)
![info](https://user-images.githubusercontent.com/38142567/38441909-2922c2ba-399b-11e8-9662-e744931133ce.png)

Livestreamer log in GUI after launching stream
![available](https://user-images.githubusercontent.com/38142567/38442499-60258426-399d-11e8-854d-4854c32d4bc3.png)

**Comment by bastimeyer** [comment]
> in the livestreamer log

You are using Livestreamer instead of Streamlink. The Livestreamer project is dead since more than two years and doesn't work properly when selecting certain stream qualities. Streamlink is the continuation of Livestreamer and Streamlink Twitch GUI has switched to Streamlink one and a half year ago and only supports Livestreamer for compatibility reasons.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities

The stream quality mapping can then be precisely configured in the settings menu.

**Comment by cypsss** [comment]
Thank you! Lol I discovered Twitch GUI through a year old youtube video that used Livestreamer, my bad. switched to streamlink now but also managed to fix the issue while using livestreamer by adding "810p60" to the Source Missing translations in the Twitch GUI Streams tab

**Comment by bastimeyer** [comment]
Yeah, it's a bit unfortunate that these video creators are telling their viewers to install Livestreamer instead of telling them to follow the official guides:
https://github.com/streamlink/streamlink-twitch-gui/wiki

If you're adding this quality name to the Livestreamer quality mapping, then it'll only work for this explicit quality and not for similar ones. That's why you should be using Streamlink, so that you can define a range of streams that will be matched by the quality selection (exclusive selection).
