### ISSUE TITLE
Adding communities to followed games

### ISSUE THREAD

**Issue by JonGuithub** [streamlink/streamlink-twitch-gui#556]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

I would like to request the possibility of adding communities to the followed games list. When you go to your followed games list there are two options, live games and all games. I would like to add "followed communities" there. I don't know if that's even a twitch feature at all, I mean if you can actually follow communities. If not feel free to close the request. Thanks

**Comment by skulblakka** [comment]
>I don't know if that's even a twitch feature at all, I mean if you can actually follow communities

You can follow communities on Twitch

**Comment by bastimeyer** [comment]
I don't want to add more features to the app which aren't officially supported by Twitch.

Following communities is not a feature provided by their public APIs. I don't know if this can be done by using their old private API, like following games, but using private APIs is generally a bad idea, because Twitch is free to change them without needing to deprecate things first (*implying they don't do this on their stable APIs, cough cough 67d23f8*). The follow-game-button just broke as a result of this in the 1.4.1 release and needed to get fixed, because endpoints were changed without any announcements (#549).

The current Twitch API situation for third party applications is quite bad. I've explained it here recently:
https://github.com/streamlink/streamlink-twitch-gui/issues/549#issuecomment-375975415
Twitch has announced their new `helix` API last year, but this one doesn't provide all of the features which their "current" public `kraken/v5` or private APIs do and it is unclear if the helix API will ever include those features. What is clear however, is that all the `kraken` APIs (v3 and v5) and probably also their private API will be shut down on 2018-12-31.

The situation with the private API is a bit weird. When Twitch rebuilt their website last year, they've also switched to their also new GraphQL based private API, which exists in addition to the new `helix` RESTful API. In the past, the website was using a combination of the public `kraken/v5` (like every other application) and private API for experimental stuff, like following games. Now with the GraphQL API, they are independent of their old APIs, both public and private, and can add more features to their website without needing to worry about breaking stuff for other applications, since the GraphQL based API isn't meant to be used by third party applications. This decision comes at the cost that applications like Streamlink Twitch GUI won't be able to provide the same features, which is probably in their interest here. For the end user and also for me personally, this is sad.
