### ISSUE TITLE
When no player is set, default should use the same default option as when set

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#559]
### Checklist

- [x] This is a bug report.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

On a computer with VLC and MPV installed, both are listed in settings/player tab, and VLC is shown as the default one. This is the one picked to launch streams by default.
However, it runs VLC with different defaults than the ones  when user force select VLC without modifying any settings. For example no "Allow the player to get closed" nor "Set custom title".

### Expected / Actual behavior

It should use the same default values as when VLC is explicitely picked as player.

### Reproduction steps
Just have no player explicitely picked.

### Environment details

Operating system and version: Archlinux
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.11

**Comment by bastimeyer** [comment]
This can't be done, since the default player depends on Streamlink's config file, which can be modified by the user and is therefore too dynamic to parse reliably.

The default Streamlink config just launches VLC without any special parameters, whereas the player profiles in the Twitch GUI have a set of parameters which will be set depending on the configuration:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.5.0/src/config/players.json

The Twitch GUI has this list of player presets, because when those are selected by the user, the parameters provided by Streamlink's config file will be ignored and the Twitch GUI will resolve the player executable by itself.

Since I don't expect everyone to have VLC or MPV installed (those two presets exist on all supported platforms), I can't make one of them the default selection and have to go with "no preset" instead, because it is the safer choice.

The only solution that is reasonable would be asking the user on the first launch to select a player preset instead of just asking to go to the settings menu.

**Comment by bastimeyer** [comment]
Forgot to include the player configuration wiki page in my previous post:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

**Comment by Porkepix** [comment]
Mmmh, okay. And while mpv can run without any configuration on the system just with default, which would allow streamlink[-twitch-gui] to see it and run defaults, VLC by default seems to write things even when nothing was changed.

So I guess nothing can be done and this should be closed?

**Comment by bastimeyer** [comment]
I could make the VLC preset the default selection, since Streamlink uses VLC by default.
But this would cause issues for people who have a customized Streamlink config file. Those would then need to select the "no preset" option.

Since the "no preset" default selection "kinda" works, I'd rather not want to change it. I don't have a better idea for this, unfortunately...

**Comment by Porkepix** [comment]
Yup, by design it seems difficult to do better: even simple things like having stream's title as window title seems to be difficult to do. You already explained earlier that only GUI can do that because streamlink isn't aware of it so that can't be part of streamlink's default, and GUI's "no preset" completely rely on streamlink's defaults.
