### ISSUE TITLE
App run with no content after add new translation

### ISSUE THREAD

**Issue by dxball** [streamlink/streamlink-twitch-gui#566]
I try to add `zh-tw` (Traditional Chinese) translation
After test build, the app run with no content.
Step to reproduce:
- copy `src/app/locales/en` to `src/app/locales/zh-tw`
- modify `src/app/locales/zh-tw/config.js` with
  ```js
  export { default } from "ember-i18n/addon/config/zh";
  ```
- modify `src/config/locales.json`
  ```json
	"default": "en",
	"locales": {
		"en": "English",
		"zh-tw": "Traditional Chinese"
	},
  ```
- test build with `grunt build`

The app show's no content
![image](https://user-images.githubusercontent.com/194673/39955865-da874fce-5608-11e8-956b-a2a43cd69686.png)

Here is the main message of the console log
```
Assertion Failed: You are looking for a translations locale in the Zh namespace, but the namespace could not be found
```
![image](https://user-images.githubusercontent.com/194673/39955890-5ab1a7da-5609-11e8-9091-f908e4eacf90.png)

---

If I use `zh` instead of `zh-tw`, the app work as except.
![image](https://user-images.githubusercontent.com/194673/39955907-9d03d6ee-5609-11e8-9443-628cd9b67887.png)

**Comment by bastimeyer** [comment]
Thanks for reporting!
It seems like `ember-i18n` is requiring the parent locale `zh` here, as it needs the parent locale for looking up missing translations. I've changed the locale import logic a bit (8b80216c1ac6ff85122367143de1f53505490f3f), so that you only have to create the `zh` config.js file in order to make the `zh-tw` locale work.
While doing that, I think I found another issue with the missing translations lookup of the parent locale, but I'm not sure if this is a bug of the latest `ember-i18n` version (5e3362fbbe913208a756d8128c0b83c688a1f2a6).

**Comment by dxball** [comment]
Thank you! It work now!

PS. I have to make a `src/app/locales/zh/config.js` file to make `zh-tw` translation work

file structure 
![image](https://user-images.githubusercontent.com/194673/39957597-3341d976-5628-11e8-9a85-5b86f8e3504e.png)
