### ISSUE TITLE
Error: Timeout message when launching stream that has previously gone offline

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink-twitch-gui#568]
### Checklist

- [x] This is a bug report.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Sometimes, seemingly after VLC closes itself automatically after a stream has ended, I face a popup saying "Error: Timeout" when next I try to launch the stream.

### Expected / Actual behavior

It's possible there's an actual issue, so it makes sense for the error message to appear, but it'd also make sense for it to reset after a while so you don't need to click close/restart next time you try to launch the stream.

### Reproduction steps

As far as I can tell it happens if you let VLC close automatically after the stream ends.

1. Let streamer end stream.
2. Wait for VLC to close. 
3. Try to launch stream again, even several hours later.

### Environment details

Operating system and version: W7 x64
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.11.0

**Comment by bastimeyer** [comment]
The timeout error message is showing, because Streamlink exited with this error. The error dialog in the GUI is just a representation of this Streamlink error. There's a difference between streams ending gracefully or between timeouts, when streams end unexpectedly.

Streams which don't end properly, currently don't get removed from the watching list, even if the stream's dialog (popup) was hidden at the time. So when you're re-opening the same stream again afterwards, you'll see the error message from before. The logic behind this is that the user should always be informed about any kind of error.

I'm not entirely sure what the best solution for this would be. Automatically re-popping up the stream dialog and interrupting the user in a potental action/navigation is not a solution. And just silently removing the stream from the watching list isn't one either. The button in the title bar leading to the watching menu needs some kind of failure indicator, like the notifications have. A notification could also be shown if the stream dialog was hidden while a stream has errored out.

**Comment by sfkpmr** [comment]
I see, and it seems a bit messy to fix.

I also like the error messages as is for streams that fail to launch right now. 

Maybe "old"/"unaddressed" errors like this could be moved to their own button next to the Twitch login, possibly with a drop down menu and a "suppress notifications" checkbox? Along with a notification like for the live streams button.
