### ISSUE TITLE
Unexpected version check output

### ISSUE THREAD

**Issue by eXcuvator** [streamlink/streamlink-twitch-gui#572]
### Description
GUI cant verify streamlink -- but I *can* run streamlink successfully directly. 

### Environment details

Operating system and version: Ubuntu 18.04 LTS, Python3 via anaconda, Python2 via apt-get
Streamlink Twitch GUI version: Most recent
Streamlink version: streamlink 0.12.1
Configuration details: 
$ which streamlink
/usr/bin/streamlink
$ which python
/home/foo/anaconda3/bin/python

I've tried both leaving the defaults in config, and setting these up. Streamlink was installed via apt, not python-pip. 
...

### Comments, logs, screenshots, etc.

Running stream via streamlink directly works:
$ streamlink https://www.twitch.tv/singsing 360p
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/singsing
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: /usr/bin/vlc
w^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...

**Comment by bastimeyer** [comment]
You have to use the python version which streamlink has been built for and not a different one that is installed in your home directory. The GUI currently uses the first matching python path result from resolving the $PATH env var, which isn't always the right choice, depending on the order of paths in your $PATH env var. This needs to get fixed in the future, but for now, run this and use the returned path as custom python path in the GUI's streaming settings menu:
```
head -n1 $(which streamlink) | sed -E s/^#!//
```

**Comment by bastimeyer** [comment]
@sinatosk You should report those library incompatibility on the [issue tracker of the Streamlink Arch package](https://bugs.archlinux.org/?project=5&string=streamlink). Maybe even on the [Streamlink repo](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). I haven't updated my Arch system since a few weeks and am also using the streamlink-git AUR package, so I can't confirm this.

**Comment by eXcuvator** [comment]
The command raised a syntax error, but the part before | delivered what I needed anyways. Working now!
