### ISSUE TITLE
Image just freezed a lot turning into squares, but sound is ok.

### ISSUE THREAD

**Issue by odesa2010** [streamlink/streamlink-twitch-gui#573]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
After start stream picture is start freeze. But sound is sounding well. Only source mode (all is ok with my connection), low andhigh mods are good to watch.
Video of this - https://youtu.be/u1V33afXaqE.

screen of internet connection
http://www.speedtest.net/result/7370438639

Used VLC player with last update.

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink Twitch GUI version: ...
Streamlink version: ...
Configuration details: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
Your issue is neither related to **Streamlink Twitch GUI** nor **Streamlink**. Streamlink Twitch GUI is just a launcher for Streamlink, and as you can see, it is properly doing that. Streamlink is properly launching the selected player as well (VLC in your case) and it is properly passing the stream data towards it, since the sound is playing.

Your issue seems to be a rendering issue of VLC. I can't help you with that and you need to resolve this on your own. Maybe you have misconfigured your VLC player and if that's the case, you should reset its configuration. However, if this doesn't work, try using a different player or different VLC version.
