### ISSUE TITLE
"My Games" only shows 16 games

### ISSUE THREAD

**Issue by xingped** [streamlink/streamlink-twitch-gui#578]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Clicking into "My -> Games" shows only a maximum of 16 games.

### Expected / Actual behavior

Previously, it would show all games being followed that currently have streamers streaming. This behavior still works as expected on twitch.tv, but not in the Streamlink GUI.

### Reproduction steps

1. Have more than 16 games followed that currently have streamers.
2. Open streamlink and see that only 16 games show and no more loads.

### Environment details

Operating system and version: Windows 10 (latest build)
Streamlink Twitch GUI version: 1.5.0
Streamlink version: Unknown
Configuration details: ?

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
This looks like it's a bug in the Twitch API. The followed games are a part of the old private Twitch API which was being used on their website before they rebuilt it a few months ago.

The issue here is that for any request being made for live followed games, the API is returning invalid metadata. When requesting all followed games, the metadata is correct.

The `_total` property in the JSON response should include the number of the overall available records, but instead, it includes the number of returned records, which doesn't make any sense when requesting data in chunks via the `offset` and `limit` parameters. See this example via `curl` and `jq`:

```bash
# requesting live followed games (max: 4)
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  -H "Authorization: OAuth $OAUTH_TOKEN" \
  "https://api.twitch.tv/api/users/$USER_NAME/follows/games/live?limit=4" \
  | jq -r "._total"
4

# requesting live followed games (max: 16)
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  -H "Authorization: OAuth $OAUTH_TOKEN" \
  "https://api.twitch.tv/api/users/$USER_NAME/follows/games/live?limit=16" \
  | jq -r "._total"
4

# requesting all followed games (max: 16)
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  -H "Authorization: OAuth $OAUTH_TOKEN" \
  "https://api.twitch.tv/api/users/$USER_NAME/follows/games?limit=16" \
  | jq -r "._total"
19
```

As I said, this data is being retrieved from the old and private Twitch API. I've described the whole Twitch API situation recently here:
https://github.com/streamlink/streamlink-twitch-gui/issues/549#issuecomment-375975415
I doubt they will fix this when I report this issue on their bug tracker.
