### ISSUE TITLE
Trying to build dev version

### ISSUE THREAD

**Issue by Chibicon** [streamlink/streamlink-twitch-gui#588]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Trying to build the latest version because there are a lot of commits between release and today. Especially want that vodcast fix.

### Expected / Actual behavior

Development version launching after build.
After Launching App appears nothing happens.

### Reproduction steps

1. Clone the repo
2. Yarn install
3. grunt build

### Environment details

Operating system and version: Windows 10 Pro
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.14.2

### Comments, logs, screenshots, etc.

https://image.prntscr.com/image/4JOv5TLNTqaNUhox95Vw_g.png

**Comment by bastimeyer** [comment]
You have misconfigured git for Windows. It is checking out Windows style line endings instead of Unix style line endings (or instead of keeping the original line endings of the files) and the code linting tool (eslint) doesn't accept these line endings.

https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

Try this to fix it locally (only in the cloned repo):
```sh
cd streamlink-twitch-gui
git config core.autocrlf input
git checkout master
```
**Or** set the option globally
```sh
git config --global core.autocrlf input
cd streamlink-twitch-gui
git checkout master
```

**Comment by Chibicon** [comment]
I knew exactly what I selected during install that screwed it up after reading that. Reinstalled git with the correct settings and it worked. Thanks man. Vodcasts now properly being faded.
