### ISSUE TITLE
Windows UAC blocking execution

### ISSUE THREAD

**Issue by Phoscur** [streamlink/streamlink-twitch-gui#593]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
the one in the 1.6.0 installer?

**Configuration details:**  
Up to date Windows Defender

### Description

When trying to update to the new 1.6.0 version on windows via installer, the program is blocked by Windows Defender

### Expected / Actual behavior

Should install normally, not beeing recognised as malicious or "being a risk".

### Reproduction steps

0. Run windows update to get newest defender definitions
1. Download new installer
2. Try to run it

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/191093/43713133-d1193296-9978-11e8-88b8-3c039504f119.png)

**Comment by bastimeyer** [comment]
This is what Windows does if you're trying to execute downloaded applications which are unsigned (see the "Unknown publisher" notice). This has nothing to do with the current release. Signing executables costs money on Windows and you have to buy the certificates from 3rd party companies. I won't spend anything on that, especially since it can cost several hundred Euros per year. There are no real solutions for non-profit open source projects.

You either have to add a permanent exception in your Windows defender settings or click the "more info" (Weitere informationen) text and confirm a temporary exception.

**Comment by Phoscur** [comment]
Was able to install now, the dialogue from the screenshot above did not appear this time.
