### ISSUE TITLE
Allow command line switches for chrome and firefox to control chat window size and position

### ISSUE THREAD

**Issue by syrteaghue** [streamlink/streamlink-twitch-gui#601]
## Feature request

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a feature request and I have read the contribution guidelines.

### Description

First time posting a suggestion, so be kind.

Just as the title says. It would be great if we could alter the preset switches you guys have so that everything could pop up in just the right place at just the right size.

### Additional comments, screenshots, etc.

N/A

**Comment by bastimeyer** [comment]
This was asked a couple of weeks/months ago, but I can't find the thread anymore. I guess the person must have deleted it, which is unfortunate.

**Firefox** is not a supported chat application, because it doesn't let you set parameters to remove the regular browser UI elements.
https://bugzilla.mozilla.org/show_bug.cgi?id=1283670

In **Chromium** or **Chrome**, you can add the following custom launch parameters:
https://github.com/chromium/chromium/blob/72.0.3592.1/chrome/common/chrome_switches.cc#L733-L740

Example:
```
--window-size=350,1080 --window-position=1570,0
```
I don't know why, but those window size and position parameters don't seem to work reliably on every platform. That's why they have not been added to the predefined parameter list.

**Comment by bastimeyer** [comment]
Closing, since the Chromium parameters are not working reliably and therefore can't be added here.
