### ISSUE TITLE
Problem after trying nwjs-upgrade branch

### ISSUE THREAD

**Issue by undeference** [streamlink/streamlink-twitch-gui#605]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:** 
```
$ cat /etc/system-release
Fedora release 28 (Twenty Eight) 
```

**Streamlink Twitch GUI version:**  (local based on master, ember-update, with nwjs-version 0.32.1 specified because of #563, last updated 5 October)

**Streamlink version:**  0.14.2 and also 0.6.0

**Configuration details:**  

### Description

I did a `
```
git checkout master
```
` and saw " 

> * [new branch]        nwjs-upgrade       -> origin/nwjs-upgrade

", so I decided I'd try that:
```
$ git checkout origin/nwjs-upgrade
$ npm install && grunt --force build:prod compile
…
>> [module] data/models/settings (0/2) (60ms)
>> [test] Serializer (0/1) (48ms)
>> [assertion 1] Died on test #1     at eval (./test/tests/data/models/settings/model.js:57:17)
>>     at Object../test/tests/data/models/settings/model.js (chrome-extension://mlcejmpilmkofhlcmphbgnpnealjhmmb/test.js:309:1)
>>     at _webpack_require_ (chrome-extension://mlcejmpilmkofhlcmphbgnpnealjhmmb/runtime~main.js:87:30)
>>     at webpackContext (./test/tests/data_sync_\.js$:35:15)
>>     at Array.forEach (<anonymous>)
>>     at importAll (./test/tests/index.js:4:11)
>>     at eval (./test/tests/index.js:12:1): Cannot use 'in' operator to search for 'streams' in undefined
>> [test] hasStreamsLanguagesSelection on didUpdate (0/1) (10ms)
>> [assertion 1] Died on test #1     at eval (./test/tests/data/models/settings/model.js:79:17)
>>     at Object../test/tests/data/models/settings/model.js (chrome-extension://mlcejmpilmkofhlcmphbgnpnealjhmmb/test.js:309:1)
>>     at _webpack_require_ (chrome-extension://mlcejmpilmkofhlcmphbgnpnealjhmmb/runtime~main.js:87:30)
>>     at webpackContext (./test/tests/data_sync_\.js$:35:15)
>>     at Array.forEach (<anonymous>)
>>     at importAll (./test/tests/index.js:4:11)
>>     at eval (./test/tests/index.js:12:1): Cannot use 'in' operator to search for 'streams' in undefined
…
>> 2/2987 assertions failed (10742ms)
```

So I decided to go back
```
$ git checkout local
$ npm update
$ grunt --force build:prod compile
…
Done, but with warnings.
$ ./start.sh
```

### Expected / Actual behavior

A window popped up saying "

> Your profile can not be used because it is from a newer version of NW.js.

" (resolved with 
```
rm ~/.config/streamlink-twitch-gui* -rf
```
) then immediately disappeared and I saw this in my terminal:

```
[10882:10924:1102/132643.235798:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 2
[10882:10882:1102/132643.487638:ERROR:desktop_window_tree_host_x11.cc(1112)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)
[10918:10918:1102/132643.537096:ERROR:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
Could not initialize application window
TypeError: Cannot use 'in' operator to search for 'streams' in undefined
    at l (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:12:8233)
    at chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:12:7518
    at r.get (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:12:8049)
    at r.get (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:296908)
    at re (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:288333)
    at ne (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:288837)
    at Object.re [as get] (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:288624)
    at r._hasStreamsLanguagesSelection (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/main.js:20:158798)
    at w (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:283398)
    at r.trigger [as _super] (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.js:78:374455)

```

It worked before I tried nwjs-upgrade ><

**Comment by bastimeyer** [comment]
I've removed the old `nwjs-0.31` branch and pushed the new `nwjs-upgrade` branch (rebased from the old one) because of this:
https://github.com/streamlink/streamlink-twitch-gui/issues/603#issuecomment-435128369

The branch itself isn't ready yet, but it builds successfully, as you can see here:
https://travis-ci.org/streamlink/streamlink-twitch-gui/builds/449461763

> ```
> $ git checkout origin/nwjs-upgrade
> $ npm install && grunt --force build:prod compile
> ```

Please use `yarn` instead of `npm`. Yarn is much more reliable in comparison to npm and if you set the `--pure-lockfile` parameter, you'll install exactly the packages which have been defined by the lockfile instead of resolving the dependency tree again (which might cause issues):
https://github.com/streamlink/streamlink-twitch-gui/blob/ed91353cbf9f41129036ec3a9762ed244b4b9bd6/.travis.yml#L40

Forcing `grunt` also doesn't do anything other than skipping failed tasks and is therefore unnecessary. If the test task has failed, then the production build will most likely be bad, too. However, since the build succeeds on TravisCI, you might have done something wrong earlier.

Since every minor NW.js upgrade is based on another major Chromium release, config and cache files in your `${XDG_CONFIG_HOME:-${HOME}/.config}` directory will be upgraded as soon as you launch the app with a newer NW.js version. If you downgrade later on by running a build from the master branch (which is using an older version), you'll see the popup message, but it usually can be ignored. I don't know though how it can be disabled.

What you should do now is backup (or remove) the config dirs in `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink-twitch-gui{,-test}` and also remove the `node_modules` folder in the git repo. Then fetch the `origin` remote again (`git fetch origin`), check out the desired branch and use yarn to install the app's dependencies with the `--pure-lockfile` parameter. Then rebuild the app as usual.

You probably won't need to do all of this, but that will completely reset the old application state.

**Comment by undeference** [comment]
I got it working by restoring from a backup. I updated my scripts to use yarn instead of npm and verified that they work. Everything is working again.

Thanks
