### ISSUE TITLE
Cannot Search if first word is a number

### ISSUE THREAD

**Issue by mystomex** [streamlink/streamlink-twitch-gui#610]
Its a simple bug report Im not gonna fill out all that info. if you dont want to hear it then oh well

Win 10, streamlink twitch gui 1.6.0

Cannot search anything with a number then space as the first 2 characters such as the game 7 Days To Die
just try searching the game and see how nothign happens when you exclude the number it works.

**Comment by bastimeyer** [comment]
> if you dont want to hear it then oh well

The issue templates are considered optional and are there to make people think before they submit an issue, so that the time spent by the dev(s) on the issue tracker can be minimized. For those simple reports like this one it's absolutely fine if you just describe what's not working correctly, just like you did, so don't worry.

----

The input field of the search bar component requires you to enter at least 3 non-whitespace characters at the beginning of your query. This has nothing to do with a leading number. See here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/ui/components/search-bar/component.js#L38

This restriction was added with channel/user names in mind, but doesn't work well when searching for certain games or stream titles. The entire search bar component is in desperate need of a complete rewrite, but I can't do it yet, because I still need to finish some other stuff first which a new implementation would depend on. For now, I'll simply change or remove the regexp. That should fix this issue at least. I'll do this tomorrow when I get the time.
