### ISSUE TITLE
Ability to launch streams from outside the application (for browser integration etc)

### ISSUE THREAD

**Issue by CodilX** [streamlink/streamlink-twitch-gui#613]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

It would be amazing if we could have an option to launch a stream externally - not using the app itself. A custom protocol handler would be the best. The use case could be browser integration - using Greasemonkey or something similar to inject buttons on Twitch with the URL such as `twitchgui://some_stream`. 

I find it easier to browse Twitch via the website, then I switch to the application, find the stream I was watching and launch it from there. Having a button on Twitch that would do that automatically would be so great, all we need is some kind of external interaction with the app itself.

**Comment by bastimeyer** [comment]
Supporting the registration of custom protocol handlers on all supported OSes, namely Linux, Windows and macOS is quite challenging. The registration methods don't just dramatically differ from OS to OS, but also from OS version to OS version. On Linux there are also a few differences between desktop environments, even though the XDG standard exists. That means you don't have to just "support Linux", but individual desktop environments, and there are a lot.

Unfortunately, there are no (usable) NodeJS modules available in the NPM registry for registering custom protocol handlers and they would have to be built from scratch. The only one that's available is for Windows, but it can't be used here, because it requires some dependencies being compiled for NW.js' NodeJS runtime, which can't be done with the nw-builder tool that's being used here to make the final app builds.

If you want to properly implement custom protocol handlers, you have to deal with a lot of stuff and care for a lot of edge cases. As an example of an edge case, there's the problem of the application path, which isn't static for the "portable" releases and once it changes, the registered protocol needs to be re-applied.

I don't think it's worth spending time on implementing custom protocol handlers unless well written and tested NodeJS modules are already available.

----

If you want to launch streams from an external source, you can already do that via the app's `--launch` parameter. See the parameters page on the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

AFAIK, you can also set up custom handlers in Firefox, which would make it easy to write a browser extension or even a so called "bookmarklet" that makes you launch streams listed on the Twitch website with Streamlink.

**Comment by CodilX** [comment]
@bastimeyer - I haven't looked into NodeJS support for protocol links, however the workaround could be Twitch GUI listening for http requests on some random port, the same could be achieved as a protocol link.

**Comment by CodilX** [comment]
> 
> 
> > http requests
> 
> This seems unnecessary...
> 

As far as I understand Twitch GUI already runs an http server for authentication to Twitch `http://localhost:65432/redirect`. Adding an option (disabled by default) for controlling Twitch GUI via http requests would be beneficial to some users if protocol handling is out of scope for Node and/or NW.js. 

I'll fiddle around with custom protocols to get what I want working (launching streams in Twitch GUI via browser), I just hope one day something could be implemented that would allow more robust external controls of the application.

**Comment by bastimeyer** [comment]
Regarding the `--launch` parameter, this was a bug in NW.js and has been fixed a long time ago. The recent Streamlink Twitch GUI releases already included this fix.

I'm closing the thread now, as there are no plans for implementing an HTTP server for sending commands to the GUI.
