### ISSUE TITLE
AppImage build for linux installation

### ISSUE THREAD

**Issue by LoveIsGrief** [streamlink/streamlink-twitch-gui#616]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

There's a TODO for creating linux executables and packages. I'd like to propose [AppImage](https://appimage.org/), which can be [built with Travis](https://docs.appimage.org/packaging-guide/hosted-services/travis-ci.html?highlight=travis). The first iteration could just provide the full `.AppImage` and further iterations could then provide an [update mechanism](https://docs.appimage.org/packaging-guide/optional/updates.html?highlight=update)

**Comment by bastimeyer** [comment]
I haven't looked that much into these new alternative packaging formats recently, but appimage looks like a better choice (for now) than flatpack or snap.

When I get the time for it, I'll see what can be done here if it's not too complex or time consuming. Pull requests are welcome, though, if you or anyone else has some experience with it, because I currently do not.

**Comment by bastimeyer** [comment]
Thanks, but that tools looks a bit outdated. It also packages its own binaries for creating the appimages and what it actually does is executing simple shell commands, so I don't think it's very useful.

I will build a proper TravisCI config and build steps after I've found the time to experiment with building appimages locally on my system.

**Comment by bastimeyer** [comment]
I've pushed an initial AppImage build config to the repo on the `appimage` branch:
https://github.com/streamlink/streamlink-twitch-gui/compare/appimage

Once I've done some more testing (not sure when), I'll open a PR, so I can add a description and a proper to-do list for the stuff that's currently missing or not working.

What's weird is that I had to unset the `PYTHONHOME` env var, which gets set by the `AppRun` executable and causes issues when trying to execute streamlink. There's an alternative `AppRun` bash script in the AppImageKit repo and this one doesn't set the env var and thus doesn't cause problems. Integrating the bash script instead however would require a bit more effort here because of the way I've implemented it, as stuff gets downloaded and verified from the AppImageKit releases page, so simply unsetting the env var was much easier. Not sure if this could cause problems for some users, though.

----

The AppImage can be built like this and then run from the `dist` directory:
```sh
yarn run grunt clean:dist build:prod dist:appimage_linux64
```
