### ISSUE TITLE
GUI doesn't save oauth token

### ISSUE THREAD

**Issue by siint** [streamlink/streamlink-twitch-gui#619]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 Pro, all updates

**Streamlink Twitch GUI version:**  
streamlink-twitch-gui-v1.6.0-win64.zip

**Streamlink version:**  
streamlink-1.0.0.exe

**Configuration details:**  

### Description

I recently reinstalled my OS and since I use Streamlink to watch Twitch on a daily basis these two applications were on the first ones I installed. Everything is working expect, that whenever I close the GUI and reopen it I'm logged out and have to reauthenticate with Twitch. I tried uninstalling and reinstalling multiple times and with various versions but nothing I tried has helped me save my oauth token when reopening the programm. I tried adding --twitch-oauth-token=XXXXXXX to the streamlinkrc file but that didn't work. I wanted to add that line to the GUI config aswell, but I couldn't find that one.
Am I missing some setting or is there a problem with twitch api?

### Expected / Actual behavior

I expect to have my Login saved and not to have to reauthenticate on every launch

### Reproduction steps

1. Open the GUI and authenticate with Twitch
2. close the GUI and reopen --> login not saved

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment]
Argh, I'm sorry, I totally forgot about this thread after opening it on my phone a month ago (it gets marked as read then).

The Twitch GUI uses its own authentication system and stores the OAuth token in its LocalStorage (HTML5 API). You don't have to set any Streamlink parameters, this is unrelated and only necessary if you want to let Twitch know that you are watching a stream with your user account. There's an option in the streaming settings menu for automatically setting the Streamlink parameter while being logged in.

If the Twitch GUI doesn't save the OAuth token, then neither do other settings get saved, because it's using the same storage system.

Since you're on Windows, make sure that the Twitch GUI is able to write its config files in `%LOCALAPPDATA%\streamlink-twitch-gui` (`C:\Users\%USERNAME%\AppData\Local\streamlink-twitch-gui`) folder.

You can also use the `--user-data-dir=PATH` parameter to let NWjs/Chromium know to store the config files in a different location.
