### ISSUE TITLE
usage: streamlink [OPTIONS] <URL> [STREAM] streamlink: error: unrecognized arguments: twitch.tv/nl_kripp best

### ISSUE THREAD

**Issue by jj-279** [streamlink/streamlink-twitch-gui#620]
## Bug report

- [x] I am not a coder, I am just a casual user looking for some error troubleshooting and I could not find any other forum to contact the dev(s).
- [x] I kind of understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version: Windows 10, up-to-date**  

**Streamlink Twitch GUI version: 1.6.0**  

**Streamlink version: 1.0.0**  

**Configuration details: Initially installed both Streamlink and Twitch GUI on a non-C: drive and then later reinstalled both on C:, however it seems to have kept my settings from my initial install instead of having cleanly uninstalled the first time**  

### Description

In the Streaming settings, I set Python executable to `C:\Program Files (x86)\Streamlink\bin\streamlink.exe` and Streamlink python script to `C:\Program Files (x86)\Streamlink\Python\pythonw.exe`. This was after I read [Issue #618](https://github.com/streamlink/streamlink-twitch-gui/issues/618).

I also installed VLC on C: Drive and set the Player executable to `C:\Program Files\VideoLAN\VLC\vlc.exe`.

This does not allow me to run streams and instead gives me the below error message

### Expected / Actual behavior

Expected - Click on Streams **->** Choose a stream and click on play button **->** VLC opens up and the stream starts playing

Actual behavior - Click on Streams **->** Choose a stream and click on play button **->** `Preparing, please wait` **->** Streamlink window opens up and tries to run `C:\Program Files (x86)\Streamlink\Python\python.exe` **->** ERROR: 
> usage: streamlink [OPTIONS] <URL> [STREAM]
> streamlink: error: unrecognized arguments: twitch.tv/nl_kripp best

Even though I explicitly set Streamlink python script to `C:\Program Files (x86)\Streamlink\Python\pythonw.exe`, it seems like `C:\Program Files (x86)\Streamlink\Python\python.exe` is running. I do not know if this is the cause of the error, as I am not well-versed with how all of this stuff works but just thought I should point it out.

### Reproduction steps

As mentioned above:

1. Click on Streams
2. Choose a stream and click on play button
3. Dialog box pops up:
> Preparing, please wait
4. Streamlink window opens up and tries to run `C:\Program Files (x86)\Streamlink\Python\python.exe`
5. ERROR: 
> 
> usage: streamlink [OPTIONS] <URL> [STREAM]
> streamlink: error: unrecognized arguments: twitch.tv/nl_kripp best

### Log output

I am not sure how to get this data, sorry.

I realise I am not able to give you all the information you may need, so any help would be much appreciated. Thanks!

**Comment by bastimeyer** [comment]
> streamlink: error: unrecognized arguments: twitch.tv/nl_kripp best

This looks like there's an issue on your system with the Streamlink command line parameters which get generated by the Twitch GUI. It could also be caused by a misconfigured [Streamlink config file](https://streamlink.github.io/cli.html#configuration-file), which the Twitch GUI has no control of. Please remove/backup the custom config file first, if it exists.

In order to see the Streamlink command line parameters which the Twitch GUI uses, you'll have to launch the GUI with the `--logleveel debug` parameter.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters
You can do this from any command line shell or by creating a shortcut to the streamlink-twitch-gui.exe and adding the parameters. Then, when launching a stream, it'll add debug log information to the current log file in `%TMPDIR%/streamlink-twitch-gui/logs`. What I'm interested in are the `StreamingService` related outputs, which look like this:

```
[debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/home/basti/.local/bin/streamlink",
        "--plugin-dir",
        "/home/basti/.config/streamlink/plugins-custom",
        "--http-header",
        "Client-ID=phiay4sq36lfv9zu7cbqwz2ndnesfd8",
        "--no-version-check",
        "--twitch-disable-hosting",
        "--player",
        "/usr/bin/mpv",
        "--player-args",
        "--keep-open=no --title \"$>Gorgc - Dota 2 - pog you\" --no-border --force-window --force-seekable=yes --hr-seek=yes --hr-seek-framedrop=yes --no-cache {filename}",
        "--twitch-oauth-token",
        "***SECRET***",
        "--hls-live-edge",
        "2",
        "--hls-segment-threads",
        "1",
        "--retry-open",
        "2",
        "--retry-streams",
        "1",
        "twitch.tv/gorgc",
        "best"
    ],
    "env": null
}
```

Make sure to remove the Twitch OAuth token, if it's included.

**Comment by lyleaigbedion** [comment]
Hi, I have the same issue and have setup debugging, here's the info you asked for.

`
[2019-03-17T23:59:13.308Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink.exe",
    "params": [
        "C:\\Program Files (x86)\\Streamlink\\Python\\pythonw.exe",
        "--http-header",
        "Client-ID=phiay4sq36lfv9zu7cbqwz2ndnesfd8",
        "--no-version-check",
        "--twitch-disable-hosting",
        "--player",
        "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
        "--player-args",
        "--no-one-instance --play-and-exit --input-title-format \"{name} - {game} - {status}\" {filename}",
        "--twitch-oauth-token",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "--stream-sorting-excludes",
        ">360p30",
        "twitch.tv/undefined",
        "low,best"
    ],
    "env": null
}
`

**Comment by bastimeyer** [comment]
> ```
> "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlink.exe",
> "params": [
>     "C:\\Program Files (x86)\\Streamlink\\Python\\pythonw.exe",
> ```

You have done the opposite thing which you were supposed to do with the temporary workaround mentioned in #618... :confused: 

`streamlink.exe` is meant as the **python script**. `pythonw.exe` belongs into the regular **python executable** field, just like normal, however, it needs to be set explicitly now because it can't be resolved automatically with this workaround.

![2019-02-05 15_42_35-streamlink twitch gui](https://user-images.githubusercontent.com/400279/52284619-ab595800-295c-11e9-8073-93cedc274bf6.png)

I'm sorry if this all is confusing. This whole messy situation will be solved very soon, see https://github.com/streamlink/streamlink-twitch-gui/issues/618#issuecomment-466003917

**Comment by lyleaigbedion** [comment]
I am so sorry about that, changing them fixed my issue immediately. Thank you for solving my silly request.

**Comment by jj-279** [comment]
Wow, I cannot believe I mixed it up like that. Thank you for pointing out the issue and thank you to lyleaigbedion for providing the setup debugging info. Problem solved!

If not for that, I was just about ready to give up entirely on using Twitch GUI, but now finally I can watch streams without having to turn off all my browser plug-ins and opening incognito popout players and reloading them 20 times.

**Comment by bastimeyer** [comment]
All good :)
