### ISSUE TITLE
`--goto` parameter broken

### ISSUE THREAD

**Issue by TydoTydo** [streamlink/streamlink-twitch-gui#630]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Windows 10

**Streamlink Twitch GUI version:**  

Latest release / v1.7.0

**Streamlink version:**  

Latest release / v1.1.1

**Configuration details:**  

External Commands: Enabled

### Description

Launch parameters set via Desktop Icon --> Properties --> Target
Do not seem to work after latest update. 
This works in v1.6.0. Does not work in v1.7.0

### Expected / Actual behavior

Expected: Launches into the Games section with Dota 2 as item choice
Actual: Launches into default position

### Reproduction steps

1. Set: Desktop Icon --> Properties --> Target: "C:\Program Files\Streamlink Twitch GUI\streamlink-twitch-gui.exe" --goto "/games/Dota%202"
2. Lauch program via same Desktop Icon

### Log output

```

```
Bug involves parameters so using parameters to get log also doesn't work

**Comment by bastimeyer** [comment]
It's (only) the `--goto` parameter, which is broken.
Caused by the rewrite of the routing initializer 3174e4e40c8465375e80314acf3c984a4943aec6.

This should have been changed, but I forgot about it
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.7.0/src/app/init/instance-initializers/nwjs/parameters.js#L46-L49
Unfortunately, the parameters initializer doesn't have any tests, so it slipped through :(
