### ISSUE TITLE
Notifications not showing anymore

### ISSUE THREAD

**Issue by 1stmadness** [streamlink/streamlink-twitch-gui#634]
## Bug report
Notifications are no longer showing up after updating to the latest version (v1.7.0)

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Windows 10 1803

**Streamlink Twitch GUI version:**  

v1.7.0

**Streamlink version:**  

1.1.1

**Configuration details:**  

Using streamlink (Windows). Had to login using token manually. Because localhost wouldn't load. I have notifications ON, and when I test it using the 'test notification' button it shows up properly.

### Description
When a followed streamer goes live I used to get a notification from streamlink twitch gui via windows action center. That no longer happens after updating to the latest version.

### Expected / Actual behavior
I expect a notification. But i'm not getting any.

### Reproduction steps

1. Open streamlink twitch gui. 
2. Wait for a streamer to go live.

### Log output

```
[2019-04-11T23:08:20.040Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

```

**Comment by bastimeyer** [comment]
> socket.cork is not a function

Same issue as #628.

See my explanations here:
https://github.com/streamlink/streamlink-twitch-gui/issues/628#issuecomment-480911297
https://github.com/streamlink/streamlink-twitch-gui/issues/628#issuecomment-481510654

The only difference between a test notification and a regular one is that the channel icon needs to get downloaded first into the app's cache directory:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.7.0/src/app/services/notification/dispatch.js#L45

Since Node's stream API is being used here via `fs.WriteStream`, it can fail due to that Node/NW.js bug.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/releases/latest
