### ISSUE TITLE
Preference quality option

### ISSUE THREAD

**Issue by zxctw** [streamlink/streamlink-twitch-gui#635]
**Description**
I think “Preference quality” can select like “1080p60,720p60,720p,480p,360p,160p and Audio Only”. It`s will be better than” Source,High,Medium and low”.

**Comment by bastimeyer** [comment]
No, this doesn't work because stream qualities can vary between different channels, eg. when a channel is not partnered or when it is streaming in a different video resolution.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities

`Source`, `High`, `Medium` and `Low` are just aliases for telling Streamlink to select a stream quality in a specific quality **range**:
- `Source`: select the best available quality - the stream source / input
- `High`: filter out everything above 720p30 and select the best remaining quality
- `Medium`: filter out everything above 540p30 and select the best remaining quality
- `Low`: filter out everything above 360p30 and select the best remaining quality

https://github.com/streamlink/streamlink-twitch-gui/blob/v1.7.1/src/app/data/models/stream/-qualities/streamlink.js

**Comment by tomasz13nocon** [comment]
I think it's doable though to allow selection of the quality when a specific stream opens, since they are listed by streamlink.
Currently there is no way to watch streams in 720p and my internet's not good enough for 1080p and 480p looks really bad.

**Comment by NeoFahrenheit** [comment]
Given the following piece of code

```
session = streamlink.Streamlink()
streams = session.streams(twitch_url)
stream_data = streams[**quality**].open()
```

This only works if I use 'best' for **quality**. I tried using 'High', 'Medim' and 'Low' and none of them worked. The information on the links @bastimeyer posted seems to work only in CLI version. Is there a function in streamlink API (Python) I can use to give these abastract quality values to the code above and retrive the the quality streamlibk chooses, like 1080p30?

Thank you.

**Comment by bastimeyer** [comment]
@NeoFahrenheit No idea why you're commenting here on this old and completely unrelated issue on a different issue tracker. This is the Streamlink Twitch GUI repo, and Streamlink Twitch GUI uses custom stream quality mappings for being able to have consistent quality names via Streamlink's `--stream-sorting-excludes` CLI parameter whose value is passed to `Plugin.streams(..., sorting_excludes=...)`.
https://streamlink.github.io/api.html#streamlink.plugin.Plugin.streams
https://streamlink.github.io/api.html#streamlink.Streamlink.streams

I've also already told you on the Streamlink discussion forum that this is not a programming advice forum, so you'll have to figure this out on your own. You're really streching the limits here of how far I'm willing to give advice. Some of the Streamlink APIs are documented (I just spent time on that a few months ago after it was neglected for several years), and if that's not enough, take a look at the code. This is not rocket science.

Locking the thread...
