### ISSUE TITLE
External commands generates new tray icons

### ISSUE THREAD

**Issue by ioangogo** [streamlink/streamlink-twitch-gui#641]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Fedora 29 KDE Spin

**Streamlink Twitch GUI version:**  

![image](https://user-images.githubusercontent.com/7449028/57458938-271fb500-726a-11e9-87b5-b6c9f6f09765.png)

**Streamlink version:**  
streamlink 1.1.1

**Configuration details:**  

- Allow external commands: on
- OS intergration: both

### Description

When launching a stream using external command the instance launched from that command makes a tray icon but fails to clean it up afterwards

### Expected behavior

it not to make a new icon/clean up the icon it made

### Reproduction steps

1. turn on external command
2. run streamlink-twitch-gui --min
3. check notification area

### Log output

Nothing of note in the terminal

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/7449028/57459410-1ae82780-726b-11e9-9e93-08928b52339f.png)

**Comment by bastimeyer** [comment]
Hm, I can't reproduce this on my system running Arch and the latest Plasma release.  The tray icon is working fine, except of the icon's blurriness which is a problem related to Qt and Chromium. This seems to be patched though on Fedora according to your screenshot.

When the Twitch GUI tries to create a new tray icon, which is the case when executing external commands, it also always tries to remove the old tray icon, if it exists. So seeing tray icons being stacked is a bit surprising.

When I get the time, I'll debug this on Fedora and see what exactly is going on.

**Comment by bastimeyer** [comment]
So I gave this a go in a fresh Fedora 30 VM and was unable to reproduce this.

Since your tray icons are not blurry (as I've said, this is a bug in Chromium/NW.js/Electron on Plasma), are you by any chance running some kind of program which replaces the tray icons? I thought the blurry icons were patched on Fedora after looking at your screenshot, but that's not the case. At least not in the default config with the default tray icon applet. This makes me wonder whether you're using something which might interfere with the tray icons.
