### ISSUE TITLE
(SOLVED) unexpected version output

### ISSUE THREAD

**Issue by labatts** [streamlink/streamlink-twitch-gui#644]
## Bug report

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**   manjaro linux

**Streamlink Twitch GUI version:**  1.7.1

**Streamlink version:**  1.1.1

**Configuration details:**  

### Description
Can't start the stream with the error "unexpected version output".  I saw the other bug reports with the same problem, and tried to fix it with what was said there (changing path of python), but I must be missing something.  Under usr/bin, I have the following python scripts installed: python, python2, 2.7,3,3.7,3.7m.  I have tried changing the path to each of these by using /usr/bin/python[#] but have been unsuccessful.  

I DID get the command line streamlink to work correctly.  

### Expected / Actual behavior 
launch stream

### Reproduction steps

1. ...I launch Streamlink Twitch GUI
2. ...I try to launch a stream
3. ...I get "Unexpected version check output"

### Log output

[2019-05-23T23:31:21.677Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:32:15.213Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:32:44.120Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:33:04.174Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:33:19.184Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:33:33.174Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:34:18.055Z][error][StreamingService]
ProviderError: Couldn't validate python script
Invalid python script

[2019-05-23T23:34:45.003Z][error][StreamingService]
Error: Unexpected version check output

[2019-05-23T23:35:21.014Z][error][StreamingService]
ProviderError: Couldn't find python script
Executables were not found

### Additional comments, screenshots, etc.
The last entry in the log is where I tried changing the streamlink python script.  **Sorry** for dredging something up that you have obviously had to deal with in the past.  I have not been smart enough to figure it out unfortunately.

**Comment by bastimeyer** [comment]
See https://github.com/streamlink/streamlink/issues/2448
or https://gitter.im/streamlink/streamlink-twitch-gui?at=5ce0db055b63ea22b3ce5e76

**Comment by labatts** [comment]
Okay, you are a god, thank you.  For other's sake:  _sudo pip install --upgrade requests_ fixed the issue.

**Comment by bastimeyer** [comment]
> sudo pip install --upgrade requests

You should never use pip globally with sudo. This will cause conflicts in the future when you're using your regular system package manager which is using the same directories for its own packages.

Just use pip in user mode (via the `--user` parameter), as mentioned many times in the linked issue thread, so it'll install its packages into `${XDG_DATA_HOME:-${HOME}/.local}` instead of `/usr`. Then you can easily remove the workaround once your distro has caught up with the bugfixes.

----

And as a final recap of this issue (I'm getting a bit tired of it :weary:):

Streamlink depends on `python-requests`, which itself depends on `python-urllib3`. A few weeks ago, a security issue was fixed in urllib3 and its devs had to publish a new release. This version bump made requests complain, as it was depending on the old urllib3 version, and it resulted in a warning message being printed to `stderr` while executing Streamlink. Since Streamlink Twitch GUI always has to verify the Streamlink install on your system before being able to launch streams for the first time, this warning message resulted in the "Unexpected version check error" because of its strict output parser. However, this is not an issue of Streamlink Twitch GUI itself, but your distro, which upgraded its urllib3 package without checking any depending packages like requests for "hard" dependencies.

The issue should be fixed on all distros now which provide the latest versions of requests and urllib3. If your distro does not, then you have to downgrade urllib3 or upgrade requests+urllib3 via pip (preferably in user mode).

As I've mentioned a couple of times now, I am fully aware that the error message in the Twitch GUI is pretty bad and not helpful at all, but before I'm able to improve it, I first want to finish some other stuff, so I can hopefully rewrite the streaming related stuff as a whole, which I wanted to do anyway. This will take some time though.
