### ISSUE TITLE
Access to streams through tab key shrink stream thumbnail by half

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#645]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details
ArchLinux
**Streamlink Twitch GUI version:**  
1.7.1

**Streamlink version:**  
1.1.1

### Description

Accessing to streams through `tab` key result in stream thumbnail being shrinked by half its height and can't be reversed without refresh.

### Expected / Actual behavior

Thumbnail shouldn't be shrinked.

### Reproduction steps

1. Hit many times `tab` key on the stream matrix to get to the first one
2. You can then continue

Or

1. Hit `tab` one time after having opened a stream as the focus will still be on that stream
2. You can then continue

I discovered issue with that second way.

### Additional comments, screenshots, etc.

![Screenshot from 2019-05-30 04-46-47](https://user-images.githubusercontent.com/709500/58605127-0eb61f80-8297-11e9-89d3-703347b0b478.png)

On the example screenshot, I did hit `tab` from the first one to the 2nd one on the third row.

**Comment by bastimeyer** [comment]
Thanks for the bug report!

This issue was caused by being able to focus some of the component's hidden anchors. I've disabled this behavior for all kinds of anchors now, which fixes the problem.

However, other elements which are not part of the active route's content, like for example the window control buttons of the title bar, can still be focused by pressing <kbd>Tab</kbd>. This is a problem, because these elements currently don't have any indicators when being focused and the user could accidentally focus and trigger them. But since I currently don't have any intentions to implement proper keyboard navigation support, I will ignore this for now.
