### ISSUE TITLE
Stream doesn't start with VLC UWP

### ISSUE THREAD

**Issue by nyakze** [streamlink/streamlink-twitch-gui#650]
Here's the application I'm trying to use: https://www.videolan.org/vlc/download-winrt.html
Streamlink can't seem to recognize it as an application, I used this command to try and run it from Streamlink Twitch GUI:
shell:appsFolder\VideoLAN.VLC_paz6r1rewnh0a!App
It works from Win+R.
The reason I want to use it instead of normal desktop VLC is power and battery usage, UWP is way lower than on traditional VLC. Any help is appreciated.

**Comment by bastimeyer** [comment]
> Streamlink can't seem to recognize it as an application, I used this command to try and run it from Streamlink Twitch GUI:
> shell:appsFolder\VideoLAN.VLC_paz6r1rewnh0a!App

What you are posting here is a launch command for an UWP app, which has to be interpreted by the Windows Explorer (explorer.exe). It is not a real executable path and is thus not supported by Streamlink or Streamlink Twitch GUI. You would need to find the absolute path of the main executable of that app, but since you can't launch these kinds of apps like this, it's not going to work. Even though I don't use UWP apps, or even Windows, I highly doubt that apps like this are even built with support for the usual POSIX interfaces like standard streams, which are needed for Streamlink to pipe the data into the player. Apart from that, I've also heard that Microsoft has already abandoned the UWP stuff. This doesn't give me any motivation to further dig into this awful system, it's just too much time unnecessarily spent, sorry.

> The reason I want to use it instead of normal desktop VLC is power and battery usage

There isn't anything magical going on here. Just try altering some settings or try out a different player, like MPV for example.

**Comment by skulblakka** [comment]
>You would need to find the absolute path of the main executable of that app, but since you can't launch these kinds of apps like this, it's not going to work. 

Just for the record Windows 10 actually added support for starting UWP apps and passing arguments from the command line in 2017. However I don't think support for this was added by VLC.
