### ISSUE TITLE
Communities : Endpoint has been deprecated

### ISSUE THREAD

**Issue by tsukasagenesis** [streamlink/streamlink-twitch-gui#652]
Hello,

when I click on community I get : 
Error:There was an error while trying to display this page.
Name:HTTP Error
Message:Gone
Detail:Endpoint has been deprecated
Status:410
Host:api.twitch.tv
Path:kraken/communities/top

Could you fix it ? I cannot see speedrunner :/

Best regards

**Comment by bastimeyer** [comment]
> Could you fix it ?

No, the "Communities" feature has been removed by Twitch. They've announced this change when they added their new API and it looks like they've finally pulled the plug. I already had to remove the featured communities in the last Twitch GUI release and now I will have to remove it completely.

Communities have been replaced by stream tags, but this isn't available in Streamlink Twitch GUI yet (#597) because the migration to the new Twitch API hasn't been done (or even started) yet. If you want to know more about the reasons, see #599 and the linked threads in my comment there. Twitch has changed a lot of bad things about the new API over the recent months, so it's probably a good idea to take a look at it again and re-evaluate the migration plans.
