### ISSUE TITLE
Change quality option from high to 720p60 etc.

### ISSUE THREAD

**Issue by MannixMD** [streamlink/streamlink-twitch-gui#660]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Change the quality options from High medium source to the numeric values like 720p60 1080p60 just like it is now on twitch. With that change we get more options to choose from to better suite our needs.

**Comment by bastimeyer** [comment]
These quality names are aliases for **quality range** selections, see the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities

These quality range selections are necessary, because Twitch's explicit quality names are tied to the channel's input stream. For example, if a channel streams in 1600x900x60, the best quality name will start at 900p60 instead of 1080p60. Since there's no API endpoint for querying the available stream qualities, Streamlink Twitch GUI has to tell Streamlink when launching a stream which **quality range** the user prefers. This preference is stored either globally or for an individual channel, and it has to be consistent, so that the same selection can be used when watching streams of different input qualities. If Streamlink Twitch GUI would use Twitch's explicit quality names, then it wouldn't be able to store the user's preference reliably, because it has to know in advance which stream quality the user wants to see.

The reason why this works on Twitch's website is that the web player is able to change the quality on the fly or dynamically, based on the user's connection and rendering performance. Streamlink can't do this.

What's also unfortunate with using Streamlink is that it only supports a one dimensional quality selection, called [stream weight](https://github.com/streamlink/streamlink/blob/1.2.0/src/streamlink/plugin/plugin.py#L54-L91), which is a combination of the video resolution and refresh rate. If you're looking for a finer quality selection for the refresh rate, then you are unfortunately out of luck and you'll have to set a custom quality selection in the Twitch GUI's stream settings (requires advanced settings to be enabled first).

https://github.com/streamlink/streamlink-twitch-gui/blob/v1.8.1/src/app/data/models/stream/-qualities/streamlink.js
