### ISSUE TITLE
Launch Streamlink and wait for channel to start streaming

### ISSUE THREAD

**Issue by afonsosantos** [streamlink/streamlink-twitch-gui#661]
## Feature request

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a feature request and I have read the contribution guidelines.

### Description

I would appreciate a way to launch the player before the stream start, if that's even possible.

### Additional comments, screenshots, etc.

Thank you for this amazing software, now I can watch Twitch lag-free!

**Comment by bastimeyer** [comment]
That's not how Streamlink Twitch GUI works. You'd need to start Streamlink with the [`--player-external-http`](https://streamlink.github.io/cli.html#cmdoption-player-external-http) parameter and open the returned URL in your already launched player, but as I've said in #659, I'm not going to implement this in the Twitch GUI, because it's an edge case which isn't supported by every video player and it's not what the Twitch GUI was built for. You can however do this from the CLI and write a little shell script for your needs.

I'm not sure why you're asking for such a feature, but if launching the video player on your system takes too long or consumes too many resources, then you should consider using a more light-weight player, like MPV for example.

**Comment by afonsosantos** [comment]
@bastimeyer Thank you for the response!

The reason I'm asking for this is because there's some delay (at least in my PC) between the stream start ans the Streamlink GUI allowing me to open the stream, so I was hoping to open the stream before and resolve this. Homewer, if I restart Streamlink GUI, the stream is Live and I can watch it.

Thanks anyways for the answer.

**Comment by bastimeyer** [comment]
You mean you want to launch Streamlink and wait for an offline channel to start streaming? This was asked for in #265, but I haven't spent any time on it (quite old thread which I forgot about - opened even before the app got renamed).

I'm still not sure if I want to implement this, because as I've said in similar issues and feature requests, I'm against any kind of "automation features" like auto-refreshing pages or automatic stream launch/record features, etc. The reason for this is that it can and will be abused by the users and Twitch might ban the app's API client-id because of this, which I don't want to risk. Regarding waiting for a channel to come online however, I can see this as being useful, so I'm a bit torn here. I'll think about it.

Let me re-open and re-word this thread and close the old one.

**Comment by afonsosantos** [comment]
Thank you for the attention, that's exactly what I'm looking for.

**Comment by bastimeyer** [comment]
Why did you close this thread? Keep it open please.

**Comment by afonsosantos** [comment]
Hi, sorry, I tough this was already addressed.

**Comment by niklasstich** [comment]
Has this feature been addressed yet? I would really love to have it in streamlink too, as I watch a few streamers who announce that they are coming online in x Minutes, and it would be quite convenient to be able to already "pre-open" their stream in the GUI on my second monitor, instead of having to refresh manually every few minutes to check if they are live yet. 

I've noticed that if you try to re-open a closed stream via the button in the dialogue, it tries to reopen the stream every second (or was it two?). Perhaps this same mechanism could be used, but with a way larger interval in between, say 30-60 seconds to avoid spamming the twitch API too much.

**Comment by WooZyDice** [comment]
@bastimeyer - There are already Channel setting Notification and Desktop Notification functions. I am not sure why we cannot automatically open a Twitch stream by reacting to those events.

**Comment by imatschoolrn11** [comment]
well while they look at that right now you can use the "restart" and is they are not live it will keep trying as many times and as fast as you have set it as in settings
/:

**Comment by afonsosantos** [comment]
Hi everyone,
What's the status of this issue? Can this be closed?

Thanks
