### ISSUE TITLE
When will the delay issues with the program be fixed?

### ISSUE THREAD

**Issue by Nepturian** [streamlink/streamlink-twitch-gui#663]
The delay with actions in the program has made me insane lately.
Why hasnt this been fixed???
If you have launched a stream and you want to go back by pressing back button, it takes 10 seconds before the action is done.
Opening the GUI comes with a empty background etc.

**Comment by Nepturian** [comment]
![gui](https://user-images.githubusercontent.com/29153523/65639802-2bfebe80-dfe9-11e9-8180-5e9e83b314d7.png)
This is how the GUI looks after some inactivity minimized, then restored.

**Comment by bastimeyer** [comment]
> delay with actions
> If you have launched a stream and you want to go back by pressing back button, it takes 10 seconds before the action is done

There is no delay when clicking the back button or pressing the Escape hotkey. This will immediately close the modal dialog and remove its nodes from the DOM.

This sounds more of an issue with your system (same as the other issues you've posted here in the past). Try clearing the app's config/cache directory and make sure that your system is working correctly. If there's anything going wrong on the side of NW.js/Chromium, it should be logged to stderr, which you should post here.

If you're however talking about ending the stream via the GUI when clicking the X button or pressing Q, then it's possible that there's a delay, but that's caused by Streamlink and your used player, because the GUI tells Streamlink to terminate its process gracefully, which can take a moment, depending on your player and its configuration (clearing buffers, etc) which also has to be ended by Streamlink first. This delay is not an issue of the GUI though and should be unnoticeable on a properly configured system.

> This is how the GUI looks after some inactivity minimized, then restored.

This is either a NW.js/Chromium related issue or again an issue on your system. All I can do here is bump the used NW.js release version, but currently there's a regression in NW.js on Windows, so the latest version which can be used here for the moment is 0.39.3 with Chromium 75.

> When will ... be fixed?
> has made me insane lately.
> Why hasnt this been fixed???

Remember that this is an open source project which has been written by and is being maintained by me (and only me so far) in my free time. If there's a bug related to the project's code or its dependencies, then I'm more than happy to fix it, but these kinds of bad-tempered bug reports without any useful informations and demanding questions are just a waste of time.
