### ISSUE TITLE
Low-res app icon in KDE Plasma

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#665]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
ArchLinux

**Streamlink Twitch GUI version:**  
1.8.1

### Description
See the screenshot below; recently I was fiddling with some different desktop environments for a change, and gave a shot at KDE. The task switcher makes use of big icons, and streamlink-twitch-gui doesn't seem to provide one for that use, resulting in a very small icon compared to the other applications

### Expected / Actual behavior
Have an icon the same size as everything else

### Reproduction steps

Just task switch with streamlin-twitch-gui opened on KDE.

### Additional comments, screenshots, etc.

![Screenshot_20191004_141927](https://user-images.githubusercontent.com/709500/66207337-ce3a3880-e6b2-11e9-9660-f3b8eeb7229d.png)

**Comment by bastimeyer** [comment]
I'm aware of this issue, but it's related to NW.js and KDE Plasma. It's similar to the blurry tray icons, which all Chromium based applications are affected by as well, unless [`libappindicator`](https://wiki.archlinux.org/index.php/KDE#Blurry_icons_in_System_tray) is installed.

I'm not exactly sure where Plasma is picking up the icon from, but something is going wrong here, because other DEs are able to properly use the high-res icon.

NW.js requires an `icon` property in its app manifest with a path to an icon in the PNG format, relative to the app's content directory. It is done this way for multi-platform reasons. Streamlink Twitch GUI uses a 256x256x32 PNG here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.8.1/src/package.json#L17
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.8.1/src/img/icon-256.png

This icon then gets set as a (binary) property on the Xorg window, either as `WM_ICON` or `_NET_WM_ICON`, but resized to a lower resolution. You can check this via
```sh
$ xprop -id (xwininfo -name "Streamlink Twitch GUI" | grep "Window id:" | grep -Eio "0x[a-z0-9]+") | less
```
*Requires `xorg-xprop` and `xorg-xwininfo` to be installed on Arch.*

I believe the reason why other DEs are properly using the high-res icon is that they are using one of the icons from the freedesktop-icons directories instead, based on the Xorg window's `WM_CLASS` property, which is `streamlink-twitch-gui`. These icons come in various resolutions and are included in 3rd party icon themes, the app's AUR package, or get created when the `add-menuitem.sh` script gets executed in the regular release archive or build folder.
```sh
$ ls -LNv1 {$HOME/.local/share,/usr{,/local}/share}/icons/*/*/apps/streamlink-twitch-gui.{png,svg}
/home/basti/.local/share/icons/hicolor/16x16/apps/streamlink-twitch-gui.png
/home/basti/.local/share/icons/hicolor/32x32/apps/streamlink-twitch-gui.png
/home/basti/.local/share/icons/hicolor/48x48/apps/streamlink-twitch-gui.png
/home/basti/.local/share/icons/hicolor/64x64/apps/streamlink-twitch-gui.png
/home/basti/.local/share/icons/hicolor/128x128/apps/streamlink-twitch-gui.png
/home/basti/.local/share/icons/hicolor/256x256/apps/streamlink-twitch-gui.png
/usr/share/icons/Papirus-Dark/16x16/apps/streamlink-twitch-gui.svg
/usr/share/icons/Papirus-Dark/16x16@2x/apps/streamlink-twitch-gui.svg
[...]
```

What I don't understand though is that Chromium does have a high-res icon in Plasma, and there's no special stuff done while packaging. Maybe it's related to its also higher resolution icon in its `_NET_WM_ICON` Xorg property, but I'm not sure.

I will have to do more research here before I can open a bug report on the NW.js issue tracker.

**Comment by Porkepix** [comment]
I noticed the same issue with Lutris for example, which isn't an Electron-based application, so I might be completely mistaken and that it's totally unrelated, but it seems to affect some applications here and there.

**Comment by Porkepix** [comment]
On a same note, but this might require another issue (tell me if you wish I open a new one), the icon in the system tray is completely blurry, while this one is mall, see screenshot:

![Screenshot_20191009_131154](https://user-images.githubusercontent.com/709500/66476762-ae31bd00-ea96-11e9-883d-74ed5ed91aa5.png)

**Comment by bastimeyer** [comment]
> It's similar to the blurry tray icons, which all Chromium based applications are affected by as well, unless [`libappindicator`](https://wiki.archlinux.org/index.php/KDE#Blurry_icons_in_System_tray) is installed.

**Comment by bastimeyer** [comment]
Did a bit of further research.

Turns out the app switcher is part of KWin and not Plasma, which means that KWin, as a window manager, has to follow the rules of X11 and use the app-window's specified icon property instead of using the icon specified by the app's `.desktop` file.
  https://bugs.kde.org/show_bug.cgi?id=351055#c35

As I've said, Chromium does have a "high-res" icon set as `_NET_WM_ICON` property, 128x128 to be precise. Streamlink Twitch GUI on the other hand only has a 16x16 and 32x32 icon set here. This is the reason for it:

1. [Where NW.js/Chromium sets the `_NET_WM_ICON` X11 property:](https://github.com/nwjs/chromium.src/blob/nw39-log/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc#L1077-L1097)
2. [Where NW.js/Chromium asks for the default icon](https://github.com/nwjs/chromium.src/blob/nw39-log/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc#L1595-L1603)
3. [Where NW.js/Chromium loads the default icon](https://github.com/nwjs/chromium.src/blob/nw39-log/chrome/browser/ui/views/chrome_views_delegate_linux.cc#L54-L60)
   1. [Where NW.js gets the app icon](https://github.com/nwjs/nw.js/blob/nw39/src/nw_content.cc#L1298-L1302)
      1. [Where it reads it from](https://github.com/nwjs/nw.js/blob/nw39/src/nw_content.cc#L806)
      2. [And where it loads it from](https://github.com/nwjs/nw.js/blob/nw39/src/nw_content.cc#L245-L271)
   2. [Compared to where main Chromium loads the default icon](https://github.com/chromium/chromium/blob/79.0.3941.2/chrome/browser/ui/views/chrome_views_delegate_linux.cc#L53-L56) ([icon path definition](https://github.com/chromium/chromium/blob/79.0.3941.2/chrome/app/theme/chrome_unscaled_resources.grd#L64))

I'm not sure where it goes wrong on the side of NW.js, but it's clearly not setting a high-res icon from the provided 256x256 png in the app manifest. I'll open a new issue on the NW.js issue tracker when I get the time.

For testing purposes, I'd really like to know if this can be fixed by providing a higher res `_NET_WM_ICON` value via `xprop`.

**Comment by Porkepix** [comment]
> For testing purposes, I'd really like to know if this can be fixed by providing a higher res `_NET_WM_ICON` value via `xprop`.

I'm not sure I have understood; is this something you want me to test? If yes, this is a little bit unclear how to do so for me.

**Comment by bastimeyer** [comment]
No, I was just wondering how to do this, because the property value is using a special format (`Xo` - an array of the size of X with 32bit integer numbers describing the width, height and ARGB values of the bitmap), as described in `xprop`'s man page. After reading it again, I think I know how to do it, but I guess it's not possible via shell scripting. I'll have to do it in Python or Node. oof...

**Comment by bastimeyer** [comment]
I think this has been fixed in one of the latest Plasma/KWin updates (currently using `5.21.4`). The app switcher (large icons) is now using the icon of the application's launcher file instead of the icon bitmap embedded in the X window properties.
