### ISSUE TITLE
Respect system light/dark appearance

### ISSUE THREAD

**Issue by NilsEnevoldsen** [streamlink/streamlink-twitch-gui#666]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Now that macOS Catalina has been released with automatic switching between system light appearance and dark appearance, it is more important for apps to automatically follow the system appearance, as there will now be a large number of users who no longer "set it and forget it", but instead have their system appearance change automatically based on the time of day. I believe Windows also has a system appearance for apps to follow.

I imagine this would take the form of a third Streamlink Twitch GUI theme option: change the options from Default/Dark to Auto/Light/Dark with Auto as the default for new installations. 

I believe https://github.com/nwjs/nw.js/issues/6819 is the associated nw.js issue. See https://electronjs.org/docs/tutorial/mojave-dark-mode-guide for an example of how it works in Electron.

**Comment by bastimeyer** [comment]
I've already implemented this in early August in 5d06774199bc4ade10e45ac941856331eeee7962 (see the [v1.8.0](https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v1.8.0) changelog) but had to revert it in 15a0e9edcdd7c509dabcf9dcd15a733ff03851e3 because NW.js 0.40, which added support for it (with Chromium 70), was crashing on Windows when the window badge label for showing the number of followed streams was set. I didn't notice the crashes when I published v1.8.0, because I was not logged in and no badge label was set when I tested the NW.js bump in my Windows VMs. As a result of this, I had to downgrade the used NW.js version in the [v1.8.1](https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v1.8.1) release to 0.39.3 and revert the automatic theme switching. I also didn't know what exactly caused the crashes, so all I could do was open an issue on the NW.js bug tracker with a crash dump, but this didn't seem to be enough information. The issue however has been found last week and it got fixed three days ago (nwjs/nw.js@f27c5a06191cc28c7d5901b0f2b2bd43c47b9c8d), but there's no new NW.js release yet (will be 0.41.3), so I will have to wait for it until I can bump the version here and re-implement the automatic theme switcher.
https://nwjs.io/blog/

**Comment by NilsEnevoldsen** [comment]
Thanks for the explanation! I searched the issues, but didn’t think to search the change log. 😀

**Comment by bastimeyer** [comment]
NW.js 0.41.3 has been released today with the necessary bugfix.

I've pushed the `nwjs-41` branch with a re-implementation of the ThemeService that checks for the light/dark system theme configuration.
https://github.com/streamlink/streamlink-twitch-gui/commits/nwjs-41

It'll be merged into `master` once I've found the time to make sure that this new NW.js version is working correctly (tomorrow I think). I just want to be extra careful with these release bumps now.
