### ISSUE TITLE
black square after installing a new version (the old version is no longer working)

### ISSUE THREAD

**Issue by exradioactivetoy** [streamlink/streamlink-twitch-gui#669]
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

**Operating system and version:**  
Windows 7 SP1

**Streamlink Twitch GUI version:**  
1.8.1

**Streamlink version:**  
1.2.0

### Description
Hello, i  have a  strange problem, will try to explain it from the beginning, sorry for bad english :)

for a long time i used the old version twitch-gui (1.4.1) with livestreamer. from some point, a few days ago, streams stopped starting, was displayed an error "alert protocol version"
I reinstalled the programm but thats not helped.

Then was installed a new version 1.8.1 and i wanted to configure it with streamlink but a new version twitch-gui not running, displayed black square like this - https://prnt.sc/pj5ubi

ive tried to clear the application's config/cache folder but result the same

And what the interesting, the old version 1.4.1, when i installed it again - its works. Was initial problem that streams not launching, but the application runs correct

But the 1.8.1 version is not. I tried to install it a different ways, 32/64 version, streamlink for current/all users, i tried all kinds of options, but nothing helps

**Comment by skulblakka** [comment]
You should try running the GUI with logging enabled and post the result here (or in-case it is quite long use https://gist.github.com/ and link it here). Run it with `--enable-logging --v=1`. You will find the log-file in `%LOCALAPPDATA%\streamlink-twitch-gui`.

You could also try running it with `--disable-gpu` as the issue might be caused by GPU acceleration.

**Comment by bastimeyer** [comment]
Thanks for helping, @skulblakka 

@exradioactivetoy 
See the application parameters wiki for getting the error/verbose log file:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

> 1.4.1

This release was based on NW.js 0.26.6 with Chromium 62, which is quite old (November 2017).
Streamlink Twitch GUI 1.8.1 is based on NW.js 0.39.3 with Chromium 75, so lots has changed internally.

As @skulblakka already said, this looks like a Chromium renderer bug, probably related to GPU acceleration. Since you're using an older OS, it is likely that your system is either misconfigured or that NW.js/Chromium itself has problems with that system configuration.

All I can do here as an NW.js app developer is bumping the used NW.js platform version. Unfortunately though, there have been some issues lately and I had to downgrade one release and wait until a new fixed NW.js version got published. This fixed version (with another bump) is in beta right now and will be available soon (0.42 with Chromium 78). I doubt though that this will fix your problems when Streamlink Twitch GUI will use it in its next release.

**Comment by exradioactivetoy** [comment]
> You should try running the GUI with logging enabled and post the result here (or in-case it is quite long use https://gist.github.com/ and link it here). Run it with `--enable-logging --v=1`. You will find the log-file in `%LOCALAPPDATA%\streamlink-twitch-gui`.
> 
> You could also try running it with `--disable-gpu` as the issue might be caused by GPU acceleration.

oh, ive seen it, about logging, but i thought that logging works in twitch-gui program, only now i realized thats was meant about windows run with command, sorry, feels blonde now :D


ok, so, it works with  
> disable-gpu

but now i have 

> couldn't validate python script

and need a  minute, log loading

**Comment by bastimeyer** [comment]
> couldn't validate python script

This is related to streaming and not launching/using the GUI.
Streamlink Twitch GUI has nothing to do with streaming. It is just a launcher / parameter generator for the streamlink command line interface.

Since you're a Windows user who migrated from Livestreamer, you have probably installed Streamlink from its Windows installer. In that case, you have to choose the `Streamlink (Windows)` streaming provider in the streaming settings menu, just like the wiki tells you (this is also the default config as a Windows user). Then it doesn't ask for any Python executable or entry script at all. You just have to point it towards the `streamlinkw.exe` file, in case the Twitch GUI is not able to find it automatically.

**Comment by exradioactivetoy** [comment]
> > couldn't validate python script
> 
> This is related to streaming and not launching/using the GUI.
> Streamlink Twitch GUI has nothing to do with streaming. It is just a launcher / parameter generator for the streamlink command line interface.
> 
> Since you're a Windows user who migrated from Livestreamer, you have probably installed Streamlink from its Windows installer. In that case, you have to choose the `Streamlink (Windows)` streaming provider in the streaming settings menu, just like the wiki tells you (this is also the default config as a Windows user). Then it doesn't ask for any Python executable or entry script at all. You just have to point it towards the `streamlinkw.exe` file, in case the Twitch GUI is not able to find it automatically.

oh yeah, again missed it in a hurry
 now it works, great, thank u very mutch :)

so only the way to use it, with command **disable-gpu**?

**Comment by bastimeyer** [comment]
> so now i have only one way to use it, with command disable-gpu, and will it work right? 

The only info you have given us so far is that you are using Windows 7 sp1. If you could post more infos regarding the renderer/rendering failure, like the error log we've been asking for and also your hardware/software configuration, maybe it becomes clear why this is not working on your system.

Btw, disabling GPU acceleration in a small application like this isn't that big of a deal. Ideally, animations would have to be disabled by the Twitch GUI in such a scenario, but it's not implemented. So the only issue could be performance, but it's negligible on fast-enough systems. Rendering wise, there shouldn't be a difference, even in font rendering I believe.

Just add the parameter to your app shortcut, so you don't have to launch the Twitch GUI with that parameter from the command line shell and be done with it.

**Comment by exradioactivetoy** [comment]
> Btw, disabling GPU acceleration in a small application like this isn't that big of a deal. Ideally, animations would have to be disabled by the Twitch GUI in such a scenario, but it's not implemented. So the only issue could be performance, but it's negligible on fast-enough systems. Rendering wise, there shouldn't be a difference, even in font rendering I believe.
> 
> Just add the parameter to your app shortcut, so you don't have to launch the Twitch GUI with that parameter from the command line shell and be done with it.


i get it
generally, it’s enough for me that the program works, and i can watch streams :)
sure i wonder why this happened and how to fix it, but this is secondary 
will not waste your time more, thank u one more time :)

**Comment by bastimeyer** [comment]
All good, no worries
