### ISSUE TITLE
410 client gone error, how to change auth key?

### ISSUE THREAD

**Issue by moopco** [streamlink/streamlink-twitch-gui#680]
A mod closed the previously open topic regarding this, claiming it wasn't a twitchgui issue.

But it is, if you just use streamlink you can change your auth key to the public twitch one to continue using the service, twitchgui overrides this value preventing streams from opening and preventing you changing the auth key. 

Can a mod please explain where we can change our authkey that twitchgui sends?

**Comment by bastimeyer** [comment]
I have explained everything in that thread. You have to follow the instructions and apply this temporary workaround on your own until a proper fix gets deployed.
https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753

> twitchgui overrides this value

hence why you need to disable "Twitch.tv login" (login sharing) in the streaming settings menu as well.

----

I'm sorry, but I can't respond to everyone individually. I'm being bombed with questions because of Twitch's change and the situation wasn't (and still isn't) 100% clear whether it's an intentional change or just a bug on their end.

**Comment by moopco** [comment]
OK, let's just make this easier for the hundreds of people that are clearly still having issues.

1. Find your streamlink folder (not twitchgui streamlink folder)

2. navigate through pkgs > streamlink > plugins

3. Open twitch.py in a proper text editor (i use idle, don't use notepad)

4. Near the top there is a value "TWITCH_CLIENT_ID", change the value to "kimne78kx3ncx6brgo4mv6wki5h1ko"

5. I could not save it directly, I had to "save as" then delete the original twitch.py and replaced it with the new save.
