### ISSUE TITLE
Build impossible following CDP related changes

### ISSUE THREAD

**Issue by IHadToPickaUsername** [streamlink/streamlink-twitch-gui#685]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Ubuntu 18.04

**Streamlink Twitch GUI version:**  
1.8.1-27-gcd6d96fa

### Description

Building from source following the [commits related to cdp](https://github.com/streamlink/streamlink-twitch-gui/commit/cea27a6f3e3259a9e4e41c3d1e8318b191c8a711) is impossible (Fatal error: cdp.off is not a function).

Reverting these changes (by using the build/tasks/ folder as it was prior to the commits) allows for a clean build.

![Screenshot from 2019-11-21 20-11-18](https://user-images.githubusercontent.com/54917003/69368887-e120c080-0c92-11ea-8a02-3f7c5da66c52.png)

**Comment by bastimeyer** [comment]
Looks like your NodeJS is too old. I didn't realize that Ubuntu 18.04 was still using 8.10.0:
https://launchpad.net/ubuntu/bionic/+source/nodejs

Currently, the lowest active LTS release of NodeJS is 10.x and official support for 8.x will be running out at the end of the year:
https://nodejs.org/en/about/releases/

TravisCI is set up for the LTS branch, so it chooses 12.x and the build succeeds:
https://github.com/streamlink/streamlink-twitch-gui/blob/cd6d96faf7dbc4bab36a0b41c004871c592a1d34/.travis.yml#L10-L11
https://travis-ci.org/streamlink/streamlink-twitch-gui/builds/614900086#L469

> EventEmitter.prototype.off

NodeJS has fixed its EventEmitter method naming scheme in v10:
https://nodejs.org/api/events.html#events_emitter_off_eventname_listener

I could change it to the old method name and fix this issue for older NodeJS releases. But since 8.x will be running out soon, I don't how much sense it makes considering that any dependency bump after that date might make it incompatible again.
https://github.com/streamlink/streamlink-twitch-gui/blob/cd6d96faf7dbc4bab36a0b41c004871c592a1d34/build/tasks/common/cdp/qunit.js#L53

On Ubuntu, you can add a custom NodeJS repo or use snap packages to get a newer version:
https://nodejs.org/en/download/package-manager/

**Comment by IHadToPickaUsername** [comment]
Thank you for the quick answer, updating NodeJS to v13.1.0 fixed the problem.

![Screenshot from 2019-11-21 22-41-52](https://user-images.githubusercontent.com/54917003/69379162-cefd4d00-0ca7-11ea-952a-bcfeecb87249.png)
