### ISSUE TITLE
New release to fix mpv breakage

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#701]
`streamlink-twitch-gui` running `mpv` was broken by latest `mpv`'s update the same way `streamlink` was until `1.3.1`'s release. It seems to already be fixed in master thanks to commit https://github.com/streamlink/streamlink-twitch-gui/commit/014bfd195ca81f57f2584bdeeacf765c75e70e97 but yet unreleased, therefore being effectively broken unless building from master.

For that reason, a `1.9.1` should also be issued here, as well as an update for the Arch AUR's `PKGBUILD` to fix current broken state with `mpv`

**Comment by bastimeyer** [comment]
I am aware of this, but I couldn't publish a new release yet because of the most recent Twitch API situation and because I had to wait for Streamlink 1.3.1 to be published (I'll still have to bump the dependency version in the Twitch GUI for that, so people don't run into the issue and instead will see an upgrade message).

**There will be a new release later today as soon as I get the time.**

> effectively broken unless building from master

You can simply deactivate the title properties in the player settings menu. And if you still want to have custom player titles, you can add your own custom parameters, similar to 014bfd1 which you've already pointed out.

> as well as an update for the Arch AUR's `PKGBUILD`

I am always updating the AUR package right after a release, so you don't have to worry about that. And if you still do, you can just use the `-git` AUR package.
