### ISSUE TITLE
"Set Streamlink's version requirement to 1.3.1" ... Okay, how?

### ISSUE THREAD

**Issue by Uzukii** [streamlink/streamlink-twitch-gui#702]
Not an issue, just a question. It says in the release highlights to set version requirement to 1.3.1. Where do we do that? I downloaded the updated versions of Streamlink Twitch and Streamlink, everything runs exactly the same, which makes me wonder if I'm missing something like returning features since Twitch fixed the API.

**Comment by bastimeyer** [comment]
> It says in the release highlights to set

No, it says that the required Streamlink version **was set** / **has been set** to `1.3.1` since the last release. This isn't something you as a user can change. As the changelog further says, all you have to do is upgrade Streamlink if you haven't done it already.

> everything runs exactly the same, which makes me wonder if I'm missing something like returning features since Twitch fixed the API

The Streamlink version bump had nothing to do with Twitch. This was necessary because of a change in the recent release of the MPV player. Both Streamlink and Streamlink Twitch GUI were using the legacy parameter format, which broke it, so it had to be fixed in both applications.

Not sure what you mean with returning features, but stuff that gets displayed in the Twitch GUI (like followed streams for example, which were not sorted for two weeks due to a bug in the Twitch API) has nothing to do with Streamlink, as Streamlink is just the program used to launch streams. Streamlink Twitch GUI is the GUI frontend / launcher for Streamlink and if something gets fixed/implemented here, then it is completely independent from Streamlink.

**Comment by Uzukii** [comment]
> Not sure what you mean with returning features

You used to be able to see followed games in Twitch GUI before the API or whatever broke. As well as hosted streams, I think. There were two other options under Followed besides streams and channels.

**Comment by bastimeyer** [comment]
The status of this hasn't changed and probably won't change (#684). I think you are confusing the line in the current changelog where it says that it has been fixed again by Twitch. This is referring to the followed streams API endpoint, which is mentioned under the same bullet point of that changelog list. If you're wondering what it means, click on the linked issue in the changelog to see more details about it.

If any kind of feature gets newly implemented or re-implemented, it will be mentioned in the changelog explicitly.
