### ISSUE TITLE
Stream lists are empty

### ISSUE THREAD

**Issue by alsadata** [streamlink/streamlink-twitch-gui#706]
## Bug report
- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.9.1
NW.js: 0.42.3
Architecture: x64

**Streamlink version:**  
streamlink 1.3.1

**Configuration details:**  
I just upgraded from 1.9.0 to 1.9.1 to see if the error was fixed but the error occures in both versions

### Description
When I open Streams in the left menu, all I get is:

> #### Top Streams ####
> The returned list of top streams is empty.

When I open Games, I can see the list of all games being streamed.
However, if I open any of them, I get the same result:

> #### Dota 2 #####
> The returned list of streams of this game is empty.

Any stream under Featured works correctly.

Two days ago, everything worked smoothly with the previous versions Streamlink Twitch GUI 1.9.0 and Streamlink 1.3.0 so I suspect it's an API change from Twitch.

### Expected / Actual behavior

I expect to see all streams under Streams and all related streams when selecting a game under Games

See description above for actual behaviour.

### Reproduction steps

1. Open Streamlink Twitch GUI
2. Click Straems in the left menubar under Browse
3. See empty list

### Log output
```
[2020-02-21T20:37:46.752Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
```

**Comment by bastimeyer** [comment]
That issue is caused by an API change on Twitch's end.

It's probably related to https://discuss.dev.twitch.tv/t/upcoming-changes-to-the-streams-v5-endpoints/23926 where they made some changes to all streams related API endpoints. The changes mentioned there however shouldn't affect Streamlink Twitch GUI, since it already [has a workaround](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/app/ui/routes/-mixins/routes/infinite-scroll/index.js#L163-L164) implemented for this property which got removed now, as it was inconsistent.

The issue with the empty API responses seems to be caused by the language filter. Filtering streams by language works by adding the `broadcaster_language` parameter to streams API requests. This is now broken and an empty list is returned if this parameter holds two values (separated with a comma). This means that you can't filter for multiple languages anymore.

No `broadcaster_language` set:
```bash
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  "https://api.twitch.tv/kraken/streams?limit=3" \
  | jq "[.streams[] | .channel.name]"
```
```json
[
  "lec",
  "rubius",
  "rocketleague"
]
```

One `broadcaster_language` set (`de` - German):
```bash
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  "https://api.twitch.tv/kraken/streams?limit=3&broadcaster_language=de" \
  | jq "[.streams[] | .channel.name]"
```
```json
[
  "montanablack88",
  "gronkh",
  "summonersinnlive"
]
```

Multiple `broadcaster_language` set: (`en,de` - English and German):
```bash
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  "https://api.twitch.tv/kraken/streams?limit=3&broadcaster_language=en,de" \
  | jq "[.streams[] | .channel.name]"
```
```json
[]
```

Let me open a new thread on the Twitch dev forums... I can already tell you though what answer we'll get:
"It's not supported, because it's not documented".

Btw, if you read the linked post from the Twitch devs, you'll see that they are once again crippling the kraken API (with a ridiculous time frame for developers - without properly notifying them), because they want developers to switch over to the helix API. The helix API however is still, after more than two years of development, very much limited in terms of features.

**Comment by fgl27** [comment]
have you read?
https://dev.twitch.tv/docs/v5/reference/streams

languages -> Constrains the language of the streams returned. Valid value: a locale ID string; for example, en, fi, es-mx. **Only one language** can be specified. Default: all languages.

I don't use **broadcaster_language** but just **language**, and it was working for multiple languages until yesterday. 

also some languages don't work anymore as "es-mx" or "pt-br", didn't try those with **broadcaster_language** yet maybe works maybe not.

**Comment by bastimeyer** [comment]
Yes, I have read the documentation. :sleepy:

There is a distinction between the `language` and `broadcaster_language` properties. `language` refers to a channel's own language settings, whereas `broadcaster_language` is used to describe the stream's language. A channel can be streaming while having two different values here. When filtering for languages in stream lists, the only thing that's important is the `broadcaster_language`, not the language setting a channel has chosen for themselves.

The comma-separated parameter was used by Twitch on their website before they switched over to the GQL API. It was actually even supported by the API before their website was using it. You can look up the related issues on this issue tracker here. It was partly broken and got re-implemented twice if I remember correctly.

**Comment by bastimeyer** [comment]
The `language` request parameter seems to be completely broken. No matter which value is set, it's returning an unfiltered list. That's a proper reason for opening an issue on the dev forums. I'll link it here once I've posted it. I'll try a couple of other things first though.

**Comment by fgl27** [comment]
Yes I was just testing and notice it, **broadcaster_language** is fine, **language** works for the clip api, **broadcaster_language** never worked there...

**Comment by bastimeyer** [comment]
https://discuss.dev.twitch.tv/t/kraken-language-and-broadcaster-language-request-parameters-partly-broken/24214

**Comment by alsadata** [comment]
You were right, I had the streams filtered to Danish and English.

By going to Settings -> Languages, clicking Uncheck all and saving the settings, the stream lists worked again (For anyone else stumbling over this issue :-) )

**Comment by alkim0** [comment]
Note that the `language` parameter now works according to [https://github.com/twitchdev/issues/issues/66](https://github.com/twitchdev/issues/issues/66). However, the `broadcaster_language` still seems broken. It seems it would be prudent to change language filtering settings from `broadcaster_language` to `language`.
