### ISSUE TITLE
News / Issues Modal

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#708]
Regarding the latest issues this program has (because of API change), would it be possible to show this info in a Modal on program start so the user is informed about it?

It could even be read from a specific github issue to be up2date, if that makes sense.

**Comment by bastimeyer** [comment]
This would be even more maintenance burden. It already is a bottomless pit of work and I don't want to spend even more time on issues which are out of my hand, especially if I have to repeat myself on one more place, since most people wouldn't read it anyway and it wouldn't remove any support questions on other channels.

If there are issues like this, it's up to the user to either come to the project's issue tracker and check for the current status or wait for a fix on Twitch's side or via a new release of the Twitch GUI (if it's possible to be fixed locally). The current API issues have been reported on the Twitch dev forums and also their \*new\* issue tracker on Github. This is all I can do here. If this is annoying to anyone, they can ask the Twitch devs why they are constantly breaking things and third-party applications. Streamlink Twitch GUI is not a commercial product.
