### ISSUE TITLE
"Unexpected version check output"

### ISSUE THREAD

**Issue by barand3** [streamlink/streamlink-twitch-gui#709]
I use Streamlink Twitch Gui on Mac and unfortunately it doesn't work.
Python version 2.7 and 3.7 are installed, Streamlink version 1.3.1 is installed.
Nevertheless, the above error message appears when starting a stream.
What can I do?

**Comment by bastimeyer** [comment]
You can't use different python versions other than the one which the Streamlink package is built for. If you look for this "Unexpected version check output" error message on this issue tracker, you will find more than enough information on how to fix this. As a short explanation though, Streamlink Twitch GUI needs to retrieve the streamlink version string first before it can launch a stream, but if you're mixing up python versions, an error message might be returned instead, causing this error to be displayed. A better error message still needs to be implemented.

As you can see in the streamlink homebrew formula, it depends on python 3.8:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/streamlink.rb#L17
However, the Python 3.8 homebrew formula is a so called keg-only formula, which means that it doesn't install the package globally (note the homebrew text output after installing the package).
https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@3.8.rb#L24

When launching a stream, Streamlink Twitch GUI will try to resolve the streamlink python entry script file and its referenced python executable automatically. If this doesn't work (for whatever reason), then you can also specify the paths manually in the streaming settings menu. See the wiki for additional help:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
if you want to debug this, there's the `--loglevel debug` parameter, which lets you see the file paths that get resolved during a stream launch attempt:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l

As another hint, in case you can't manage to solve this, check the absolute path of the Streamlink python entry script file and the python path from its shebang, and set the returned paths in the settings menu. Example:
```bash
$ which streamlink
/usr/local/bin/streamlink
$ head -n1 $(which streamlink) | cut -c3-
/usr/local/Cellar/streamlink/1.3.1_1/libexec/bin/python3.8
```

**Comment by barand3** [comment]
Thanks for the hint with code.
That's exactly what I needed

**Comment by argalad** [comment]
I've tried this and the problem still persists. 
I am using Streamlink 5.1.2 and my streaming config:
Python executable
/Applications/Xcode.app/Contents/Developer/usr/bin/python3.9
Streamlink python script
/Users/argalad/Library/Python/3.9/bin/streamlink

I am using macOS Ventura 13.0.1
If I run streamlink from the command line it works without any problem

**Comment by bastimeyer** [comment]
> Python executable
> /Applications/Xcode.app/Contents/Developer/usr/bin/python3.9
> Streamlink python script
> /Users/argalad/Library/Python/3.9/bin/streamlink

You are mixing two different python environments. Of course this will not work. If you start the Twitch GUI with its `--loglevel=debug` parameter, then you'll see the exact command it executes when launching Streamlink.

> If I run streamlink from the command line

If you run `streamlink` from your command line shell, then this is something entirely different because your command line shell first needs to resolve its absolute path via the `PATH` env var. Then this resolved `streamlink` executable script is being run by a different python environment.

So this raises the question. Why exactly are you setting any custom paths in the Twitch GUI? And why are you mixing two separate python environments?

Read this
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
and this
https://streamlink.github.io/install.html

Also, this issue thread is two and a half years old and unrelated to your issue. Please don't hijack old and resolved issues.

**Comment by ProditorMagnus** [comment]
(Linux) `--loglevel=debug` revealed that my streamlink was too old, switched it to appimage then.
