### ISSUE TITLE
Process of "Build from source" for Linux (Mint)

### ISSUE THREAD

**Issue by Fooughhy** [streamlink/streamlink-twitch-gui#710]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Linux Mint 19.3
![NeoFetch](https://user-images.githubusercontent.com/6977416/77515203-694ce780-6e78-11ea-90d5-9b066c8f378f.png)
**Streamlink Twitch GUI version:**  

Source (Commit: dc3c891f7e0f05410467efd584389189a80536ee)
**Streamlink version:**  

1.3.1
**Configuration details:**  

### Description

Tried to build from source using both yarn and npm. The build instructions are generally poor (you request that grunt is installed globally, but this seems to have been disabled, so grunt has to be installed locally, where npm actually needs another option in the command (yarn: yarn add grunt-cli, npm: npm install grunt-cli --save-dev). After installation, I am running "grunt release" to produce a compiled build of the application.

### Expected / Actual behavior

I expect the application to pass all tests, compile and a folder to be created in "build/releases" which has a built and compiled version of "streamlink-twitch-gui".

What actually happens is that it fails a test, shown ![here](https://user-images.githubusercontent.com/6977416/77515212-6baf4180-6e78-11ea-99a5-597ad6d96619.png) and thus doesn't complete the build/compile phase.

### Reproduction steps

1. Follow steps to download latest version from GitHub
2. Install Yarn (1.22.4), Node.js (13.11.0) and npm (6.13.7)
3. run "npm install grunt-cli --save-dev" or "yarn add grunt-cli" (installs grunt 1.3.2)
4. run "yarn install" or "npm install"
5. run "grunt build"

### Log output

https://gist.github.com/Fooughhy/8ccf696574fbedb39c0ac79fe88fb1e1

### Additional comments, screenshots, etc.

![neofetch-2020-03-25-09-03-06-30302](https://user-images.githubusercontent.com/6977416/77515203-694ce780-6e78-11ea-90d5-9b066c8f378f.png)
![Screenshot from 2020-03-25 09-08-39](https://user-images.githubusercontent.com/6977416/77515206-6a7e1480-6e78-11ea-9452-7c6774fcb1cd.png)
![Screenshot from 2020-03-25 09-08-50](https://user-images.githubusercontent.com/6977416/77515212-6baf4180-6e78-11ea-99a5-597ad6d96619.png)

**Comment by bastimeyer** [comment]
> I expect the application to pass all tests

The tests are working fine and are all passing, as you can see on [TravisCI's build log](https://travis-ci.org/github/streamlink/streamlink-twitch-gui/branches). You must have messed up something while installing the dependencies. Let me try to help...

> The build instructions are generally poor

You're referring to CONTRIBUTING.md, right? This hasn't been updated in a long time, sorry about the confusion. I'll see if I can improve/fix this later.

**Please only use yarn**, otherwise the package lockfile will get ignored. And most importantly, don't try to mix up two different package managers.

If you're installing a package globally via yarn (in this case here, `grunt-cli`), its executable file won't be located in the repo's `./node_modules/.bin/` path, but in yarn's global `bin` path instead. You can check that path via `yarn global bin`. If this path is not included in your system's `PATH` env var, you'll have to add it, or change the global yarn config to a different path before installing global packages.

An alternative, or rather preferred way for installing global packages like this, is installing them via your system's package manager (eg. `grunt-cli` on Arch, or `node-grunt-cli` on Ubuntu/Mint/etc), as installing global packages via yarn/npm might conflict with other packages on your system. And if that all is not working out for you, `grunt-cli` can still be installed locally in the repo and then be executed from `./node_modules/.bin/`. However, installing additional local packages will change the lockfile and potentially mess it up, so be aware of that.

----

In order to fix your build issues, please do the following

1. Install `grunt-cli` globally, either via yarn or your system's package manager, as mentioned above
2. Reset the repo's state
   ```bash
   git checkout -- .
   rm -rf ./node_modules/
   ```
3. Install dependencies via yarn
   ```bash
   yarn install
   ```
4. Build
   ```bash
   # "release" is a shortcut for "build:prod compile"
   grunt release
   ```

If you have further questions, please ask.

**Comment by Fooughhy** [comment]
Thank you for your help! Sorry for taking up your time!

I assumed there was an issue with grunt as when you install it globally with yarn, and then just run "grunt", (for me atleast) there is a warning message stating that "there is no local grunt install". I also believe that I was previously unable to even use grunt when this error message appeared. But it is VERY possible it was the permissions for the folder which screwed things up, as the folder was owned by 'root', which I now have changed.

So now, having installed grunt globall with yarn again, and chown'ing the source folder, all tests pass, grunt builds the application and the "releases" folder is created! I will say though, that I was careful to remove the package-lock.json, yarn.lock and node_modules files/folders when trying both yarn and npm before, but I guess it was the permissions then.

I ended up using the released version instead, which worked fine for me! :+1:
