### ISSUE TITLE
Streamlink fails to run when using certain wrapper scripts

### ISSUE THREAD

**Issue by rileyinman** [streamlink/streamlink-twitch-gui#718]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
NixOS 19.09

**Streamlink Twitch GUI version:**  
1.9.1

**Streamlink version:**  
1.3.1

### Description

I'm attempting to write a Nix derivation for streamlink-twitch-gui, and having an issue with the automatic handling of wrapper scripts. I'm not sure if this may be an issue with the shebang type being different on NixOS or a different problem, but either way streamlink-twitch-gui refuses to run the script unless I manually set the path to the "unwrapped" binary in the settings. For reference, here is the wrapper script:

```bash
#! /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/syqcp8zb9c0vxj2sx6jbv5f9q7yki4jz-python3-3.7.7/bin:/nix/store/7lc2j0zxq6hakf89swr08a6jvdnmvk24-streamlink-1.3.1/bin:/nix/store/wyvzykym54601iry33v05hzp864cbqzi-python3.7-chardet-3.0.4/bin:/nix/store/qfi1h97flkdax6ag0n0aj7545xcivr5g-python3.7-setuptools-45.2.0/bin:/nix/store/n8nw2xs2q4vk8ybd0yj3f333fr74ixdd-python3.7-websocket_client-0.56.0/bin:/nix/store/kc74iz3k6j67vr2lxfdrj2m3ww5hd1qh-openssl-1.1.1f-bin/bin:/nix/store/ybv5a5mbalj3791l1w3v2jy452n58vf1-rtmpdump-2019-03-30/bin:/nix/store/2sfcwvmmg3pj4pyqgf81ikf1l6jbn41c-ffmpeg-3.4.7-bin/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/7lc2j0zxq6hakf89swr08a6jvdnmvk24-streamlink-1.3.1/bin/.streamlink-wrapped"  "$@"
```

Setting the path to ".streamlink-wrapped" manually in the settings fixes it temporarily, but is an annoying workaround since the built derivation path for streamlink will change with updates.

### Expected / Actual behavior

I expect streamlink-twitch-gui to be able to use the wrapper script as expected, and run streamlink.

### Reproduction steps

1. Use the nix derivation I've created (see [here](https://github.com/rileyinman/nixpkgs/blob/20b35dcb2f7c974b1419f14075e919266b44a6c6/pkgs/applications/video/streamlink-twitch-gui/bin.nix) for the current state).
2. Run the built derivation binary and attempt to launch a stream.
3. Get the error.

### Log output

```
[error][StreamingService]
ProviderError: Couldn't validate python script
Executables were not found
```

**Comment by bastimeyer** [comment]
So you're packaging Streamlink Twitch GUI for NixOS? Cool. Let me try to help.

> automatic handling of wrapper scripts

Streamlink Twitch GUI does support bash wrapper scripts, but this is currently limited to the special cases of some of the packaged streamlink wrapper scripts on macOS and Windows, where it is (or was) necessary to read from these files. This wasn't built with general-purpose wrapper scripts in mind and is therefore too strict during the validation.

- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/app/services/streaming/provider/find-pythonscript-interpreter.js#L29-L46
- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/test/tests/services/streaming/provider/find-pythonscript-interpreter.js#L245-L251

The point of this part of the validation is to get the python entry script and python executable path from such a wrapper script and optionally replace it with a different one on Windows for example. It doesn't try to execute the script itself and therefore wouldn't work if the validation logic would be extended.

The solution however could be adding an additional streaming provider for custom wrapper scripts, just like the special [`streamlinkw`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/config/streaming.json#L66-L82) one for the Streamlink Windows standalone executable.

As long as one of the file names the streaming provider's default config can be found in the PATH or list of fallback paths, then it should work without having to apply custom settings.

Even if I add this in the next release, it would probably be better to build the app while packaging instead of downloading the pre-built one from the Github releases, because the user would still have to select this non-default streaming provider first to make it work, and while packaging a custom build, you can apply a patch which changes the default provider.

**Example:**

```patch
diff --git a/src/app/locales/en/settings.yml b/src/app/locales/en/settings.yml
index 5603d854..bebe90e6 100644
--- a/src/app/locales/en/settings.yml
+++ b/src/app/locales/en/settings.yml
@@ -85,6 +85,7 @@ streaming:
         executable:
             python: Python executable
             streamlinkw: Streamlink executable
+            streamlinkwrapper: Streamlink wrapper script
         python-script:
             streamlink: Streamlink python script
         parameters:
diff --git a/src/config/streaming.json b/src/config/streaming.json
index 385dd4a2..0cc16518 100644
--- a/src/config/streaming.json
+++ b/src/config/streaming.json
@@ -1,5 +1,5 @@
 {
-	"default-provider": "streamlink",
+	"default-provider": "streamlinkwrapper",
 	"download-url": {
 		"streamlink": "https://streamlink.github.io/install.html"
 	},
@@ -79,6 +79,18 @@
 					"%PROGRAMFILES(X86)%\\Streamlink\\bin"
 				]
 			}
+		},
+		"streamlinkwrapper": {
+			"type": "streamlink",
+			"flavor": "default",
+			"name": "Streamlink",
+			"label": "Streamlink (wrapper script)",
+			"exec": {
+				"win32": false,
+				"darwin": false,
+				"linux": [ ".streamlink-wrapped", "streamlink" ]
+			},
+			"fallback": {}
 		}
 	}
 }
```

**Comment by rileyinman** [comment]
Thanks so much! I had decided to try packaging the binary version first since the node build was giving me trouble, but I'll give it another shot and see if I can get it working yet. Thank you for pointing out the specific patches that would be needed to make it work too, this is a huge help :)

**Comment by rileyinman** [comment]
I now remember one of the unfortunate problems that caused me to try patching the binary downloads. Because of the way you determine the list of contributors ([here](https://github.com/streamlink/streamlink-twitch-gui/blob/v0.15.2/src/web_loaders/metadata-loader.js#L42)), the build requires the entire repository including the .git folder. However, this is not a deterministic download as seen here: https://github.com/NixOS/nixpkgs/issues/8567. This means I end up with the error shown in [this issue](https://github.com/streamlink/streamlink-twitch-gui/issues/321).

**Comment by bastimeyer** [comment]
> list of contributors

You are linking the metadata loader from `v0.15.2`. The contributor data was removed a long time ago, in 2016, via 5013699.

It currently only reads the version string from `git describe --tags`, which is used so that dev builds will show the correct version instead of the version set in the package.json, which refers to the last release and is thus not always correct. This is not an uncommon to do (Streamlink also does this, btw) and it is deterministic as long as you fetch the "latest" tag and enough commits so that git can connect both nodes/objects. If this is an issue when downloading a tarball instead of cloning the git repo, then you'll have to patch this as well.

- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/web_loaders/metadata-loader.js#L65
- https://github.com/streamlink/streamlink-twitch-gui/blob/master/src/web_loaders/metadata-loader.js#L42

**Comment by rileyinman** [comment]
Oh, my mistake on the contributor data 😅 In that case, I'll look into patching out the git operation that currently remains.

**Comment by bastimeyer** [comment]
Just a quick note regarding the streaming provider config:
I guess the unnecessary complexity with the custom python module script resolver can be removed, as it's not necessary anymore. I will see if I can rewrite the resolver config to a simpler one this weekend, which should make patching custom stuff required by packages like this much easier. Most causes of the notorious "invalid version string output" error will also be fixed by that, as there won't be room for invalid python path configs.

To explain this a bit more in detail, the Streamlink python and python script resolver had to be implemented in the past due to an issue on Windows related to the Streamlink launcher file, as it had the wrong python executable hardcoded, which caused it to always spawn a terminal window, which was unacceptable for the Twitch GUI. The system-independent solution was to find Streamlink's python entry module script file and get the path of the python executable from its shebang at the top and replace the executable name with the proper one on Windows and launch python with the module script as first parameter. An additional step also had to be implemented for macOS's homebrew package, as it uses a BASH script wrapper to set an additional python env var. This is where the wrapper script "support" comes from.

Since my pull request with a fix got merged last year into Streamlink's Windows installer dependency `pynsist`, this resolver workaround wasn't needed anymore, as there were two separate Streamlink launchers now, and the additional "streamlinkw" resolver config as added. It was basically the same as the old Livestreamer resolver config, because Livestreamer never had this problem. It got removed a few months later though, as it became fully incompatible with Twitch.

The remnants of this whole nonsense is the current situation with two separate resolver configs, one of them being a workaround that isn't needed anymore but works fine (except for situations as described in this thread) and one resolver config for Windows which would also work on all OSes, but only has Windows related data set.

**Comment by rileyinman** [comment]
Hi! Sorry this took me so long to get back around to, I unfortunately haven't had much luck getting the yarn build to work (the node ecosystem is still a bit difficult to work with on NixOS) but this will make packaging the binary releases work much better. I just tested it and the new release works great! Thanks so much for your help :D
