### ISSUE TITLE
Featured Channels can have no thumbnails

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#720]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Happens on every OS

**Streamlink Twitch GUI version:**  
1.9.1

**Streamlink version:**  
1.3.1

### Description

This happens regularly for channels on the `featured` page to have no thumbnails, while the big picture is here if user select the channel. See the joined screenshot.

### Expected / Actual behavior

A thumbnail or a substitute should always be here

### Reproduction steps

Just show the `featured` page when there are problematic channels.

### Additional comments, screenshots, etc.

![Screenshot from 2020-05-10 20-07-43](https://user-images.githubusercontent.com/709500/81507055-d0c0d880-92fa-11ea-877b-ef0408c6249f.png)

**Comment by bastimeyer** [comment]
Twitch seems to be returning transparent images now:

```
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \
  "https://api.twitch.tv/kraken/streams/featured?limit=5&offset=0" \
  | jq -r '.featured[].image'
https://s.jtvnw.net/jtv_user_pictures/hosted_images/TWITCH
https://s.jtvnw.net/jtv_user_pictures/hosted_images/TWITCH
https://s.jtvnw.net/jtv_user_pictures/hosted_images/clear
https://s.jtvnw.net/jtv_user_pictures/hosted_images/clear
https://s.jtvnw.net/jtv_user_pictures/hosted_images/TWITCH
```

I can't find any announcements regarding a change of that API endpoint, so I'm not sure if this is a temporary issue on their end or not. Also not sure why they would return transparent images instead of a placeholder or why there are (at least) two different URLs.

The docs still list the API response which the Twitch GUI expects:
https://dev.twitch.tv/docs/v5/reference/streams#get-featured-streams

As an alternative, channel logos could be used, but that would require a change of the route's layout which I'd dislike very much.

----

In February, Twitch announced lots of other changes on the deprecated kraken v5 API, including rate limiting, but then they backtracked after receiving a shitstorm from lots of devs, especially because the "new" helix API is still pretty much unusable for almost all 3d party apps. Then they apologized and announced a new API strategy with respect for 3rd party app developers. That included an internal beta program for new features on helix, but after that there were no new posts. It's possible that this issue is caused by new changes regarding that, but who knows.

**Comment by bastimeyer** [comment]
Let's wait before merging a8375f7. Maybe it's just a temporary issue that doesn't need fixing here.

This change will show the same stream image as preview image on the featured streams route. Not ideal, but better than a potential re-layout.

**Comment by bastimeyer** [comment]
Reported it on the Twitch issue tracker, just in case...

**Comment by Porkepix** [comment]
> Let's wait before merging [a8375f7](https://github.com/streamlink/streamlink-twitch-gui/commit/a8375f7188d90806f014310a7eb11c984b63a81b). Maybe it's just a temporary issue that doesn't need fixing here.

To Be honest, it's been quite some times I noticed this issue, but forgot and didn't took the necessary time to report it. So it's unlikely that, last the latest ad problem, it's a temporary problem that will go away in two days. I think I see it for at least several months, but this screenshot is one will all channels having issues.

Most of the time I only have one to three channels with an issue while the other ones are behaving as usual. So it seems it can also be an issue affecting only some kind of channels (I often noticed it for music chans for example, but this can be a bias)

Here's for example a new screenshot with 4 chans having an issue, and one not.
![Screenshot from 2020-05-10 22-23-43](https://user-images.githubusercontent.com/709500/81509714-01117280-930d-11ea-85cf-30fcc0090204.png)

**Comment by bastimeyer** [comment]
No response from them within an entire week. Need to merge this now, so that missing preview images are not included in the next release, which will be soon. Once they've fixed it, I can revert this change.

**Comment by Porkepix** [comment]
> No response from them within an entire week. Need to merge this now, so that missing preview images are not included in the next release, which will be soon. Once they've fixed it, I can revert this change.

It can't detect whether a channel image is found or not and do this only in case of failure?

**Comment by bastimeyer** [comment]
Since they already use multiple URLs for transparent image placeholders, I don't want to implement a check for this. They could simply add another one which would break my implementation.
