### ISSUE TITLE
Apply low-latency setting to channel individually

### ISSUE THREAD

**Issue by dxball** [streamlink/streamlink-twitch-gui#723]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Currently, the low-latency setting is global. If some channel didn't open the low-latency mode, I have to manually disable this setting before open the stream.

So it will be nice to have a local low-latency setting in the channel's setting page like `Quality` or `Automatically open chat`

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/194673/82243323-f6d91f00-9971-11ea-863e-063a4d1eb0db.png)

**Comment by bastimeyer** [comment]
I wasn't sure whether I want to implement custom channel settings for low latency streaming, because enabling it also requires customizing the player's buffering in most cases, and since player settings can't be added to the channel settings right now without a major rewrite, global player customizations could theoretically interfere with individual low latency channel settings. The whole situation isn't ideal, hence why this low latency feature wasn't merged sooner in Streamlink.

But yeah, let me add this, because I think not giving the option at all is probably worse.

**Comment by bastimeyer** [comment]
Also added the disable ads option to the channel settings.
