### ISSUE TITLE
Chatty won't launch

### ISSUE THREAD

**Issue by skipperhi** [streamlink/streamlink-twitch-gui#729]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  Windows 10

**Streamlink Twitch GUI version:**  1.10.0

**Streamlink version:**  1.4.1

**Configuration details:**  Chatty Standalone as the chat app

### Description

Chatty won't open when pressing the chat button. Chatty was working fine before the update. I've tried uninstalling and reinstalling streamlink, streamlink gui, and chatty.

### Expected / Actual behavior

Chatty should open when the chat button is pressed, instead the button shakes and nothing happens.

### Reproduction steps

1. Set chatty standalone as chat app
2. Launch a stream
3. Press chat

### Log output

```

```

**Comment by bastimeyer** [comment]
Make sure that Chatty itself is able to start and that you have set the correct path in the chat settings menu in the Twitch GUI. Chatty standalone is a simple executable, so there are not many reasons why it could fail.

Also check the Twitch GUI's error log output after trying to launch Chatty:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l

> Chatty was working fine before the update.

Nothing chat related has been changed since the last release. The only change which could affect the chat config (when using a relative path) is the removal of the CWD override workaround on Windows.
