### ISSUE TITLE
Trying to switch to hosted stream breaks ModalStreamingComponent

### ISSUE THREAD

**Issue by MrLint** [streamlink/streamlink-twitch-gui#731]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.10

### Description
When switching to a hosted stream the video quality drop down reports wording of 'missing translation : qualities"
### Expected / Actual behavior
Unknown
![streamlinkgui](https://user-images.githubusercontent.com/18565454/83957112-0346ee00-a833-11ea-8b96-bd69c52458a4.png)

**Comment by bastimeyer** [comment]
> switching to a hosted stream

The entire modal dialog seems to be missing its stream data when switching the channel, hence the lack of title and body texts. The missing translation message is just another result of this, since it doesn't know which selection it currently is on.

I feel like something similar was reported and fixed last year or so, but I can't find it anywhere and can't remember exactly what it was. 533bd22 is related, but this was a different bugfix.

**Comment by bastimeyer** [comment]
#637

**Comment by bastimeyer** [comment]
Should be resolved now with the merge of 8378695f8680b6f1e9900e28203cee53ffc1375e.
