### ISSUE TITLE
Back navigation should remember scroll/view position

### ISSUE THREAD

**Issue by Flavelius** [streamlink/streamlink-twitch-gui#743]
## Feature request

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ x] This is a feature request and I have read the contribution guidelines.

### Description

When scrolling down in the games section and clicking on a game, upon exiting (navigate back) the scrollposition is reverted to the top (top played games). This makes it hard to discover lesser known/played games as it requires re-navigating down every time.

There should be a way for the position to be remembered/restored (like it's typical for webbrowsers).

**Comment by bastimeyer** [comment]
> like it's typical for webbrowsers

Streamlink Twitch GUI is a web browser which running an EmberJS app. For static websites, this is very simple to achieve, but since the data is loaded on runtime and the DOM is built dynamically, this makes it very difficult.

There is no data history being stored for specific routes you've visited in the app and it always refreshes the data when going back to the previous route. That's because of how Ember and EmberData work and how the data models are implemented and set up.

Restoring the scrolling position when reloading the content doesn't make sense, because you'll very likely see different data. The infinite scroll mechanic also makes this impossible, because it would require re-requesting everything again with multiple API queries, and those will be rate limited on the new API namespace. Storing the data history is unfortunately (currently) not possible and doesn't make much sense on a platform with rapid user-content changes.

Your use case is an exception and I agree that it's a problem, but it's not worth the effort in my opinion, sorry. And what Twitch does with their website is something entirely different.

**Comment by LoganND** [comment]
Yeah this is annoying as hell.  Best work around I've found is to control click the game link so it opens a separate tab of just that game.  This way you can always go back to your scroll in progress.

**Comment by bastimeyer** [comment]
> opens a separate tab

Not sure what you're talking about, but Streamlink Twitch GUI doesn't support tabs.

All link components ignore right clicks, middle clicks, shift clicks, ctrl clicks, alt clicks and meta clicks:
https://github.com/streamlink/streamlink-twitch-gui/blob/3dc8b5e3b617789ff41e65787996999a173291f2/src/app/ui/components/link/link-to/component.js#L54-L58
https://github.com/streamlink/streamlink-twitch-gui/blob/3dc8b5e3b617789ff41e65787996999a173291f2/src/test/tests/ui/components/link/link-to.js#L180-L213

Other components with routing activities that are not anchor elements, like preview images for example, have custom click event listeners where any kind of regular "link-behavior" doesn't exist, so modifier keys don't work.

**Comment by LoganND** [comment]
I have no idea what any of that programming mumbo jumbo means, or what those pictures you posted mean, but I can tell you with Firefox I can control left-click a game on Twitch's scrolling game browsing page and it opens another tab with the streamers playing that game.  Once I'm done with that tab I can simply go back to my original tab where I was scrolling and resume scrolling.  That works on any website not just Twitch.

**Comment by Flavelius** [comment]
I can see that using a normal web browser instead of this app is a workaround for this app not providing that functionality, but in that case your wording was confusing, as it sounds like you're using that workaround inside streamlink twitch gui.

**Comment by LoganND** [comment]
Oh.  Yeah, I googled "twitch doesn't remember my scroll" and this forum popped up, so that's why I commented here.  I don't use any twitch app, I simply use Firefox on my desktop to watch streams.

**Comment by bastimeyer** [comment]
Locking the thread and blocking @LoganND from the orga, as I don't have time for this nonsense from confused karens.
