### ISSUE TITLE
Please make a void linux package

### ISSUE THREAD

**Issue by Codythedragonrude** [streamlink/streamlink-twitch-gui#751]
Even if we have to use the nonfree repo and xbps src to get the program going 
it would be nice to have a void linux package or some way to install it 

currently the build process constantly errors in the terminal 

![Screenshot_20200929_181755](https://user-images.githubusercontent.com/47878493/94622563-706a0d80-0280-11eb-9226-b0ad936bdd0a.png)

![Screenshot_20200929_181928](https://user-images.githubusercontent.com/47878493/94622592-7cee6600-0280-11eb-9150-5dc12ba40233.png)

![Screenshot_20200929_182011](https://user-images.githubusercontent.com/47878493/94622604-8081ed00-0280-11eb-9ac1-107a15f524fc.png)

**Comment by bastimeyer** [comment]
I personally don't use Void, so it won't happen that I'm writing a package for this.

As the sole developer here ever since, I just can't and don't want to maintain packages on my own for every existing distro and package manager out there. I simply don't have the time for this. If anyone wants to work on packaging the application on yet unavailable platforms, they are free and more than welcome to do so. If you want the app packages for your distro, ask one of the distro's package maintainers.

The next release will have an appimage build though, so if there are no packages available for your distro, simply setting +x on the appimage and running it should be much simpler than extracting a release build from tarballs or building the app yourself.

----

> Running "runtest" task
> `ERROR:platform_thread_posix.cc(129)] pthread_create: Invalid argument (22)`
> NW.js exited prematurely

According to this thread, this is a Chromium related issue on your system which prevents it from starting:
https://github.com/void-linux/void-packages/issues/18068

When building, tests need to be run in an SDK build of NW.js first before the application can be compiled and builded with an NW.js release build.

**Comment by Codythedragonrude** [comment]
> I personally don't use Void, so it won't happen that I'm writing a package for this.
> 
> As the sole developer here ever since, I just can't and don't want to maintain packages on my own for every existing distro and package manager out there. I simply don't have the time for this. If anyone wants to work on packaging the application on yet unavailable platforms, they are free and more than welcome to do so. If you want the app packages for your distro, ask one of the distro's package maintainers.
> 
> The next release will have an appimage build though, so if there are no packages available for your distro, simply setting +x on the appimage and running it should be much simpler than extracting a release build from tarballs or building the app yourself.
> 
> > Running "runtest" task
> > `ERROR:platform_thread_posix.cc(129)] pthread_create: Invalid argument (22)`
> > NW.js exited prematurely
> 
> According to this thread, this is a Chromium related issue on your system which prevents it from starting:
> [void-linux/void-packages#18068](https://github.com/void-linux/void-packages/issues/18068)
> 
> When building, tests need to be run in an SDK build of NW.js first before the application can be compiled and builded with an NW.js release build.

yeah the appimage should fix this the joy of things like appimage and flatpaks they solve most problems
