### ISSUE TITLE
Allow multiple language selections when fading out

### ISSUE THREAD

**Issue by Ten0** [streamlink/streamlink-twitch-gui#753]
Hi,

First of all thank you so much for this great app.

I watch streams in several languages and care more about the content than which of these languages it's using.
However the "Languages" parameter tab only allows to check a single language, and will grey out all streams in all languages but that one, and I couldn't figure out how to select several languages there, so the GUI would show live streams in all of them.

Could you please allow selecting several languages there ?

Thanks!

**Comment by Ten0** [comment]
It looks like as of the API change that corresponds to 1c591563d637d88b6cb818d3fbbe40affb6250f4 we could instead have StreamLink Twitch GUI query without language filter, then grey out or completely filter out based on that filter, with additionally, if there's actually a single one selected and the parameter to have them disappear completely is checked, we could filter via the API param.

**Comment by bastimeyer** [comment]
> or completely filter out based on the checked languages in the parameters

No, client side filtering won't be implemented and I won't further comment on it.
https://github.com/streamlink/streamlink-twitch-gui/issues/724#issuecomment-632014478
https://github.com/streamlink/streamlink-twitch-gui/issues/724#issuecomment-632027590

> grey out

The fading mechanic is currently tied to the single language selection due to the API filtering restriction and it shares the same `language` attribute in the `SettingsGUI` data model fragment. This could be changed, but having two separate language selections for fading and filtering is also not a totally great solution, as it can potentially confuse the user and a brief note/description may need to be added.

**Comment by Ten0** [comment]
Hi! Thank you for your quick answer, and for the additional references.
It looks like you've already spent quite some time thinking about this issue.

I agree client-side filtering is dirty, extremely inefficient and never the good solution if you have control over both the server API and the client. I have no idea why Twitch removed that feature of allowing to filter on several languages.

> having two separate language selections for fading and filtering is also not a totally great solution, as it can potentially confuse the user and a brief note/description may need to be added.

Unfortunately I beleive you're right it's not a totally great solution, but given the API limitations I'm afraid there's indeed no totally great solution. ^^'

However, I'm not sure whether that's what you meant, but it looks like we wouldn't need to have two different graphical language selections in order to have this, we could just prevent from being in `Filter out streams` mode if several languages are checked (with indeed an additional note for the user that says `due to Twitch API limitations, it's not possible to select multiple languages in when in "Filter out Streams" mode`).
It looks like automatically switching to `Fade out streams` mode and disabling the `Filter out streams` checkbox when a user selects a second language would be a reasonably easy and not-too-dirty solution to implement this.

----
at https://github.com/streamlink/streamlink-twitch-gui/issues/113#issuecomment-117373647:
> The infinite scroll mechanism is just one of those: Imagine the scenario where a user has only enabled one single language in which only a few poeple are streaming. Multiple consecutive API requests would be needed in order to fill the blank space of a stream list. **This would increase the loading time by a lot**.

If the previous suggestion was to be implemented, that would already be a huge gain for me. However I still feel like:
 - **Loading time is even waaay longer if the user is the one having to manually** click the "Fetch more" button to trigger the loading and have his brain compute which streams are greyed out so that he can just examine the other ones, and they are spreaded everywhere un-evenly on the screen.
 - Even if I still had to end up clicking the "Fetch more" button for just one of two streams and it took a while to load, I'd rather have that than 98% greyed-out streams and having to manually search which two are not greyed out in the list.
 - Though it's dirty because we wouldn't really know how many streams to query, it seems reasonable to me that we fill the view with a variable amount of streams as responses arrive, and we keep making other queries as long as it's not filled. (We could query a max amount of streams based on the rate of streams matching the filter in the previous response, if we wanted to fine-tune it and not just query 100 streams everytime.)
 - In practice, most multilingual people will know english and another language, and english will represent a large proportion of the streams, so the impact on the number of queries probably wouldn't be *too* high.

----

Thanks again for your answer,
What do you think?

**Comment by bastimeyer** [comment]
I have pushed some changes onto the [`rewrite-language-filtering`](https://github.com/streamlink/streamlink-twitch-gui/compare/rewrite-language-filtering) branch for now. Unless I find any issues today, it will be merged into `master` later, so that it's included in today's nightly build.

This allows selecting multiple languages again and it replaces the fading/filtering radio-boxes with check-boxes which get disabled based on the language selection. Both get disabled if no language has been selected, filtering gets disabled if more than one language has been selected and fading gets disabled if one language has been selected and filtering is activated. Although it's not *that* simple, it should be fairly easy to understand, especially since I've added additional descriptions.

The only thing which annoys me a bit is that I had to copy the English translations to the other locales, as the descriptions are now text blocks with two lines, and the localization fallback mechanic doesn't work in this case. This also won't report missing translations in the `webpack:i18n` task. The affected translations are annotated with a `FIXME` comment.
