### ISSUE TITLE
Getting error --no-version-check

### ISSUE THREAD

**Issue by deaglenomics** [streamlink/streamlink-twitch-gui#757]
Hi guys, 

For some reason im getting an error of -

usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --no-version-check

Looks like streamlink does not support that command 

C:\Windows\System32>streamlink --no-version-check --player-passthrough hls --twitch-disable-ads twitch.tv/nightblue3 best
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --no-version-check

C:\Windows\System32>streamlink --version
streamlink 1.7.0+34.gf2cd9e8

Is there a way to remove that option from streamlink-twitch-gui?

**Comment by bastimeyer** [comment]
`--no-version-check` has been removed from Streamlink in streamlink/streamlink@d8c8a02 in preparation for its `2.0.0` release. The parameter was already deprecated for a long time.

The Twitch GUI still had the parameter hardcoded, which means you can't remove it. It has however already been removed in streamlink/streamlink-twitch-gui@b4dec09 8 days ago (currently the latest commit on the master branch), even an hour before the parameter removal commit was merged into Streamlink's master branch.

**If you're using Streamlink `>= 1.7.0+25.gd8c8a02`, then you'll have to use Streamlink Twitch GUI `>= v1.10.0+88.gb4dec095` as well.**

Once Streamlink has had its `2.0.0` release, the version requirement will be bumped here in the Twitch GUI so that people using an older incompatible version of Streamlink will see a proper error message, and `v1.11.0` will be released afterwards. Due to the nature of semver strings and build data of the version string being optional and thus unreliable, this comparison check is currently not possible, otherwise I had bumped the requirement already.

So either downgrade Streamlink, or use Twitch GUI nightly builds, or build the application from the master branch on your own. All instructions are as always documented here:

- https://github.com/streamlink/streamlink-twitch-gui/blob/master/README.md#development-version
- https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building

**Comment by bluewww** [comment]
Or you can manually patch in a `--no-version-check` stub into `streamlink_cli/argparser.py` for those who want a quick solution.
