### ISSUE TITLE
Checking in on a possible aarch64 raspberry pi 4 build

### ISSUE THREAD

**Issue by Codythedragonrude** [streamlink/streamlink-twitch-gui#759]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Additional comments, screenshots, etc.

Just wondering if it's possible with whats changed in raspberry pi land yet?
currently running manjaro arm kde on the pi4 with 8gb of ram which is why i'm specifically wondering if an aarch64 build is possible yet

**Comment by bastimeyer** [comment]
Once there are official ARM builds of NW.js available, I will upgrade the build configs here, but this isn't the case yet. With Apple's push towards ARM, this will probably happen soon. I can't tell you though if there will be builds for Linux as well.
https://github.com/nwjs/nw.js/issues?q=ARM
https://dl.nwjs.io/v0.49.2/

As you can see in #431, I've tried adding custom ARM Linux builds of an NW.js fork to Streamlink Twitch GUI a few years ago, but this was just an experimental hack of the build config at that time. This isn't up2date anymore and not much of use.
https://github.com/streamlink/streamlink-twitch-gui/tree/arm64

This is the repo with the custom ARMv7 Linux builds:
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases

If you feel like tinkering, you might get it to work by assembling the custom NW.js build with a Streamlink Twitch GUI production build manually. But since I don't own an R-PI, I can't help you with that.
