### ISSUE TITLE
VIProductVersion issue with windows installer building

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink-twitch-gui#760]
Windows installer building phase gives error from github actions with relation to VIProductVersion

I think you should make sure _VIProductVersion_ and _VIAddVersionKey "FileVersion"_ variables in _installer.nsi_ only get a "number" value (like 1.1.1.1) and not a value with initial "v" (like v1.1.1)

**Comment by bastimeyer** [comment]
Thanks for the hint. This issue was introduced by 6e2bf03 and did not get noticed, as the installer does only get built on a release. I would've caught it eventually though, as the CI has been switched to Github since the last release and I'm going to do a test release on my test account anyway before the next release, to make sure that everything will work correctly. Well, I guess one issue already found.

Just a question, why are you trying to build the installer on your forked repo? You also seem to have added win32 builds to the scheduled debug builds. If you just want to use the latest version of the application for your own usage, then just build it locally, without the installer, as it's just meant for actual releases. Then you don't have to deal with custom releases and diverging branches, which you have just done...

**Comment by fenopa** [comment]
I wanted to try your latest nightly build but saw that you only provide x64 for them, I needed win32, so wanted to see if I can configure it to produce win32 build myself. Failed a few times, then wanted to play a bit to figure out how things work. Then noticed this bug and wanted to let you know. Was gonna delete everything and the forked repo anyway.
