### ISSUE TITLE
VLC install path Flatpack [Ubuntu 20.04]

### ISSUE THREAD

**Issue by pflanzenandi** [streamlink/streamlink-twitch-gui#761]
Hello, in version 1.10 the GUI does not automatically detect the installation path of VLC if it was installed as a flatpack.
The deb variant of VLC is automatically detected and a stream starts.

Question: Which VLC flatpack file do I have to provide to the GUI to start VLC automatically?

**Comment by bastimeyer** [comment]
The command to launch flatpak applications is
```bash
flatpak run app-UUID
```

This means for Streamlink, you'll have to set the player executable via [`--player`](https://streamlink.github.io/cli.html#cmdoption-p) to `flatpak` and the remaining arguments as player arguments, `run app-UUID`, via [`--player-args`](https://streamlink.github.io/cli.html#cmdoption-a). Since flatpak will re-direct all input and output streams automatically, there shouldn't be any issues.

Example for launching VLC via flatpak in Streamlink:

```bash
streamlink --player flatpak --player-args 'run org.videolan.VLC {filename}' URL STREAM
```

The `{filename}` variable does not need to be set if you're using a Streamlink version greater than [`1.7.0+45.gea703e3`](https://github.com/streamlink/streamlink/commit/ea703e36c2e09ee85018d14dbf278e9d24193edb), but is mandatory in versions prior to that. The Twitch GUI adds this automatically until version [`v1.10.0+90.gc94cc96`](https://github.com/streamlink/streamlink-twitch-gui/commit/c94cc96d1569b85b08df64aaddc6dfd3cb5c1243) and users never have to set it here manually.

**In the Twitch GUI, you can add these parameters in the player settings menu.** When you're not using a player profile, set the player path to `flatpak` or `/usr/bin/flatpak` and the custom args to `run org.videolan.VLC` which will appear once you've set a custom player path.

The same applies when using the VLC player profile. Since the Twitch GUI appends its own player profile arguments to the user's custom arguments list, there won't be any issues here either.
