### ISSUE TITLE
Twitch block streamlink-twitch-gui and play a vlc message

### ISSUE THREAD

**Issue by m19u31** [streamlink/streamlink-twitch-gui#766]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  

**Streamlink Twitch GUI version:**  

**Streamlink version:**  

**Configuration details:**  

### Reproduction steps

1. ... open streamlink-twitch-gui and play stream in vlc
2. ... wait to a ads
3. ... vlc crash

### Additional comments, screenshots, etc.
is happening only while an advertisement is happening.
the message says use twitch by the browser or something and after a few seconds the vlc closes.
I'm trying to take a print but it stopped happening. happened 3 times and then started normal.

**Comment by bastimeyer** [comment]
Wrong repo.

> * I understand the difference between _Streamlink_ and _Streamlink Twitch GUI_.

Streamlink Twitch GUI is just a launcher for Streamlink and has nothing to do with streaming (see the readme). If you're having issues with anything streaming related, go to the Streamlink issue tracker.

> **Streamlink Twitch GUI version:**
> 
> **Streamlink version:**
>

----

- https://github.com/streamlink/streamlink-twitch-gui/issues/754
- https://github.com/streamlink/streamlink/issues/3210

TL;DR

Streamlink allows you to filter out embedded ads on Twitch (`--twitch-disable-ads`). This is working 100% correctly and reliably. Workarounds for preventing ads entirely only last so long, as they require a loophole to be exploited in Twitch's web-player system, similar to what ad-blockers do in your web browser. See the linked threads.

**In the Twitch GUI's streaming settings menu, there's the "Skip embedded ads" checkbox, which sets the `--twitch-disable-ads` Streamlink parameter when launching streams and it filters out the ads.** On pre-roll ads, this will delay launching the stream a bit and on mid-roll ads, there will be a gap in the playback. Otherwise, there is not much that can be done.

If you don't want to filter out ads and your VLC player is crashing, then you should either try to update it, check its settings (eg. try disabling GPU acceleration), use a different/better player (eg. MPV) that doesn't crash while a stream discontinuity between an ad and the regular content happens. I have answered this dozens of times already on the Streamlink issue tracker (and probably here too, as well as on several other 3rd party platforms), so there's no need for me to repeat it here another time.

**Comment by m19u31** [comment]
thanks! "Skip embedded ads" checkbox fix problem.
