### ISSUE TITLE
Zoom GUI functionality

### ISSUE THREAD

**Issue by sleepyspider1** [streamlink/streamlink-twitch-gui#771]
Some way to zoom the gui in and out would be useful so I can browse streams from far away. The text is unreadable.

**Comment by bastimeyer** [comment]
This is too much of an edge case and not worth the time spending on implementing this, as it is also tied to the window size and everything that's related to it. What you are describing is also rather a problem with the font size instead of just the overall window scaling, and making the font size variable means having to re-layout everything, not to mention that the current stylesheet setup is ancient and such a change would require to completely rewrite it as well. Not worth the effort.

You can try out Chromium's `--force-device-scale-factor=N` command line parameter which overrides the system's DPI scaling value read by Chromium/NW.js. Only integer values are supported (I believe).
