### ISSUE TITLE
Failed to load plugin dplay

### ISSUE THREAD

**Issue by Marsinator** [streamlink/streamlink-twitch-gui#781]
## Bug report
 [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
 [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 

**Streamlink Twitch GUI version:**  
v1.11.0

**Streamlink version:**  
2.0.0

**Configuration details:**  
 probably unimportant, it worked before, I did not change anything

### Description

When trying to open a stream, only the chat opens, not the stream itself (via vlc). It used to work fine until yesterday

### Expected / Actual behavior

VLC opening and playing the stream I selected

### Reproduction steps

Try starting a stream via streamlink gui using the versions and OS mentioned above.

1. open streamlink gui
2. go to followed streams
3. open an entry (for me it was twitch.tv/shurjoka)

### Log output

Somehow the log parameter did not create a log file. I was able to pull the following from streamlink gui itself, hope this helps

```
Failed to load plugin dplay from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 423, in load_plugins
mod = load_module(module_name, path)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 25, in load_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\dplay.py", line 6, in <module>
from streamlink.compat import quote
ImportError: cannot import name 'quote' from 'streamlink.compat' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\compat.py)
Found matching plugin twitch for URL twitch.tv/shurjoka
```

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/7913458/109675679-4a6ecf00-7b78-11eb-826d-4b11c1357523.png)

**Comment by bastimeyer** [comment]
Wrong repo. Your Streamlink install is messed up with an invalid plugin file, namely dplay. This plugin is trying to import something which doesn't exist anymore in the latest Streamlink version.

This is however an unrelated issue and **not a problem of Streamlink Twitch GUI, as it is just a launcher for Streamlink.**

**Fully uninstall Streamlink and re-install it.**

----

To give you a bit more detail about the issue:

The dplay plugin got removed between Streamlink 0.14.2 (2018-06-29) and Streamlink 1.0.0 (2019-01-30) via streamlink/streamlink@2eb54a3.

The Streamlink installer for Windows always deletes old plugin files which were removed from Streamlink's master branch if you're re-installing Streamlink without removing it first, so that bad plugins don't cause any issues. For some reason though, this plugin is not part of the removed-plugins list, so the installer doesn't know that it needs to delete it.

This is the same error reported on the Streamlink repo a couple of months ago, but the author of that thread wasn't particularly helpful:
https://github.com/streamlink/streamlink/issues/3291
