### ISSUE TITLE
Clicking on notifications in the Action Center does nothing

### ISSUE THREAD

**Issue by 0xf0f** [streamlink/streamlink-twitch-gui#782]
## Bug report

- [x] This is a bug report and I have read the contribution guidelines.

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.

### Environment details

**Operating system and version:**  Windows 10 20H2 build 19042.804

**Streamlink Twitch GUI version:**  1.11.0

**Streamlink version:**  2.0.0

### Description

In the Notifications settings tab of the app, 'Notification Click' is set to 'Open Stream'.
Clicking on a notification as it pops up on screen works correctly and the stream opens.
However, clicking on a notification inside the Action Center does nothing.

### Expected / Actual behavior

Expected: For the action selected in settings to be executed when the notification is clicked in the Action Center i.e. the stream opens.
Actual: Nothing happens.

### Reproduction steps

1. Wait for a notification from streamlink-twitch-gui to show up.
2. Don't click on it yet, let it disappear.
3. Open the action center and click on the notification there.

### Log output
(Note the lack of debug output for Notification Click)

```
[2021-03-03T05:11:57.816Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2021-03-03T05:14:01.514Z][debug][NotificationService]
Showing notification
{
    "provider": "auto",
    "current": "snoretoast",
    "data": {
        "title": "Ottomated has started streaming",
        "message": "just a chill coding stream, nothing weird going on here",
        "icon": "C:\\Users\\admin\\AppData\\Local\\Temp\\streamlink-twitch-gui\\cache\\icons\\b8e9e828-e391-4db8-8f0d-ab217e53f3bb-profile_image-300x300.png",
        "settings": 2
    }
}
```

### Additional comments, screenshots, etc.
![image](https://user-images.githubusercontent.com/43546760/109757203-30072500-7c4e-11eb-8d9f-ce41043f5979.png)

**Comment by bastimeyer** [comment]
This should be fixed now on the [`snoretoast-0.7.0`](https://github.com/streamlink/streamlink-twitch-gui/compare/snoretoast-0.7.0) branch. Unless I find any other issues, it'll be merged into `master` later today or tomorrow. After that, the next nightly debug build will include these changes. If you want to test it right now and don't want to wait, please see the build guide in CONTRIBUTING.md.

The upgrade from snoretoast `0.5.2` to `0.7.0` required a couple of rewrites, as it unexpectedly broke its interface (there should've been a major version bump).

As you can read in the commit message of the last commit (440731dd1da8e469d7da7221db13fb8b9945bc5e), launching streams from the notification center won't be possible for now if Streamlink Twitch GUI is not running, as it would require implementing a workaround for the missing feature in snoretoast 0.7.0, because application launch parameters can't be set. I don't think though that this is a big issue, as old notifications don't reflect the current live-status of the channels anyway and those channels could already be offline when clicking the notification, so just opening Streamlink Twitch GUI without launching the streams is good enough.
