### ISSUE TITLE
Support for features in a profile's tabs

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#784]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Support for respectively the About, schedule and VODs tabs as you can see them on Twitch.
I know that for the specific VOD case, #81 exists, so it's just mentioned here alongside the others. I can't tell about API support, but I would guess the About page would be the easier to get, as it should only be displaying the HTML as is with the different texts, images and links. Schedule might needs more work if it's even available.

This would improve Twitch GUI alongside other things as a full drop-in replacement to the website.

**Comment by bastimeyer** [comment]
None of this is available on the public Twitch APIs, neither kraken, nor helix (which isn't even implemented here yet).
- kraken: https://dev.twitch.tv/docs/v5
- helix: https://dev.twitch.tv/docs/api/reference

The "About" content on a channel on Twitch.tv, aka "channel panels", was already used here and had to be removed in #684, as it was accessing the old private API, which is now gone. VOD content doesn't make any sense as long as VODs are not supported.

The API that's being used on their website is GraphQL based and can't be used here without additional data adapters and serializers, which I don't plan to implement. Not to mention that it's their private API which requires using their own client-id, it is undocumented, and it is by definition not stable and thus not suited for being used in an application like this, as it can change any time. I also don't want to risk my legitimate client-id to be banned because of implementations which "reverse engineer" their website, which is against the ToS.

If you want these kinds of features in 3rd party applications, then ask Twitch to add them to their public APIs. They won't do it though and your request will get buried between the hundreds of other requests, because they don't care.

Closing, as it's not possible at the moment.
