### ISSUE TITLE
Can't play streams on Ubuntu using video players installed as snap apps

### ISSUE THREAD

**Issue by terzag** [streamlink/streamlink-twitch-gui#785]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Ubuntu 20.10

**Streamlink Twitch GUI version:**  

Streamlink Twitch GUI v1.11.0

**Streamlink version:**  

Streamlink 2.0.0

**Configuration details:**  

Streamlink Twitch GUI is installed as an AppImage. Streamlink is a deb from WebUpd8's PPA. VLC is installed as a snap (because of issues on my system with the current deb version from the Ubuntu repos).

### Description

Starting a stream doesn't work, VLC ends with an error "Failed to start player: /snap/bin/vlc (Process exited prematurely)".

### Expected / Actual behavior

Starting a stream. Streamlink Twith GUI gets the stream data (it sees the quality formats available and such) but when passing it to VLC, it doesn't play and exits immediately. The VLC window doesn't even appear. It's worth noting that when using Streamlink in command line, it works fine. It breaks only in Streamlink Twitch GUI.
I've also tried MPV, installed as a snap too, same issue and same error (with the path to MPV obviously).

### Reproduction steps

1. Install a video player like VLC as a snap from the Snap Store (be sure not to have also the deb version installed as it might be used by default, or set /snap/bin/vlc as the video player in the settings).
2. Start Streamlink Twitch GUI and simply click on a stream.

### Log output

```
[2021-03-24T19:52:06.280Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2021-03-24T19:52:08.993Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "esl_csgo",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-03-24T19:52:08.971Z",
    "stream": "31239503",
    "channel": "31239503"
}

[2021-03-24T19:52:08.999Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "",
        "params": null,
        "pythonscript": null
    }
}

[2021-03-24T19:52:09.001Z][debug][StreamingService]
Found streaming provider
{
    "exec": "/usr/bin/streamlink",
    "params": null,
    "env": null
}

[2021-03-24T19:52:09.014Z][debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/streamlink",
    "params": [
        "--version"
    ],
    "env": null
}

[2021-03-24T19:52:09.529Z][debug][StreamingService]
Validated streaming provider
{
    "version": "2.0.0"
}

[2021-03-24T19:52:09.585Z][debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/streamlink",
    "params": [
        "--twitch-disable-hosting",
        "--hls-live-edge",
        "3",
        "--hls-segment-threads",
        "1",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/esl_csgo",
        "best"
    ],
    "env": null
}

[2021-03-24T19:52:16.360Z][error][StreamingService]
Error: error: Failed to start player: 
{
    "id": "esl_csgo",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-03-24T19:52:08.971Z",
    "stream": "31239503",
    "channel": "31239503"
}

```
Unfortunately, the log doesn't seem very helpful. Note that I clicked on the stream that was featured on the front page, the issue doesn't happen only with that specific channel.

### Additional comments, screenshots, etc.

I understand that my configuration is a bit peculiar, with the player installed as a snap (though there might be more and more Ubuntu users using them) and might be a bit too specific to be looked into but well, maybe someone else encountered it and managed to find a fix.

**Comment by bastimeyer** [comment]
> Failed to start player: /snap/bin/vlc (Process exited prematurely)

Not a Streamlink Twitch GUI issue. Streamlink Twitch GUI is just a launcher for Streamlink and doesn't handle anything related to the player process. This is entirely done by Streamlink and Streamlink Twitch GUI only sets the Streamlink parameters accordingly (and also checks the selected executable paths for existence).

> ```
> Spawning process
> {
>     "exec": "/usr/bin/streamlink",
>     "params": [
>         "--twitch-disable-hosting",
>         "--hls-live-edge",
>         "3",
>         "--hls-segment-threads",
>         "1",
>         "--retry-open",
>         "1",
>         "--retry-streams",
>         "1",
>         "twitch.tv/esl_csgo",
>         "best"
>     ],
>     "env": null
> }
> ```

You have not set any custom player settings in the Twitch GUI, otherwise Streamlink's `--player` parameter would have been set here.

> It's worth noting that when using Streamlink in command line, it works fine. It breaks only in Streamlink Twitch GUI.

Then you must be doing something differently here. You can see the entire command line above.
If your player is failing for whatever reason, you can set Streamlink's [`--verbose-player`](https://streamlink.github.io/cli.html#cmdoption-verbose-player) parameter to see the player's stdout and stderr.

----

I don't have any experience with snap packages, but here's an answer from a couple of months ago regarding VLC's flatpak package:
https://github.com/streamlink/streamlink-twitch-gui/issues/761#issuecomment-727911849

**Comment by terzag** [comment]
When I ran the debug option for the report, I had not set a player in the preferences given that it seemed to find /snap/bin/vlc by itself. But setting the path to the player in the preferences triggers the same issue.

And I can confirm the same with streamlink in command line: either specifying the player (through --player) or not works in both cases. That's why I assumed the issue is with Streamlink Twitch GUI.

I've just tried to specify all the options seen in params (just in case one of them was the culprit) but still the same: works fine in command line. The error (and inability to start the stream) only happens with Streamlink Twitch GUI.

**Comment by bastimeyer** [comment]
> it seemed to find /snap/bin/vlc by itself

If `/snap/bin` is in your `PATH` env var, then Streamlink will automatically find `vlc` when no `--player` parameter was set, as it is the default player. Streamlink Twitch GUI will also automatically find it by resolving the `PATH` env var if you've selected the VLC player preset while not having set a custom path.

> And I can confirm the same with streamlink in command line: either specifying the player (through --player) or not works in both cases.

The error message you've posted is a Streamlink error, not Streamlink Twitch GUI. You have posted an execution error which occurs when the player process terminates before stream data can be written by Streamlink to the player's stdin. This is usually the case when the player runs into an issue on its own and "crashes". Since I don't use snaps, I can't tell you what's going wrong. But as I've said, you can set the `--verbose-player` Streamlink parameter to see the player's output.

The debug log output of the Twitch GUI shows you the exact list of parameters it is using when executing streamlink, so if you are seeing different results with Streamlink run from your shell and from the Twitch GUI, then there's something else going on your system which I can't tell.

According to your debug log, this is the simple streamlink call (translated into a shell command):
```bash
/usr/bin/streamlink \
  --twitch-disable-hosting \
  --hls-live-edge 3 \
  --hls-segment-threads 1 \
  --retry-open 1 \
  --retry-streams 1 \
  twitch.tv/esl_csgo \
  best
```

There shouldn't be any reason why this wouldn't work from the Twitch GUI when it's working from your command line shell. As said, it's Streamlink which is creating the player subprocess, not the Twitch GUI.

**Comment by terzag** [comment]
Oh, sorry, when you said to use --verbose-player, I thought you were talking about running Streamlink in command line and as it worked, I didn't understand why. I didn't see that there were an option to add parameters inside Streamlink Twitch GUI's settings.

So, I've tried and I get the following output:
```
Starting player: /snap/bin/vlc
cannot open path of the current working directory: Permission denied
Interrupted! Exiting...
```
And I'm wondering: given that the snap app format is sandboxed, is it possible that when Streamlink is launched from Streamlink Twitch GUI, it's done as a different user (or process id, or whatever) and doesn't have permissions to run the snap app; while when it's run from a terminal, it's done as the user id and works. Would that be somewhat coherent?

**Comment by bastimeyer** [comment]
> Permission denied

Well, that's what I assumed was the culprit here, because there are not many other possibilities.

> it's done as a different user

This depends on how you launch Streamlink Twitch GUI. You said you're using the AppImage, but all it does is mount its app-content to your system's tmpfs and run the app-executable from there. Its child processes all inherit the same user, env vars, etc, which means both streamlink (python) and the player will be run with the same user ID unless you're applying some customizations here. Just check the process's user ID and compare it.

Your problem however is probably the snap/apparmor configuration on your system. See the `dmesg` output which should log the permission errors. Like I've said, I don't use snaps and can't help you with any of that.

- https://wiki.archlinux.org/index.php/Snap
- https://wiki.archlinux.org/index.php/AppArmor

All I can suggest now is maybe try to run the Twitch GUI with the `--appimage-extract-and-run` parameter, or `--appimage-extract` and run it from `./squashfs-root/AppRun` or `./squashfs-root/usr/bin/streamlink-twitch-gui`, so that it's not run from the mounted squashfs of the appimage, which may cause these problems.
