### ISSUE TITLE
Restarting my PC pushes the version back to 1.9.0

### ISSUE THREAD

**Issue by Ferdiad** [streamlink/streamlink-twitch-gui#796]
## Bug report

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Windows 10

**Streamlink Twitch GUI version:**  

v1.11.0

**Streamlink version:**  

2.0.0

**Configuration details:**  

### Description

I've been having this issue for a while that every time my pc restarts I have to reinstall 1.11.0 as the program reverts to 1.9 every time I restart my PC.  This wouldn't be so bad but I can't watch any streams in 1.9 for some reason even if I set the paths of the python .exe or the script manually.

### Expected / Actual behavior

I expect to be able to install v1.11.0 once and not have to reinstall it every time I want to watch a stream.

### Reproduction steps

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment]
I'm sorry, but I don't know what you expect from this issue thread. This is obviously an issue with your system configuration, and I can't help you with that. There could be dozens of reasons for that behavior, and the information you've provided is very scarce.

Make sure that you have not installed multiple versions at the same time in different places / at different locations and that you are indeed running the latest version and not an older one by accident. If you're starting the GUI via a shortcut, then check where the shortcut is pointing to. And since you're using Windows, there's also the possibility of accidental filesystem rollbacks or whatnot when rebooting.
