### ISSUE TITLE
No refreshing on focus

### ISSUE THREAD

**Issue by OlMon** [streamlink/streamlink-twitch-gui#799]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Linux (5.12.3-arch1-1)

**Streamlink Twitch GUI version:**  

1.11.0+34.g64616e35

**Streamlink version:**  

2.1.1+14.g2884485

**Configuration details:**  

Refresh content is enabled

### Description

The content is not refreshed after the time it was set to. Refresh by hand is working.
This seems to be the case for the current git build. The release version has not the problem.

### Expected / Actual behavior

- Window is not in focus for (1,2,3) minutes
- Window regains focus and refreshes content automatically 
### Reproduction steps

1. Deleted all config files in ~/.config/streamlink-twitch-gui
2. Set account and the option to refresh content
3. Focused other window for x amount of minutes
4. Focused streamlink-twitch-gui
5. No refresh

### Log output

```
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": false,
    "version-check": false,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
[25349:25359:0513/114822.249474:ERROR:cert_verify_proc_builtin.cc(559)
```

### Additional comments, screenshots, etc.
Thank you very much, if I can provide any thing more let me know.

**Comment by bastimeyer** [comment]
Looks like there's another blur/focus event issue in NW.js. The NW.js version got bumped from 0.45 to 0.52 a month ago:
97717576b4e771843a376155a340439fba8253f8

I've already reported a blur event bug upstream last year, which was the reason why I was hesitant with upgrading, but I didn't see the issue when I finally upgraded last month.
nwjs/nw.js#7488

I'll take a look at it as soon as I get the time. Disabling NW2 could probably be enough for now, but I'm not sure. It's probably related to nwjs/nw.js#7648

**Comment by bastimeyer** [comment]
I had another go at this yesterday and it's indeed a problem with NW.js' `nw2` implementation, a rewrite of their JS API.

For some weird reason, the main application window's first `blur` event doesn't fire and it thus doesn't execute the callback of the `RefreshRouteMixin`, which is responsible for reloading the content. The `blur` event does only work when the application gained focus from the `focus` event first. This was the reason why I didn't notice the issue when upgrading.

Unfortunately, I haven't been able to fully reproduce the problem, so all I can do now is disable `nw2` again.

This is how the main application window is initialized:
1. it's hidden by default via the manifest/package.json file
2. global event listeners are set up on the main window for tracking its state
3. application settings get loaded, routing gets initialized and event listeners get set by the route's refresh mixin
4. routing and remaining setup finishes and the window gets shown (unless the `--tray` param was set)

Reproducing this in an empty NW.js app with the same NW.js version didn't work and all events fired correctly. This means that the issue is somewhere else, but not in the app code, as it's working fine with nw1 and older NW.js versions.

**Comment by OlMon** [comment]
Just for documentation: It works now for me.
