### ISSUE TITLE
AppImages: Missing Icon

### ISSUE THREAD

**Issue by JaxxArmstrong** [streamlink/streamlink-twitch-gui#800]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
All Linux distributions (due to being an AppImage)

**Streamlink Twitch GUI version:**  
v1.11.0

### Description

Normally a accompanying PNG icon is supplied with the AppImages. May I humbly recommend that you considering supplying it within your AppImages in the future, please.

I would also like to thank you for supplying us with AppImages to begin with. I have waited for a long time for it and it's an excellent way to circumvent version mismatches and dependancy hellscapes.

Thank you!

**Comment by bastimeyer** [comment]
The app icon and the desktop file are correctly embedded in the appimage's squashfs, both in the [appimage of the v1.11.0 release](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.11.0/build/resources/appimage/build.sh.tpl#L90-L117) and the [appimages with the rewritten build config from a couple of days ago](https://github.com/streamlink/streamlink-twitch-gui/blob/64616e3521d24917aba55054f1b397e151631daf/build/resources/appimage/build.sh#L85-L112).

In order to be able to see appimage icons in your desktop environment, you'll need a helper tool installed which can read the icon and other metadata from the appimage file.

- https://docs.appimage.org/user-guide/faq.html#question-how-can-i-integrate-appimages-with-the-system
- https://github.com/TheAssassin/AppImageLauncher

Other than packaging the appimage correctly, there's not much that can be done here.
