### ISSUE TITLE
Need help: the streamlink keep saying error 404 when trying to record a stream

### ISSUE THREAD

**Issue by No496** [streamlink/streamlink-twitch-gui#805]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
I am trying to download youtube videos, so i guess i don't need that?

**Streamlink version:**  
version 2.2.0(just updated to the latest version)

**Configuration details:**  
Python 3.8 is installed, which is recommended by the documentations I think.

### Description

As soon as i type in the typical command in cmd 
streamlink (link) best
it fails to put the stream into vlc and record it

### Expected / Actual behavior

Log: 
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=T2cKoToVJaI
error: Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=T2cKoToVJaI&el=detailpage)

### Reproduction steps

1. type in the typical command for streamlink
2. the error occur for me

### Additional comments, screenshots, etc.
![image](https://user-images.githubusercontent.com/75769501/123962863-7a25ca80-d9e4-11eb-9ae7-dd096e80f7b5.png)

**Comment by bastimeyer** [comment]
> - [x] I understand the difference between _Streamlink_ and _Streamlink Twitch GUI_.

https://github.com/streamlink/streamlink-twitch-gui#streamlink-twitch-gui

**Comment by No496** [comment]
sorry for disturbing you again, as you see, i am pretty new to this aspect, and i have a bunch of questions >.<
i wanna ask after i download the twitch gui, will i be able to download the youtube stream?
also, i keep failing to download the win64 installer of the twitch gui for some reason, is there any alternate approach to installing the twitch gui?
(last time i use streamlink i download a stream without the gui, hence this time it is causing me so much trouble, hope you can understand :)

**Comment by bastimeyer** [comment]
> **Streamlink Twitch GUI**
> A multi platform Twitch.tv browser for Streamlink
> A graphical user interface on top of the Streamlink command line interface.

----

> i wanna ask after i download the twitch gui, will i be able to download the youtube stream?

No, not even recording Twitch.tv streams is supported by Streamlink Twitch GUI.

You are looking for **Streamlink**, and not **Streamlink Twitch GUI**
https://streamlink.github.io/
https://github.com/streamlink/streamlink

However, I can already tell you that you are not using the latest Streamlink version, because otherwise you wouldn't be seeing Youtube 404 errors. Install the latest Streamlink version and check via `--version` or `--loglevel debug` whether you're indeed using the latest version and not an older one by accident.

Locking now, as this is the wrong repo / issue tracker and I won't answer any Streamlink related questions here.
