### ISSUE TITLE
Suggestion for 3rd party integration

### ISSUE THREAD

**Issue by Trung0246** [streamlink/streamlink-twitch-gui#807]
Hi, this is a suggestion is not meant for feature request.

Due to the fact that streamlink-twitch-gui only support twitch and not other platforms like youtube, I have tried to look for alternative that support youtube and seems like https://github.com/FreeTubeApp/FreeTube/issues/1397 will be a good candidate.

However I have no idea how they would implement UI to select the youtube stream quality nor they would implement the feature at all.

Any suggestion for what they could implement (like what to add in the UI) to integrate with streamlink?

**Comment by bastimeyer** [comment]
> Any suggestion for what they could implement

Not sure what this has to do with Streamlink Twitch GUI. Your questions belong on the Streamlink discussion forum, and not here, but even there it doesn't make much sense, because this is a question for downstream projects which want to integrate Streamlink. This means the answer is "Whatever they want and what is achievable with Streamlink". Anything GUI-wise, like a stream quality selection for example, needs data from the APIs provided by the site/service and not from Streamlink, because Streamlink is not built for that. It is not an API wrapper for querying stuff.

> Due to the fact that streamlink-twitch-gui only support twitch and not other platforms like youtube

When I started working on Streamlink Twitch GUI, I didn't have the intention to build a universal GUI frontend for Streamlink (Livestreamer back then). This was and is purely meant for Twitch. If you're looking for universal Streamlink frontends, there are other 3rd party solutions available.
