### ISSUE TITLE
Support for native Wayland without XWayland

### ISSUE THREAD

**Issue by AidanGG** [streamlink/streamlink-twitch-gui#827]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v1.13.0 from AUR, and also 2553.9c0aeed from AUR -git package

### Streamlink version

2.4.0 but not really relevant here

### Operating system, environment and configuration details

Arch Linux, Wayland through Sway, specifically without XWayland installed

### Description

According to https://nwjs.io/blog/v0.50.0/, I should be able to launch with
```
streamlink-twitch-gui --enable-features=UseOzonePlatform --ozone-platform=wayland
```
to get Wayland support, when I do not have XWayland installed. However, it fails to launch and I receive an error
```
[25121:25121:0922/025714.747733:ERROR:browser_main_loop.cc(1417)] Unable to open X display.
```
which suggests that some dependence on X is still occurring. Chromium and my Electron-based apps all work fine on my system. Streamlink itself works fine with MPV from the command line.

**Comment by bastimeyer** [comment]
NW.js gets bundled in the Streamlink Twitch GUI releases as-is from the pre-built NW.js releases on nwjs.io without any modification of the binaries.

According to the blog post you've linked, wayland should be supported via Chromium's new Ozone implementation which arrived with the 87.x milestone that was included in NW.js 0.50.

It's possible that the parameters don't get passed through to Chromium correctly. In the package.json file, there's a `chromium-flags` field where Chromium specific parameters can be added which NW.js doesn't touch in its own launch parameter logic.

According to a post on the NW.js issue tracker, the chromium-flags field wasn't working in an early release and needed a fix:
https://github.com/nwjs/nw.js/issues/5705#issuecomment-711101920

I'm still on X because wayland on Plasma is still rather bad, so I haven't checked wayland support yet. I'll take a look later when I get the time.

**Comment by AidanGG** [comment]
Thanks for the response. I can try to fiddle with the `chromium-args` field in streamlink-twitch-gui's `package.json`, and if that does not resolve the problem, I'll try some minimal example with NW.js' prebuilt binaries to see if I can launch anything on Wayland.

**Comment by bastimeyer** [comment]
> streamlink-twitch-gui --enable-features=UseOzonePlatform --ozone-platform=wayland

This should be working with the 2.0.0 release and upwards, similar to any other Chromium-based application. I can't add it to the `chromium-args` field of the `package.json` app manifest, because that would conflict with X11 and any other platform.

Just add `--enable-features=UseOzonePlatform --ozone-platform=wayland` to the `Exec` field of the `.desktop` launcher file, or add a wrapper launch script which adds those launch arguments.

I don't know the current status of Chromium's Ozone platform implementation, but it'll choose wayland by default at some point and the launch arguments won't be required anymore. This isn't the case though in the current 101 release of Chromium (NW.js v0.64.0) which the next Streamlink Twitch GUI release will be based on.

----

```sh
$ echo $WAYLAND_DISPLAY 
wayland-0
$ streamlink-twitch-gui --enable-features=UseOzonePlatform --ozone-platform=wayland &
$ xwininfo -name "Streamlink Twitch GUI" | grep 'xwininfo'
xwininfo: error: No window with name "Streamlink Twitch GUI" exists!
```

```sh
$ echo $WAYLAND_DISPLAY 
wayland-0
$ streamlink-twitch-gui &
$ xwininfo -name "Streamlink Twitch GUI" | grep 'xwininfo'
xwininfo: Window id: 0x1800003 "Streamlink Twitch GUI"
```
