### ISSUE TITLE
Refresh current view on stream notification.

### ISSUE THREAD

**Issue by Okxa** [streamlink/streamlink-twitch-gui#828]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

On multimonitor systems I have the window always open on followed streamer page, but without interacting with the window (or notification), it does not refresh. This hinders mu usage, as to see what streams are on.

While in #226 (and #114, #91) you said auto refresh is not desired, would it be possible to refresh the current page whenever a notification is made. That would be better on resources (and API rate limiting) rather than constantly refreshing.

Also this kind of feature makes most sense on pages like the followed streams page, so might be best limit only to some pages.

**Comment by bastimeyer** [comment]
> would it be possible to refresh the current page whenever a notification is made. That would be better on resources (and API rate limiting) rather than constantly refreshing.

That is exactly the same as auto-refreshing. The notifications are part of an API polling system which retrieves new data every minute. Refreshing the followed streams route on new desktop notifications would not only be disruptive for the user when the application is in focus, it would also waste resources when the application is not in focus, which is why I'm against auto refreshing. Not to mention that new streams will be at the bottom of the streams list anyway, as Twitch always sorts followed streams by viewer count, which means those new streams won't be visible when lots of followed streams are live at the same time, and this makes refreshing the route pointless.

A desktop notification already gives you information about which channels have come online.

**Comment by Okxa** [comment]
On my system the notification is not always visible because sometimes the active monitor has a fullscreen application. So I will miss the notification.

Thats why I would like to see the current online streams always in the window.
