### ISSUE TITLE
PROFILE ERROR OCCURRED

### ISSUE THREAD

**Issue by k566o** [streamlink/streamlink-twitch-gui#857]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

1.13

### Streamlink version

3.11

### Operating system, environment and configuration details

Windows 10

### Description

A box shows up for a split second that says
Profile error occurred
Your profile can not be used because it's from a newer version of NW.js
Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js

Streamlink Twitch GUI then loads normally, and looks to be working fine. 
When I try to stream anything I get the Launch screen, but it never loads anything, final message is "Waiting for streams, retrying every 1.0 seconds" Instead of leaving player setting on default I chose VLC, but that changed nothing.

I tried running your latest build preview version , but twitch will not allow me authorisation, nor will it use my authorisation code from this build

**Comment by bastimeyer** [comment]
You are mixing three different things here without being specific in any of them.

----

First

> Profile error occurred
> Your profile can not be used because it's from a newer version of NW.js

> I tried running your latest build preview version

The next version is based on NW.js 0.60 (Chromium 97) while the current one is based on NW.js 0.55 (Chromium 92). By running the preview build (once) and then running the normal/stable one, you are basically trying to downgrade the application's config/cache that got upgraded earlier. This is unsupported, hence this message. This shouldn't be a problem though, as the only config/cache data that gets changed on the application level are the search queries, but that's unrelated to the popup. What happens to internal NW.js (Chromium) configs should be irrelevant, despite the popup.

If you don't want to see this message again while using the current stable version, then you'll have to delete the application's user data directory. See the default paths here:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#user-data-directory

My advise is to simply ignore it, because it doesn't matter and you will have to upgrade soon anyway. As I said, the next release will be coming very soon.

----

Second

> When I try to stream anything I get the Launch screen, but it never loads anything

This has nothing to do with Streamlink Twitch GUI, because Streamlink Twitch GUI is just a launcher for Streamlink. If you're having issues with streams not launching, then this may be caused by a bad Streamlink install or a bad configuration of Streamlink, either itself or in the Twitch GUI's streaming settings menu.

Check your configuration in the Twitch GUI's settings menu and make sure that Streamlink itself is working correctly. On Windows, you'll need any release of Streamlink that's newer than 2.4.0, except 3.1.0.

Also set the Twitch GUI's `--loglevel=debug` launch parameters (for Windows users the easiest way is to do this via a desktop shortcut, etc.) and then check the output of the debug log file that gets written to your file system. This debug log includes the exact paths and parameters used for launching Streamlink.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l

Streaming setup-wise, nothing has changed between the releases. Once again, make sure that you have not misconfigured Streamlink. Otherwise, post the debug log output.

----

Third

> twitch will not allow me authorisation, nor will it use my authorisation code from this build

As you may have read in the helix API thread on the issue tracker or in the changelog of the upcoming release, both versions are based on a different API and they require different authentication permissions by Twitch. This means that you can't share the same OAuth token, the stored login secret) between these builds and you'll have to login again when switching.

If you're having issues with the login itself, aka. the user+password and confirmation prompt on Twitch's website that gets opened when logging in from Streamlink Twitch GUI, then this is not the problem of the app.

What Streamlink Twitch GUI does and needs to do is launch a local HTTP server, so that it's able to receive the authentication response from Twitch when you confirm the authentication, because Twitch will redirect you to `http://localhost:65432/` with the included auth data.

If your system has blocked this local HTTP server, eg. via some firewall rules you've applied (automatically), then of course the authentication won't be successful, because the Twitch GUI can't receive the login response from Twitch with the required OAuth token that then gets used for validating the authentication.

Make sure that you're not blocking Streamlink Twitch GUI's local HTTP server listening on TCP port 65432.

This is nothing new though and has remained the same between those releases.
