### ISSUE TITLE
Streamlink twich gui 2.0 Streamlink 2.4-3.1.1 Windows 7 cant use anymore

### ISSUE THREAD

**Issue by Rinceewind** [streamlink/streamlink-twitch-gui#870]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.0

### Streamlink version

3.1.1

### Operating system, environment and configuration details

Windows 7 x64

### Description

After last update of Streamlink Twich Gui to 2.0 we are forced to update Streamlink to at least 2.4.0.Problem is Streamlink 2.4.0 and newer need Python version3.9.6 which is not compatable with Win 7 .Is there workaround like using supporting version of python with Streamlink? Or only fix is to upgrade to Windows 8.1+

Screenshot shown errors in twich gui and if i try to run only streamlink

As of today 1.13 not working anymore.

![Screenshot_1](https://user-images.githubusercontent.com/99695287/153963641-3da80efb-8ce6-4932-a904-c1453e35a693.png)
![Screenshot_2](https://user-images.githubusercontent.com/99695287/153963644-a76701f8-990f-4287-82f1-3141b428f30f.png)
![Screenshot_3](https://user-images.githubusercontent.com/99695287/153963648-80c6b1f3-0bcf-4b18-8b04-1dbc701404d6.png)

**Comment by bastimeyer** [comment]
> Problem is Streamlink 2.4.0 and newer need Python version3.9.6 which is not compatable with Win 7

Take a look at Streamlink's documentation:

https://streamlink.github.io/install.html#windows-binaries

> The Streamlink installer for Windows is currently based on Python 3.9.
> Versions of Windows prior to 10 are not supported.
> 
> Be aware that the packages for [Chocolatey](https://chocolatey.org/packages/streamlink) and the [Windows Package Manager](https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Streamlink/Streamlink) are just wrappers around the stable installer and thus depend on Windows 10+ as well.
> 
> **Alternatively, [Streamlink can be installed via python-pip](https://streamlink.github.io/install.html#pypi-package-and-source-code) in a [compatible Python environment](https://streamlink.github.io/install.html#dependencies).**

**Comment by Rinceewind** [comment]
> The Streamlink installer for Windows is currently based on Python 3.9.
> Versions of Windows prior to 10 are not supported.

You basicly telling me only fix is to install Windows 10 ?  If i try to use [this](https://github.com/nalexandru/api-ms-win-core-path-HACK) with Python3.9.6 no error from screenshot 3 instead i have Python stop working msg.

> Alternatively, [Streamlink can be installed via python-pip](https://streamlink.github.io/install.html#pypi-package-and-source-code) in a [compatible Python environment](https://streamlink.github.io/install.html#dependencies).

I can install different version of python ,but problem is if i try to use it i got error from screenshot 1 :)

1.13 start to work again so i ll stick with it
Thanks

**Comment by bastimeyer** [comment]
> You basicly telling me only fix is to install Windows 10

You are using an outdated operating system which is not supported by Python 3.9.

Streamlink's Windows installer, which bundles Python 3.9, does not work on Windows versions prior to 10. It has to bundle at least Python 3.9 because 3.8 does not "receive updates anymore which the installer can use". More/better details here:
https://github.com/streamlink/streamlink/pull/3918#issue-972813843

Streamlink 3.1.1 however supports Python from version 3.6 till 3.10, and older releases of Python 3.8 can still be installed on Windows 7. If you install Python 3.8 and then install Streamlink in this local Python environment, then it'll still work on Windows 7.

How you can do that via `pip` is all described in Streamlink's documentation. Make sure that you uninstall any other Streamlink versions first. Good luck.

----

Streamlink Twitch GUI v1.13.0 will stop working at the end of February, as you can read in the 2.0.0 changelog and in #849.
https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v2.0.0

The reason why v1.13.0 wasn't working today is because Twitch is already phasing out support for the old kraken API in incremental steps. This was the third step today which lasted 4 hours.
https://github.com/streamlink/streamlink-twitch-gui/issues/849#issuecomment-1034134200

And btw, Chromium (and thus NW.js too) has had its Windows 7 phase-out already in June 2021, but it got extended for a bit by Google. I will always use the latest available NW.js release here when publishing new versions of Streamlink Twitch GUI, so there is no guarantee that future releases will keep working on Windows 7.

Upgrade or change your OS.

**Comment by Rinceewind** [comment]
I succeeded . Installed Streamlink 3.1.1 with Python 3.6.Small notes if someone else need 2 things i needed to do. Upgrade Pip and take ownership of Python36 folder in AppData\Local,than set Twich Gui like this

![Screenshot_2](https://user-images.githubusercontent.com/99695287/153987647-3cf17796-6caa-49d0-af90-39856ea8854a.png)

> I will always use the latest available NW.js release here when publishing new versions of Streamlink Twitch GUI, so there is no guarantee that future releases will keep working on Windows 7.
> 
> Upgrade or change your OS

I just cant force myself to install Win 10 :).Using Twich Gui for so many years.First Livestreamer,now Streamlink.Thanks for this marvelous project. I will be so sad when i will not be able to use it on Win 7,but i have Mint in Dual bot at least ;)

Thanks for your time and patience.
