### ISSUE TITLE
"exit code 3221225781" after updating to latest Streamlink/GUI versions on Windows 7

### ISSUE THREAD

**Issue by haebawari** [streamlink/streamlink-twitch-gui#874]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.0.0

### Streamlink version

3.1.1

### Operating system, environment and configuration details

Windows 7

### Description

Was prompted to update to newest Streamlink/Streamlink Twitch GUI versions after I wasn't able to log in.
However now the streams won't open with the error "exit code 3221225781".
I'm aware about the dropped support for Windows 7 on latest Python versions, however #860 seemed to be able to run 2.0.0 and 3.1.1 on Windows 7.

Is the support for Windows 7 dropped completely, or is there still some way to use Streamlink/GUI on it?

**Comment by bastimeyer** [comment]
Not a Streamlink Twitch GUI issue.

Your problem is with Streamlink's Windows installer, which isn't compatible with Windows 7, as it bundles Python 3.9.
Streamlink 3.1.1 still supports Python versions down to 3.6, so you're running Windows 7, you'll have to install Python 3.8 (the last Python version that supports Windows 7) and install Streamlink via python-pip in this environment.

https://streamlink.github.io/install.html#windows-binaries
https://streamlink.github.io/install.html#pypi-package-and-source-code

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/870#issuecomment-1039708275

**Comment by haebawari** [comment]
managed to make it work, thank you!
