### ISSUE TITLE
Support for the Steam Deck (in Gaming Mode)

### ISSUE THREAD

**Issue by Jakyrian** [streamlink/streamlink-twitch-gui#882]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Any chance we could get support for the Steam Deck? It's currently unable to open a stream in "gaming mode", but works fine in the Steam Deck's "desktop mode". In gaming mode, the only visible error is: "Invalid version check output".

This is reproducible on a standard Linux PC, so I believe fixing it there should make it work on the Steam Deck too (in the gaming mode). Steps to reproduce are as following:

1) Add non-steam game to steam, select /usr/bin/streamlink-twitch-gui
2) Run streamlink-twitch-gui from the Steam library view and attempt to play a stream

**Comment by bastimeyer** [comment]
> Any chance we could get support for the Steam Deck?

Sure, if you buy me a Steam Deck, I will make sure that there's official Steam Deck support...

> the only visible error is: "Invalid version check output"

This error message gets shown if Streamlink Twitch GUI can't validate the `stdout` output of the Streamlink executable when checking its version string via the `--version` launch parameter:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#unexpected-version-check-output-error

This is usually caused by error messages printed by Streamlink if its install is broken (eg. a Python stack trace output of broken imports) or if it's misconfigured (eg. invalid Streamlink config file format/values).

Make sure that Streamlink itself is working fine when you execute it from the command line shell and make sure that you have set the correct executable path in the Twitch GUI's settings menu.

I've talked about a dozen of times already over the past years here on this issue tracker that I will see if I can improve the error message output, but I could never be bothered spending time on this, so you'll have to check this yourself. Streamlink Twitch GUI is just a launcher, and if the application that is supposed to get launched by the launcher is returning errors can can't get started, then this needs to be debugged in that application, not the launcher. If you set the `--loglevel=debug` parameter when starting Streamlink Twitch GUI, it'll log how it's invoking the streamlink executable.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#streamlink-twitch-gui-parameters

> Run streamlink-twitch-gui from the Steam library view and attempt to play a stream

Since I don't own a Steam Deck and won't be installing SteamOS 3.0 in a VM for this (is it even out yet apart from the rescue ISO?), one advice I can give is checking whether Steam overrides shared system library imports in its "library view" by setting the [`LD_LIBRARY_PATH` or `LD_PRELOAD` env vars](https://man.archlinux.org/man/ld.so.8#Environment_variables) which break loading the Python executable or any other dependencies.

Other than that, try the AppImages of Streamlink and Streamlink Twitch GUI if you haven't already. They should work independently of the system libraries.
- https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation#appimage
- https://streamlink.github.io/install.html#appimages

**Comment by Jakyrian** [comment]
> This error message gets shown if Streamlink Twitch GUI can't validate the `stdout` output of the Streamlink executable when checking its version string via the `--version` launch parameter: https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#unexpected-version-check-output-error
>
I know that streamlink is working fine as running "streamlink --version" returns the expected value (in desktop mode). However when running the konsole in gaming mode (added to steam as a non-steam game), the result is different - which I imagine is what is causing the streamlink-twitch-gui "invalid version check output" error:

```
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
streamlink 2.4.0
pid 3656 != 3582, skipping destruction (fork without exec?)
```

> If you set the --loglevel=debug parameter when starting Streamlink Twitch GUI, it'll log how it's invoking the streamlink executable.
>
Attempted this as well, see below:
```
[2022-03-27T17:33:55.818Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": false,
    "version-check": false,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2022-03-27T17:34:00.709Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "71092938",
    "quality": "source",
    "low_latency": true,
    "disable_ads": true,
    "chat_open": false,
    "started": "2022-03-27T17:34:00.669Z",
    "stream": "71092938",
    "user": "71092938"
}

[2022-03-27T17:34:00.722Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "",
        "params": "",
        "pythonscript": null
    }
}

[2022-03-27T17:34:00.734Z][debug][StreamingService]
Found streaming provider
{
    "exec": "/usr/bin/streamlink",
    "params": null,
    "env": null
}

[2022-03-27T17:34:00.756Z][debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/streamlink",
    "params": [
        "--version"
    ],
    "env": null
}

[2022-03-27T17:34:00.784Z][error][StreamingService]
Error: Invalid version check output
{
    "id": "71092938",
    "quality": "source",
    "low_latency": true,
    "disable_ads": true,
    "chat_open": false,
    "started": "2022-03-27T17:34:00.669Z",
    "stream": "71092938",
    "user": "71092938"
}
```

Regarding the following:
> Since I don't own a Steam Deck and won't be installing SteamOS 3.0 in a VM for this (is it even out yet apart from the rescue ISO?)
>
I was actually referring to my desktop PC (which is running Arch Linux and not SteamOS 3.0). It seems the issue is related to running it as a non-steam application through Steam, as the issue is not isolated to the Steam Deck.

> Other than that, try the AppImages of Streamlink and Streamlink Twitch GUI if you haven't already. They should work independently of the system libraries.
>
Tried both AppImages and specified them in streamlink-twitch-gui (to no avail), but I'm pretty confident that "ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored." is the root cause here of the "invalid version check output" error.

**Comment by bastimeyer** [comment]
> ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

Steam adds the `LD_PRELOAD` env var when launching games/applications via its interface, because it tries to inject the i686 and amd64 versions of its game overlay library. When loading an amd64 game/application, this results in an error message being printed to `stderr` by the linker due to the i686 library version mismatch, and the same happens when trying to load an i686 game/application while trying to inject an amd64 library. Steam does it this way, because it usually doesn't cause any issue with games and the linker simply rejects any invalid libraries.

The `stderr` message however is a problem for Streamlink Twitch GUI, because it is very strict with its version string parsing. The `LD_PRELOAD` env var gets inherited by the spawned streamlink child process, where it emits this error message. Users can choose any executable they want as Streamlink provider in the Twitch GUI's streaming settings menu, so validating the version string output very strictly and stopping on any kind of error or unexpected output as early as possible is necessary.

To overcome this, try launching either Streamlink or Streamlink Twitch GUI via a wrapper shell script where `LD_PRELOAD` gets unset and where all input parameters get passed through accordingly.

`wrapper.sh`
```sh
#!/usr/bin/env bash
export LD_PRELOAD=
"$@"
```

Then launch it this way (don't forget to `chmod +x wrapper.sh` first):
```sh
/path/to/wrapper.sh "/path/to/executable" any additional arguments "1 2 3"
```

That should work, I have tested this on my system. Make sure to change the drop-down in Steam to "any application" when selecting the wrapper shell script, instead of filtering for `.desktop` files.

**Comment by Jakyrian** [comment]
That was super helpful, thank you! I didn't know you could override the LD_PRELOAD variable.

With that in mind, it's actually even easier to get working. I re-added /usr/bin/streamlink-twitch-gui as a non-steam game to Steam, and in the properties I set its launch option to:

`LD_PRELOAD="" %command%`

In combination with streamlink-twitch-gui's `Settings -> GUI -> Minimize GUI -> Move to tray` option, it now works flawlessly in the Steam Deck's gaming mode. Thanks for your help once again, it's much appreciated.
