### ISSUE TITLE
Appimage not opening application on doubleclick + issues shown on terminal

### ISSUE THREAD

**Issue by stortzm** [streamlink/streamlink-twitch-gui#890]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

streamlink-twitch-gui-v2.1.0-x86_64.AppImage

### Operating system, environment and configuration details

Ubuntu 20.04.4 LTS

### Description

even after setting chmod +x for the Appimage file + letting it be executed in proprieties, double clicking it does not open the newest version ( 2.1.0 ). Neither does right click > Open. 

the Appimage can still be opened successfully and the program works fine, through the terminal. However, seems like an issue is occuring:

`>[0526/100711.382835:ERROR:zip_reader.cc(132)] Cannot open ZIP from file handle 4
[0526/100711.388095:ERROR:zip.cc(202)] Cannot open ZIP from file handle 4
[9435:9435:0526/100712.229511:ERROR:gl_angle_util_vulkan.cc(17)] Failed to retrieve EGLDisplay
[9435:9435:0526/100712.229555:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
[9435:9435:0526/100712.434635:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[9438:9448:0526/100713.719680:ERROR:cert_verify_proc_builtin.cc(603)] No net_fetcher for performing AIA chasing.
[9438:9447:0526/100714.764189:ERROR:cert_verify_proc_builtin.cc(603)] No net_fetcher for performing AIA chasing.
`

![image](https://user-images.githubusercontent.com/22046129/170493902-84c9dcf4-811e-477d-b3bb-78f792574e7a.png)

could this be related to the Appimage not executing without terminal command? 
So far, this issue has not incurred any problems in the application itself, if you can call it an issue; More of an annoyance to be unable to just double click to open the program. 

Let me know if I can provide further information.

**Comment by bastimeyer** [comment]
I can't reproduce this in a completely fresh Ubuntu 22.04 VM after installing fuse, which is the only requirement for launching appimages. Since you're able to launch the appimage from the shell, this suggests that fuse is installed on your system.

Streamlink Twitch GUI is a singleton process application, which means it can only run once at the same time on your system. Make sure that no other processes of the app are still running when trying to open the appimage.

Also check that no other application (eg. your file browser (nautilus), appimagelauncher, etc) is not doing something that could intercept the launch of the appimage. Appimagelauncher for example installs bin-format hooks to `/usr/lib/binfmt.d/`, which tells the system to use appimagelauncher as the interpreter for the appimage file format, so it can be used as a wrapper to manage the appimages.
https://manpages.debian.org/testing/systemd/binfmt.d.5.en.html

The error messages you've posted are coming from NW.js and Chromium, the platform Streamlink Twitch GUI is built on, and they can be ignored, as they are irrelevant.

**Comment by stortzm** [comment]
> The error messages you've posted are coming from NW.js and Chromium, the platform Streamlink Twitch GUI is built on, and they can be ignored, as they are irrelevant.

noted.
the program still functions fine, I was worried it might be something relevant so I still posted it
