### ISSUE TITLE
Dependency warnings during compilation

### ISSUE THREAD

**Issue by toby63** [streamlink/streamlink-twitch-gui#899]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.1.0

### Streamlink version

4.1.0

### Operating system, environment and configuration details

Manjaro Linux
I use the package from AUR: https://aur.archlinux.org/packages/streamlink-twitch-gui
Streamlink is from Manjaro Repos.

### Description

During compilation I get a few dependency warnings, see below.

### Debug log

```text
[2/5] Resolving packages...
warning Resolution field "qunit@2.17.2" is incompatible with requested version "qunit@~2.6.0"
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > inject-loader@4.0.1" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "node-fetch > fetch-blob@2.1.1" has unmet peer dependency "domexception@^2.0.1".
```

**Comment by bastimeyer** [comment]
This is intentional because of custom dependency resolutions and other reasons. The messages can be safely ignored. Whenever dependencies get updated here, I am careful about breaking changes and incompatibilities. This isn't just a careless mistake because of negligence.

> "qunit@2.17.2" is incompatible with requested version "qunit@~2.6.0"

This is because of the currently used ember-qunit version which depends on qunit 2.6.x instead of 2.x for no reason, so it gets overridden here, so a more recent version can be used.

> warning " > inject-loader@4.0.1" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".

The inject-loader is a discontinued project, but it's still widely used in the tests, so it can't be removed without rewriting lots of tests. It's compatible with webpack 5, even though it doesn't advertise it.

> warning "node-fetch > fetch-blob@2.1.1" has unmet peer dependency "domexception@^2.0.1".

node-fetch is used for deploying release assets to GitHub releases, and domexception is not needed for that.
