### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by abyssis** [streamlink/streamlink-twitch-gui#9]
Hello,

Do you think it'd be possible to implement the chat directly from Twitch?Keep it up!

**Comment by esdf** [comment]
would be nice if app had irc embedded

**Comment by mawekuwe** [comment]
if is not possible to popup the chat for every plateform, can you add a field to change the defaut command line to open the chat? I would like to open the chat as popup with the following command:
`chrome.exe --chrome-frame --app="http://www.twitch.tv/{channel}/chat"`

**Comment by bastimeyer** [comment]
> I would like to open the chat as popup with the following command

This can only be a temporary solution, as the internal IRC client should be the main goal. I also don't know if it's worth the time implementing something like this, just for getting rid of the address and bookmarks bar of your browser.

I've already had custom chat opening methods in mind though, when I was working on the Chatty integration. But it has to be a little bit better than a simple command line. My idea right now would be a dropdown with supported browsers (chromium based, firefox, msie, and a custom command line as well) and a file-select field for the executable (like the livestreamer file-select with fallback paths), so that parameters don't need to be used.

I've done a little bit of research and found these parameters/methods for the following browsers:

- Chromium
  `chromium --app=http://twitch.tv/CHANNEL/chat`

- Firefox
  `firefox -chrome http://twitch.tv/CHANNEL/chat`

- MSIE
  `cscript msie-no-toolbars.vbs http://twitch.tv/CHANNEL/chat`
  ```vbs
Dim objIENoToolbars 
Set objIENoToolbars = WScript.CreateObject("InternetExplorer.Application") 
ObjIENoToolbars.Toolbar = false 
objIENoToolbars.Navigate WScript.Arguments.Item(0)
objIENoToolbars.Visible = true
  ```

I haven't found anything about Edge, Safari and Opera, and I don't know if it's even possible in those browsers. I also think that all this is just a big overkill, but whatever...

**Comment by mawekuwe** [comment]
I do not think to cover most web browsers is the answer because many do not support. Just put a field to change the default web browser for those who know what to do like for the video player would be great.

I also tried `firefox -chrome http://twitch.tv/CHANNEL/chat` for 2 different versions and does not work here.

**Comment by bastimeyer** [comment]
See #132

**Comment by mawekuwe** [comment]
Great! Thank you very much :+1:

**Comment by mtaki14** [comment]
Why am i included in these emails? Can you please remove me from your list or
point out to me how to do it myself?

Thanks for understanding

On Mon, Aug 31, 2015 at 8:03 pm, Olympia Mckee < notifications@github.com [notifications@github.com] > wrote:
Great! Thank you very much:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/bastimeyer/livestreamer-twitch-gui/issues/9#issuecomment-136468366] .[https://github.com/notifications/beacon/AHng5tp-u4tJmOpVceT8beTXoSDLi3Frks5otJycgaJpZM4CBiR8.gif]

**Comment by skulblakka** [comment]
>Can you please remove me from your list or point out to me how to do it myself?

Hit the "view directly on GitHub" at the bottom of the mail. Then click "Unsubscribe" on the right.

**Comment by bastimeyer** [comment]
> Why am i included in these emails? Can you please remove me from your list or
> point out to me how to do it myself?

Just change your github notification settings (in the "Participating" section) or click the **unsubscribe** button at the top of the thread.

I'm going to remove my and your post then, as you'll receive the mail with my answer...
Sorry to the other guys, receiving this noisy mails...

**Comment by bastimeyer** [comment]
Closing the thread, since a chat button and configuration for external apps has been added a long time ago. The next release 1.4.0 will include a rewritten chat configuration, similar to the player selection.

An internal IRC client is still very far off, but maybe (hopefully) it will happen at some point in the future. For anybody further interested, I have added a project to the list:
https://github.com/streamlink/streamlink-twitch-gui/projects
