### ISSUE TITLE
Quality does not match selection

### ISSUE THREAD

**Issue by cqmpact** [streamlink/streamlink-twitch-gui#906]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.0.0

### Streamlink version

3.2.0

### Operating system, environment and configuration details

Windows 10 Pro x64

HLS LIve Edge: 1
Stream segment threads: 2
Player: MPV (choco install)
No player cache is on.
Preferred quality: was high, set to source, still same.

### Description

The quality is always low no matter what settings I use.
I put it on high, it still looks like crap.
I put it to source, it still looks like crap.
It's so bad I can barely tell what's going on the screen sometimes.
Just look at the pixelated background and the cam, it's awful.
 
https://i.imgur.com/h8D3efe.png

https://i.imgur.com/SHBzP3C.png

This happens on all streams that I watch.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
```

**Comment by bastimeyer** [comment]
> ### Streamlink Twitch GUI version
> v2.0.0
> 
> ### Streamlink version
> 3.2.0

Both are outdated. Install the latest versions of Streamlink and Streamlink Twitch GUI.

> ```
> [cli][debug] Arguments:
> [cli][debug]  --loglevel=debug
> [cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
> ```

The debug log you've posted does not contain enough useful information. **Post the entire log.**

In the Twitch GUI, check that you have not modified any quality presets in the "Streams" settings menu (advanced settings need to be enabled for it to be shown), and make sure that you have not overridden the default quality in a specific channel (custom channel settings). Also check whether you have a [Streamlink config file](https://streamlink.github.io/cli/config.html) (which you shouldn't be using when using the Twitch GUI) where you are overriding the stream quality selection.

Otherwise, the stream weights of Streamlink's Twitch plugin are working fine and Streamlink Twitch GUI correctly sets the stream quality of the "Source", "High", "Medium", "Low" and "Audio only" quality presets.

**Comment by cqmpact** [comment]
Hello and thank you for your reply.

I updated the application and the quality is crystal clear now. 
I did not have a config file and I did not modify quality presets.
