### ISSUE TITLE
Add in channel settings a switch to activate audio compressor

### ISSUE THREAD

**Issue by KaMyKaSii** [streamlink/streamlink-twitch-gui#917]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Some streamers (few but there are) don't really care about the audio quality of their stream and don't proper setup audio settings in the streaming program. This means that the viewer is usually forced to turn the volume up to maximum to be able to hear the streamer satisfactorily most of the time but when the streamer screams for some reason it is extremely uncomfortable for the viewer. I wish you could add an option (that pass the needed parameter to the player) so the user can manually fix this for these specific streamers. For mpv the parameter is `--af=lavfi=acompressor` and VLC apparently needs multiple parameters so I ended up not testing it.
Thank you so much for your time and great work!

**Comment by bastimeyer** [comment]
This is way too specific for a new channel settings option. If anything, it would only make sense adding an option for custom player launch arguments. However, since player settings depend on the selected player preset and since all player options are nested Ember data model fragments based on JSON data declared externally, this makes the implementation way too difficult and cumbersome. I don't see the benefits outweighing the efforts.

Just add a hotkey to your MPV config that toggles the audio normalization/compression:
https://github.com/mpv-player/mpv/issues/3979
