### ISSUE TITLE
appimage 32bit not booting

### ISSUE THREAD

**Issue by Littlemac123** [streamlink/streamlink-twitch-gui#922]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.2.0 i686

### Streamlink version

2.0.0

### Operating system, environment and configuration details

Linuxmint Debian edition 32bit based on debian 11

### Description

its not booting

### Debug log

```text
mac_xp@presaric2800tcompaq:~/Downloads$ ./streamlink-twitch-gui-v2.2.0-i686.AppImage 
/tmp/.mount_streamAi1r0b/AppRun: line 4:  2322 Illegal instruction     (core dumped) "${HERE}/usr/bin/streamlink-twitch-gui" "${@}"
```

**Comment by bastimeyer** [comment]
The AppImage is working perfectly fine in a freshly set up Debian 11 i386 virtual machine. I have just tested and verified it.

The information which you have provided so far is nowhere near enough to help you in any way. Which CPU are you using? "Illegal instruction" implies that your CPU doesn't support some features of the i386 instruction set which NW.js/Chromium is using, so you won't be able to run Streamlink Twitch GUI, as your CPU is simply too old.

Streamlink Twitch GUI uses pre-built NW.js binaries, built by the NW.js developers:
https://nwjs.io/

Since you're able to mount the AppImage (according to your log ouput), try extracting its contents by setting `--appimage-extract` as the AppImage's launch argument. Then you'll find the contents in the `squashfs-root` directory that's created in the current directory, and you can continue debugging from there. The main executable is `AppRun`, which is a BASH wrapper script which launches the Streamlink Twitch GUI executable (NW.js / Chromium).
