### ISSUE TITLE
Twitch.tv Commercial break in progress

### ISSUE THREAD

**Issue by lextra2** [streamlink/streamlink-twitch-gui#923]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.2.0

### Streamlink version

5.0.1-1

### Operating system, environment and configuration details

Windows 10 21H1

### Description

This ad banner is shown when ads are played. This issue started to happen today. Before, no ads or ad banner was shown. I know it will probably be fixed shortly, but I wanted to mention it anyways.

![mpv-shot0001](https://user-images.githubusercontent.com/20690384/201005332-ae40db88-b293-4df8-8b60-1bb4fdf7cde9.png)

**Comment by Urbinholt** [comment]
Same (almost) issue here. At around 22:00 UTC streamlink-cli (4.2.0, tried updating to 5.0.1 with no luck) stopped fetching twitch streams and is showing only short video which says "Preparing your stream..." and some bs about hamsters running their servers (which seems to be true).
![vlc_MNsdYZ7lKS](https://user-images.githubusercontent.com/20501228/201018577-c2cd11e9-9ce5-48da-b9e5-45949717675b.png)
Enabling "twitch-no-ads", changing quality and stream itself did not help.

**Comment by bastimeyer** [comment]
Wrong issue tracker. Streamlink Twitch GUI is just a launcher for Streamlink and is totally unrelated to anything streaming related. This is done by Streamlink. Make sure that you have enabled the "Skip advertisements" checkbox in the Twitch GUI's streaming settings menu, which will set the [`--twitch-disable-ads`](https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads) CLI parameter when launching streams. This is working fine for pre-roll ads, but apparently there are new issues for mid-roll ads, which needs to be looked into and which is a bit tricky to debug.

Please follow the threads on the Streamlink issue tracker instead and be patient, we are already aware of this.
https://github.com/streamlink/streamlink/issues

Instead of closing this one, I'll lock it and keep it open, in order to avoid unnecessary duplicates from people who don't look for closed threads.

----

- https://streamlink.github.io/cli/plugins/twitch.html
- https://github.com/streamlink/streamlink-twitch-gui/wiki/Embedded-ads

**Comment by bastimeyer** [comment]
I've updated the stickied thread that was already there since a few years. Forgot about that when writing the answer. Closing this one now. Also removed the embedded ads page from the wiki, as it's redundant and unnecessary maintenance work for me.

https://github.com/streamlink/streamlink-twitch-gui/issues/754
