### ISSUE TITLE
Support for team pages

### ISSUE THREAD

**Issue by Poorchop** [streamlink/streamlink-twitch-gui#93]
Last time I checked about a year or so ago, the twitch API didn't support team pages, and the actual team API was very poor. I'm not sure if anything has changed in this regard, but I would love to be able to see team pages from within this program. Currently, I have to open a web browser to view team pages and then get the name of the streamer that I want to watch.
###### Example team pages:
- http://www.twitch.tv/team/srl
- http://www.twitch.tv/team/sda
- http://www.twitch.tv/team/fgcpros

**Comment by bastimeyer** [comment]
Yes, team pages are already on my 2do list and will be implemented at some time in the near future.

The one issue I'm having with teams is, that browsing for teams doesn't work well. You're able to retrieve a list of teams from the API, but these teams are ordered by their ID, which makes it pretty much useless. And searching for teams is not possible as far as I know, so the only option you have is adding team links to channel profiles. But accessing multiple teams with this method is a bit painful, though. In your browser it's different, since you're having bookmarks for visiting the team pages, so I really don't know if team pages are really worth being implemented (yet).

**Comment by Poorchop** [comment]
I took a look at the teams API again and you have a point about the IDs. I also just noticed that the team object contains only a bunch of useless information like the logo and banner. As far as I can tell, there is no way to get a list of currently live streams for that team, which is the main point of team pages. I think I should open up an issue with twitch or see if there is already an open issue regarding this.

**Comment by bastimeyer** [comment]
The v5 API now supports `/teams/:team` requests which contain a list of users of that team. This means that team pages can be implemented once the switch to v5 has been completed.

**Comment by bastimeyer** [comment]
The TeamIndexRoute currently still has a bug and doesn't retrieve the correct stream records when scrolling. The API doesn't support requesting broadcasting team members, so a rather messy solution is needed here. I just wanted to merge this now, but this will be fixed before the next release, so that there are no duplicates in the infinite scroll list.
