### ISSUE TITLE
Incompatibility with game Hue

### ISSUE THREAD

**Issue by braiam** [streamlink/streamlink-twitch-gui#964]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.2.0

### Streamlink version

5.2.1

### Operating system, environment and configuration details

Debian Testing.

### Description

Trying to open Hue at the same time that stg, Hue can't open with:

```
Player is already running
 
(Filename:  Line: 461)
```

in the Player.log. It's a unity game. The opposite doesn't happen. I suspect that stg just ignores this, while Hue doesn't. I don't  have much expectations that Hue would fix this, since this is a known thing that can happen on Linux with plain Chrome.

**Comment by bastimeyer** [comment]
Ask the developers of that game. There is nothing that can be done here. Streamlink Twitch GUI is an NW.js / Chromium application and its NW.js binaries are built by the NW.js devs, not here.

The game also doesn't launch when regular Chromium is running. You can run the game via Proton and it'll work fine.

Closing, because it's unrelated to Streamlink Twitch GUI.
