### ISSUE TITLE
Windows 7 caveat missing from last release as it's not supported (due to nw.js)

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#976]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

Not relevant

### Streamlink version

v2.3.0

### Operating system, environment and configuration details

Windows 7

### Description

Latest release (2.3.0) doesn't start anymore on Windows 7. After some search it appears that nw.js was compatible with Windows up to release 0.72.0 and therefore latest Streamlink Twitch GUI uses one that's more recent and thereore note supporting W7 anymore.

Maybe it wasn't seen on the version choice, or maybe it was intentional; either way I think it deserve a caveats in the release.

That means that W7 users are stuck on release 2.2 and for that reason, it would seems relevant to do a caveat in the future release of Streamlink that would require Streamlink Twitch GUI above version 2.2 to work.

**Comment by bastimeyer** [comment]
I was aware of this, but I forgot to include this in the changelog.

Chromium has ended its support for Windows 7, 8 and 8.1 in its 110 release, which was in February this year:

- https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023?hl=en
- https://chromiumdash.appspot.com/schedule

Streamlink Twitch GUI v2.2.0 was based on Chromium 105. v2.3.0 is now based on Chromium 115.

Windows 7 has been unsupported for over 8.5 years now, with its extended paid security support having ended 3.5 years ago. Microsoft's support for Windows 8.1 has run out this year, shortly before Chromium did, which is why Chromium waited until then:

- https://endoflife.date/windows

> That means that W7 users are stuck on release 2.2

I honestly don't care. If this is an issue for anyone using an outdated, unsupported and insecure operating system, then they can fork and build the application themselves.

Going to update the changelog and release notes now.

**Comment by bastimeyer** [comment]
2a44dc4c12aafcbb92641eae0c6e7bd828fed9bb

**Comment by Porkepix** [comment]
Just to make it clear, it wasn't a critics or anything for the drop of support, I found out the drop of support for nw.js as shown above, but did so the hard way  (just a side computer running W7 I don't use for anything important, and never cared enough to update, but it so happens I sometimes put streams there).

It's just that I think it deserved to be notified as a caveat in the release.

My guess is that anyway the support will probably drop soon for streamlink too, which already needed some specific release of python to run on W7 and therefore its own releases (though I just checked and 3.8 still have a little bit more than one year of support. Wouldn't have bet it was still supported when there was already 3 others major releases since).

**Comment by bastimeyer** [comment]
I will stop publishing py38 based Streamlink releases once supports ends by the Python devs, which will be next year:
https://peps.python.org/pep-0569/#lifespan

I already commented on that on the Streamlink issue tracker. It's just copying a few extra checksums for me when managing and building new releases, so it hasn't bothered me much.

**Comment by bastimeyer** [comment]
No idea about the bundled FFmpeg though. If something breaks there, then I will drop py38 Streamlink releases sooner

**Comment by eldepor** [comment]
Callin w7 "old" and removing support for it is the most stupid shit ive ever seen. I wont upgrade. Period.

**Comment by bastimeyer** [comment]
> Windows 7 has been unsupported for over 8.5 years now, with its extended paid security support having ended 3.5 years ago. Microsoft's support for Windows 8.1 has run out this year, shortly before Chromium did, which is why Chromium waited until then:
> 
> * [endoflife.date/windows](https://endoflife.date/windows)

> > That means that W7 users are stuck on release 2.2
> 
> I honestly don't care. If this is an issue for anyone using an outdated, unsupported and insecure operating system, then they can fork and build the application themselves.

Good luck with that.

Locking the thread.
