### ISSUE TITLE
Enable app native key binding for router component refresh on macOS

### ISSUE THREAD

**Issue by templateK** [streamlink/streamlink-twitch-gui#985]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Currently, refresh rebinding on macOS must set through system settings. One downside of this is that users cannot set it with single character such as ascii `a`.  The system shortcut setting requires at least one additional modifier when using ascii. 

I've looked around the master branch and found this. https://github.com/streamlink/streamlink-twitch-gui/blob/2c2fc161132bbc8ca4f821595b2b536d3bfb2ca4/src/app/ui/components/main-menu/component.js#L33-L37

Is there any reason why app native key binding is blocked on macOS? Once I've commented out line 35, the `refresh` works without any problem in my usage. Also, I still could rebind through system settings after that change.

**Comment by bastimeyer** [comment]
> Is there any reason why app native key binding is blocked on macOS?

I had a quick look and it seems like it's a remnant of the previous implementation, where hotkeys were not customizable.

Customizable hotkeys were added in aaf60cd96aa6e6083c7dc67a7b63eb4b3bf89f92.

If you take a look at the git-blame of the `MainMenuComponent` from the commit prior to that, you can see that the refresh callback was unchanged and just got moved when the customizable hotkeys were implemented:

- https://github.com/streamlink/streamlink-twitch-gui/blame/df73b7e2654af5b2dd519dab23ca61a824b6dbe0/src/app/ui/components/main-menu/component.js#L21-L26
- https://github.com/streamlink/streamlink-twitch-gui/blame/df73b7e2654af5b2dd519dab23ca61a824b6dbe0/src/app/ui/components/main-menu/component.js#L44-L48
- https://github.com/streamlink/streamlink-twitch-gui/commit/aaf60cd96aa6e6083c7dc67a7b63eb4b3bf89f92#diff-00e4acc8c9a2852c479064e5fae65d09e55455b62c624d68efff93e4ae235717

The `if ( isDarwin ) { return; }` block was added to the `MainMenuComponent`'s `refresh` callback, because the macOS system menubar always gets added with the static `CMD+r` hotkey (due to convention), same as the `CMD+,` for opening the settings menu, so back then it was deemed redundant having the `CTRL+r` refresh hotkey as well.

- https://github.com/streamlink/streamlink-twitch-gui/blame/v2.4.1/src/app/nwjs/Menubar.js#L48-L54

----

Let's remove the `isDarwin` check.

Since you already had a look at the code, do you want to open a quick PR which removes the check and the comment above? This won't affect any tests, so it's just these two lines. If not, then I can apply the changes myself later.

**Comment by templateK** [comment]
Thanks for detailed answer.  Let me know if there's anything needs to change on pr.
