### ISSUE TITLE
Import/Export Configuration

### ISSUE THREAD

**Issue by shookieTea** [streamlink/streamlink-twitch-gui#992]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

#387 

Documentation seems to have changed, and I can no longer find the page where this information exists. Is this a feature that has been removed, or is this still possible?

**Comment by bastimeyer** [comment]
The issue you've linked has nothing to do with what you're asking for. This was a migration guide of the NW.js/Chromium config/cache dirs when the Twitch GUI got renamed after the switch to Streamlink in 2016, when Streamlink was forked from the dead Livestreamer project.

The config/cache dirs of NW.js/Chromium are documented here:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#user-data-directory

I've already commented on an import/export feature somewhere on this issue tracker (can't find it right now), and the answer is that I won't implement it, because it's not worth the effort, especially since this would require validating potentially malicious inputs. Considering that the Twitch GUI is pretty much feature locked for a long time already due to me having lost most of my interest with all the Twitch API feature removals and the tech debt that's been piling up left, right, and center, I don't see the point implementing new stuff. Just back up your settings manually or back up the entire config dir.

**Comment by shookieTea** [comment]
Understood, will proceed forward by assuming the config directory is `AppData\Local\streamlink-twitch-gui\User Data`
