### ISSUE TITLE
Could there be an option to ALLOW advertisements? Long total silences during watching not nice 

### ISSUE THREAD

**Issue by vrement** [streamlink/streamlink-twitch-gui#995]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

I don't know of others but when the adverts kick in watching Twitch streams things halt for often long while. Total silence and waiting. Could there be a simple option in the settings to just allow them ads? They never bothered me. Or what is the reason for the stream to stop or be silenced during ad breaks?

**Comment by vrement** [comment]
![Commercial](https://github.com/streamlink/streamlink-twitch-gui/assets/139187581/af6c8919-f442-41f6-b355-f637ad7abd50)
The annoyance in question is this screen during watching, which is there silent for often very long time.

**Comment by bastimeyer** [comment]
Read this
https://streamlink.github.io/cli/plugins/twitch.html

Streamlink always requires streaming access tokens while pretending to be Twitch's embedded web player. This is where they don't serve ads and instead show the "purple screen", because they can't or don't want to show ads on 3rd party websites.

If you want to see ads for whatever reason, then disable ad filtering (`--twitch-disable-ads`) in the Twitch GUI's streaming settings menu (you already have disabled this, otherwise you wouldn't see the "purple screen"), and then set the following Streamlink parameter, which can be done in the Twitch GUI's streaming settings menu after enabling advanced settings in the main settings menu, or set it in your Streamlink config file (see the Streamlink docs):
`--twitch-access-token-param=playerType=web`

Seeing ads or the purple screen however always results in a stream discontinuity, which needs to be avoided, or demuxing/decoding issues in your player can occur. This is also the case when filtering, but here it's the continuation of the same bitstream, albeit with a gap, but players usually can recover from this just fine.
